### ISSUE TITLE
can't retrieve the logs from file

### ISSUE THREAD

**Issue by rvi** [Instabug/Instabug-iOS#100]
Hey,

I try to send the logs while sending an Instabug, and I can't see any log in my dashboard...

For writing and saving logs we use [SwiftyBeaver](http://swiftybeaver.com/). (see the class FileDestination).

Here's my code:

```swift
Instabug.start(withToken: token, invocationEvent: .shake)
Instabug.setCrashReportingEnabled(false)
Instabug.setIntroMessageEnabled(false)

let file = FileDestination()
if let path = file.logFileURL?.absoluteString {
   Instabug.setFileAttachment(path)
}
```

What am I doing wrong?

**Comment by Kmohamed** [comment]
@rvi 
I would like to clarify something that attached files will not shown in log field but will be shown as attachment "file attachment".
are you unable to find your attached file ?

**Comment by rvi** [comment]
Thanks @Kmohamed.

I found it, yes, but I always have an empty file named `d10d7d0721904cfaff23dc0074e0402b_original`.

**Comment by Kmohamed** [comment]
@rvi 
are you sure that you upload a valid file ?

**Comment by rvi** [comment]
Well, I don't know what's SwiftyBeeaver does with it, maybe it's empty at the begining?

**Comment by rvi** [comment]
Anyway, I used `IBGLog()`, and it's fine now. Thanks for your help.

**Comment by Kmohamed** [comment]
@rvi 
I think this is the point.
once you use this API `Instabug.setFileAttachment` we copy your file into a private path.
so it's changed later will not be uploaded.

**Comment by brunomunizaf** [comment]
(Non-related to Instabug - but It works on Instabug) How do you guys export a file with only its url? I'm trying to export a .sqlite file but writing as NSData doesn't help cause i'm not able to set the name prior to export it so it loses its extension. Help pleaaase 🙏🏻
