### ISSUE TITLE
-[IBGTextView removeObserver:]: unrecognized selector sent to instance 0x7fbca7845600

### ISSUE THREAD

**Issue by mikewlange** [Instabug/Instabug-iOS#101]
Everything works great until you submit a bug. The bug even shows up in the instabug dash. However, since  Version: 6.1 post submission crashed the app. This crash happens lazily too, the view that you submitted the bug on shows for a sec then this breaks it. Can't test because instabug is closed. Any thoughts? Thanks so much!! 

Here is the stack starting/ending with instabug work

2016-12-28 20:47:10.640581 STCUSA[6143:1654190] [Warning] <_UIPopoverBackgroundVisualEffectView 0x7fbca762cdb0> is being asked to animate its opacity. This will cause the effect to appear broken until opacity returns to 1.
2016-12-28 20:47:11.041 xx[6143:1654190] tapped: report a bug
2016-12-28 20:47:15.050550 xx[6143:1654190] [MC] System group container for systemgroup.com.apple.configurationprofiles path is /Users/xx/Library/Developer/CoreSimulator/Devices/xx/data/Containers/Shared/SystemGroup/systemgroup.com.apple.configurationprofiles
2016-12-28 20:47:15.051926 STCUSA[6143:1654190] [MC] Reading from private effective user settings.
2016-12-28 20:47:23.816 STCUSA[6143:1654190] -[IBGTextView removeObserver:]: unrecognized selector sent to instance 0x7fbca7845600
2016-12-28 20:47:23.832 STCUSA[6143:1654190] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[IBGTextView removeObserver:]: unrecognized selector sent to instance 0x7fbca7845600'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010d6b1d4b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x000000011094f21e objc_exception_throw + 48
	2   CoreFoundation                      0x000000010d721f04 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x000000010d637005 ___forwarding___ + 1013
	4   CoreFoundation                      0x000000010d636b88 _CF_forwarding_prep_0 + 120
	5   Typeset                             0x000000010bae1c09 __31+[UITextViewTypesetHelper load]_block_invoke + 57
	6   Instabug                            0x000000010aa713d3 -[IBGTextView dealloc] + 107
	7   Instabug                            0x000000010aa2a2d6 -[IBGBugInputView .cxx_destruct] + 105
	8   libobjc.A.dylib                     0x000000011094da0a _ZL27object_cxxDestructFromClassP11objc_objectP10objc_class + 127
	9   libobjc.A.dylib                     0x00000001109595f6 objc_destructInstance + 129
	10  libobjc.A.dylib                     0x0000000110959628 object_dispose + 22
	11  UIKit                               0x000000010bd60dc2 -[UIResponder dealloc] + 146
	12  UIKit                               0x00000001247c37a7 -[UIResponderAccessibility dealloc] + 56
	13  UIKit                               0x000000010bbdfe74 -[UIView dealloc] + 1916
	14  Instabug                            0x000000010aa28d86 -[IBGBugInputView dealloc] + 107
	15  libobjc.A.dylib                     0x00000001109641d1 _ZN12_GLOBAL__N_119AutoreleasePoolPage3popEPv + 715
	16  UIKit                               0x000000010bbdfe4c -[UIView dealloc] + 1876
	17  libobjc.A.dylib                     0x00000001109641d1 _ZN12_GLOBAL__N_119AutoreleasePoolPage3popEPv + 715
	18  UIKit                               0x000000010bbdfe4c -[UIView dealloc] + 1876
	19  UIKit                               0x000000010bc1b9c0 -[UIScrollView dealloc] + 846
	20  libobjc.A.dylib                     0x00000001109641d1 _ZN12_GLOBAL__N_119AutoreleasePoolPage3popEPv + 715
	21  UIKit                               0x000000010bbdfe4c -[UIView dealloc] + 1876
	22  CoreFoundation                      0x000000010d70925e common_removeAllObjects + 254
	23  CoreFoundation                      0x000000010d5e5c93 -[__NSArrayM dealloc] + 19
	24  libobjc.A.dylib                     0x0000000110963b12 _ZN11objc_object17sidetable_releaseEb + 212
	25  libobjc.A.dylib                     0x00000001109641d1 _ZN12_GLOBAL__N_119AutoreleasePoolPage3popEPv + 715
	26  UIKit                               0x000000010bbdfe4c -[UIView dealloc] + 1876
	27  CoreFoundation                      0x000000010d5ec71d -[__NSArrayI dealloc] + 77
	28  libobjc.A.dylib                     0x0000000110963b12 _ZN11objc_object17sidetable_releaseEb + 212
	29  Instabug                            0x000000010a9f8710 -[IBGBugVC .cxx_destruct] + 75
	30  libobjc.A.dylib                     0x000000011094da0a _ZL27object_cxxDestructFromClassP11objc_objectP10objc_class + 127
	31  libobjc.A.dylib                     0x00000001109595f6 objc_destructInstance + 129
	32  libobjc.A.dylib                     0x0000000110959628 object_dispose + 22
	33  UIKit                               0x000000010bd60dc2 -[UIResponder dealloc] + 146
	34  UIKit                               0x00000001247c37a7 -[UIResponderAccessibility dealloc] + 56
	35  UIKit                               0x000000010bce8699 -[UIViewController dealloc] + 1920
	36  Instabug                            0x000000010a9f7a22 -[IBGBugVC dealloc] + 252

**Comment by HeshamMegid** [comment]
Hi @mikewlange, let me look into this and get back to you.

**Comment by HeshamMegid** [comment]
@mikewlange, unfortunately I haven't been able to reproduce that issue. Would you mind sharing more details about your environment to help us reproduce it, like which version of iOS you're running, whether that crash happens on iPhones or iPads, and which version of the SDK you're on.

Also, it would be great if you could share the code you use to initialize the SDK, as well as any customizations you do to it.
