### ISSUE TITLE
Setting email required/ and default email not working

### ISSUE THREAD

**Issue by leojkwan** [Instabug/Instabug-iOS#102]
I want to remove the optional email field in the feedback section.

in appdelegate I am calling
```
Instabug.setUserEmail("guest")
Instabug.setEmailFieldRequired(false)
```
but the feedback modal still shows the 'enter your email' field.

**Comment by Kmohamed** [comment]
Hi @leojkwan,
Can you tell me your SDK version ?

**Comment by leojkwan** [comment]
version 9? bundle version 6.3

**Comment by Kmohamed** [comment]
I tried to reproduce the bug but unfortunately I fail.
Could you provide me with more details about Instabug intilizaion code ?

**Comment by leojkwan** [comment]
Sure thing, I'm calling this in the app delegate.
```
Instabug.start(withToken: Constants.environment.instabugKey, invocationEvent: .floatingButton)
    Instabug.setUserEmail("guest")
    Instabug.setEmailFieldRequired(false)
````

**Comment by leojkwan** [comment]
Very strange, on my 7+ it wasn't working, but on another device the email field is gone. Is the framework caching the properties? Hmm I will investigate more, but thanks @Kmohamed !

**Comment by Kmohamed** [comment]
@leojkwan 
This very strange !!!
I will investigate anyway also keep me updated.

**Comment by Kmohamed** [comment]
@leojkwan 
I just realized what happened ?
If the email is not correct the email field will not disappear.
Could you try a valid email ?

**Comment by leojkwan** [comment]
Correct you are! That works thank you!
