### ISSUE TITLE
Add Device Family to Instabug info.plist

### ISSUE THREAD

**Issue by leojkwan** [Instabug/Instabug-iOS#103]
This is a one off case with my CI service Buddybuild. Ever since I've added instabug's dependency, my builds have been failing. In my failure logs, I got.

<img width="1202" alt="screen shot 2017-01-07 at 5 43 01 pm" src="https://cloud.githubusercontent.com/assets/10264891/21745949/5322489e-d504-11e6-833b-d21b7a692ea0.png">

I am certain that it's Instabug's framework, because after looking at a similar error: https://code.google.com/p/google-cast-sdk/issues/detail?id=954

I decided to add the UIDeviceFamily key with an array of strings [1,2] (iphone and ipad device support) into Instabug's info.plist. I've built again and again with and without instabug so I am certain it's this dependency. Strangely enough, no problems arised on TestFlight when manually archive and uploading. Just a one off error I wanted to raise in the event it happens to someone else!

**Comment by Kmohamed** [comment]
@leojkwan 
Hello again, let me look into this and get back to you.

**Comment by HeshamMegid** [comment]
Hi @leojkwan. Thanks for reporting this.

We've just fixed this issue, so please update to v6.3.1 of the SDK.

**Comment by leojkwan** [comment]
awesome, thank you!
