### ISSUE TITLE
Versions >= 6.3 brokes UIWebView navigation

### ISSUE THREAD

**Issue by sherm4n90** [Instabug/Instabug-iOS#105]
Previously had version 5.3.2 and my UIWebVIew navigation was ok(Login with Instagram). The updated to the 6.3 version or 6.3.1 and it brokes the WebView navigation. I thinsk is related with the new Network logs feature of the SDK.

**Comment by HeshamMegid** [comment]
@sherm4n90 let me look into this and get back to you.

**Comment by sherm4n90** [comment]
@HeshamMegid thanks!

**Comment by HeshamMegid** [comment]
@sherm4n90 this is indeed related to network logs. As a temporary workaround while we look into this, you can disable network logs for certain URLs using `setNetworkLoggingFilterPredicate:` or disable it altogether using `setNetworkLoggingEnabled`.

**Comment by sherm4n90** [comment]
@HeshamMegid Thanks for the fast response. I will try this soon.

**Comment by HeshamMegid** [comment]
@sherm4n90 We've been digging into this over the past couple of days we have a fix that we wanted to verify with you. Would you please give this build a try and let us know if it fixes your issue?

[Instabug.zip](https://github.com/Instabug/Instabug-iOS/files/698980/Instabug.zip)

**Comment by sherm4n90** [comment]
@HeshamMegid The build worked. Thanks a lot. Would I wait for the update then?

**Comment by HeshamMegid** [comment]
@sherm4n90  Yes, we will be releasing an update that has the fix shortly. Will let you know once it's out.

**Comment by HeshamMegid** [comment]
@sherm4n90 the fix is included in [v6.4](https://github.com/Instabug/Instabug-iOS/releases/tag/6.4).

**Comment by sherm4n90** [comment]
@HeshamMegid Awesome! Thanks for the quick actions.
