### ISSUE TITLE
ld: framework not found Instabug

### ISSUE THREAD

**Issue by andrei-sadagurschi** [Instabug/Instabug-iOS#106]
After updating to Instabug 6.3.1 (from 6.0.2) I am getting a build error:

`ld: framework not found Instabug`
`clang: error: linker command failed with exit code 1 (use -v to see invocation)`

I've updated the Instabug framework through `pod update`.
I've already tried to completely reinstall all the pods from the project.
The cocoapods version that I am using is 1.1.1.
Any help is much appreciated.

**Comment by Figo0o** [comment]
Hey @andrei-sadagurschi, let me check that and get back to you.

**Comment by mcocaro** [comment]
same here

**Comment by Figo0o** [comment]
@andrei-sadagurschi, can you share with us a screenshot of 'Framework Search Paths' from your project directory ?

**Comment by andrei-sadagurschi** [comment]
![screen shot 2017-01-09 at 10 04 24 pm](https://cloud.githubusercontent.com/assets/2855014/21781419/e7c21a9c-d6b7-11e6-9b13-b845db3da605.png)
Here it is. I hid part of the path for security reasons. Thank you!

**Comment by Figo0o** [comment]
I've tried to reproduce this issue with the same scenario (updating from 6.0.3 to 6.3.1) but I failed, every thing works correctly. I believe it cocoaPods issue. 

try to remove cocoaPods and re-install it again. Hopping this solves the problem. 
cc @andrei-sadagurschi

**Comment by andrei-sadagurschi** [comment]
@Figo0o, I've already tried that. It doesn't fix the issue. Any other suggestions?

**Comment by andrei-sadagurschi** [comment]
It seems to be something related to the new framework added to the pod. That framework doesn't seem to get linked to the main project. The bundle folder (which is added in a similar way) gets linked properly.

**Comment by Figo0o** [comment]
@andrei-sadagurschi, Could you verify that the framework binary actually exists locally on your machine? You can do that by navigating to the Pods directory in Finder, then selecting Instabug > Instabug.framework and checking that the Instabug binary is there.

**Comment by andrei-sadagurschi** [comment]
@Figo0o, the binary is there.

**Comment by Figo0o** [comment]
@andrei-sadagurschi, Okay, Then what happened when removing Instabug from `podfile`, is this issue fixed or still remaining with other frameworks?

**Comment by Figo0o** [comment]
@mcocaro any updates ?

**Comment by andrei-sadagurschi** [comment]
@Figo0o, I've removed the pod and manually installed the library (instructions from here: https://instabug.com/developers). Now the build succeeded, but the library is not loaded:

`dyld: Library not loaded: @rpath/Instabug.framework/Instabug`
`  Referenced from: /Users/myuser/Library/Developer/CoreSimulator/Devices/73CBA6CC-158D-467B-8549-C6F431CF4BFC/data/Containers/Bundle/Application/48189CA1-7F84-4E84-B279-DC03EEF69713/AppName.app/AppName`
`  Reason: image not found`

**Comment by Figo0o** [comment]
@andrei-sadagurschi, Please make user that Instabug.framework found in your project's "Embedded Binaries" section under the "General" tab. this should solves the problem.

**Comment by andrei-sadagurschi** [comment]
@Figo0o, this solves the manual installation. The cocoapods installation is still broken from my point of view.

**Comment by mcocaro** [comment]
I've had this issue since a few weeks now, I managed to resolve it but pulling the Pod from the Git repo directly as opposed to the CocoaPods version. Yesterday I decided to revert back to the CocoaPods version, did a `pod install` and the same error popped up again. It seems that version 6.2.1 has the problem, I can see that there is a Typechange for the framework when I do the pod install of that version. Then I removed the pod from the Podfile, did a pod install - added it again and the problem disappeared.

As far as I was able to see, this issue appears when CocoaPods removes the Instabug framework from the install-frameworks script.

typechange: Pods/Instabug/Instabug.framework/Instabug

**Comment by Figo0o** [comment]
@andrei-sadagurschi, Thats good for now, I am still digging deep into that to figure out what causes this issue. and will get back as soon as possible.

**Comment by HeshamMegid** [comment]
@mcocaro out of curiosity, do you commit your Pods directory to your repo?

We've ran into similar issues when the Pod directory is in the repo while using a Git client that doesn't play well with typechange (like SourceTree).

**Comment by mcocaro** [comment]
yes, and yes - do use Sourcetree and did find out that the typechange was
not recognized by it


--
Martin

**Comment by andrei-sadagurschi** [comment]
You are right. The Pods directory is committed to the repo and I am using SourceTree.

**Comment by HeshamMegid** [comment]
@andrei-sadagurschi would you please try what @mcocaro suggested and let us know if that solves the issue for you?

>Then I removed the pod from the Podfile, did a pod install - added it again and the problem disappeared.

**Comment by andrei-sadagurschi** [comment]
@HeshamMegid, I've already tried that. It does not fix the problem. I've also tried removing the whole Pods directory and installing them again.

**Comment by HeshamMegid** [comment]
@andrei-sadagurschi this is most likely a Cocoapods issue. Is it okay for you to use the framework without Cocoapods for now while we look more into this, or that would be an issue?

**Comment by andrei-sadagurschi** [comment]
@HeshamMegid, I've already switched to manual installation for now. Please let me know if you find a fix for the Cocoapods install. Thank you!

**Comment by saiday** [comment]
Any updates? 
Integrate Instabug `7.0.2` on CocoaPods have the same issue, `6.1.3` have no problem.

**Comment by andrei-sadagurschi** [comment]
@saiday The problem seems to be fixed when using cocoapods `1.2.0` and Instabug `7.0.2`. I think we can close this one. Thank you!

**Comment by HeshamMegid** [comment]
Actually, we've done no changes from our side regrading this, so it's the CocoaPods update that did the trick.

Thanks for reporting that @andrei-sadagurschi!

**Comment by saiday** [comment]
Hi, @HeshamMegid @andrei-sadagurschi 

Tried CocoaPods `1.2.0`, still have no luck with Instabug `7.0.2`.
Clean installed `cocoapods` gem, clean installed `Pods` with cocoapods 1.2.0, got same error on app launched.

```
dyld: Library not loaded: @rpath/Instabug.framework/Instabug
  Referenced from: /var/containers/Bundle/Application/51325C5A-F190-4BFB-B63A-8C4DC6F40AA8/myapp.app/myapp
  Reason: image not found
```

**Comment by saiday** [comment]
Hi, Instabug versions > `6.2` had `dyld: Library not loaded: @rpath/Instabug.framework/Instabug` issue.

Noticed that https://github.com/Instabug/Instabug-iOS/blob/master/Instabug.podspec changes (`sources_files`, `preserve_paths`, `frameworks`, `vendored_frameworks`, `resource`) on 6.2 release, is this a possible cause?

**Comment by HeshamMegid** [comment]
@saiday version >= 6.2 has switched to distributing the SDK as a dynamic framework instead of a static one.

So far we have found that the solution that works in most cases is removing Instabug from your podfile, doing a `pod install`, adding Instabug again, and finally doing another `pod install`. Have you tried that?

**Comment by saiday** [comment]
@HeshamMegid I tried, it doesn't fix.

**Comment by bvanderdrift** [comment]
This issue popped up as the only issue on top of my Google search when searching for `Unable to install vendored xcframework 'Instabug' for Pod 'instabug-reactnative', because it contains both static and dynamic frameworks` which happened after `pod install` after my build process had given me a `framework not found Instabug`.

The solution for me was to upgrade the `instabug-reactnative` npm package from `10.8.1` from `10.4.0`. Hopefully this helps someone else running into the same issue and landing here.
