### ISSUE TITLE
Carthage support

### ISSUE THREAD

**Issue by soffes** [Instabug/Instabug-iOS#108]
It would be really great if [Carthage](https://github.com/Carthage/Carthage) support was added :heart:

**Comment by HeshamMegid** [comment]
Hi Sam! We've considered adding Carthage support but we thought it wouldn't add any value since we're closed source, so essentially all Carthage would be doing is downloading the framework for you, so I'm curious to know why you think Carthage would make getting the framework easier.

**Comment by soffes** [comment]
@HeshamMegid for my app, all of my dependencies are from Carthage. I don't want to add CocoaPods just for this one dependency. Having to use a workspace and now explaining to new team members that they have to use both dependency managers isn't ideal.

**Comment by HeshamMegid** [comment]
@soffes To make sure I fully understand the benefit of using Carthage in this scenario, how does using it with Instabug differ from downloading the framework and adding it directly to your project without a dependency manager (since Instabug is distributed as a precompiled dynamic framework). I assume you want to keep 3rd party dependencies off your repo, maybe?

**Comment by soffes** [comment]
@HeshamMegid this provides a consistent automated way to do this. I mean you could say the same for CocoaPods. You could do the whole things with shell scripts :)

**Comment by HeshamMegid** [comment]
@soffes makes sense. 

We'll be adding it in a future release. Will ping you once it's ready.

**Comment by soffes** [comment]
Thanks so much!

**Comment by txaiwieser** [comment]
Please, Carthage support would be great!

**Comment by klaaspieter** [comment]
I noticed that the [releases][] already have an attached .zip including the framework. Renaming the attached zip from `Instabug.zip` to [`Instabug.framework.zip`](https://github.com/Carthage/Carthage#archive-prebuilt-frameworks-into-one-zip-file) should make Carthage work as expected.

[releases]: https://github.com/Instabug/Instabug-iOS/releases

**Comment by klaaspieter** [comment]
While official support would still be appreciated, it _is_ possible to install Instabug with Carthage using the new [binary framework support][Carthage binary framework support].

I created a gist to point to the latest version: https://gist.github.com/klaaspieter/e94c5617bb59a7437fcfa870ffb2edaf and put `binary "https://gist.githubusercontent.com/klaaspieter/e94c5617bb59a7437fcfa870ffb2edaf/raw/8db7d8e1e44d9dfcd65fcc6bb1dff771467ce513/Instabug.json"` in my `Cartfile`

[Carthage binary framework support]: https://github.com/americanexpress/Carthage/blob/3492f0afc420315091e51d1ebf9b3c0f0f05a85c/Documentation/Artifacts.md#binary-only-frameworks

**Comment by txaiwieser** [comment]
@klaaspieter: I'm using
```github "Instabug/Instabug-iOS" "dynamic_framework"```
It works, but I think it could be supported in the main branch, in the Carthage official way.

**Comment by klaaspieter** [comment]
@txaiwieser We were using that, but iirc it was an older version than on master.

**Comment by HeshamMegid** [comment]
We've added official Carthage support. Thanks for your patience everyone!

Check the instructions on our [readme](https://github.com/Instabug/Instabug-iOS#carthage) file.
