### ISSUE TITLE
Crashes are being reported even though reporting is turned off

### ISSUE THREAD

**Issue by Aaang** [Instabug/Instabug-iOS#110]
Hi!

We're currently experiencing issues with the Instabug integration in our apps, as the framework is reporting crashes even though it's specifically disabled by calling `Instabug.setCrashReportingEnabled(false)`.

Instabug version: **6.1.3**
_Unfortunately we can't use the latest dynamic frameworks version yet_

We're still using HockeyApp and New Relic for crash reporting and can't switch to Instabug crash reporting for now. The problem is that crash reporting works just fine for builds where Instabug is not integrated, but as soon as we integrate Instabug, the crashes are only reported to Instabug even though it should be disabled and report to another tool.

Here's our Instabug set up code:

        // first invocationEvent .none, because we want to enable it at a specific time
        Instabug.start(withToken: XXX, invocationEvent: .none)

        Instabug.setIntroMessageEnabled(false)
        Instabug.setCrashReportingEnabled(false)
        Instabug.setPromptOptionsEnabledWithBug(true, feedback: true, chat: false)
        Instabug.setPushNotificationsEnabled(false)
        Instabug.setCommentFieldRequired(false)
        Instabug.setEmailFieldRequired(true)

As soon as we specifically enable Instabug:

        Instabug.setInvocationEvent(.shake)
        Instabug.setUserStepsEnabled(true)
        Instabug.setUserEmail(XXX)

My guess is that there's a mess up with the method swizzling when using multiple crash reporting tools as Instabug is initialized after the crash reporting tool.

A possible solution could be using CocoaPods subspecs to only deliver the source files needed within the app? Or do you have any another solution to this problem?

Thanks in advance,
Aaang

**Comment by Kmohamed** [comment]
Hello @Aaang,
Let me check and get back to you.

**Comment by Aaang** [comment]
Thanks!

Sorry, I've just realized that we were using a different Instabug version when the issue occurred.

Instabug version: **5.3**

I'll re-test if it also happens with the version 6.1.3.

**Comment by Kmohamed** [comment]
@Aaang 
Sure, let me know If you find the same issue.

**Comment by Aaang** [comment]
@Kmohamed sorry for the confusion, looks like it's fixed in 6.1.3.

**Comment by Kmohamed** [comment]
Great 👍
