### ISSUE TITLE
StatusBar tintColor problems

### ISSUE THREAD

**Issue by txaiwieser** [Instabug/Instabug-iOS#111]
We just implemented the instabug framework in our App. But we are experiencing a lot of bugs related to the StatusBar color, we made a lot of tests and its definitely Instabug's fault. 

We use a ViewController based StatusBar configuration, and most view controllers have a white StatusBar. And even without accessing the instabug button, the status bar turn black in some app VCS.

One small case is when we present in a VC (white statusbar) a SFViewController (black statusbar) it changes to black (as it should) and when we dismiss the SFViewController it should change back to white. Bug with Instabug enabled it doesnt change back in some times. When it does changes it appears to be fake and without animations.

I love instabug, but with this bug its very unlikely we can push to our betas :/

Thanks! 👍

**Comment by Kmohamed** [comment]
@txaiwieser 
Let me check and get back to you.

**Comment by Kmohamed** [comment]
@txaiwieser 
I success on reproduce the bug 
I would like to ask If you are using floating button or not.

**Comment by txaiwieser** [comment]
@Kmohamed Yes, we are using the floating button. But this issue happens even when the button wasn't pressed.

**Comment by Kmohamed** [comment]
@txaiwieser 
Sorry for inconvenience.
Here is a custom build with a fix. and we are going to release the fix soon.
[Instabug.framework.zip](https://github.com/Instabug/Instabug-iOS/files/719572/Instabug.framework.zip)

**Comment by txaiwieser** [comment]
Thanks you for the quick fix! Gladly appreciated!

😄👍

**Comment by Kmohamed** [comment]
Anytime :)

**Comment by txaiwieser** [comment]
This bug has returned!
Now it happens every time I "peak and pop" in a cell, for example

**Comment by Kmohamed** [comment]
@txaiwieser Could you send me screenshot with the bug ?

**Comment by txaiwieser** [comment]
The status bar just changes to black after you "peak and pop" in any cell that supports it. (the app I work has white status bar)

**Comment by Kmohamed** [comment]
I will check it and get back to you as soon as possible

**Comment by Kmohamed** [comment]
@txaiwieser I implement Peek and pop in a project using Instabug SDK but it does not change status bar color.
Could you confirm the SDK version runs on that device is greater than 7.0

**Comment by txaiwieser** [comment]
Yes, I using the latest version through Carthage. And the App uses UIViewControllerBasedStatusBarAppearance.

**Comment by Kmohamed** [comment]
My demo also uses UIViewControllerBasedStatusBarAppearance
Could you send to me a sample app with the bug ?

**Comment by Kmohamed** [comment]
@txaiwieser I would like to ask If you have enough time to send to us a sample project with peek and pop bug.

**Comment by txaiwieser** [comment]
I did the sample project and it turns out the problem happens only when linking with Carthage (with the new method described in the readme).
```
binary "https://raw.githubusercontent.com/Instabug/Instabug-iOS/master/Carthage.json"
```
It's not linked with the latest version 7.1 (with has this problem solved)

Sorry for the trouble, can we have this son pointing to the latest version? 

Thanks!

**Comment by HeshamMegid** [comment]
@txaiwieser that's weird. Both CocoaPods and Carthage and currently updated to the latest version. Would you please confirm that the build number of the SDK you get is 7311?

**Comment by txaiwieser** [comment]
It seems to be solved in the last version.

**Comment by txaiwieser** [comment]
This is still happening on iOS 9.3

Why do you have to swizzle everything? :/

**Comment by Kmohamed** [comment]
@txaiwieser could please which problem is still happening on iOS 9.3 ?

**Comment by txaiwieser** [comment]
* New Xcode project
* Change ViewController status bar style
```
 override var preferredStatusBarStyle: UIStatusBarStyle {
    return .lightContent
}
```
* Add Instabug with dark style


Status bar does not change to light on iOS 9.3

**Comment by Kmohamed** [comment]
I just tried your steps but did not succeed to reproduce the issue. The status bar style is light before invoking Instabug and after dismissing Instabug.
are you sure it is not and old version of sdk that has the issue ?

**Comment by txaiwieser** [comment]
I'm using 7.3.7.
Did you have related fixes on yesterday's version?

**Comment by Kmohamed** [comment]
No, but I can send you my sample project to see if I making something wrong or you can send me a sample project if you have.

**Comment by txaiwieser** [comment]
Sure, I added one line to AppDelegate from the Xcode template. And setting the VC to use .lightContent
[Testing.zip](https://github.com/Instabug/Instabug-iOS/files/1307198/Testing.zip)

**Comment by Kmohamed** [comment]
@txaiwieser Thanks a lot I will look in it and get back to you soon.

**Comment by Kmohamed** [comment]
@txaiwieser  I would like to share with you something very interesting that If you create the same project from Xcode 8 and run it on iOS 9.3 it will work fine. 
could you confirm this point please ?

**Comment by Kmohamed** [comment]
@txaiwieser also could you confirm that it's not simulator bug "Xcode 9 GM - iOS 9.3 simulator" ?

**Comment by Kmohamed** [comment]
@txaiwieser could you confirm please this strange behaviour ?

**Comment by txaiwieser** [comment]
@Kmohamed Unfortunately I couldn’t get an iOS 9 device yet, but the problem persist on the simulator

**Comment by Kmohamed** [comment]
@txaiwieser I am very sorry for being late. But it takes a lot of time to find a work around on iOS9 
could you give this [custom build](pod ‘Instabug’, :git => ’https://github.com/Instabug/Instabug-iOS.git', :branch => ‘fix/StatusBarColor_iOS9’) a try and tell if it works fine.

**Comment by Kmohamed** [comment]
@txaiwieser I will close the issue now but also feel free to open it again if it shows up again.

**Comment by txaiwieser** [comment]
Unfortunately this is not perfect yet.

• At first it seemed fixed, but after entering a SafariViewController or even on Instabug (via button), (any vc that changes the statusBar to black). After I go back to the app the bar stays black and doesn't change to white again.

**Comment by txaiwieser** [comment]
Up

**Comment by Kmohamed** [comment]
I am very sorry for being late we are still working on it and definitely will update you once it’s fixed.

**Comment by Kmohamed** [comment]
Hello @txaiwieser  Finally we found a fix for the issue  🎉🎉🎉🎉🎉
We are very sorry for being later you can not imagine how it takes to fix this issue, so kindly give it a try 🙂
pod ‘Instabug’, :git => ’https://github.com/Instabug/Instabug-iOS.git', :branch => ‘custom/fix-statusbar-style-iOS9’
