### ISSUE TITLE
core data multithreading violation

### ISSUE THREAD

**Issue by itsalan** [Instabug/Instabug-iOS#113]
Instabug 6.4.1, ios 10, swift.  Instabug.start causes a core data multithreading violation with the multi-threading assertions enabled.

**Comment by HeshamMegid** [comment]
Hi @itsalan, we're looking into this issue.

**Comment by HeshamMegid** [comment]
@itsalan, just letting you know that we have a fix for this issue that we're including in the next release, which will be out soon.

**Comment by HeshamMegid** [comment]
@itsalan Please check version 7.0 of the SDK and let me know if you're still experiencing this issue.

**Comment by itsalan** [comment]
@HeshamMegid, It's still happening with 7.0.

**Comment by HeshamMegid** [comment]
Oh, let us check again then and get back to you.

**Comment by HeshamMegid** [comment]
@itsalan, would you please check version 7.0.1 of the SDK and confirm that it solves this issue?

**Comment by itsalan** [comment]
@HeshamMegid 7.0.1 fixes the issue.  Thanks!
