### ISSUE TITLE
Tap already selected Annotation tool results in deadlock

### ISSUE THREAD

**Issue by manderson420** [Instabug/Instabug-iOS#114]
The most recent releases (both Instabug version 6.4.1 and 7.0) have a pretty major bug that results in a deadlock:

1. From the Instabug dialog choose "Report a Problem" with annotation view enabled
2. The pencil/annotation tool is selected by default (bottom left on the toolbar). Tap that icon while its already selected.

Expected: Nothing happens, user can continue interacting with the Instabug interface
Actual: Deadlock occurs resulting in upset users/developers requiring quitting/restarting the app.

Testing device is a iPhone 6S+ running iOS 9.3.5

Below is our configuration for Instabug. The solution for us is to just disable the annotation view.

`Instabug.start(withToken: self.apiKey, invocationEvent: .none)
  Instabug.setUserStepsEnabled(false)
  Instabug.setPromptOptionsEnabledWithBug(true, feedback: true, chat: false)
  Instabug.setCrashReportingEnabled(false) // Stops reporting crashes but doesn't actually avoid hooking into NSSetUncaughtExceptionHandler
  Instabug.setAttachmentTypesEnabledScreenShot(true, extraScreenShot: false, galleryImage: true, voiceNote: false, screenRecording: false)
  Instabug.setWillSkipScreenshotAnnotation(false)
  Instabug.setPrimaryColor(ColorPalette.aquaMarine)`

**Comment by Kmohamed** [comment]
Let me check and get back to you.

**Comment by Kmohamed** [comment]
@manderson420 
We succeed  in reproducing the bug and we fixed it.
It will be released soon today.

**Comment by Kmohamed** [comment]
@manderson420 Kindly check SDK v7.0.1 it should fix your issue.

**Comment by manderson420** [comment]
Thanks @Kmohamed we haven't been brave enough to update our cocoapods and test but will keep you posted in the future when we verify.
