### ISSUE TITLE
Disable/remove "IBGLog will now print to Xcode's console when debugger is attached." feature

### ISSUE THREAD

**Issue by Avtolic** [Instabug/Instabug-iOS#115]
Hello,
Thank you for improving Instabug.

How could I disable "IBGLog will now print to Xcode's console when debugger is attached." feature? I do not need it since we already use a custom logging manager. I also do not like how NSLog formats messages. We have some conflicts with a logging mechanism we use and would like to have this feature as optional, not mandatory.

Thank you

**Comment by Kmohamed** [comment]
@Avtolic 
You can disable it using `[Instabug setSDKDebugLogsLevel:IBGSDKDebugLogsLevelNone];`
Also it make sense to filtering it from Console log.

**Comment by HeshamMegid** [comment]
Hi @Avtolic, sorry about the confusion, this is not related to the method @Kmohamed has mentioned.

Are you seeing the duplication only for reports you do when you're debugging? Or do all reports have the duplicates?

**Comment by Avtolic** [comment]
Hello @HeshamMegid , sorry, it seems I have to clarify my issue. 

We have a custom logging class based on https://github.com/SwiftyBeaver/SwiftyBeaver lib. It allows us to use custom log levels, custom formatters, log synchronously for better debugging or asynchronously for better performance, simply manage which classes/functions should be able to log something and so on. This lib is very good.

We have 3 "destinations" for logs: console (via print function, not NSLog!), SwiftyBeaver's back-end and Instabug via Instabug.logInfo/logWarn/logError methods. So every "Log" function sends a message to three destinations. The root of the issue is that we have different rules and formats for console, Instabug and SwiftyBeaver back-end destinations. 

Everything was great when we were able to manage destinations separately. For example we have a compact format for console and more informative for Instabug. But now it is impossible to write something to Instabug log without writing the same to the console. And this pollutes a Debug window a lot with redundant messages and verbose format. Compare:
```
🍀AppDelegate: Start
2017-02-05 00:01:26.915 Wawibox Scan[78856:1672718] 🍀  AppDelegate: Start   (AppDelegate:79)
```
On the back-end we see the same logs as previously, nothing wrong here. But debugging worsened. 
Is it possible to disable somehow a new Instabug SDK feature : "IBGLog will now print to Xcode's console when debugger is attached"? If not is it possible to make it an optional in future releases?

Thank you.

**Comment by HeshamMegid** [comment]
@Avtolic thanks for the detailed explanation! Your use case is clear now.

Let me discuss this with the team and get back to you.

**Comment by philgrida** [comment]
I'm also interested in disabling Instabug logging l in the Xcode Console as well. Is there any update on this ?

**Comment by HeshamMegid** [comment]
@philgrida @Avtolic, we will be adding an API for this in an upcoming release. Will let you know once it's ready.

**Comment by HeshamMegid** [comment]
@philgrida @Avtolic, please check version 7.1. We've added `setIBGLogPrintsToConsole:` that lets you control this.

**Comment by kdawgwilk** [comment]
This new setter doesn't appear to work for me :( 
```swift
Instabug.setIBGLogPrintsToConsole(false)
Instabug.setSDKDebugLogsLevel(.none)
let instabug = InstabugDestination()
instabug.minLevel = logLevel
SwiftyBeaver.addDestination(instabug)
```

This still is double printing out to the console

**Comment by Kmohamed** [comment]
@kdawgwilk so everything is working as expected ?

**Comment by kdawgwilk** [comment]
Well it seemed like it was but I may have found some problems with it still double printing

**Comment by Kmohamed** [comment]
Are you sure that you called these methods after startWithToken ?

**Comment by kdawgwilk** [comment]
Does that really matter in this case?  I feel like it should behave the same no matter when I call it

**Comment by Kmohamed** [comment]
@kdawgwilk Actually we did not execute any method until you initialize the SDK.
