### ISSUE TITLE
Network logging does not work

### ISSUE THREAD

**Issue by Avtolic** [Instabug/Instabug-iOS#116]
Hello,
I can not make network logging work.
My code in AppDelegate:
```
Instabug.start(withToken:  ...
Instabug.setNetworkLoggingEnabled(true)
```
In network layer class (I am using Alamofire):
```
let serverTrustPolicy = ServerTrustPolicy.pinCertificates( certificates: ServerTrustPolicy.certificates(), validateCertificateChain: true, validateHost: true )
let serverTrustPolicyManager = ServerTrustPolicyManager(policies: [certificatedPath: serverTrustPolicy])

let configuration = URLSessionConfiguration.default
configuration.timeoutIntervalForRequest = 20
        
let sessionDelegate = SessionDelegate()
sessionDelegate.sessionDidReceiveChallenge = {(session: URLSession, challenge: URLAuthenticationChallenge) -> (URLSession.AuthChallengeDisposition, URLCredential?) in
            if challenge.protectionSpace.authenticationMethod == NSURLAuthenticationMethodServerTrust
                , let serverTrust = challenge.protectionSpace.serverTrust
                , testHosts.contains(challenge.protectionSpace.host)
            {
                Log.debug("Special credentials generated")
                return (.useCredential, URLCredential(trust: serverTrust))
            } else {
                return (.performDefaultHandling, nil)
            }
        }
        
Instabug.enableLogging(for: configuration)
        
manager = SessionManager(configuration: configuration, delegate: sessionDelegate, serverTrustPolicyManager: serverTrustPolicyManager)
```
Then I use let `manager` to send GET and POST requests. I have found in docs that there is some issue with POST requests but logging does not work with GET requests either.

Could you help me please?
Thank you

**Comment by Figo0o** [comment]
Hey @Avtolic, Let me look into this for you and get back ASAP.

**Comment by Figo0o** [comment]
@Avtolic,

I need to know Is all your requests before invoking Instabug failed to be logged ? when your requests done? 

And please be sure that `Instabug.enableLogging(for: configuration)` in your network layer is called away after Instabug initialization.

Thanks!

**Comment by Avtolic** [comment]
@Figo0o ,

> be sure that Instabug.enableLogging(for: configuration) in your network layer is called away after Instabug initialisation

Yes, `Instabug.enableLogging(for: configuration)` is called after Instabug initialisation.

> Is all your requests before invoking Instabug failed to be logged ? when your requests done?

Not sure I understand your question correctly. I am sending request the following way:

```
let request = manager.request(urlString, method: method, parameters: parameters, encoding: JSONEncoding.default, headers: headers)

request.response { r in 
// response processing code here
}
```

`manager` is the same `SessionManager` I have mentioned in the initial post. No requests are logged.

**Comment by Figo0o** [comment]
@Avtolic, Please make sure you're using latest Instabug version (7.0.1) 

I was asking if all your requests on your app startup or what ?

**Comment by Avtolic** [comment]
@Figo0o 
Some of requests are made on startup, some - later.
I have used Instabug 7.0. I will test the app with a newest version and will post results here.

**Comment by Figo0o** [comment]
@Avtolic, We are working in a hot fix that's going to be released soon. I will notify you after releasing. 

Thanks for reporting that.

**Comment by HeshamMegid** [comment]
@Avtolic, please check v7.0.3 of the SDK and let us know if you're still experiencing this issue.
