### ISSUE TITLE
Email - placeholder text

### ISSUE THREAD

**Issue by xiaosongshu** [Instabug/Instabug-iOS#117]
Is there a way to adjust the email placeholder text? 

From an UX perspective, would be good to let users know the email address is optional.

Or...is there a clever default email address that can be used for this purpose? I'm using "your.email.if.response.required@domain.com" / "optional.email@domain.com" but the user might get confused at what that is...and seeing "Enter Your Email" placeholder text might make users hesitant to submit

**Comment by HeshamMegid** [comment]
Hi @xiaosongshu,

You could adjust the email placeholder using `[Instabug setValue:@"Custom email placeholder" forStringWithKey:kIBGEmailFieldPlaceholderStringName];`.

Check `IBGTypes` to see all the other customizable strings in the SDK.

**Comment by xiaosongshu** [comment]
Thanks @HeshamMegid! Super useful. One other quick question - is it possible to customize the color of the navbar title (`Report a problem` / `Suggest an improvement`)? I've set the `primaryColor` to a white color but the navbar title still shows up as black.

It looks like a previous version of Instabug let you customize individual components of the UI (https://twitter.com/instabug/status/474898001631379456). Is it correct to say this is not possible anymore aside from `setPrimaryColor`?

**Comment by HeshamMegid** [comment]
Yes, that's currently not possible. As you mentioned, you can use `setPrimaryColor:` to only set the colors of tappable items. You can also use `setColorTheme:` to switch between dark and light themes.
