### ISSUE TITLE
Crash while opening App

### ISSUE THREAD

**Issue by mcocaro** [Instabug/Instabug-iOS#118]
Here's the stack trace:

Crashed: NSOperationQueue 0x13826ba30 :: NSOperation 0x1384ec0c0 (QOS: LEGACY)
0  libsystem_platform.dylib       0x181cb97d0 _os_lock_corruption_abort + 162
1  libsystem_platform.dylib       0x181cb97d0 _os_lock_corruption_abort + 162
2  CFNetwork                      0x18263b308 CFURLProtocol_NS::forgetProtocolClient() + 36
3  Instabug                       0x1031f15e8 __30-[IBGURLProtocol startLoading]_block_invoke + 400
4  CFNetwork                      0x182637344 __75-[__NSURLSessionLocal taskForClass:request:uploadFile:bodyData:completion:]_block_invoke + 32
5  CFNetwork                      0x182649cc4 __49-[__NSCFLocalSessionTask _task_onqueue_didFinish]_block_invoke + 296
6  Foundation                     0x1829fc334 __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 16
7  Foundation                     0x18294f100 -[NSBlockOperation main] + 96
8  Foundation                     0x18293f348 -[__NSOperationInternal _start:] + 604
9  Foundation                     0x1829fe728 __NSOQSchedule_f + 224
10 libdispatch.dylib              0x181aa95f0 _dispatch_client_callout + 16
11 libdispatch.dylib              0x181ab5634 _dispatch_queue_drain + 864
12 libdispatch.dylib              0x181aad0f4 _dispatch_queue_invoke + 464
13 libdispatch.dylib              0x181ab7504 _dispatch_root_queue_drain + 728
14 libdispatch.dylib              0x181ab7224 _dispatch_worker_thread3 + 112
15 libsystem_pthread.dylib        0x181cbd470 _pthread_wqthread + 1092
16 libsystem_pthread.dylib        0x181cbd020 start_wqthread + 4

**Comment by yousefhamza** [comment]
He @mcocaro, Can you provide more info? 

1. Like Is it happening consistently?
2. What Instabug version are you using?
3. If there's a specific setup or sample project that reproduce this issue.

Thanks for your feedback and helping us making Instabug better.

**Comment by HeshamMegid** [comment]
@mcocaro, closing this for now. Please feel free to reopen if you have any details that could help us reproduce it on our side.
