### ISSUE TITLE
License

### ISSUE THREAD

**Issue by valiantv7** [Instabug/Instabug-iOS#119]
Please add a LICENSE file with the relevant license info

**Comment by HeshamMegid** [comment]
Hi @valiantv7, we previously had our license embedded directly in the podfile. Now it's in a separate [LICENSE.md](https://github.com/Instabug/Instabug-iOS/blob/master/LICENSE.md) file.

**Comment by valiantv7** [comment]
Hi @HeshamMegid, thank you for adding the license. We have created a Xamarin binding for the Instabug iOS framework, which wraps the framework (without modifying it) into a NuGet package, and we would like to make the NuGet package publicly available on https://www.nuget.org/, as well as making the binding configuration open source on github. Would this be allowed under the current license, and if not, would it be possible to modify the license to allow this?
