### ISSUE TITLE
App is not terminated properly with Instabug version 7.0.1

### ISSUE THREAD

**Issue by HHK1** [Instabug/Instabug-iOS#120]
I tried integrating the crash report tool with Instabug today.

**What I did:**

I upgraded Instabug to 7.0.1
I added `[][1]` when clicking on a button inside my app.
I built my app in a debug configuration, stopped the debugger, relaunched the app and clicked on the button supposed to trigger the crash.

**What I expected:**

I expected the app to crash, and the crash report to be seen in Instabug

**What happened instead:**

The app froze, and was not terminated. It can be closed, or killed manually. If closed, it can be reopened, and it will still be frozen. No crash report was sent to Instabug.

**Other Informations:**

I downgraded the Instabug SDK back to 6.4.1. I was not able to reproduce the issue with that version of the SDK.

**Comment by Figo0o** [comment]
Hello @HHK1,

Thanks for Reporting that out. We have a fix that will be releasing very soon. 

Let me notify you when do.

**Comment by Figo0o** [comment]
@HHK1, Instabug v 7.0.2 is out. it has a fix to this issue. Please update and let me know if you're still facing any other issues 

Thanks!
