### ISSUE TITLE
The capture button from the IBGScreenshotCaptureWindow window is not visible under certain conditions

### ISSUE THREAD

**Issue by arturgrigor** [Instabug/Instabug-iOS#121]
## Summary:
The capture button is not visible on iPad if the app supports only the `Landscape (left home button)` and `Landscape (right home button)` interface orientations.

## Steps to Reproduce:
- Create a new project
- Integrate Instabug
- Update the value for the `UISupportedInterfaceOrientations~ipad` Info.plist key to:
```
        <key>UISupportedInterfaceOrientations~ipad</key>
	<array>
		<string>UIInterfaceOrientationLandscapeLeft</string>
		<string>UIInterfaceOrientationLandscapeRight</string>
	</array>
```
- Run the app
- Report a problem
- Add an additional image using the "Take a screenshot" option

## Expected Results:
- The capture screenshot button to be visible in the bottom-right corner.

## Actual Results:
- The capture screenshot button is not visible.

## Version:
- 7.0.x

**Comment by Figo0o** [comment]
Hello @arturgrigor, Thank you so muck for the details .. Let me have a look into this.

**Comment by Figo0o** [comment]
Hello Again,

Here is a custom build for you that fixes this problem. 

Please try It and let me know if you're still facing any issues. 

[Instabug.framework.zip](https://github.com/Instabug/Instabug-iOS/files/767765/Instabug.framework.zip)

**Comment by arturgrigor** [comment]
Hey @Figo0o,

This new build seems to work. Can you please release a new pod version with this build?

Thanks!

**Comment by Figo0o** [comment]
Hello @arturgrigor, 

We are going to release that very soon. Let me notify you when we do. 

Thanks!

**Comment by HeshamMegid** [comment]
@arturgrigor, please check v7.0.3 of the SDK. It has a fix for this issue.

**Comment by arturgrigor** [comment]
Hey @HeshamMegid, the v7.0.3 fixes my problem. Thank you!
