### ISSUE TITLE
Disabling auto dismissing of the prompt option dialog 

### ISSUE THREAD

**Issue by whitepixelstudios** [Instabug/Instabug-iOS#122]
We're working on an implementation that manually invokes instabug and are hoping to change the autodismissal behaviour.

Currently the "how can we help you dialog" closes after a few seconds of inactivity. Would it be possible to add a variable such as 'autoDismissAfter', with a value of zero disabling automatic dismissal?

Thanks!

**Comment by HeshamMegid** [comment]
Hi @whitepixelstudios,

Currently the dialog auto-dismisses after 10 seconds. Just to fully understand what you're trying to do, why do you need the dialog to remain open after more than 10 seconds of inactivity?

**Comment by whitepixelstudios** [comment]
Hi Hesham,

When instabug is manually invoked by a button press we've found it's somewhat unexpected behaviour when the dialog then closes itself. Granted it is an unusual use case that the user would remain on the screen for ten seconds without progressing. Would be great to simply have a variable that stops that auto-dismiss

Thanks

**Comment by HeshamMegid** [comment]
I get your point now. We will be adding this in a future version of the SDK.

Thanks!

**Comment by randaelbaz** [comment]
@whitepixelstudios Hey I know that this issue has been there for a while, sorry for the delay, but here is a quick update, automatic dismissing of the prompt dialog will be removed in the next release for all the invocation events except for the shaking.

I will rename the title of the issue to make it more relevant to the problem.

**Comment by randaelbaz** [comment]
Hey @whitepixelstudios 

Disabling auto dismissing of the prompt option dialog feature, is now released in version 7.4. 
Please update your current SDK to the latest version. 

I will close this issue for now. Feel free to reopen it if the issue still exists.
