### ISSUE TITLE
setPrimaryColor not working as expected

### ISSUE THREAD

**Issue by lokae0** [Instabug/Instabug-iOS#123]
Version 7.0.2:

If you call `Instabug.start` with .floatingButton, setPrimaryColor does not take effect until either:

* you background and reopen the app
* you call setInvocationEvent(.floatingButton) alongside setPrimaryColor

**Comment by HeshamMegid** [comment]
Hi @lokae0, sure sounds like a bug, sorry about that! Will look into it and let you know as soon as we have a fix.

**Comment by HeshamMegid** [comment]
@lokae0, we just released v7.0.3 of the SDK that has a fix for this.

**Comment by lokae0** [comment]
Awesome. Thank you!
