### ISSUE TITLE
Manual Report Bug (reportError)

### ISSUE THREAD

**Issue by xiaosongshu** [Instabug/Instabug-iOS#126]
Is there an example of how to report a bug manually based on an event (without the GUI, just via code), while also giving the bug a tag and user data? 

I see ` (void)reportError:(NSError *)error` in the docs but am unsure how I would go about manually sending a custom bug, with a tag and user data on it.

ie.

Bug 1
Tag: "unique-tag-1"
User Data: {"user_1: ABC, "user_2": XYZ}

**Comment by HeshamMegid** [comment]
Hi @xiaosongshu,

We don't currently support sending bugs manually. 

Just to make sure I completely understand what you want to do, what's the use case that would require sending a bug report, instead of an `NSError`?

**Comment by xiaosongshu** [comment]
Hi @HeshamMegid,

I wanted to use it for tracking when a user flags a post (the data I wanted to include would be the "user id" and the "post id"). 

I didn't realize it, but technically I should be able to just send a custom NSError for this right? If so, would you have an example of best practices for doing so?

**Comment by HeshamMegid** [comment]
You could use `reportError:` for that, though I have to admit that this wouldn't be the best use of this API since you'll have to add the user ID and post ID to the error domain.

We will be adding the ability to manually report an issue in a future release of the SDK.

**Comment by elyalvarado** [comment]
Hi @HeshamMegid reporting issues in code is really important. In our case we can detect when an issue happens with a third party library, and we need to capture all the information Instabug provides, and even attach the console logs so that we can debug further.

**Comment by HeshamMegid** [comment]
@elyalvarado you could do exactly what you need using the `reportError:` API. Have you tried using it and something was missing?

**Comment by HeshamMegid** [comment]
Closing this for now. Please free to reopen if you have further comments.
