### ISSUE TITLE
Cannot disable Instabug crash reporting

### ISSUE THREAD

**Issue by keith** [Instabug/Instabug-iOS#129]
Currently in our app our instabug configuration is setup like this:

```swift
        let event: IBGInvocationEvent = UIDevice.isSimulator() ? .shake : .screenshot
        Instabug.start(withToken: Constants.Vendor.instabugAppToken, invocationEvent: event)
        Instabug.setEmailFieldRequired(false)
        Instabug.setNetworkLoggingEnabled(false)
        Instabug.setCrashReportingEnabled(false)
        Instabug.setPromptOptionsEnabledWithBug(true, feedback: false, chat: false)
        Instabug.setWillSkipScreenshotAnnotation(true)
        Instabug.setIntroMessageEnabled(false)
        Instabug.setReportCategoriesWithTitles(titles, iconNames: nil)
```

Yet on our Instabug dashboard we're still seeing crash reports. Is there a chance `setCrashReportingEnabled(false)` isn't working as expected? It seems like the other configuration here does work as the modal has the titles we're setting below. This is with Instabug 7.0

**Comment by keith** [comment]
Ah, it appears this may have been fixed somewhere between 7.0 and 7.0.3. But I don't see it in the [release notes](https://github.com/Instabug/Instabug-iOS/releases)

**Comment by keith** [comment]
Is that expected?

**Comment by HeshamMegid** [comment]
Hi @keith, that issue has indeed been fixed in 7.0.3. We haven't added the specifics to the release notes, but 7.0.3 has various other fixes in addition to that one.

**Comment by keith** [comment]
Is there any way you could provide a subspec for this in the future? It would be nice to exclude this logic that we don't need from the SDK, and that would also solve the fact that crashes caught by Instabug weren't getting sent to the crash reporting system we were actually using, so we were silently missing crashes!

**Comment by HeshamMegid** [comment]
@keith, sorry you've missed crashes because of Instabug 😔 

We are actually working on having subspecs for each product we offer, so in the future you'd be able to only import Instabug's bug reporting.

**Comment by SudoPlz** [comment]
I'm missing crash reports from Bugsnag too.

Will disabling crash reports w/ `Instabug.setCrashReportingEnabled(false)` do the trick or do we have to somehow include only specific subspecs (if they exist by now) ?

@HeshamMegid @keith ?

Thanks!

**Comment by Figo0o** [comment]
@SudoPlz, Yes sure, Just disabling Instabug crash reporting will do it. Please let me know after doing so if you still facing any issues.

**Comment by SudoPlz** [comment]
Hmm I'm using `instabug-react-native` and it looks like [crash reports are always de-activated there](https://github.com/Instabug/instabug-reactnative/blob/master/ios/RNInstabug/InstabugReactBridge.m#L36).

I thought that was the reason I did not receive crash reports form my crash reporting tool (bugsnag) but I might haven been wrong after all..

**Comment by NadineMansour** [comment]
@SudoPlz Yes, exactly. 
Given that you are using React Native the crash reporting is disabled by default and Instabug shouldn't affect any other crash reporter that you are using in this case. 

Please, let us know if you have any concerns about this.
