### ISSUE TITLE
Network logs issue

### ISSUE THREAD

**Issue by robertofrontado** [Instabug/Instabug-iOS#133]
Hello guys, I found and issue while using the network logs functionality (which is awesome btw)

I'm using Instabug SDK v7.0.4

My setup is the following:
```swift
    let config = URLSessionConfiguration.default
    config.httpCookieStorage = HTTPCookieStorage.shared
    config.httpCookieAcceptPolicy = .always
    config.httpShouldSetCookies = true
    Instabug.enableLogging(for: config)
    session = Foundation.URLSession(configuration: config, delegate: self, delegateQueue: OperationQueue.main)
```

So since I added `Instabug.enableLogging(for: config)`,  `URLSessionTaskDelegate` stopped working, so this method is not being called anymore:

```swift
 func urlSession(_ session: URLSession, task: URLSessionTask, didSendBodyData bytesSent: Int64, totalBytesSent: Int64, totalBytesExpectedToSend: Int64) {
    let progress = totalBytesSent / totalBytesExpectedToSend
  }
```

Any idea?

**Comment by HeshamMegid** [comment]
Hi @robertofrontado, that definitely should not be happening. Let me check on what might be causing that and get back to you.

**Comment by HeshamMegid** [comment]
@robertofrontado, sorry for the delay in getting back to you about this. We've been looking into it and unfortunately the Foundation class we use to intercept the URL requests made by the app doesn't allow us to do a callback for sending body data (rdar://9226157).

The workaround for this is to set the filter predicate via `+ [Instabug setNetworkLoggingRequestFilterPredicate:responseFilterPredicate:]` to exclude that particular request from logging (which would let you get callbacks for `urlSession(_,task:didSendBodyData:totalBytesSent: totalBytesExpectedToSend:)` normally).

Let me know how that works for you.
