### ISSUE TITLE
UICollectionViewCells are hidden after Reporting Issue via Instabug

### ISSUE THREAD

**Issue by brokenzz** [Instabug/Instabug-iOS#135]
Hello,

I have found that if I report a problem via Instabug when a UICollectionView is on screen, then when the problem is Reported and Instabug overlays disappear, the reusable UICollectionViewCells that are off screen have their `hidden` property set to `YES`.

Which leads to the following situation:

![instabug_bug](https://cloud.githubusercontent.com/assets/10776576/23748878/60960a18-04bd-11e7-9685-b689f68e918d.jpg)

As you can see, numerous cell are "hidden".

There is off course a workaround for this - setting the `self.hidden` property to `NO` in `prepareForReuse`, but nevertheless it would be very good to see this fixed in the Framework itself.

This was initially discovered in v 7.0.3, and still present in v7.0.5.

Thanks

**Comment by Kmohamed** [comment]
Hello @brokenzz
Thanks a lot for reporting this issue.
Actually we fixed this issue and it will be in next release.

**Comment by brokenzz** [comment]
Ah good to know! Thanks! :)

**Comment by HeshamMegid** [comment]
@brokenzz the fix for this issue in include in our 7.1 release. Please check it out.
