### ISSUE TITLE
Crash when calling `Instabug.ibgLog`

### ISSUE THREAD

**Issue by lha-ryq** [Instabug/Instabug-iOS#136]
Hi,
We encountered crash in our application that is related with Instabug. It happened only one time.
Instabug version: 7.0.3
Environment: Xcode8.2.1/Swift3.0.2

Crash due to signal: SIGSEGV(SEGV_MAPERR) at 00000000
Crashed: topspot.DDInstabugLogger
0  libsystem_platform.dylib       0x18bdb0e50 _platform_memmove + 80
1  CoreFoundation                 0x18cc08bc0 _CFStringCheckAndGetCharacters + 260
2  CoreFoundation                 0x18cc08bc0 _CFStringCheckAndGetCharacters + 260
3  CoreFoundation                 0x18cc08a64 -[__NSCFString getCharacters:range:] + 48
4  Foundation                     0x18d7376f0 _NSNewStringByAppendingStrings + 696
5  Foundation                     0x18d7373e8 -[NSString stringByAppendingFormat:] + 136
6  Instabug                       0x1006f6e08 -[IBGMethodsLogger LogMethod:] (IBGMethodsLogger.m:69)
7  Instabug                       0x1007159dc __19+[Instabug IBGLog:]_block_invoke (Instabug.m:938)
8  Instabug                       0x100669328 -[IBGOperationQueue addOperationWithBlock:] (IBGOperationQueue.m:15)
9  Instabug                       0x1007158d4 +[Instabug IBGLog:] (Instabug.m:937)
10 topspot                        0x10033fd90 specialized DDInstabugLogger.log(message : DDLogMessage!) -> () (DDInstabugLogger.swift)
11 topspot                        0x10033f230 @objc DDInstabugLogger.log(message : DDLogMessage!) -> () (DDInstabugLogger.swift)
12 CocoaLumberjack                0x1011fb044 _hidden#77_ (__hidden#178_:824)
13 libdispatch.dylib              0x18bbae1fc _dispatch_call_block_and_release + 24
14 libdispatch.dylib              0x18bbae1bc _dispatch_client_callout + 16
15 libdispatch.dylib              0x18bbbc12c _dispatch_queue_serial_drain + 240
16 libdispatch.dylib              0x18bbb19a4 _dispatch_queue_invoke + 652
17 libdispatch.dylib              0x18bbbe34c _dispatch_root_queue_drain + 572
18 libdispatch.dylib              0x18bbbe0ac _dispatch_worker_thread3 + 124
19 libsystem_pthread.dylib        0x18bdb72a0 _pthread_wqthread + 1288
20 libsystem_pthread.dylib        0x18bdb6d8c start_wqthread + 4

**Comment by HeshamMegid** [comment]
Hi @lha-ryq, we're looking into this and we'll get back to you ASAP.

**Comment by HeshamMegid** [comment]
@lha-ryq we have just shipped an update that fixes this issue. Please check v7.1.

**Comment by lha-ryq** [comment]
Great! Thank you for providing the fix!
