### ISSUE TITLE
Leak in the SDK?

### ISSUE THREAD

**Issue by lgalabru** [Instabug/Instabug-iOS#137]
Hello there,

Profiling my app, I'm noticing a bunch of leaks, caused by your SDK...
Is this a known issue?
Best,

Ludovic

![screen shot 2017-03-13 at 16 10 35](https://cloud.githubusercontent.com/assets/87777/23873237/b5e86518-0807-11e7-97e6-95f5d7faaac4.png)

**Comment by Kmohamed** [comment]
Hello @lgalabru 
Thanks a lot for reporting this issue.
we will fix it as soon as possible.
sorry for that.

**Comment by HeshamMegid** [comment]
@lgalabru, which version of the SDK is this happening on?

**Comment by lgalabru** [comment]
pod 'Instabug', '~> 7.0.2'

**Comment by HeshamMegid** [comment]
This leak has been fixed in v7.0.5, please update and let us know if you're still having any issues.
