### ISSUE TITLE
SQLite error code:11, 'database disk image is malformed'

### ISSUE THREAD

**Issue by bruce-lumo** [Instabug/Instabug-iOS#140]
I'm seeing multiple crash reports with ```SQLite error code:11, 'database disk image is malformed'``` relative to InstabugDataModel.sqlite.

Are there steps to work around this?

Thanks!

**Comment by Kmohamed** [comment]
Hello @bruce 
Could you send to us the stacktrace please ?

**Comment by bruce-lumo** [comment]
[366b2843af333010be9bad3dd3a1ccf6.log.txt](https://github.com/Instabug/Instabug-iOS/files/856450/366b2843af333010be9bad3dd3a1ccf6.log.txt)

**Comment by Kmohamed** [comment]
Is it happening consistently ?

**Comment by bruce-lumo** [comment]
Just twice for the same user two days apart. I haven't been able to reproduce this in the lab.

**Comment by Kmohamed** [comment]
Let me check it and get back to you.

**Comment by Kmohamed** [comment]
@bruce some stack frames aren't symbolicated "instabug stack frame" could you provide us these frames symbolicated ?

**Comment by Kmohamed** [comment]
@bruce-lumo Thanks a lot for reporting this to us it will be fixed in the next release SDK v7.1.1

**Comment by bruce-lumo** [comment]
Is this fix in 7.2?

**Comment by Kmohamed** [comment]
Yes it will fix it.

**Comment by officialmanishgupta** [comment]
hi @Kmohamed - how did you fix it ?

**Comment by Kmohamed** [comment]
@officialmanishgupta
 If you trying to write to database then the application crashed it will result in `database disk image is malformed` so the fix was changing the options of `NSPersistentStoreCoordinator` to `options[NSSQLitePragmasOption] = @{ @"journal_mode":@"WAL" };` 
which makes checkpoints so if the database is corrupted it can revert to the latest checkpoint.

**Comment by cvinson830** [comment]
Still seeing this happening on v8.5.62.0
"PrepareDB Exception: SQLite3 Error 11: database disk image is malformed [File Size: 16384]."

Stack trace:
```
thread $1a364 (TRunProfile):
00f234d2 SyncBackFree.exe SelectionSettings  347  +45 PrepareDB
00f23bca SyncBackFree.exe SelectionSettings  365   +8 TSelectionDB.Create
00f25acc SyncBackFree.exe SelectionSettings  894   +3 TSelectionSettings.Create
00f25a5f SyncBackFree.exe SelectionSettings  884   +1 TSelectionSettings.Create
013bcf36 SyncBackFree.exe ProfileEngine     2604  +10 TRunProfile.DoSelectedDelete
013c736c SyncBackFree.exe ProfileEngine     5887 +252 TRunProfile.RunTheProfile
013c034e SyncBackFree.exe ProfileEngine     3476 +253 TRunProfile.Execute
004b59cb SyncBackFree.exe madExcept                   HookedTThreadExecute
0054a555 SyncBackFree.exe System.Classes              ThreadProc
0040bed8 SyncBackFree.exe System              72   +0 ThreadWrapper
004b58b1 SyncBackFree.exe madExcept                   CallThreadProcSafe
004b5916 SyncBackFree.exe madExcept                   ThreadExceptFrame
75bc62c2 KERNEL32.DLL                                 BaseThreadInitThunk
>> created by main thread ($18030) at:
013b7dad SyncBackFree.exe ProfileEngine     1209  +35 TRunProfile.Create
```
stack dump:
```
056df244  d7 34 f2 00 de fa ed 0e - 01 00 00 00 07 00 00 00  .4..............
056df254  58 f2 6d 05 d7 34 f2 00 - f0 fb 89 05 78 22 41 0a  X.m..4......x"A.
056df264  00 00 00 00 a4 f9 6d 05 - f8 f9 6d 05 74 f2 6d 05  ......m...m.t.m.
056df274  00 00 00 00 97 4f e8 00 - 78 22 41 0a 98 f3 6d 05  .....O..x"A...m.
056df284  ac f2 6d 05 b8 f2 6d 05 - 00 00 00 00 00 00 00 00  ..m...m.........
056df294  00 00 00 00 72 2d 30 77 - 98 f3 6d 05 a4 f9 6d 05  ....r-0w..m...m.
056df2a4  e8 f3 6d 05 24 f3 6d 05 - 54 f9 6d 05 90 2d 30 77  ..m.$.m.T.m..-0w
056df2b4  a4 f9 6d 05 80 f3 6d 05 - 44 2d 30 77 98 f3 6d 05  ..m...m.D-0w..m.
056df2c4  a4 f9 6d 05 e8 f3 6d 05 - 24 f3 6d 05 5e 34 f2 00  ..m...m.$.m.^4..
056df2d4  a4 f9 6d 05 98 f3 6d 05 - 00 00 00 00 5f f2 2d 77  ..m...m....._.-w
056df2e4  98 f3 6d 05 a4 f9 6d 05 - e8 f3 6d 05 24 f3 6d 05  ..m...m...m.$.m.
056df2f4  5e 34 f2 00 40 fa 6d 05 - 0b 00 00 00 98 f3 6d 05  ^4..@.m.......m.
056df304  3c f7 6d 00 e8 f3 6d 05 - a4 f9 6d 05 0d 00 00 00  <.m...m...m.....
056df314  00 c0 6d 05 00 00 6e 05 - 00 00 00 00 00 00 00 00  ..m...n.........
056df324  00 00 00 00 00 00 00 00 - 48 f3 6d 05 89 d9 ec 00  ........H.m.....
056df334  00 00 00 00 01 00 00 00 - d8 01 be 06 3c f7 6d 05  ............<.m.
056df344  00 00 00 00 00 00 00 00 - ec f5 6d 05 3c f7 6d 05  ..........m.<.m.
056df354  d8 01 be 06 38 f7 6d 05 - 9b 8e e8 00 01 00 00 00  ....8.m.........
056df364  38 f7 6d 05 48 4b ee 00 - d8 01 be 06 58 16 05 0b  8.m.HK......X...
056df374  75 4b ee 00 56 46 e9 00 - f4 a1 9f 9e 20 f9 6d 05  uK..VF...... .m.
```

**Comment by Kmohamed** [comment]
I can’t see Instabug in stacktrace 
Could share with me a complete stacktrace?

**Comment by officialmanishgupta** [comment]
> @officialmanishgupta
> If you trying to write to database then the application crashed it will result in `database disk image is malformed` so the fix was changing the options of `NSPersistentStoreCoordinator` to `options[NSSQLitePragmasOption] = @{ @"journal_mode":@"WAL" };`
> which makes checkpoints so if the database is corrupted it can revert to the latest checkpoint.

Thanks @Kmohamed and sorry I did not revert back, this solution had fixed the issue.
