### ISSUE TITLE
How to disable landscape for instabug pop up view controller?

### ISSUE THREAD

**Issue by yupengyang** [Instabug/Instabug-iOS#141]
for some reason, our app need keep landscape available on target level. But we don't want switch our VCs to landscape mode when user rotate their phone. 

But when instabug VC pop up, it can change to landscape mode. when it dismiss, it may introduce some strange UI problems on Navigation, which is not what we want.

Can I disable landscape mode for instabug VC? how?

**Comment by Kmohamed** [comment]
Hello @yupengyang 
Could you provide us with SDK version number ?

**Comment by yupengyang** [comment]
@Kmohamed version number is 6.1.3

**Comment by Kmohamed** [comment]
@yupengyang Could you update to the latest version it should fix your issue.

**Comment by yupengyang** [comment]
@Kmohamed Thanks！
