### ISSUE TITLE
Question about default metadata tracked by Instabug

### ISSUE THREAD

**Issue by brokenzz** [Instabug/Instabug-iOS#142]
Hello,

Currently Instabug very helpfully reports a lot of metadata with each bug + crash report - such as device info, OS info etc.

However, it also reports the name of the WiFi session the user is connected to, as well as their carrier network. Is there a way to disable these from being reported?

Just to clarify, I am talking about these:

![instabug_report](https://cloud.githubusercontent.com/assets/10776576/24241129/bcb71546-0fab-11e7-8d2d-5c53c1505b97.png)

Thanks

**Comment by HeshamMegid** [comment]
Hi @brokenzz,

Currently we don't have a way to specify fields to omit from a bug report. 

Just to be sure I fully understand, would you please elaborate on why you want to omit those 2 fields?
