### ISSUE TITLE
Identify user with name in web UI

### ISSUE THREAD

**Issue by keith** [Instabug/Instabug-iOS#143]
After the 7.0 SDK was released we moved to using the [`identifyUserWithEmail:name`](https://github.com/Instabug/Instabug-iOS/blob/16fb222bb655662e96262b406488d8ba578a4db3/Instabug.framework/Headers/Instabug.h#L284-L290) instabug call. We previously put the user's name in the `userData` instead, so we could see it on the web UI, but we were assuming this would replace that. Currently I don't see the user's name anywhere on the reports, is this expected?

**Comment by msoliman** [comment]
@keith yes, that's the expected behavior. You can see the user name in the user profile (you can open it by pressing the user email in the report). You can still use the `userData` API that you were using prior to 7.0, specially if you want to view these details on 3rd party integrations like JIRA.

**Comment by keith** [comment]
Ah thanks for pointing that out! It might be nice if the username was on the main page for the bug as well. Thanks!
