### ISSUE TITLE
Pods/Instabug/Instabug.framework/Instabug' was built without full bitcode. All frameworks and dylibs for bitcode must be generated from Xcode Archive or Install build for architecture armv7

### ISSUE THREAD

**Issue by alexsanderkhitev** [Instabug/Instabug-iOS#145]
Hello! When I try to make an archive application, I get such an error.

`Pods/Instabug/Instabug.framework/Instabug' was built without full bitcode. All frameworks and dylibs for bitcode must be generated from Xcode Archive or Install build for architecture armv7`

**Comment by HeshamMegid** [comment]
Hi @alexsanderkhitev, we are aware of this issue and we'll be releasing an update very shortly that fixes it.

**Comment by alexsanderkhitev** [comment]
Hi @HeshamMegid thanks.

**Comment by HeshamMegid** [comment]
@alexsanderkhitev we just released v7.2.2 that fixes this issue. Please give it a try.
