### ISSUE TITLE
Carthage json is incorrect

### ISSUE THREAD

**Issue by edfanhouse** [Instabug/Instabug-iOS#146]
Hi,

The latest release (7.2.3) contains an error in the Carthage.json, a comma is missed so installation with Carthage failed.

**Comment by klaaspieter** [comment]
I fixed this in #149. Using `https://raw.githubusercontent.com/klaaspieter/Instabug-iOS/fix-carthage/Carthage.json` should work until it's merged.

**Comment by HeshamMegid** [comment]
Oops, sorry about that! It's fixed now.
