### ISSUE TITLE
IBGCoreDataPersistenceManager

### ISSUE THREAD

**Issue by KaanOzkan** [Instabug/Instabug-iOS#147]
Our App seems to be crashing at IBGCoreDataPersistenceManager.m line 219. Please take a look. There are many occurences in the past few days. 
Here is the fabric message, unfortunately instabug is not giving enough information

<img width="922" alt="screen shot 2017-04-17 at 2 46 44 pm" src="https://cloud.githubusercontent.com/assets/16736048/25100277/7c75f0e8-237d-11e7-9d20-868e75642200.png">

**Comment by keith** [comment]
Our app is also crashing, with a slightly different core data issue:

```
NSInternalInconsistencyException: This NSPersistentStoreCoordinator has no persistent stores (schema mismatch or migration failure).  It cannot perform a save operation.

0  CoreFoundation          ___exceptionPreprocess
1  libobjc.A.dylib         objc_exception_throw
2  CoreData                -[NSPersistentStoreCoordinator _coordinator_you_never_successfully_opened_the_database_schema_mismatch:]
3  CoreData                -[NSPersistentStoreCoordinator _introspectLastErrorAndThrow]
4  CoreData                ___65-[NSPersistentStoreCoordinator executeRequest:withContext:error:]_block_invoke
5  CoreData                gutsOfBlockToNSPersistentStoreCoordinatorPerform
6  libdispatch.dylib       __dispatch_client_callout
7  libdispatch.dylib       __dispatch_barrier_sync_f_invoke
8  CoreData                __perform
9  CoreData                -[NSPersistentStoreCoordinator executeRequest:withContext:error:]
10 CoreData                -[NSPersistentStoreCoordinator executeRequest:withContext:error:]
11 CoreData                -[NSManagedObjectContext save:]
12 Instabug                __37-[IBGCoreDataPersistenceManager save]_block_invoke_2
13 CoreData                developerSubmittedBlockToNSManagedObjectContextPerform
14 libdispatch.dylib       __dispatch_queue_drain
15 libdispatch.dylib       __dispatch_queue_invoke
16 libdispatch.dylib       __dispatch_root_queue_drain
17 libdispatch.dylib       __dispatch_worker_thread3
18 libsystem_pthread.dylib __pthread_wqthread
19 libsystem_pthread.dylib start_wqthread```

**Comment by keith** [comment]
Should we revert to a previous version of instabug? Will this failure leave all of our users in a broken state?

**Comment by msoliman** [comment]
@keith this should be fixed on 7.2.3. Which version are you on?

**Comment by keith** [comment]
We're on 7.2.2. I can update now. Is this going to be ok for users who have the broken version?

**Comment by msoliman** [comment]
@keith yes. We're handling it as well in 7.2.3

**Comment by keith** [comment]
Actually this was on version 7.0.5

**Comment by msoliman** [comment]
@keith should be fine. Let me know if you encounter any problems on 7.2.3

**Comment by msoliman** [comment]
@KaanOzkan did you try it out on 7.2.3. It should be fixed there. 
Feel free to reopen if you encounter it again on 7.2.3

**Comment by ankushgupta1393** [comment]
@msoliman Hi, I'm also getting the same error for my app what @keith has reported in his comment on Apr 19 2017. Can you please share how can I fix it?

**Comment by HeshamMegid** [comment]
@ankushgupta1393 which version of the SDK are you getting this crash on?

**Comment by ankushgupta1393** [comment]
Just wanted to let you know that I'm getting the same error for another app I'm working on, not Instabug-iOS

**Comment by HeshamMegid** [comment]
That was more than a year ago, so we don't remember what the issue or the fix was 😅
