### ISSUE TITLE
App crashes when adding a screenshot

### ISSUE THREAD

**Issue by omaralbeik** [Instabug/Instabug-iOS#148]
We think that the `getDestinationPointInRect` in `IBGFloatingButton` is causing the problem

How to produce the crash
1- shake to bring the instabug feedback view
2- enter email
3- tap on add a screenshot
4- remove the screenshot and tap on the add screenshot button again

We are using Instabug v7.2.3 in Xcode 8.3

here is the full stack

```
Instabug`-[IBGFloatingButton activerightConstraint]:
    0x101435e40 <+0>:   stp    x22, x21, [sp, #-0x30]!
    0x101435e44 <+4>:   stp    x20, x19, [sp, #0x10]
    0x101435e48 <+8>:   stp    x29, x30, [sp, #0x20]
    0x101435e4c <+12>:  add    x29, sp, #0x20            ; =0x20 
    0x101435e50 <+16>:  mov    x19, x0
    0x101435e54 <+20>:  adrp   x8, 295
    0x101435e58 <+24>:  ldr    x1, [x8, #0xed8]
    0x101435e5c <+28>:  bl     0x1014cc0c8               ; symbol stub for: objc_msgSend
    0x101435e60 <+32>:  mov    x29, x29
    0x101435e64 <+36>:  bl     0x1014cc11c               ; symbol stub for: objc_retainAutoreleasedReturnValue
    0x101435e68 <+40>:  mov    x20, x0
    0x101435e6c <+44>:  adrp   x8, 295
    0x101435e70 <+48>:  ldr    x21, [x8, #0xac0]
    0x101435e74 <+52>:  mov    w2, #0x0
    0x101435e78 <+56>:  mov    x1, x21
    0x101435e7c <+60>:  bl     0x1014cc0c8               ; symbol stub for: objc_msgSend
    0x101435e80 <+64>:  mov    x0, x20
    0x101435e84 <+68>:  bl     0x1014cc0ec               ; symbol stub for: objc_release
    0x101435e88 <+72>:  adrp   x8, 297
    0x101435e8c <+76>:  ldr    x1, [x8, #0x450]
    0x101435e90 <+80>:  mov    x0, x19
    0x101435e94 <+84>:  bl     0x1014cc0c8               ; symbol stub for: objc_msgSend
    0x101435e98 <+88>:  mov    x29, x29
    0x101435e9c <+92>:  bl     0x1014cc11c               ; symbol stub for: objc_retainAutoreleasedReturnValue
    0x101435ea0 <+96>:  mov    x19, x0
    0x101435ea4 <+100>: orr    w2, wzr, #0x1
    0x101435ea8 <+104>: mov    x1, x21
    0x101435eac <+108>: bl     0x1014cc0c8               ; symbol stub for: objc_msgSend
    0x101435eb0 <+112>: mov    x0, x19
    0x101435eb4 <+116>: ldp    x29, x30, [sp, #0x20]
    0x101435eb8 <+120>: ldp    x20, x19, [sp, #0x10]
    0x101435ebc <+124>: ldp    x22, x21, [sp], #0x30
    0x101435ec0 <+128>: b      0x1014cc0ec               ; symbol stub for: objc_release

```

**Comment by Kmohamed** [comment]
Hello @omaralbeik
Could you please send to me a symbolicated stack trace ?

**Comment by omaralbeik** [comment]
@Kmohamed Thank you for your reply
the app is not in the AppStore, could you please advice how to get a symbolicated stack trace

**Comment by Kmohamed** [comment]
Did you use our crash reporting or any other crash reporting ?

**Comment by mattbischoff** [comment]
We’re also running into the same issue.

**Comment by omaralbeik** [comment]
@Kmohamed the crash appears on Instabug crashes dashboard as
```
Crash due to signal: SIGTRAP(TRAP_BRKPT) at e7ffdefe
```

**Comment by Kmohamed** [comment]
@omaralbeik Could you send me the Instabug code which you are use ?

**Comment by omaralbeik** [comment]
@Kmohamed Sure, here it is
```swift
Instabug.start(withToken: "OUR TOKEN", invocationEvent: .shake)
Instabug.setAttachmentTypesEnabledScreenShot(false, extraScreenShot: true, galleryImage: true, voiceNote: false, screenRecording: false)
```

Now I'm wondering should we set first arg to true?

**Comment by Kmohamed** [comment]
@omaralbeik I attach a custom build with a fix
Could you give it a try ?
[Instabug.framework.zip](https://github.com/Instabug/Instabug-iOS/files/942979/Instabug.framework.zip)

**Comment by omaralbeik** [comment]
@Kmohamed Looks like the bug is gone for now
We added the new Instabug framework, removed the previous cocoa pod and report 7 test bugs with the screenshots, didn't get any crash so far.

**Comment by Kmohamed** [comment]
Great 👍 we will release the fix very soon
Sorry for inconvenience.

**Comment by omaralbeik** [comment]
Thank you @Kmohamed !

**Comment by Kmohamed** [comment]
Thanks for your support

**Comment by omaralbeik** [comment]
@Kmohamed We got error shown in the attached image when trying to push the app to the AppStore, any idea why is this happening and how to fix it?
It says that Instabug was not signed with Apple linker
<img width="1307" alt="instabug_crash" src="https://cloud.githubusercontent.com/assets/8127757/25597477/b6301082-2e83-11e7-932f-58ce97746547.png">

**Comment by Kmohamed** [comment]
@omaralbeik
Sorry for that I think you still use framework which is being build using Xcode 8.3 could you use the cocoapods one "build using xcode 8.2"
I think it's a bug in Xcode 8.3.

Also If you still face this issue please inform me

**Comment by omaralbeik** [comment]
@Kmohamed Im sorry I didn't understand, do you mean to add Instabug using Cocoapods again instead of the build you sent here, or just archive the app using Xcode 8.2 ?
btw the crashing bug was happening before upgrading to Xcode 8.3 as well

**Comment by Kmohamed** [comment]
Yes just use the cocoapods one and tell me if it still exist
