### ISSUE TITLE
Network logs issue v7.2.4

### ISSUE THREAD

**Issue by robertofrontado** [Instabug/Instabug-iOS#151]
Hello guys, I just updated Instabug SDK from v7.0.5 to v7.2.4 and Network logs stopped working

```swift
let config = URLSessionConfiguration.default
config.httpCookieStorage = HTTPCookieStorage.shared
config.httpCookieAcceptPolicy = .always
config.httpShouldSetCookies = true
Instabug.enableLogging(for: config)
session = Foundation.URLSession(configuration: config, delegate: self, delegateQueue: OperationQueue.main)
```

Do I have to do something extra? or its a bug on that version?

**Comment by Kmohamed** [comment]
@robertofrontado 
I just tried it now and it's works fine.
I would like to inform you that we only support these content types  "JSON, XML, HTML, PlainText"
Does your request has one of these content types ?

**Comment by robertofrontado** [comment]
@Kmohamed Yes, weird is that it is working with v7.0.5

We are using this `Content-Type:  "application/json; charset=utf-8"`

**Comment by Kmohamed** [comment]
Could you enable SDK Logging throught `setSDKDebugLogsLevel` to Verbose
and send it to me

**Comment by Kmohamed** [comment]
@robertofrontado If Instabug SDK succeed to capture request you should see something like this in console logs: 
[Instabug] Saved network log:"REQUEST_DATA"

**Comment by robertofrontado** [comment]
Nvm, somehow with the new version:
`Instabug.enableLogging(for: configuration)` 
was being called before:
`Instabug.start(withToken: token, invocationEvent: .shake)`

I did some changes and now its working nicely 👍 

Thanks @Kmohamed

**Comment by Kmohamed** [comment]
welcome

**Comment by robertofrontado** [comment]
@Kmohamed Btw regarding this issue https://github.com/Instabug/Instabug-iOS/issues/133

There's a way to log an `http request/response` manually? but with the same format do you use?

**Comment by Kmohamed** [comment]
Actually there is no method to log requests and  response manually.
But I am curious to know why do you want something like this ?

**Comment by robertofrontado** [comment]
Because of [issue #133](https://github.com/Instabug/Instabug-iOS/issues/133), the network logs functionality is messing with this method:

```swift
 func urlSession(_ session: URLSession, task: URLSessionTask, didSendBodyData bytesSent: Int64, totalBytesSent: Int64, totalBytesExpectedToSend: Int64) {
    let progress = totalBytesSent / totalBytesExpectedToSend
  }
```
From `URLSessionTaskDelegate`, its not being called anymore

**Comment by Kmohamed** [comment]
You are right 👍
We will find solution for this issue.
Maybe we can provide an callback with total bytes sent or 
We can provide a way to log requests manually
Anyway I will let you know once we release it.

**Comment by robertofrontado** [comment]
That would be nice 😄 

Thanks @Kmohamed

**Comment by bp323** [comment]
@Kmohamed Do you have a timeframe for tackling the issue, has it been taken up for investigation?

**Comment by Kmohamed** [comment]
@bp323 what about sending custom build untill the next release ?

**Comment by Kmohamed** [comment]
@bp323 @robertofrontado Here is a custom build until we offically relase it 
[Instabug.framework.zip](https://github.com/Instabug/Instabug-iOS/files/970470/Instabug.framework.zip)

**Comment by robertofrontado** [comment]
@Kmohamed what are the differences between that build and the current release? 😄

**Comment by Kmohamed** [comment]
@robertofrontado that build contains api to handle requestProgress
Called "setRequestProgresshandlerforRequest:progressHandler:"

**Comment by robertofrontado** [comment]
@Kmohamed I can't find that method in that build 🤔

**Comment by Kmohamed** [comment]
@robertofrontado sorry I update method name "setNetworkRequestForRequestURL:progressHandler:"

**Comment by robertofrontado** [comment]
Can you upload the custom build again? 👍

**Comment by Kmohamed** [comment]
You did not find it in the previous build ?

**Comment by robertofrontado** [comment]
Nope

**Comment by robertofrontado** [comment]
@Kmohamed Forget about it, its there 😄

**Comment by Kmohamed** [comment]
👍

**Comment by robertofrontado** [comment]
@Kmohamed Ok I don't know what you did, but there's no need to call the new method:

```swift
Instabug.setNetworkRequestForRequest(url) { (task, bytesSent, totalBytesSent, totalBytesExpectedToSend) in
  // Do something..
}
```

Somehow now the method from the delegate is being triggered:

```swift
@objc func urlSession(_ session: URLSession, task: URLSessionTask, didSendBodyData bytesSent: Int64, totalBytesSent: Int64, totalBytesExpectedToSend: Int64) {
  let progress = Float(totalBytesSent) / Float(totalBytesExpectedToSend)
  print("Progress: \(progress)")
}
```

Actually, the new method does not work, its not being triggered

It might be possible that you fixed it?

**Comment by Kmohamed** [comment]
I think you still use the predict to prevent SDK from intercepting the requests.

**Comment by Kmohamed** [comment]
am I right ?

**Comment by robertofrontado** [comment]
Nvm, you're right,

I forgot to fix an issue with the initialization of `Instabug` on that branch,

I did it and now you're method is the one who's being called 👍 

Are you planning on include this for the next release?

**Comment by Kmohamed** [comment]
Yes, It will be in the next release.

**Comment by robertofrontado** [comment]
Do you have a release date?

**Comment by Kmohamed** [comment]
Next week

**Comment by robertofrontado** [comment]
Sounds good, thanks!!! @Kmohamed 👍

**Comment by Kmohamed** [comment]
welcome ☺️
