### ISSUE TITLE
Attach UIImage in Bug Report Available? 

### ISSUE THREAD

**Issue by AhmedShammala** [Instabug/Instabug-iOS#155]
Hi , i spend some time to figure how to attach Images in Real time with each new Bug Report ,
unfortunately i didn't find answer ,  seem **addFileAttachment** read just from main Bundle ? is attaching images like that supported ?

Thanks

**Comment by HeshamMegid** [comment]
Hi @AhmedShammala,

Please check `addFileAttachmentWithURL:`. The file need to exist locally on disk by the time the bug gets sent.

Feel free to reopen if you need further help.
