### ISSUE TITLE
Free hand annotation without shape detection

### ISSUE THREAD

**Issue by eneko** [Instabug/Instabug-iOS#156]
One of my favorite features of Instabug was being able to quickly draw shapes and hand-written text on screen (see the screenshot on your home page).

![landing_page](https://cloud.githubusercontent.com/assets/32922/26079629/42888f1a-3978-11e7-8bcc-e805c7a98b09.png)

Currently this is very hard to do because since version 6.x, Instabug does shape detection and converts the user input into some shapes. This feature is nice, but should be optional and not the default, as it makes it nearly impossible to write text or complex shapes.

**Comment by yousefhamza** [comment]
Hi this Yousef from Instabug team.

Here's a tip, if you tapped the undo button after shape is detected you will get the original shape again.

Hope this helped.

**Comment by HeshamMegid** [comment]
@eneko what you're saying makes sense. We're working on adjusting auto-detected shapes to make the experience easier when handwriting text.

**Comment by eneko** [comment]
Would it be possible to add another button to the bottom toolbar for "Free Writing"? This is, when that option is selected, the app will work as it used to do, without trying to recognize any shapes. Then, if the "Shape" option is selected, it would work as it does now.

**Comment by HeshamMegid** [comment]
@eneko that's a good suggestion. I've added this to our backlog to consider it with the team for a future update.

**Comment by eneko** [comment]
Any updates on this? iOS 11 screenshots look very promising.

**Comment by NadineMansour** [comment]
@eneko I have some updates for you. We are currently working on refactoring the annotation experience. We’ll disable the automatic shape detection and the users will have the freedom to pick if they want to stick to the free hand drawn shapes or the ones detected by Instabug. It should be ready and released in a month.
Btw, I renamed the issue to help everyone catch its topic easily.

**Comment by ZiadAyman** [comment]
Hey @eneko 
I have some updates for you regarding the annotation.
Please update to the latest SDK to version 7.4 and give it a try :)

Shape detection is now an option you can use or leave after you draw on the screen. Give it a try and let me know if its up to expectations!
