### ISSUE TITLE
Permission to use Photos is shown on first launch not when it's actually needed

### ISSUE THREAD

**Issue by samsonjs** [Instabug/Instabug-iOS#157]
The readme in this repo states:

> **The permission alert for accessing the microphone/photo library will NOT appear unless users attempt to attach a voice note/photo while using Instabug**

However this is not true. Permission to use the photo library is requested immediately on first launch, before setting up Instabug or anything.

**Comment by HeshamMegid** [comment]
Hi @samsonjs, unfortunately we haven't been able to reproduce this issue.

A sample app or a code snippets that reproduces this would be highly appreciated.

**Comment by samsonjs** [comment]
Ah, yes you're right. Reducing to the simplest test case eliminated the problem so something more complicated is causing it. I'll try to figure out the real issue.

**Comment by samsonjs** [comment]
This is my mistake. Instabug showed up in the stack but it must have been due to logging or something unrelated. The fault was in our app's code (of course). Sorry for the noise!

**Comment by HeshamMegid** [comment]
@samsonjs no worries, glad you figured it out 🍻
