### ISSUE TITLE
iOS Carthage support not working

### ISSUE THREAD

**Issue by alexkent** [Instabug/Instabug-iOS#165]
Hi,

I added the `binary "https://raw.githubusercontent.com/Instabug/Instabug-iOS/master/Carthage.json"` line to my `Cartfile`, and ran `carthage update` but I' presented with this error:

`
Failed to read file or folder at /private/var/folders/jg/s3qx8p_s75qgcrgtzmgyw2405z4fzn/T/carthage-archive.Ev00Je/__MACOSX/Instabug/Instabug.framework: Error Domain=com.antitypical.Result Code=0 "the DTSDKName key in its plist file is missing" UserInfo={com.antitypical.Result.file=/tmp/carthage-20170519-51100-1ewwkj8/Source/CarthageKit/Project.swift, com.antitypical.Result.function=readFailed, com.antitypical.Result.line=1126, NSLocalizedDescription=the DTSDKName key in its plist file is missing}
`

I'm using Carthage 0.23.0.

**Comment by txaiwieser** [comment]
Same problem here, it started in the last version. This is breaking our CI builds. Can this be fixed quickly? Thanks

**Comment by Figo0o** [comment]
We are so sorry for inconvenience, I'm checking this for now and gonna be fixed ASAP.

**Comment by Figo0o** [comment]
Hello guys, Can you please give it a try now. it should be fix. ✋

**Comment by txaiwieser** [comment]
It did work! Our CI just sent the dayli builds! Thank you! 
:+1:

**Comment by Figo0o** [comment]
Yaaay! 🎉

**Comment by txaiwieser** [comment]
I'm having this problem again.

**Comment by Kmohamed** [comment]
@txaiwieser do you face this problem on your CI or locally ?
maybe a caching problem.

**Comment by txaiwieser** [comment]
Yes, it was a cache problem. Just cleaned the CI cache using `rm -rf ~/Library/Caches/org.carthage.CarthageKit` and now it works!

Thanks again! 👍

**Comment by Kmohamed** [comment]
@txaiwieser you are welcome
