### ISSUE TITLE
Missing bitcode support in 7.2.9?

### ISSUE THREAD

**Issue by wojteklembryk-ah** [Instabug/Instabug-iOS#168]
Trying to build with an app with Instabug 7.2.9 and getting following error:
`.../Frameworks/Instabug.framework" isn’t consistent with the Mach-O in the main bundle. The main bundle Mach-O contains armv7(machine code) and arm64(machine code), while the nested bundle Mach-O contains armv7(bitcode) and armv7s(bitcode) and arm64(bitcode). Verify that all of the targets for a platform have a consistent value for the ENABLE_BITCODE build setting.`

I have enabled bitecode for all targets.

Thanks in advance.

**Comment by Kmohamed** [comment]
@wojteklembryk-ah 
are you using cocoa-pods or manual integration ?

**Comment by wojteklembryk-ah** [comment]
@Kmohamed cocoapods `Using Instabug (7.2.9)`

**Comment by Kmohamed** [comment]
@wojteklembryk-ah This error means the bitcode settings in the application vs the frameworks/extensions it includes, or even just between frameworks/extensions are not consistent.
So are you sure that every framework and extension are enabling bitcode ?
not just the app target.

**Comment by wojteklembryk-ah** [comment]
I have following cocoapods post_install step:
 ```
 installer.pods_project.targets.each { |target|
    target.set_build_setting("ENABLE_BITCODE", "Yes", ['Debug', 'Stage', 'Prod'])
 }
```
Instabug SDK integration is only one change I did.

**Comment by Kmohamed** [comment]
@wojteklembryk-ah I just double checked the latest version of SDK with our [InstabugApp](https://itunes.apple.com/eg/app/instabug/id1230889027?mt=8) and it works.
![screen shot 2017-07-11 at 3 55 20 pm](https://user-images.githubusercontent.com/1115748/28072211-a0fa2e3a-6652-11e7-8593-d2d400cfcf7e.png)

Could you remove Instabug and try to validate the app.

**Comment by wojteklembryk-ah** [comment]
@Kmohamed will do, thanks for support 🍺

**Comment by Kmohamed** [comment]
@wojteklembryk-ah 
urw, Did you figure out the cause of the error ? does the app validated successfully after removing Instabug

**Comment by wojteklembryk-ah** [comment]
@Kmohamed not yet, I'm on it. Will let you know when I'll fix it. Thanks again 👍

**Comment by Kmohamed** [comment]
anytime, waiting your feedback

**Comment by wojteklembryk-ah** [comment]
@Kmohamed it turned out that my CI server had old Xcode version and this coused a problem. cheers

**Comment by Kmohamed** [comment]
@wojteklembryk-ah Great 👍
