### ISSUE TITLE
sdk not open source?

### ISSUE THREAD

**Issue by dustturtle** [Instabug/Instabug-iOS#179]
RT

**Comment by keith** [comment]
I don't work at Instabug, but no, unfortunately it is not.

**Comment by msoliman** [comment]
Thanks @keith. 

@dustturtle It isn't at the moment, it's in the plan to open source it, but we don't have a specific date set yet. Are you having any concerns with it being closed source? Anything I can clear up for you?

**Comment by dustturtle** [comment]
I just want to see the codes inside it. If it's your plan, I will watch your project.
