### ISSUE TITLE
-[IBGMethodSwizzler sendEvent:] + 284

### ISSUE THREAD

**Issue by noinlijin** [Instabug/Instabug-iOS#180]
instabug version :7.3.1

![image](https://user-images.githubusercontent.com/3073370/29342614-4db19a42-825e-11e7-8310-d0dad7a3a499.png)

![image](https://user-images.githubusercontent.com/3073370/29342626-5d333cfa-825e-11e7-8463-ec186b960025.png)

**Comment by Kmohamed** [comment]
@noinlijin let me check and get back to you soon

**Comment by Kmohamed** [comment]
@noinlijin Could you please open an issue on support and I will flow up with you.

**Comment by noinlijin** [comment]
this crash I find it is in flurry crash collect by user ,I can not reappear

**Comment by Kmohamed** [comment]
No problem just open an issue on out support from Instabug website and I will follow up with you

**Comment by reemalashry1** [comment]
Hey @noinlijin 

Would you please contact our support team to follow up with you on this issue?
Just send an email please to: support@instabug.com

**Comment by Kmohamed** [comment]
@noinlijin Please update to the latest version it should fix it feel free to open it again if it shows up again.
