### ISSUE TITLE
Invalid param, Expected String

### ISSUE THREAD

**Issue by SudoPlz** [Instabug/Instabug-iOS#181]
Don't let the app crash when something other than a **string** get's passed to `setUserAttribute` (i.e a boolean)

Instead try to convert it to a string, or fail gracefully (add nothing to the attribute), but don't let the app crash because of it.

**Comment by Figo0o** [comment]
Hello @SudoPlz, We are so sorry for inconvenience, 

Thank you for your feedback, We will keep that in mind and make our API's more defensive as mush as we can.

**Comment by Kmohamed** [comment]
@SudoPlz we added extra check on this method in the new release which will prevent SDK from crash and print an error message in console

**Comment by jacquesdev** [comment]
I'm seeing an issue where it's giving this error on an empty string "" which seems incorrect

**Comment by Kmohamed** [comment]
@jacquesdev could you provide me with more details please.
