### ISSUE TITLE
IBGNewMethodSwizzler assertion crash on viewDidAppear

### ISSUE THREAD

**Issue by kaandedeoglu** [Instabug/Instabug-iOS#185]
We're using Stripe SDK along with Instabug. Presenting `STPPaymentMethodsViewController` crashes our application with the message:

```
Assertion failed: ([NSStringFromSelector(_cmd) isEqualToString:@"viewDidAppear:"]), function __IBGSwizzle_viewDidAppear, file /Users/distiller/ios/Instabug/Helpers/IBGNewMethodSwizzler.m, line 181.
```

doing `Instabug.setUserStepsEnabled(false)` fixes the issue.

**Comment by Kmohamed** [comment]
@kaandedeoglu are you able to reproduce it ?

**Comment by kaandedeoglu** [comment]
yes, it crashes every single time.

**Comment by Kmohamed** [comment]
I will be thankful If you send to me a sample app cause I can not reproduce this crash.
Also It will be helpful if you send to me all third parties you are using.

**Comment by kaandedeoglu** [comment]
I'm afraid I can't create a sample app as setting up Stripe is a complicated process, plus I can't create a sample Stripe key on our company account. As for the dependencies, here's a list after excluding some of our internal ones:

>stripe-ios
mixpanel
Reachability.swift
SimpleKeychain
JVFloatLabeledTextField
MBProgressHUD
Mantle

**Comment by Kmohamed** [comment]
[Instabug.framework.zip](https://github.com/Instabug/Instabug-iOS/files/1246432/Instabug.framework.zip)
@kaandedeoglu here is a custom build with the fix until we release it very soon.

**Comment by Kmohamed** [comment]
@kaandedeoglu we just release version of SDK 7.3.7 with the fix. please let me know if you face this issue again.

**Comment by kaandedeoglu** [comment]
thank you for the great support! I will make sure to try it out soon 👍

**Comment by henawey-t** [comment]
I'm facing this issue again, with NewRelic and I just did a workaround as here: https://discuss.newrelic.com/t/new-relic-conflicts-with-aspects-library-detected-an-unrecognized-selector/35759/3 and it did work. however, they mentioned the author of the library should fix it.
I'm using 10.10.0 with iOS 11 as deployment target
