### ISSUE TITLE
I do not want to add extra Info.plist keys for gallery and audio recording.

### ISSUE THREAD

**Issue by goa** [Instabug/Instabug-iOS#187]
I have disabled voice and gallery images using the following:

[Instabug setAttachmentTypesEnabledScreenShot:YES extraScreenShot:YES galleryImage:NO voiceNote:NO screenRecording:NO];

Do I still have to add the extra Info.plist keys?

Thanks.

**Comment by Kmohamed** [comment]
@goa No you don't need to add keys in the Info.plist

**Comment by goa** [comment]
@Kmohamed If I don't, I get the following warning from iTunes:

Missing Info.plist key - This app attempts to access privacy-sensitive data without a usage description. The app's Info.plist must contain an NSPhotoLibraryUsageDescription key with a string value explaining to the user how the app uses this data.

Missing Info.plist key - This app attempts to access privacy-sensitive data without a usage description. The app's Info.plist must contain an NSMicrophoneUsageDescription key with a string value explaining to the user how the app uses this data.

This is a problem for our company, since we mostly use Instabug as a crash reporter for the production version of our app, but we still require the user feedback capabilities (without voice recording, or gallery photo attachments) for our beta program.

**Comment by Figo0o** [comment]
@goa, We are so sorry for the misunderstanding, Unfortunately you need to add those keys while integrating Instabug because we still have an access to those components although the voice recording and photo gallery attachment buttons are not shown to the user (disabled by the API you've mentioned).

**Comment by Kmohamed** [comment]
@goa @Figo0o is correct I thought it will just give you a warning and will not block you submit to the Appstore so you have to put them in the info.plist.
I am really sorry for that.

**Comment by goa** [comment]
Ok, thanks very much for your help.

Just a comment / suggestion for future releases of the library:

Perhaps the main Instabug lib could be provided without audio recording and photo gallery attachment functionality, and those two could be added in the form of additional plugins.

Thanks again and keep up the good work :)

**Comment by Figo0o** [comment]
Thanks for your feedback, Totally we will keep that in mind and sorry for inconvenience.
