### ISSUE TITLE
"Too many symbol files" when submitting to App Store.

### ISSUE THREAD

**Issue by goa** [Instabug/Instabug-iOS#188]
### Steps to reproduce the problem

I have added Instabug to my project using Cocoapods. I am using the latest version (7.37).
I have uploaded my archive to the App Store.

### Expected behavior

The build should be processed and then be available for testing on iTunes Connect.

### Actual behavior

I receive an e-mail from iTunes Connect saying: "Too many symbol files - These symbols have no corresponding slice in any binary [3DB3A537-99E9-3A79-B51A-25084C271623.symbols]"

I have checked the 3DB3A537-99E9-3A79-B51A-25084C271623 UUID and it belongs to the Instabug dSYM file.

Although I need my app's dSYM file, the Instabug dSYM file should not be included. I believe the Instabug pod should work that way out of the box.

Thanks.

**Comment by Kmohamed** [comment]
@goa Does your app support all architectures ? could you send them to me

**Comment by goa** [comment]
@Kmohamed Our project Build Settings are the following:

**Architectures:** Standard Architectures (armv7, arm64)
**Build Active Architecture Only:** Yes
**Valid Architectures:** arm64, armv7, armv7s

Our app is built entirely on Objective C.

Cocoapods version is 1.3.1.

Please let me know if you need any additional information.

**Comment by Figo0o** [comment]
@goa, Can you please check all your pod targets that they have the same config ?

**Comment by goa** [comment]
@Figo0o, I only have one target in my Podfile. 

This is what it looks like:

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

target 'MyTarget' do
pod 'other-pod'
pod 'other-pod'
**pod 'Instabug', '~> 7.3'**
end

**Comment by Kmohamed** [comment]
@goa First this message will not block your release it's just a warning.
Also this message can be caused by many reasons
May be the app has different Valid architectures than Cocoa-pods target "you confirm that they are the same".
But could you run this command dwarfdump -u Instabug.framework.dSYM and share with me the result ?

**Comment by goa** [comment]
@Kmohamed 

I am confused... I don't see dSYM files from any other pods, only Instabug. 

Actually there are only **two** dSYM files present in my archive. The application's main dSYM and Instabug.framework.dSYM - no other dSYM files, although I am using numerous other pods.

Please see the results of the **dwarfdump -u Instabug.framework.dSYM** command below:

UUID: 30CD93F4-D0C1-3C11-8ABE-E07987E693EA (armv7) Instabug.framework.dSYM/Contents/Resources/DWARF/Instabug
UUID: 3DB3A537-99E9-3A79-B51A-25084C271623 (armv7s) Instabug.framework.dSYM/Contents/Resources/DWARF/Instabug
UUID: 17BCFAEA-2368-3DEF-ADD3-A43ED0DFC1A8 (arm64) Instabug.framework.dSYM/Contents/Resources/DWARF/Instabug

**Comment by Kmohamed** [comment]
Thanks a lot i will investigate a lot in this issue
But could tell me if you enabled bitcode or not ?

**Comment by goa** [comment]
Bitcode is disabled.

Thank you!

**Comment by goa** [comment]
@Kmohamed I just tried submitting a beta build with Bitcode turned on (as it should be) and I get no warnings from iTunes connect anymore.

However the Instabug .dSYM file is still included in my archive and again, no other libraries' dSYMs are included.

Hope that helps :)

**Comment by Figo0o** [comment]
@goa, So everything is working now as expected ?

**Comment by goa** [comment]
With bitcode turned on, yes. Otherwise I see the same problem.

**Comment by Kmohamed** [comment]
@goa I will check it and get back to you soon

**Comment by twobitlabs** [comment]
Same problem here, just updated from Instabug 7.3.2 to to Instabug 7.3.7 and get "Too many symbol files"

**Comment by NadineMansour** [comment]
@twobitlabs Can you please tell me if you are enabling bitcode or not?

**Comment by twobitlabs** [comment]
@NadineMansour yep, bitcode is disabled in the app.

**Comment by twobitlabs** [comment]
The message from iTunes reads:

Too many symbol files - These symbols have no corresponding slice in any binary [3DB3A537-99E9-3A79-B51A-25084C271623.symbols]

When I open my archive and go into the dSYMs folder and run `dwarfdump --uuid *` I see:

```
UUID: 3DB3A537-99E9-3A79-B51A-25084C271623 (armv7s) Instabug.framework.dSYM/Contents/Resources/DWARF/Instabug
```

which is the ONLY armv7s dSym in the bunch. All the other dSyms are armv7 and arm64. On all of my apps I have valid architectures set to "armv7 armv7s arm64", however, when I go into any app archive all of the dSym files are either armv7 or arm64. Instabug is the only framework I'm seeing that's getting an armv7s dSym and that seems to be causing the warning.

**Comment by twobitlabs** [comment]
Well, I'm not sure what the issue was but the issue has cleared up for me. It seems the problem may have been related to switching back and forth between Xcode 9 GM and Xcode 8. I finally did a `git clean -dfx` to remove all untracked and git ignored files in my repo (like cached cocoapods), switched back to Xcode 8, did a clean followed by an archive and submitted a build and had no problem. Then switched to Xcode 9 and archive and submitted and also no problem.

Note of warning if anyone stumbles across this in the future, if you're going to do a `git clean -dfx` on your repo realize that it's going to remove any untracked or ignored files in your repo including xcuserdata settings.

I simply can't get the archive to generate with the extra dSym anymore. Wish I had better steps to help but problem solved for now...

**Comment by NadineMansour** [comment]
@twobitlabs Thank you so much for sharing the fix. 
Please let us know if there is anything we can help you with from our side. 

@goa Does this fix apply to you?

**Comment by winzig** [comment]
I am hesitant to do `git clean -dfx` at this point, but I am still experiencing this issue, and I'm seeing the same thing (only Instabug shows with an armv7s dsym).

**Comment by Kmohamed** [comment]
@winzig did your app supports arm7s ?

**Comment by winzig** [comment]
It does list it as a supported architecture, but I'm not familiar enough with armv7s to know if we really have anyone using our app on that architecture. But none of the other libraries we use have that included.

**Comment by Kmohamed** [comment]
We still trying to find a way to remove un supported architectures from dsyms meanwhile you can upload to appstore it will nit block your release

**Comment by winzig** [comment]
ok

**Comment by kdawgwilk** [comment]
I am also seeing this with Bitcode disabled.  I actually recently disabled bitcode and that is when this issue started

**Comment by Kmohamed** [comment]
Hello @kdawgwilk I checked cocoapods release notes and I found the they are start uploading Framework DSYMs could you go to Framework path and delete the DSYMs file and try to submit again and tell me if it worked.

**Comment by kdawgwilk** [comment]
How can I delete only the architecture I don't want from the DSYM bundle?  I still want the other DSYMs there for crash logs

**Comment by kdawgwilk** [comment]
Looks like the issue will be addressed over in CocoaPods here: CocoaPods/CocoaPods#7111

**Comment by Kmohamed** [comment]
Thanks a lot 👍
Also we still trying to find a way to strip DSYMs.

**Comment by alyakan** [comment]
## Steps to correctly strip symbols

1. In your application's `Podfile` replace `pod 'Instabug'` with `pod 'Instabug', :git => 'https://github.com/Instabug/Instabug-iOS', :branch => 'fix/too-many-symbol-files'`.
2. In XCode, Go to Product -> Scheme -> Edit Scheme. Expand *Archive* section on the left and select Post-actions.
<img width="1440" alt="screen shot 2017-10-21 at 2 50 06 pm" src="https://user-images.githubusercontent.com/10628643/31852198-4969a626-b67c-11e7-8b8f-58e994d933ce.png">
3. Press the **+** Icon on the bottom left and select *New Run Script Action*.
4. Above the edtior that appeared, you will see *Provide build settings from*, select your application's target.
5. Add the following code snippet to the edtior:
```
SCRIPT_SRC=$(find "$PROJECT_DIR" -name 'Instabug_dsym_strip.sh' | head -1)
LOG_FILE="Instabug_dsym_strip_invalid_archs_log.txt"
if [ ! "${SCRIPT_SRC}" ]; then
    cd "${ARCHIVE_DSYMS_PATH}"
    echo "Instabug: err: script not found. Make sure that you're including Instabug.bundle in your project directory" >> $LOG_FILE
    exit 1
fi
source "${SCRIPT_SRC}"
```
6. The end result should look like this
<img width="1440" alt="screen shot 2017-10-21 at 2 49 50 pm" src="https://user-images.githubusercontent.com/10628643/31852196-34c23936-b67c-11e7-9698-c970b9fca2f6.png">

Now archive your application and everything should be well. You can check that everything is working by running `dwarfdump -u Instabug.framework.dSYM` on the dSYM file that can be found inside the archive.

**Comment by Kmohamed** [comment]
@goa @twobitlabs @winzig @kdawgwilk 
could you give this build a try tell If it works ?

**Comment by kdawgwilk** [comment]
I will try that out tomorrow, thanks!

**Comment by Kmohamed** [comment]
Hello @kdawgwilk,
Did you get a chance to check the custom build ?

**Comment by kdawgwilk** [comment]
Yeah I️ did and it seems to be working great

**Comment by mishagray** [comment]
Im seeing this issue with the latest Instabug and targeting iOS 11 only.
(which only does 64bit targets)...

Is there a way to get rid of this warning with the latest build?

**Comment by Kmohamed** [comment]
Are you using cocopods ?

**Comment by mishagray** [comment]
Using cocoapods 1.5.0,  with a min deployment of iOS 11.
My guess is that since iOS 11 drops 32bit support, there is a 32bit dSYM that is getting added to the app?  Not sure how to strip it.

**Comment by Kmohamed** [comment]
@mishagray you are totally right but starting from cocoapods version 1.4.0 it will strip the DSYM file based on application supported architecture.

**Comment by connorpower** [comment]
The issue does indeed seem to be caused by 32-bit symbols being included. We resolved this issue by forcing only 64-bit architectures in our `Podfile`:

```ruby
post_install do |installer|
   installer.pods_project.targets.each do |target|
     target.build_configurations.each do |config|
       config.build_settings['ARCHS'] = '$ARCHS_STANDARD_64_BIT'
     end
   end
 end
```

`ARCHS_STANDARD_64_BIT` is a standard Xcode environment variable, so I assume this solution is somewhat future-proof.

**Comment by vmatsnev** [comment]
Solution that helped me.

Set to all pods deployment target according to deployment target of your project

For example if application for iOS 11 and higher

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
    end
  end
end
