### ISSUE TITLE
Decrease size of library

### ISSUE THREAD

**Issue by AvdLee** [Instabug/Instabug-iOS#189]
Right now the library is about 48MB, which is quite much. We're running CI for each PR and want to improve wherever possible. 

I'm curious about the possibilities of decreasing the library size.

**Comment by NadineMansour** [comment]
@AvdLee Can you please elaborate more on the problem you are facing because of the size. 
Is it fetching the dependencies on CI?

**Comment by AvdLee** [comment]
We're integrating Instabug through a submodule and as the binary is already 48MB, the download takes time on each CI run. We're on caching already, but that does not always solve it.

Question is, why is it 48MB and is it really needed?

**Comment by NadineMansour** [comment]
@AvdLee One main reason behind the SDK size is that it accommodates all the iOS architectures. 
I am trying to understand your use case specifically to be able to tailor a relevant solution. 
Can you please tell me if you are running the CI only on a simulator or not? 
Another question, this problem occurs only while releasing a new build, right?

**Comment by Kmohamed** [comment]
@AvdLee we are working very hard to reduce SDK size since you report this issue.  
so could you try this custom build and tell us if it fits you.
pod ‘Instabug’, :git => ’https://github.com/Instabug/Instabug-iOS.git', :branch => ‘fix/iOS11Optimization’

**Comment by Kmohamed** [comment]
@AvdLee we Just released SDK version 7.3.11 with a big size optimization.

**Comment by AvdLee** [comment]
Great! It's on our roadmap for this sprint. I'll post you back the results. Thanks so far!

**Comment by AvdLee** [comment]
@Kmohamed just wanted to say that we're happy with the results. Quite a big decrease in the library size 🎉

**Comment by Kmohamed** [comment]
@AvdLee you are most welcome 🤩🤩

**Comment by ariofrio** [comment]
This seems to be a problem again. Instabug.framework/Instabug is over 50 MB, and if it is included in a Git repository, GitHub actually rejects the commit.

Is there a way to use Instabug without such a large file in version control that GitHub rejects it?
