### ISSUE TITLE
Upload DSYM Script

### ISSUE THREAD

**Issue by kylehorn** [Instabug/Instabug-iOS#19]
The `Instabug_dsym_upload.sh` script is searching for the first occurrence of either `Instabug startWithToken:@\"[0-9a-zA-Z]*\"` or `Instabug.startWithToken:@\"[0-9a-zA-Z]*\"` in the source code.

We are switching between a staging and production environment which means we have to have the same line of code twice and it will still only use the first one. It also doesn't allow us to use a constant or variable to switch tokens.

Is there a better way to search for this API token? Or some other place we can store the token that can consistently and reliably select the correct token for the correct environment?

**Comment by msoliman** [comment]
You can explicitly set the `APP_TOKEN` in the build phase script itself. Just add `APP_TOKEN="{your token}"` right before the line `source "${SCRIPT_SRC}"`.
You can also check your `CONFIGURATION` environment variable to set the token.

Is this what you were looking for?

**Comment by kylehorn** [comment]
@msoliman yes thank you.
