### ISSUE TITLE
rx.exceptions.OnErrorNotImplementedException · Raw

### ISSUE THREAD

**Issue by SudoPlz** [Instabug/Instabug-iOS#191]
rx.exceptions.OnErrorNotImplementedException
        InternalObservableUtils.java:386 rx.internal.util.InternalObservableUtils$ErrorNotImplementedAction.call
        InternalObservableUtils.java:383 rx.internal.util.InternalObservableUtils$ErrorNotImplementedAction.call
        ActionSubscriber.java:44 rx.internal.util.ActionSubscriber.onError
        SafeSubscriber.java:152 rx.observers.SafeSubscriber._onError
        SafeSubscriber.java:115 rx.observers.SafeSubscriber.onError
        Exceptions.java:205 rx.exceptions.Exceptions.throwOrReport
        SafeSubscriber.java:139 rx.observers.SafeSubscriber.onNext
        PublishSubject.java:305 rx.subjects.PublishSubject$PublishSubjectProducer.onNext
        PublishSubject.java:220 rx.subjects.PublishSubject$PublishSubjectState.onNext
        PublishSubject.java:73 rx.subjects.PublishSubject.onNext
        EventBus.java:24 com.instabug.library.core.eventbus.a.a
        SDKCoreEventPublisher.java:9 com.instabug.library.core.eventbus.coreeventbus.b.a
        SessionManager.java:233 com.instabug.library.l.a
        SessionManager.java:202 com.instabug.library.l.k
        SessionManager.java:138 com.instabug.library.l.c
        SessionManager.java:269 com.instabug.library.l.a
        CurrentActivityLifecycleChanged.java:25 com.instabug.library.tracking.b.onReceive
        LocalBroadcastManager.java:297 android.support.v4.content.LocalBroadcastManager.executePendingBroadcasts
        LocalBroadcastManager.java:46 android.support.v4.content.LocalBroadcastManager.access$000
        LocalBroadcastManager.java:116 android.support.v4.content.LocalBroadcastManager$1.handleMessage
        Handler.java:102 android.os.Handler.dispatchMessage
        Looper.java:154 android.os.Looper.loop
        ActivityThread.java:6688 android.app.ActivityThread.main
        Method.java:-2 java.lang.reflect.Method.invoke
        ZygoteInit.java:1468 com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run
        ZygoteInit.java:1358 com.android.internal.os.ZygoteInit.main

    Caused by: java.util.ConcurrentModificationException
        HashMap.java:851 java.util.HashMap$HashIterator.nextEntry
        HashMap.java:891 java.util.HashMap$EntryIterator.next
        HashMap.java:890 java.util.HashMap$EntryIterator.next
        InstabugUserEventLogger.java:185 com.instabug.library.logging.InstabugUserEventLogger$1.a
        InstabugUserEventLogger.java:180 com.instabug.library.logging.InstabugUserEventLogger$1.call
        ActionSubscriber.java:39 rx.internal.util.ActionSubscriber.onNext
        SafeSubscriber.java:134 rx.observers.SafeSubscriber.onNext
        PublishSubject.java:305 rx.subjects.PublishSubject$PublishSubjectProducer.onNext
        PublishSubject.java:220 rx.subjects.PublishSubject$PublishSubjectState.onNext
        PublishSubject.java:73 rx.subjects.PublishSubject.onNext
        EventBus.java:24 com.instabug.library.core.eventbus.a.a
        SDKCoreEventPublisher.java:9 com.instabug.library.core.eventbus.coreeventbus.b.a
        SessionManager.java:233 com.instabug.library.l.a
        SessionManager.java:202 com.instabug.library.l.k
        SessionManager.java:138 com.instabug.library.l.c
        SessionManager.java:269 com.instabug.library.l.a
        CurrentActivityLifecycleChanged.java:25 com.instabug.library.tracking.b.onReceive
        LocalBroadcastManager.java:297 android.support.v4.content.LocalBroadcastManager.executePendingBroadcasts
        LocalBroadcastManager.java:46 android.support.v4.content.LocalBroadcastManager.access$000
        LocalBroadcastManager.java:116 android.support.v4.content.LocalBroadcastManager$1.handleMessage
        Handler.java:102 android.os.Handler.dispatchMessage
        Looper.java:154 android.os.Looper.loop
        ActivityThread.java:6688 android.app.ActivityThread.main
        Method.java:-2 java.lang.reflect.Method.invoke
        ZygoteInit.java:1468 com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run
        ZygoteInit.java:1358 com.android.internal.os.ZygoteInit.main

### SDK version
instabug-react-native: 2.0.3

**Comment by Kmohamed** [comment]
Hi @sudoplz is this from android app ?

**Comment by SudoPlz** [comment]
Whooooops yeah, sorry for that, yeah let me open another thread there..
