### ISSUE TITLE
Allow a configuration to go straight to "Report a bug" or "Submit feedback"

### ISSUE THREAD

**Issue by jlmendezbonini** [Instabug/Instabug-iOS#20]
The SDK currently has `+ invokeBugReporter` and `+ invokeFeedbackSender` to bypass the action sheet, but it would be great if we could have an `SDK Experience Customization` set of methods along the lines of: `+ setDefaultToBugReporter ` and `+setDefaultToSendFeedback` to skip the action sheet.

**Comment by msoliman** [comment]
@jlmendezbonini Actually you can do that using the method 
```[Instabug setDefaultInvocationMode:(IBGInvocationMode)invocationMode];```

It's set by default to `IBGInvocationModeNA` which shows the action sheet, but you can set it to either `IBGInvocationModeBugReporter` or `IBGInvocationModeFeedbackSender` to skip the action sheet.

Is this what you were looking for?
