### ISSUE TITLE
Top-left exit button is not responsive

### ISSUE THREAD

**Issue by asklausen** [Instabug/Instabug-iOS#206]
Using iOS 11.

Problem: It's very difficult to exit the initial "Report a problem" screen, as the top-left button is not very responsive.

**Comment by asklausen** [comment]
Action area is too small. Sometimes I'm able to click it on my first or second try. But very often, I use 5-6 taps before it reacts.

In comparison, I'm easily able to tap other buttons such as the top-right arrow on my first try.

**Comment by Kmohamed** [comment]
let me check it and get back to you soon.

**Comment by Kmohamed** [comment]
@asklausen we fixed the bug and here is custom build with the fix kindly check it.
pod ‘Instabug’, :git => ’https://github.com/Instabug/Instabug-iOS.git', :branch => ‘fix/CloseButton-actionArea-iOS11’

**Comment by asklausen** [comment]
@Kmohamed Great. It's working. Thanks for the quick fix!

**Comment by Kmohamed** [comment]
@asklausen you are welcome 😊
