### ISSUE TITLE
Unstable in-app push notification

### ISSUE THREAD

**Issue by asklausen** [Instabug/Instabug-iOS#207]
Using iOS 11.

Installing an application for the first time, in which Instabug is configured in the AppDelegate, an in-app push notification containing the latest message to the user, is shown at the top of the screen every time. Even though Push Notifications && Chat are both set to false as seen in the info below.

Instabug is configured with the following information:

.start(..)
.setPrimaryColor(..)
.setPushNotificationsEnabled(false)
.setShakingTreshholdForiPhone(..)
.setPromptOptionsEnabledWithBug(true, feedback:false, chat: false)
.setAttachmentTypesEnabledScreenShot(..)
.setIntroMessage(false)

**Comment by Kmohamed** [comment]
You should disable in app notification using this api setChatNotificationEnabled

**Comment by asklausen** [comment]
Awesome. This solved it. Thanks!
