### ISSUE TITLE
Error building for simulator run -> fatal error: lipo: -remove's specified would result in an empty fat file

### ISSUE THREAD

**Issue by lm2s** [Instabug/Instabug-iOS#208]
### Steps to reproduce the problem
Build and run on Simulator

### Expected behavior
Build and run on Simulator

### Actual behavior
Build fails with error:
`fatal error: lipo: -remove's specified would result in an empty fat file`

### SDK version
7.3.12 (via Cocoapods)

### iOS Version
9, 10, 11...

### Device
Any Simulator

Maybe the problem lies in Cocoapods? But only Instabug is causing this problem, other pods are build without issue.. Realm, Mapbox, ...

**This error does not occur when running in a physical device.**

**Comment by Kmohamed** [comment]
@lm2s let me check it and get back to you soon.

**Comment by Kmohamed** [comment]
@lm2s I just tried what you said and it works fine could you try to remove pods and install it again I think it's error from Cocoapods.

**Comment by lm2s** [comment]
Yes, I tried to deintegrate, clear caches, generate new xcworkspace and I still get this error. If it's only happening here, then it must be related to me having removed almost all simulators and then re-adding them. I'll try to reinstall Xcode to see if it fixes the issue.

**Comment by Kmohamed** [comment]
that's weird!!! Also I am waiting your feedback.

**Comment by piellarda** [comment]
I have the same issue and if I look at the cocoapods script called [CP] Embed Pods Framework in the build phase I have the following input files:
${PODS_ROOT}/Instabug/Instabug.framework
${PODS_ROOT}/Instabug/Instabug.framework.dSYM
all my other pods are like 
${BUILT_PRODUCTS_DIR}/<framework_name>/<framework_name>.framework

**Comment by lm2s** [comment]
@piellarda I believe that's related to a framework being pre-built. Mapbox has the same kind of input files that Instabug has.

**Comment by Kmohamed** [comment]
@piellarda could you tell me what version of Cocoapods you are using ?
@lm2s Yes we have to distribute .framework and .DSYMs files in order to allow symbolication of Instabug frames in application crash file.

**Comment by piellarda** [comment]
So this probably due to the use of the beta version of cocoapods 1.4.0.beta.2.
https://github.com/CocoaPods/CocoaPods/issues/7196

**Comment by Kmohamed** [comment]
@piellarda Great news 🎉🎉🎉
@lm2s could you confirm that it's cocoapods issues ?

**Comment by lm2s** [comment]
🎉🎉🎉

Yes, it's 1.4.0.beta.2. I downgraded to 1.3.1 and it's building correctly again.

**Comment by Kmohamed** [comment]
Fantastic 🤩
