### ISSUE TITLE
issue on running 

### ISSUE THREAD

**Issue by NrmeenTomoum** [Instabug/Instabug-iOS#210]
error: failed to remove /Users/macbook/Library/Developer/Xcode/DerivedData/Akalney-dgyrdpsewmczzsamslwqqrehiekk/Build/Products/Debug-iphoneos/Akalney.app/Info.plist: “Info.plist” couldn’t be removed.

After I added SDK, I got this error

**Comment by Kmohamed** [comment]
@NrmeenTomoum I don't think so this error related to Instabug could you double check the error ?

**Comment by NrmeenTomoum** [comment]
Oooh Instabug discover bugs in and out, it is worked fine now thanks @Kmohamed

**Comment by Kmohamed** [comment]
@NrmeenTomoum urw anytime 😊
