### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by NrmeenTomoum** [Instabug/Instabug-iOS#211]
when I touch on attachmentActionSheet :
for first time  ==> give blue color 
for second time of touch === > Crash

**Comment by Kmohamed** [comment]
@NrmeenTomoum could you tell me your SDK version ?

**Comment by NrmeenTomoum** [comment]
The leatest one v 3.7.13

**Comment by Kmohamed** [comment]
@NrmeenTomoum could you provide me with stack trace ?

**Comment by NrmeenTomoum** [comment]
Reported at: 2017-11-21 17:33:36 UTC
Thread 0:
0 libsystem_kernel.dylib 0x1825e0bc4 mach_absolute_time + 4 1 CoreFoundation 0x182a8fce4 _CFPropertyListCreateSingleValue + 304 2 CoreFoundation 0x182a8d8b0 CFPlugInFindFactoriesForPlugInType + 72 3 CoreFoundation 0x1829ae2d8 CFNumberGetValue + 216 4 GraphicsServices 0x18483ff84 GSEventRunModal + 84 5 UIKit 0x18bf5b880 UIApplicationMain + 228 6 Akalney 0x10116d5c0 (null) 7 libdyld.dylib 0x1824d256c start + 4
Thread 1:
0 libsystem_kernel.dylib 0x1825e0bc4 mach_absolute_time + 4 1 CoreFoundation 0x182a8fce4 _CFPropertyListCreateSingleValue + 304 2 CoreFoundation 0x182a8d8b0 CFPlugInFindFactoriesForPlugInType + 72 3 CoreFoundation 0x1829ae2d8 CFNumberGetValue + 216 4 Foundation 0x1833d66e4 -[NSString stringByTrimmingCharactersInSet:] + 104 5 Foundation 0x1833f5afc -[NSIndexPath copyWithZone:] + 0 6 UIKit 0x18caa702c -[UITextView _firstGlyphBaselineRightPointWithLayoutManager:] + 368 7 Foundation 0x1834d7860 -[NSThread runLoop] + 56 8 libsystem_pthread.dylib 0x18271432c _pthread_start + 100 9 libsystem_pthread.dylib 0x1827141f8 pthread_attr_getschedpolicy + 28 10 libsystem_pthread.dylib 0x182712c38 thread_start + 4
Thread 2:
0 libsystem_kernel.dylib 0x1825e0bc4 mach_absolute_time + 4 1 CoreFoundation 0x182a8fce4 _CFPropertyListCreateSingleValue + 304 2 CoreFoundation 0x182a8d8b0 CFPlugInFindFactoriesForPlugInType + 72 3 CoreFoundation 0x1829ae2d8 CFNumberGetValue + 216 4 CoreFoundation 0x1829fd12c -[NSSet descriptionWithLocale:indent:] + 40 5 CoreMotion 0x187d92088 0x0000000185e46088 + 952 6 libsystem_pthread.dylib 0x18271432c _pthread_start + 100 7 libsystem_pthread.dylib 0x1827141f8 pthread_attr_getschedpolicy + 28 8 libsystem_pthread.dylib 0x182712c38 thread_start + 4
Thread 3:
0 libsystem_kernel.dylib 0x1825e0bc4 mach_absolute_time + 4 1 CoreFoundation 0x182a8fce4 _CFPropertyListCreateSingleValue + 304 2 CoreFoundation 0x182a8d8b0 CFPlugInFindFactoriesForPlugInType + 72 3 CoreFoundation 0x1829ae2d8 CFNumberGetValue + 216 4 CFNetwork 0x183117b40 _CFURLCacheCopyAllPartitionNames + 20 5 Foundation 0x1834d7860 -[NSThread runLoop] + 56 6 libsystem_pthread.dylib 0x18271432c _pthread_start + 100 7 libsystem_pthread.dylib 0x1827141f8 pthread_attr_getschedpolicy + 28 8 libsystem_pthread.dylib 0x182712c38 thread_start + 4
Thread 4:
0 libsystem_kernel.dylib 0x1825e0bc4 mach_absolute_time + 4 1 Instabug 0x102b38d00 exception_server_thread + 200 2 libsystem_pthread.dylib 0x18271432c _pthread_start + 100 3 libsystem_pthread.dylib 0x1827141f8 pthread_attr_getschedpolicy + 28 4 libsystem_pthread.dylib 0x182712c38 thread_start + 4
Thread 5:
0 libsystem_kernel.dylib 0x1825e0bc4 mach_absolute_time + 4 1 CoreFoundation 0x182a8fce4 _CFPropertyListCreateSingleValue + 304 2 CoreFoundation 0x182a8d8b0 CFPlugInFindFactoriesForPlugInType + 72 3 CoreFoundation 0x1829ae2d8 CFNumberGetValue + 216 4 CFNetwork 0x183296928 ___ZN12DispatchHost18signalKickerLockedEv_block_invoke + 0 5 libsystem_pthread.dylib 0x18271432c _pthread_start + 100 6 libsystem_pthread.dylib 0x1827141f8 pthread_attr_getschedpolicy + 28 7 libsystem_pthread.dylib 0x182712c38 thread_start + 4
Thread 6:
0 libsystem_kernel.dylib 0x182601dbc __wait4_nocancel + 20 1 libsystem_pthread.dylib 0x182712c30 start_wqthread + 4
Thread 7:
0 libsystem_kernel.dylib 0x1825e2ebc thread_get_state + 28 1 libsqlite3.dylib 0x182f5801c 0x000000018100c01c + 664 2 libsqlite3.dylib 0x182f4c3b8 sqlite3_column_double + 188 3 libsqlite3.dylib 0x182f38ddc 0x0000000180fecddc + 168 4 libsqlite3.dylib 0x182f061b0 0x0000000180fba1b0 + 2572 5 libsqlite3.dylib 0x182f31f74 0x0000000180fe5f74 + 56556 6 libsqlite3.dylib 0x182f23b7c sqlite3_step + 3732 7 libsqlite3.dylib 0x182eedd68 sqlite3_exec + 536 8 Akalney 0x101298cfc (null) 9 Akalney 0x1012989bc (null) 10 Akalney 0x1012b4fc4 (null) 11 Akalney 0x1012b49ec (null) 12 Akalney 0x1012c66e4 (null) 13 libdispatch.dylib 0x18246d088 _dispatch_call_block_and_release + 24 14 libdispatch.dylib 0x18246d048 _dispatch_client_callout + 16 15 libdispatch.dylib 0x182476e48 _dispatch_queue_class_wakeup$VARIANT$mp + 532 16 libdispatch.dylib 0x1824777d8 _dispatch_queue_serial_drain$VARIANT$mp + 1136 17 libdispatch.dylib 0x182478200 _dispatch_queue_invoke$VARIANT$mp + 932 18 libdispatch.dylib 0x1824804a0 dispatch_source_set_timer$VARIANT$mp + 104 19 libsystem_pthread.dylib 0x182712fe0 _pthread_wqthread + 404 20 libsystem_pthread.dylib 0x182712c30 start_wqthread + 4
Thread 8 [Crashed]:
0 libsystem_kernel.dylib 0x1826000a8 carbon_delete + 28 1 libsystem_kernel.dylib 0x1825fb12c mach_get_times + 112 2 TCC 0x18554d99c CRASHING_DUE_TO_PRIVACY_VIOLATION + 208 3 TCC 0x18554d8bc TCCAccessRequest_block_invoke.75 + 692 4 TCC 0x18555113c __tccd_send_block_invoke + 300 5 libxpc.dylib 0x18274da0c _xpc_dictionary_apply_wire_f + 248 6 libxpc.dylib 0x18274d948 _xpc_dictionary_apply_wire_f + 52 7 libdispatch.dylib 0x18246d758 _dispatch_send_consume_send_once_right + 72 8 libdispatch.dylib 0x182485060 dispatch_mach_send_barrier_f$VARIANT$mp + 144 9 libdispatch.dylib 0x182473f54 _dispatch_async_redirect_invoke$VARIANT$mp + 360 10 libdispatch.dylib 0x18247a1c8 _dispatch_main_queue_callback_4CF$VARIANT$mp + 132 11 libdispatch.dylib 0x182479f10 _dispatch_runloop_root_queue_perform_4CF$VARIANT$mp + 1344 12 libsystem_pthread.dylib 0x182713130 _pthread_wqthread + 740 13 libsystem_pthread.dylib 0x182712c30 start_wqthread + 4
Thread 9:
0 libsystem_kernel.dylib 0x182601dbc __wait4_nocancel + 20 1 libsystem_pthread.dylib 0x182712c30 start_wqthread + 4
Thread 10:
0 libsystem_kernel.dylib 0x1825e0bc4 mach_absolute_time + 4 1 CoreFoundation 0x182a8fce4 _CFPropertyListCreateSingleValue + 304 2 CoreFoundation 0x182a8d8b0 CFPlugInFindFactoriesForPlugInType + 72 3 CoreFoundation 0x1829ae2d8 CFNumberGetValue + 216 4 AVFAudio 0x188277774 AVAudioSessionAddSPIPropertListeners(AVAudioSession*) + 2196 5 AVFAudio 0x1882a2018 GCC_except_table3 + 56 6 libsystem_pthread.dylib 0x18271432c _pthread_start + 100 7 libsystem_pthread.dylib 0x1827141f8 pthread_attr_getschedpolicy + 28 8 libsystem_pthread.dylib 0x182712c38 thread_start + 4
Thread 11:
0 libsystem_kernel.dylib 0x182601dbc __wait4_nocancel + 20 1 libsystem_pthread.dylib 0x182712c30 start_wqthread + 4
Binary Images:
0x1825e0000 libsystem_kernel.dylib arm64 05B1DA08-EBA1-3342-B0A7-76A29AD02C23 0x1829a6000 CoreFoundation arm64 89E52E2B-D28F-3D3E-BB80-0ED0D39A067F 0x184835000 GraphicsServices arm64 90FDE06D-13AF-38FD-9E26-1FCE7D8F90A1 0x18bee8000 UIKit arm64 0ACB1223-8243-3154-9D21-7A9941528BDF 0x100fc8000 Akalney arm64 44839C9B-4CE2-34B3-A2E1-95675C4E511F 0x1824d1000 libdyld.dylib arm64 07EA3EDA-E26B-33CC-B1E8-8EF771FF7EE4 0x1833ca000 Foundation arm64 EF884462-CA23-3774-A8BD-EB9D443ACDA9 0x182712000 libsystem_pthread.dylib arm64 79349704-B029-373D-A3A4-116DA895EADC 0x187d16000 CoreMotion arm64 59997815-A733-3F01-8512-DF3E05612FAF 0x183069000 CFNetwork arm64 D800884A-C364-3FD3-985B-4F9901874F31 0x102a20000 Instabug arm64 D32D6AEF-8499-3EC7-8F8C-8600A7DF0C17 0x182ee3000 libsqlite3.dylib arm64 2482D470-50D5-3820-BA2C-94E7069EBA3C 0x18246c000 libdispatch.dylib arm64 D1654155-0D40-3E77-967B-D529061C87A4 0x18554c000 TCC arm64 55DF2388-DEB0-36D0-B400-92217B2B1903 0x182749000 libxpc.dylib arm64 A75CF23F-010B-383A-AA4A-5A162F4DA1F8 0x1881f3000 AVFAudio arm64 4B3F80EC-E4FF-3AEB-B7CB-594C390667A4
Number: 2
URL: https://insta.co/crashes/6J0iIJC5
Status: New
Email: nrmeen.tomoum@alumni.fci-cu.edu.eg
Reported At: 2017-11-21 17:33:36 UTC
Location: Cairo, Egypt
Device: iPhone 6 Plus
Memory: 799.0/820.0 MB
Storage: 7.975/61.025 GB
Connectivity: Carrier: Vodafone, WiFi: OSALCOM
Battery: 67, Charging
App Version: 1.10 (1)
Duration: 220
User Data:
Console Log:

Instabug Log:

User Steps:
 email(UITextField) in Akalney.MenuTableViewController

1511285503812 Selector: emailChanged: by email(UITextField) in Akalney.MenuTableViewController

1511285503911 Selector: emailChanged: by email(UITextField) in Akalney.MenuTableViewController

1511285504012 Selector: emailChanged: by email(UITextField) in Akalney.MenuTableViewController

1511285504111 Selector: emailChanged: by email(UITextField) in Akalney.MenuTableViewController

1511285504222 Selector: emailChanged: by email(UITextField) in Akalney.MenuTableViewController

1511285504239 Selector: emailChanged: by email(UITextField) in Akalney.MenuTableViewController

1511285504935 Swipe: (UIKeyboardLayoutStar) in Akalney.MenuTableViewController

1511285505849 Touch: (IBGTextView) in Akalney.MenuTableViewController

1511285506783 Touch: (IBGButton) in Akalney.MenuTableViewController

1511285506785 Selector: cancelButtonPressed: by (IBGButton) in Akalney.MenuTableViewController

1511285509101 Shake in: Akalney.MenuTableViewController

1511285509500 Shake in: Akalney.MenuTableViewController

1511285509686 Shake in: Akalney.MenuTableViewController

1511285510395 Shake in: Akalney.MenuTableViewController

1511285522612 Shake in: Akalney.MenuTableViewController

1511285523369 Shake in: Akalney.MenuTableViewController

1511285525092 Shake in: Akalney.MenuTableViewController

1511285526688 Shake in: Akalney.MenuTableViewController

1511285536008 Shake in: Akalney.MenuTableViewController

1511285536716 Shake in: Akalney.MenuTableViewController

1511285548658 Shake in: Akalney.MenuTableViewController

1511285549920 Shake in: Akalney.MenuTableViewController

1511285550306 Shake in: Akalney.MenuTableViewController

1511285552113 Shake in: Akalney.MenuTableViewController

1511285561832 Shake in: Akalney.MenuTableViewController

1511285563829 Shake in: Akalney.MenuTableViewController

1511285569824 Touch: (UITableViewCellContentView) in Akalney.MenuTableViewController

1511285571824 Touch: (IBGButton) in Akalney.MenuTableViewController

1511285571825 Selector: nextButtonTapped: by (IBGButton) in Akalney.MenuTableViewController

1511285579710 Touch: (UIKeyboardLayoutStar) in Akalney.MenuTableViewController

1511285590077 Touch: (UIView) in Akalney.MenuTableViewController

1511285594844 Touch: (UIView) in Akalney.MenuTableViewController

1511285595877 Touch: (UIView) in Akalney.MenuTableViewController

1511285596426 Touch: (UIView) in Akalney.MenuTableViewController

1511285597192 Touch: (IBGTextView) in Akalney.MenuTableViewController

1511285598310 Touch: (UIView) in Akalney.MenuTableViewController

1511285602411 Touch: (IBGTextView) in Akalney.MenuTableViewController

1511285604427 Touch: (IBGTextView) in Akalney.MenuTableViewController

1511285605419 Touch: (UIView) in Akalney.MenuTableViewController

1511285606561 Touch: (IBGTextView) in Akalney.MenuTableViewController

1511285614453 Touch: (UIView) in Akalney.MenuTableViewController

1511285616012 Touch: (UIView) in Akalney.MenuTableViewController
Current View: NA
Orientation: Unknown
Screen Size: 414x736
Density: @3X
@Kmohamed

**Comment by Kmohamed** [comment]
@NrmeenTomoum The crash is due to __CRASHING_DUE_TO_PRIVACY_VIOLATION__
could you please add the permission keys inside the info.plist as mentioned [here](https://docs.instabug.com/docs/ios-integration#section-microphone-and-photo-library-usage-description)
