### ISSUE TITLE
it is normal behavier

### ISSUE THREAD

**Issue by NrmeenTomoum** [Instabug/Instabug-iOS#213]
![2017-11-28 at 09 49 43 1](https://user-images.githubusercontent.com/19241793/33308463-3935a51a-d423-11e7-944a-f6b4100ef383.png)

### SDK 
 version v7.3.13

### iOS 
Version 11.0.3

### 
Device iPhone 6

**Comment by Kmohamed** [comment]
@NrmeenTomoum could you reproduce this bug ?

**Comment by NrmeenTomoum** [comment]
It is bug, yes I can reproduce this bug

**Comment by Kmohamed** [comment]
@NrmeenTomoum could you give me the scenario please ?

**Comment by NrmeenTomoum** [comment]
this demo show all scenario 
[https://www.mediafire.com/file/5n91w5r93xm4skr/2017-11-28+at+09.49.43.mp4](url)

**Comment by Kmohamed** [comment]
Thanks i will check it now

**Comment by ZiadAyman** [comment]
Hey @NrmeenTomoum 

Can you please update your SDK to the latest version 7.4 and check if this behavior is still taking place or not?

**Comment by ZiadAyman** [comment]
Hey @NrmeenTomoum 
I will close this for now. Please get back to us if you need any further assistance here or contact our support team on contactus@instabug.com
