### ISSUE TITLE
Crashes on Clicking Screen Record Button

### ISSUE THREAD

**Issue by joshuacleetus** [Instabug/Instabug-iOS#215]
### Steps to reproduce the problem
Shake the app and the Instabug form appears.
Click on Suggest an improvement
Then Click on take a screen recording 
And the app crashes

### Expected behavior
When we click Take a screen recording it should record the screen 

### Actual behavior
App crashes

### Instabug integration code "Don't put your token publicly"
        Instabug.start(withToken: "abcd", invocationEvent: .shake)

### SDK version
7.3.14
### iOS Version
11.0
### Device
iphone 6

**Comment by Kmohamed** [comment]
The crash is due to CRASHING_DUE_TO_PRIVACY_VIOLATION
could you please add the permission keys inside the info.plist as mentioned here
https://docs.instabug.com/docs/ios-integration#section-microphone-and-photo-library-usage-description
