### ISSUE TITLE
Keyboard not showing automatically

### ISSUE THREAD

**Issue by anfriis** [Instabug/Instabug-iOS#221]
### Steps to Reproduce the Problem
- Use newest version v7.6 and run on iPhone X
- Shake to open Instabug dialog
- Choose either of the options (report problem or suggest improvement)
- The view expands but the keyboard does not show up, unless the text field is tapped
- I tried with a previous version (v7.3.5) and it works fine with that version

### Expected Behavior
- The keyboard should show up automatically after opening the page

### Actual Behavior
- The keyboard does NOT show up automatically after opening the page

### Instabug integration code
```
Instabug.setCrashReportingEnabled(false)
Instabug.setShakingThresholdForiPhone(1.8, foriPad: 1.6)
Instabug.setEmailFieldRequired(false)
Instabug.setShowEmailField(false)
Instabug.setPromptOptionsEnabledWithBug(true, feedback: true, chat: false)
Instabug.setPushNotificationsEnabled(true)
Instabug.setColorTheme(.light)
Instabug.setIntroMessageEnabled(false)
Instabug.setPrimaryColor(UIColor.defaultColor)
Instabug.setUserStepsEnabled(false)
Instabug.setLocale(.danish)
Instabug.setNetworkLoggingEnabled(false)
Instabug.setViewHierarchyEnabled(false)
Instabug.setIBGLogPrintsToConsole(false)
```

### SDK Version
v7.6

### iOS Version
11.2.1

### Device Type
iPhone X

**Comment by anfriis** [comment]
Anyone?

**Comment by ZiadAyman** [comment]
Hey @anfriis 
Apologies for the late reply on this. 
Already communicated with iOS team and they are on it. 

Will keep you posted.

**Comment by anfriis** [comment]
Any news on this?

**Comment by Kmohamed** [comment]
@anfriis I am sorry for being late It's fixed now and will be included in the next release. We can provide you with a custom build if you want.

**Comment by anfriis** [comment]
Sounds great! 
Yeah i would like that, unless you release it today or tomorrow anyway :)

**Comment by Kmohamed** [comment]
Most probably will be Released next Sunday. are you using cocoapods ?

**Comment by anfriis** [comment]
Ah okay, I need to release before then. I am using Carthage

**Comment by Kmohamed** [comment]
@anfriis here is the custom build and I will inform you once we release this fix.
[Instabug.zip](https://github.com/Instabug/Instabug-iOS/files/1610995/Instabug.zip)
[InstabugCore.zip](https://github.com/Instabug/Instabug-iOS/files/1610996/InstabugCore.zip)

**Comment by anfriis** [comment]
Thank you!

**Comment by anfriis** [comment]
You said it would be included in the next release, but it seems that it does not work in the new release v7.8? 
Would be great if you could fix it in a release very soon :)

**Comment by Kmohamed** [comment]
@anfriis I am so sorry but the pull request still in the testing process. So I will notify you once the PR released.

**Comment by anfriis** [comment]
Seems to have been fixed in version 7.8.1. 
Thank you!

**Comment by Kmohamed** [comment]
Yes, It’s released yesterday sorry for not inform you after release 😬😬

**Comment by anfriis** [comment]
No problem :)
