### ISSUE TITLE
7.6 crash

### ISSUE THREAD

**Issue by keith** [Instabug/Instabug-iOS#222]
We've gotten some reports of crashes with the new 7.6 SDK. The app crashes after an upgrade on launch. From the user's device we were able to pull a crash log that has these symbols:

```
-[IBGCache contains:] (in InstabugCore) (IBGCache.m:85)
-[IBGCacheManager saveCacheModel:] (in InstabugCore) (IBGCacheManager.m:119)
__22-[IBGAnalytics didLog]_block_invoke (in InstabugCore) (IBGAnalytics.m:84)
```

Before crashing in libdispatch. After uninstalling and reinstalling the crash was fixed, which makes me assume it had something to do with a previous model on disk.

**Comment by Kmohamed** [comment]
Hello @keith 
Could you tell me the previous version of your Instabug sdk ?

**Comment by keith** [comment]
We upgrade weekly so our last version was 7.5, but there's a possibility it was slightly older if the user hadn't upgraded in the last week or so. Since this isn't happening to everyone I assume this user also had something unique left over on disk

**Comment by Kmohamed** [comment]
I will check it now and will fix it asap but
could you provide me with complete stacktrace ?

**Comment by keith** [comment]
Here's a gist with the log https://gist.github.com/keith/1f343241e79966b1018e932e38c757ad

**Comment by Kmohamed** [comment]
We just released V7.6.1 with fix could you double check and tell me if you still face the issue.

**Comment by Kmohamed** [comment]
Thanks a lot @keith for your collaboration 🙏.

**Comment by keith** [comment]
Thanks!
