### ISSUE TITLE
Restore status bar color after showing the Instabug UI?

### ISSUE THREAD

**Issue by kevinrenskers** [Instabug/Instabug-iOS#226]
My app uses the status bar style with white letters and symbols, but after using the shake gesture to bring up the instabug UI (which uses a black status bar) and then closing that modal, the status bar stays black.

Even if you only shake to bring up the modal where you choose between reporting a problem or making a suggestion, and simply closing that screen, the status bar changes to black.

I'm using SDK 7.8.1, integrated via Cocoapods.

"View controller-based status bar appearance" is set to NO in my info.plist, and Status Bar Style set to Light in the General settings.

**Comment by Kmohamed** [comment]
@kevinrenskers  let me check it and get back to you soon.

**Comment by Kmohamed** [comment]
@kevinrenskers here is a custom build 
pod 'Instabug', :git => 'https://github.com/Instabug/Instabug-iOS.git', :branch => 'fix/StatusBarColor'
Kindly check it and tell me if works.

**Comment by kevinrenskers** [comment]
Yep, that build fixes the problem.

**Comment by Kmohamed** [comment]
@kevinrenskers The fix was released on v7.8.2
