### ISSUE TITLE
IBGDiskPersistenceManager crash

### ISSUE THREAD

**Issue by kevinrenskers** [Instabug/Instabug-iOS#228]
```
Thread 5 Crashed:
0   libobjc.A.dylib                     0x0000000180640430 objc_msgSend + 16
1   InstabugCore                        0x00000001059a87d0 -[IBGDiskPersistenceManager randomName] + 148
2   InstabugCore                        0x00000001059a8cdc -[IBGDiskPersistenceManager persistDataInTempDirectory:withCompletion:] + 72
3   InstabugCore                        0x000000010599712c -[IBGServerDataRequest prepareRequestWithCompletionHandler:] + 820
4   InstabugCore                        0x0000000105985d68 -[IBGServerManager executeServerRequest:] + 148
5   InstabugCore                        0x0000000105996dbc +[IBGServerDataRequest executeWithURL:HTTPMethod:payload:headers:delegate:] + 232
6   InstabugCore                        0x0000000105996ca8 +[IBGServerDataRequest executeWithURL:HTTPMethod:payload:delegate:] + 92
7   Instabug                            0x000000010582addc -[IBGSyncRequest executeNow] + 616
8   Instabug                            0x00000001057faef0 -[IBGSyncManager syncWithNumberOfMessages:readMessagesReceipts:lastMessageDate:] + 212
9   Instabug                            0x00000001057fade0 -[IBGSyncManager sync] + 588
10  Instabug                            0x00000001057faa68 __41-[IBGSyncManager initializationOperation]_block_invoke + 148
11  InstabugCore                        0x00000001059ab8e4 -[IBGOperation start] + 168
12  Foundation                          0x0000000181dbf894 <redacted> + 404
13  libdispatch.dylib                   0x0000000180d62a14 <redacted> + 16
14  libdispatch.dylib                   0x0000000180d6af08 <redacted> + 428
15  libdispatch.dylib                   0x0000000180d6980c <redacted> + 604
16  libdispatch.dylib                   0x0000000180d6fcf4 <redacted> + 600
17  libdispatch.dylib                   0x0000000180d6fa38 <redacted> + 120
18  libsystem_pthread.dylib             0x000000018100b06c _pthread_wqthread + 1268
19  libsystem_pthread.dylib             0x000000018100ab6c start_wqthread + 4
```

This one happened in 7.4, I have no clue if it was fixed in later versions? Could not find a similar report here in the github issues.

**Comment by Kmohamed** [comment]
@kevinrenskers Yes this also should be fixed in the latest version If you found it please open it again.
Sorry for inconvenience 🙁

**Comment by kevinrenskers** [comment]
No problem! I have more crash reports that I have not seen here in github issues yet, also for 7.4 and 7.6. Do you want me to crash issues for them as well? No idea if they are fixed in later SDK versions..

**Comment by ZiadAyman** [comment]
Hey @kevinrenskers 
Please send the crashes stack traces on contactus@instabug.com and we can proceed with the fixing process from there! 
Thank you for the collaboration :)

**Comment by ZiadAyman** [comment]
https://github.com/Instabug/Instabug-iOS/releases/tag/7.8

**Comment by kevinrenskers** [comment]
Mail sent, with 4 stack traces. 3 for 7.4, one for 7.6.

**Comment by ZiadAyman** [comment]
@kevinrenskers Got it, will take it from there. Thanks!

**Comment by kevinrenskers** [comment]
Hi @ZiadAyman, I just sent 5 more crashes to contactus@instabug.com that are happening in 7.11.1. This is rather scary for a bug/crash reporter to cause so many crashes itself :( Please let me know if there is something I can do to help so these crashes can get fixed asap.

**Comment by Kmohamed** [comment]
@kevinrenskers are you sure that all these crashes came from v7.11.1 because we already have these crashes on old versions and we fixed them. what I mean that these crash may came from an old versions.

**Comment by kevinrenskers** [comment]
Sorry, all of them actually happened on 7.10, but I was told after 7.6 that many of these were already fixed as well. 

One of them happened on 7.10.1:

![screen shot 2018-03-24 at 11 47 09](https://user-images.githubusercontent.com/229384/37863131-1c8a1c3e-2f59-11e8-9f0d-11627f21fd39.png)
