### ISSUE TITLE
should Instabug_dsym_upload.sh bail before grep'ing for sim builds?

### ISSUE THREAD

**Issue by littlebobert** [Instabug/Instabug-iOS#23]
Should Instabug_dsym_upload.sh bail early for sim builds before grep'ing the project for the use of an Instabug API key? grep'ing takes much of the scripts time and the script doesn't seem to do anything with the API key when bailing. See the patch here:

https://gist.github.com/littlebobert/319380962a7a78bad707

**Comment by msoliman** [comment]
That makes sense, I'll make sure that we include this in our next release, planned for next week.
