### ISSUE TITLE
__hidden symbols in bitcode

### ISSUE THREAD

**Issue by keith** [Instabug/Instabug-iOS#232]
Crash reports, such as [this one](https://github.com/Instabug/Instabug-iOS/issues/231) now have their bitcode obfuscated (see the conversation on that issue for more information).

This appears to have been introduced in 7.3.11 which has the release notes "Optimizing SDK size", which I assume has something to do with this unintentional change.

Are we safe to downgrade to 7.3.10 until this issue is fixed?

**Comment by Kmohamed** [comment]
@keith I do not think it's a good idea to downgrade to 7.3.10 you will lose a lot of fixes and features.
But could you send me the .crash file of this crash because I want to check something.

**Comment by keith** [comment]
Like I said in https://github.com/Instabug/Instabug-iOS/issues/231 the issue here is `-bitcode_hide_symbols` being passed. The report there has an example.

**Comment by Kmohamed** [comment]
@keith I totally agree with you that if we set -bitocde_hide_symbols with No will fix the issue but it will stop generation of bcsymboMap which will prevent ITC from regenerate Instabug DSYMs.

Also could you check apple reply here:

Glad to hear you do have .bcsymbolmap files for all your frameworks. I understand that you see __hidden symbols in the bitcode for your framework. However, this shouldn’t affect symbolication. A crash report doesn’t use the symbols from the binary — a raw crash report only has function addresses like 0x0009bd98, and Xcode looks at the .dSYM file corresponding with the binary to convert those function addresses into symbols (so 0x0009bd98 becomes scanMangledField). Unless you are using a third party crash reporting solution, the only way __hidden symbols should appear after symbolicating a crash report is if a .dSYM file still has obfuscated __hidden symbols.

**Comment by Kmohamed** [comment]
What I am trying to do I wanna try to fix DSYM file using the bcsymbolMap 
`dsymutil -symbol-map` and re symbolicate the crash again
@keith what do you think ?

**Comment by keith** [comment]
Removing this flag won't affect Apple's ability to generate useful crash info. GoogleMaps had this issue, and fixed it, and now their crash reports are working correctly.

**Comment by Kmohamed** [comment]
Actually we received a lot of complains that apps distributed through TestFlight or Appstore are not fully symbolicated because they can not find Instabug DSYM inside ITC.

And this Apple reply about this issue:
`After building with this command, you’ll notice you have several build products - the framework, the dSYM, and bcsymbolmaps with file names that match the UUIDs of the framework slices. You need both the dSYM and the bcsymbolmaps to get symbolicated crash logs from the App Store.`

They mention that it's required to include framework DSYM and bcsymbolMap inside project archive
The problem here that setting bitcode_hide_symbols with NO will prevent generation of bcsymbolMap which will regenerate the problem.

**Comment by keith** [comment]
Interesting. Currently with GoogleMaps we upload only the framework, without dsyms and without bcsymbolmaps and we get valid crash reports.

**Comment by Kmohamed** [comment]
Are these crash reports form AppStore or ITC ?

**Comment by keith** [comment]
Neither 😄  we seem them in both Xcode and our third party crash reporting tool that we upload the generated dsyms to.

**Comment by Kmohamed** [comment]
Make sense 😃
Would you mind send to me the .crash file in order to re-symbolicate the crash again
after run dsymutil -symbol-map on DSYM file.

**Comment by keith** [comment]
We actually don't have dsyms at all from our alpha builds for Instabug and InstabugCore

**Comment by Kmohamed** [comment]
But I have a copy of DSYM file from each release and since you are not distributed through ITC I can send to you a new DSYM file or you can send to me the .crash file and I will try it.
as u like.

**Comment by Kmohamed** [comment]
@keith here are 7.7.1 dsyms after run `dsymutil -symbol-map` could you give it a try 
[7.7.1_DSYMs.zip](https://github.com/Instabug/Instabug-iOS/files/1676483/7.7.1_DSYMs.zip)

**Comment by Kmohamed** [comment]
btw I integrate GoogleMaps in a sample project and upload a new version but I did not find DSYMs related to GoogleMaps on ITC.

**Comment by Kmohamed** [comment]
Hello @keith 
I made an experiment on a crash from a build downloaded from ITC that have InstabugCore frames `__hidden` then de-obfuscate the DSYMs with bcSymbolMap then symbolicates the crash again and the crash symbolicated correctly. We just made a release with this fix.

**Comment by Kmohamed** [comment]
Also I would like to share this reply from apple with you:

When you upload your app with bitcode to the App Store, you may choose not to send your application’s symbols by unchecking the “Upload your app’s symbols to receive symbolicated reports from Apple” box in the submission dialog. If you choose not to send your app’s symbol information to Apple, Xcode will replace the symbols in your app’s .dSYM files with obfuscated symbols such as “__hidden#109_” before sending your app to iTunes Connect. Xcode creates a mapping between the original symbols and the “hidden” symbols and stores this mapping in a .bcsymbolmap file inside the application archive. Each .dSYM file will have a corresponding .bcsymbolmap file.
>
>Before symbolicating crash reports, you will need to de-obfuscate the symbols in the .dSYM files downloaded from iTunes Connect. If you use the Download dSYMs button in Xcode, this de-obfuscation will be performed automatically for you. However, if you use the iTunes Connect website to download the .dSYM files, open Terminal and use the following command to de-obfuscate your symbols (replacing the example paths with your own archive and the dSYMs folder downloaded from iTunes Connect)

**Comment by keith** [comment]
What did you actually change in the new release? I see the symbol maps in both, and the binary still has __hidden symbols

**Comment by Kmohamed** [comment]
@keith Sorry for replying too late
First what changed in this version is Instabug DSYMs is de-obfuscated using bcsymbol map according to Apple mail:

> Xcode creates a mapping between the original symbols and the “hidden” symbols and stores this mapping in a .bcsymbolmap file

Also we already tried this solution on a crash which contains a hidden symbols. when we de-obfuscate the DSYMs with bcSymbol map file and re symbolicate the crash the hidden symbols disappear which proves that what apple said in the mail was correct.

**Comment by Kmohamed** [comment]
Hello @keith,
I wanna ask you if you see any crash with hidden symbols after our fix.

**Comment by keith** [comment]
So you're saying that we should be uploading your bcsymbolmap files to Apple when we upload our builds? And that they will take those into account when recompiling your framework from bitcode in order to generate dsyms with de-obfuscated symbols?

**Comment by Kmohamed** [comment]
I will recap what I said in order to make everything clear
1- Before distributing every version for Instabug framework we need to de-obfuscate the DSYMs with bcSymbolMap  to remove `__hidden` symbols. 
2- Application developer should include framework's (DSYM & bcSymbolMap) inside project archive before uploading to iTunesConnect in order to find framework new DSYMs inside iTunesConnect.

Also these information is a result of DTS with apple and we already try them.

**Comment by Kmohamed** [comment]
@keith what do you mean by include them in bitcode ?

**Comment by Kmohamed** [comment]
@keith I tried it but when I try to download all DSYMs form iTunesConnect I can not find Instabug DSYMs.

**Comment by Kmohamed** [comment]
Hello @keith,
did you see any hidden symbols from Instabug in the latest versions ?

**Comment by keith** [comment]
Yep, still see it with 8.0.2. You can see this yourself with a few steps:

```sh
# Instabug being the path to the binary in Instabug.framework
lipo -thin arm64 -output slice Instabug
xcrun segedit slice -extract __LLVM __bundle bitcode.xar
xar -xf bitcode.xar
# You will now have a ton of files in the local directory like 001, 002 etc
nm 001 # the output of which will show the hidden symbols
```

**Comment by BNGriffin** [comment]
😁

**Comment by Kmohamed** [comment]
Hello @keith.
it's been a while since your last comment on this issue. I would like to share with you this update on apple docs. Did you come across this before?

> Translating 'hidden' symbol names back to their original names
> 
> When you upload your app with bitcode to the App Store, you may choose not to send your application's symbols by unchecking the "Upload your app's symbols to receive symbolicated reports from Apple" box in the submission dialog. If you choose not to send your app's symbol information to Apple, Xcode will replace the symbols in your app's .dSYM files with obfuscated symbols such as "__hidden#109_" before sending your app to iTunes Connect. Xcode creates a mapping between the original symbols and the "hidden" symbols and stores this mapping in a .bcsymbolmap file inside the application archive. Each .dSYM file will have a corresponding .bcsymbolmap file.
> 
> Before symbolicating crash reports, you will need to de-obfuscate the symbols in the .dSYM files downloaded from iTunes Connect. If you use the Download dSYMs button in Xcode, this de-obfuscation will be performed automatically for you. However, if you use the iTunes Connect website to download the .dSYM files, open Terminal and use the following command to de-obfuscate your symbols (replacing the example paths with your own archive and the dSYMs folder downloaded from iTunes Connect):
https://developer.apple.com/library/archive/technotes/tn2151/_index.html
