### ISSUE TITLE
Cannot set attributed string for intro messages

### ISSUE THREAD

**Issue by jarvis-wu** [Instabug/Instabug-iOS#235]
### Steps to Reproduce the Problem

The default intro message has a bold **shake** in it. I want to override that message but still keep the bold **shake**. But it seems there is no easy way to do that. I guess this is not a bug but is something that could potentially be improved in later versions.

### Expected Behavior

Want to use an attributed string in the intro message

### Actual Behavior

Cannot use attributed string in the function `setValue(_ value: String, forStringWithKey key: String)`

### Instabug integration code

`Instabug.start(withToken: "*******", invocationEvent: .shake)`
`let string = NSAttributedString(string: "test", attributes: nil)`
`Instabug.setValue("test", forStringWithKey: kIBGShakeStartAlertTextStringName)`
`Instabug.setShakingThresholdForiPhone(1.5, foriPad: 0.6)`

### SDK Version

7.8.4

### iOS Version

11.2

### Device Type

iPhone 6s

<img width="237" alt="wx20180208-172831 2x" src="https://user-images.githubusercontent.com/24983448/36001763-830b71dc-0cf5-11e8-960e-b5d9c328aed5.png">

**Comment by Kmohamed** [comment]
@jarvis-wu Yes it's not a bug but you can make it with a workaround like this
`Instabug.setValue("<test>", forStringWithKey: kIBGShakeStartAlertTextStringName)`
