### ISSUE TITLE
Feature request: Hungarian language

### ISSUE THREAD

**Issue by yan-zaitsev** [Instabug/Instabug-iOS#236]
Hi, my company has application for Hungarian market and we want to enable instabug for it, but you don't have yet localization in "hu" :(

We already prepare localization for keys that you define in IBGTypes in 7.3.9 version https://pastebin.com/GaMwzndr

**Comment by Kmohamed** [comment]
Fantastic once you finish localization for keys in IBGTypes send it to me and i will include them in the next release 
Thanks 🙏

**Comment by yan-zaitsev** [comment]
@Kmohamed I have already sent you all translations, that we have: https://pastebin.com/GaMwzndr

**Comment by Kmohamed** [comment]
Sorry i did no recognize the link. 
let me check it and tell you once it’s released Thanks again @yan-zaitsev

**Comment by yan-zaitsev** [comment]
@Kmohamed 
If you sent me whole Localizable.strings that you use in framework bundle in Czech and English languages, we could make full translation to Hungarian. I see you have add ~10 new strings to latest versions (relative to 7.3.9)

**Comment by Kmohamed** [comment]
Sure I attached the localization.strings file in english and Czech
[Localizable.zip](https://github.com/Instabug/Instabug-iOS/files/1712224/Localizable.zip)

**Comment by stachon** [comment]
We had a typo in Yan's paste, it should be : 
```"INSTABUG_kIBGThankYouAlertMessageStringName" = "Visszajelzésedet megkaptuk.\nKöszönjük, hogy segítesz javítani az alkalmazást %@.";```
(there was a space missing before %@)

**Comment by yan-zaitsev** [comment]
@Kmohamed thanks, we will prepare it and send you back.

**Comment by Kmohamed** [comment]
@yan-zaitsev any updates ?

**Comment by Kmohamed** [comment]
I will close this issue due to lack of interactions.
@yan-zaitsev feel free to open it again anytime.

**Comment by TewWe** [comment]
Hi Everyone, we have picked up the thread where @yan-zaitsev left off and added all the Hungarian texts to the zip file (we have used informal addressing, as it generally results in shorter texts, and may fit better to the target audience ):
[Localizable.zip](https://github.com/Instabug/Instabug-iOS/files/2184418/Localizable.zip)
@Kmohamed, could you please check if this fits you?

**Comment by Kmohamed** [comment]
Thanks a lot @TewWe  I will check it and get back to you

**Comment by yan-zaitsev** [comment]
I am sorry, our translations were lost in our company translating processes :(

**Comment by Kmohamed** [comment]
@yan-zaitsev no worries 👍

**Comment by Csejky** [comment]
Hi, @Kmohamed 
progress has been made on the matter? Hungarian localizable.zip

**Comment by Korazy** [comment]
Hey @Csejky 

There is currently some missing translations excluding the ones sent above. Would you be able to translate those?
[Archive.zip](https://github.com/Instabug/Instabug-iOS/files/2366111/Archive.zip)

**Comment by Csejky** [comment]
Hey @Kmohamed 
I've attached the extended version

[Localizable_hu.zip](https://github.com/Instabug/Instabug-iOS/files/2388146/Localizable_hu.zip)

**Comment by Kmohamed** [comment]
@Csejky SDK `v8.0.15` supports Hungarian Thanks for your help 🙏.
