### ISSUE TITLE
Slovak localization : wrong text for collectingDataText

### ISSUE THREAD

**Issue by stachon** [Instabug/Instabug-iOS#237]
Hello, the Slovak (SK) translation for `collectingDataText` (`kIBGCollectingDataText`) is currently `"Samlar in data..."`. This appears to be Swedish. The correct Slovak text for this key would be `"Zber dát..."`

**Comment by Kmohamed** [comment]
@stachon we will fix it as soon as possible Thanks a lot 🙏.

**Comment by Kmohamed** [comment]
@stachon we include your translation in the latest release thanks a lot for your collaboration 🙏
