### ISSUE TITLE
Another day, another Instabug + Carthage problem

### ISSUE THREAD

**Issue by txaiwieser** [Instabug/Instabug-iOS#240]
### Steps to Reproduce the Problem
Try to update|bootstrap Carthage with instabug configured

### Expected Behavior
It should work

### Actual Behavior

*** xcodebuild output can be found in /var/folders/d1/x6c1jgcd18l01356m4gnxrjh0000gq/T/carthage-xcodebuild.6AVPgC.log
Unable to parse binary-only framework JSON at https://raw.githubusercontent.com/Instabug/Instabug-iOS/master/InstabugCore/Carthage.json due to error: invalid JSON: dataCorrupted(Swift.DecodingError.Context(codingPath: [], debugDescription: "The given data was not valid JSON.", underlyingError: Optional(Error Domain=NSCocoaErrorDomain Code=3840 "JSON text did not start with array or object and option to allow fragments not set." UserInfo={NSDebugDescription=JSON text did not start with array or object and option to allow fragments not set.})))
### SDK Version
Last
### iOS Version
Last
### Device Type
...

**Comment by Kmohamed** [comment]
@txaiwieser is this fix your problem ?

**Comment by txaiwieser** [comment]
Yes, that was the problem! Thanks for replying quickly! 👍

**Comment by Kmohamed** [comment]
@txaiwieser Great and sorry again for this hassle 🙏

**Comment by Kmohamed** [comment]
Hello @txaiwieser ,
I am sorry to tell you that we release a new version of SDK that contains only Instabug.framework
and removing InstabugCore.framework so please check the [docs](https://docs.instabug.com/docs/ios-integration#section-carthage).

**Comment by txaiwieser** [comment]
Thanks for the warning! 👍 
Will update asap! :)

**Comment by manderson420** [comment]
So just to confirm, if we were previously targeting 7.14.2 for example, we are forced to update to 8.x and remove binary "https://raw.githubusercontent.com/Instabug/Instabug-iOS/master/InstabugCore/InstabugCore.json" == 7.14.2
?

**Comment by Kmohamed** [comment]
Yes you need to remove "https://raw.githubusercontent.com/Instabug/Instabug-iOS/master/InstabugCore/InstabugCore.json" from the cartfile if you upgrade to 8.0.3 or higher.

**Comment by manderson420** [comment]
I was trying to avoid updating just yet to 8.x. Currently I get the error described by @txaiwieser when trying to rebuild the Carthage dependencies while still targeting the 7.14.2 release. So it looks like I am forced to do the update.

**Comment by Kmohamed** [comment]
Could you try remove binaries folder ?
Like this one 
https://github.com/Instabug/Instabug-iOS/issues/271
