### ISSUE TITLE
SDK 7.12 spams "Could not successfully update network info during initialization." when using simulator.

### ISSUE THREAD

**Issue by logananderson** [Instabug/Instabug-iOS#241]
### Steps to Reproduce the Problem
Use 7.12 SDK
Instabug.start()
Run in a simulator environment.
Observe console.
Use 7.11.2
Observe console

### Actual Behavior
Constant logging of `Could not successfully update network info during initialization.`

### SDK Version
7.12

### iOS Version
11.2

### Device Type
Simulators

The "Could not successfully update network info during initialization." log is shown every time you initialize the CTTelephonyNetworkInfo in a device without SIM card.  Looks like a check is needed for simulators.

**Comment by Kmohamed** [comment]
@logananderson Sorry for this inconvenience we will fix it and send you custom build until we release it very soon.

**Comment by logananderson** [comment]
It's fine, just a minor annoyance is all ¯\_(ツ)_/¯

**Comment by Kmohamed** [comment]
@logananderson here is a custom build until we release it very soon.
pod 'Instabug', :git => 'https://github.com/Instabug/Instabug-iOS.git', :branch => 'remove-network-spam'

**Comment by Kmohamed** [comment]
@logananderson it's fixed in SDK version https://github.com/Instabug/Instabug-iOS/releases/tag/7.12.1

**Comment by Kmohamed** [comment]
Anytime
