### ISSUE TITLE
Crashed: com.instabug.queueUsageLoggerQueue

### ISSUE THREAD

**Issue by TinyQ** [Instabug/Instabug-iOS#242]
### Steps to Reproduce the Problem
![image](https://user-images.githubusercontent.com/3217732/39341707-ff908898-4a06-11e8-8d69-3489a2496693.png)

### Crashlytics
[com.zhihu.ios-dev_issue_768_crash_102ce4884c004507bc3422a794a0f393_DNE_0_v2.txt](https://github.com/Instabug/Instabug-iOS/files/1953686/com.zhihu.ios-dev_issue_768_crash_102ce4884c004507bc3422a794a0f393_DNE_0_v2.txt)

### SDK Version
7.12.2
### iOS Version
iOS 10 25% 
iOS 11 75%
### Device Type
iPhone

**Comment by Kmohamed** [comment]
Thanks @TinyQ we are aware of this crash and it will be fixed next sunday

**Comment by Kmohamed** [comment]
@TinyQ we just released a fix for this crash in SDK version 7.12.5 so please update and feel free to open this issue if you face this crash again.
