### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by kevinrenskers** [Instabug/Instabug-iOS#243]
### Steps to Reproduce the Problem
Tried to log feedback via the shake gesture, app crashed.

![screen shot 2018-04-30 at 10 41 31](https://user-images.githubusercontent.com/229384/39420127-6a3ebca6-4c63-11e8-949a-d404697db36a.png)

### SDK Version
7.12.4

### iOS Version
11.2.5

### Device Type
iPhone 7 Plus

**Comment by Kmohamed** [comment]
Could you tell me the occurrences of this crash and are you able to reproduce it or not ?

**Comment by kevinrenskers** [comment]
One of our users got this once, when trying to log feedback to us (via the shake gesture). I was not able to reproduce this myself.

**Comment by Kmohamed** [comment]
@kevinrenskers let me check and get back to you

**Comment by Kmohamed** [comment]
@kevinrenskers are you making any operation which results to delete files in Library directory ?

**Comment by kevinrenskers** [comment]
No

**Comment by Kmohamed** [comment]
@kevinrenskers I succeed to reproduce and will be released next Sunday.

**Comment by Kmohamed** [comment]
@kevinrenskers we just released a fix for your Crash in SDK version 7.12.6
