### ISSUE TITLE
Instabug_dsym_upload.sh can't find APP_TOKEN

### ISSUE THREAD

**Issue by dalef84** [Instabug/Instabug-iOS#25]
Instabug_dsym_upload.sh looks great, but I was using a constant for the APP_TOKEN and it was failing because of that.

`
    [Instabug startWithToken:kSTEInstabugToken
               captureSource:IBGCaptureSourceUIKit
             invocationEvent:IBGInvocationEventShake];
`

I'd suggest against parsing the project dir source, as it's error prone, and moving this configuration parameters someplace else like a plist, a constants file or maybe even the script file.

Best!

**Comment by msoliman** [comment]
@dalef84 that's true, thanks for sending this over.
This already exists, you can just add the line `APP_TOKEN = "your_app_token"` to the top of the build script and this will stop the script from searching in the dir source.

**Comment by dalef84** [comment]
Thanks @msoliman !
