### ISSUE TITLE
Visual bug during navigation controller transitions while using repro step tracking

### ISSUE THREAD

**Issue by nealyoung** [Instabug/Instabug-iOS#253]
### Steps to Reproduce the Problem
1. Start Instabug in your app with an account using user steps tracking.
2. Create a navigation controller with a root view controller containing an input view.
3. While the keyboard is visible, push another view controller with an input view that becomes first responder on `viewDidLoad`.
4. Observe that the pushed view controller appears as a black view during the transition.
5. Remove the call to `Instabug.start`, and observe that the transition appears normally.

I've [uploaded a screen recording](https://www.dropbox.com/s/2m4dr7en2stbf65/RTKP2488.MP4?dl=0) of the behavior in the sample app.

### Expected Behavior
Instabug would not affect the appearance of the transition.

### Actual Behavior
When Instabug is tracking user steps, the view being pushed appears as a completely black screen during the transition animation.

### Instabug integration code
I've created an example project demonstrating this behavior [here](https://github.com/nealyoung/InstabugReport). The only integration code is a call to `Instabug.start` in `application(_:didFinishLaunchingWithOptions:)`.

### SDK Version
Instabug 7.12.0

### iOS Version
iOS 11.3.1

### Device Type
This is only reproducible on iPhone X, on the device (not in a simulator).

**Comment by Kmohamed** [comment]
@nealyoung Thanks a lot for your these clear steps I will check and get back to you very soon.

**Comment by Kmohamed** [comment]
Thanks again for the detailed bug report
Here is a custom build with the fix and I will make sure to notify once we release the fix
pod 'Instabug', :git => 'https://github.com/Instabug/Instabug-iOS.git', :branch => 'fix-blackscreen-navigation'

**Comment by Kmohamed** [comment]
@nealyoung did you manage to check the custom build ?

**Comment by nealyoung** [comment]
@Kmohamed It looks like it's working, thanks for the quick response!

**Comment by Kmohamed** [comment]
@nealyoung anytime and thanks for detailed bug report it makes my life easy 🙏
