### ISSUE TITLE
Framework size too big? 7.12.6

### ISSUE THREAD

**Issue by psineur** [Instabug/Instabug-iOS#257]
### Steps to Reproduce the Problem
1. Edit podfile to add InstaBug
2. run pod install
3. clean build folder, archive
4. check appname.app bundle size increase (organizer->archives->ShowInFinder->Show Package Contents) = it's around 50MB

### Expected Behavior
App increase around 1MB, as stated in FAQ https://instabug.com/faq
> How will the SDK affect my app size?
> The iOS SDK is a static library, which means that the SDK is in a precompiled format, and gets linked at compile time while building the app. The size of the SDK itself varies every version, but the overhead size in your final app is around 1MB.

### Actual Behavior
Almost 50MB in InstaBug & InstaBugCore frameworks
![screenshot 2018-05-29 19 45 21](https://user-images.githubusercontent.com/507338/40694258-f245200a-6378-11e8-9cc6-677b270219b1.png)

### Instabug integration code
```
#import <InstaBug/InstaBug.h>
...
[Instabug startWithToken:@"vrotmnenogi" invocationEvent:IBGInvocationEventShake];

```
### SDK Version
7.12.6 

### iOS Version
11.1

### Device Type
iPhone 6

**Comment by Kmohamed** [comment]
@psineur let me check it and get back to you

**Comment by Kmohamed** [comment]
@psineur Sorry for being late I would like to correct something that this is not the framework size it's the fat binary size which contains all architecture slices.
But you can find Instabug download size and Install size using ItunesConnect
![screen shot 2018-06-01 at 3 02 53 am](https://user-images.githubusercontent.com/1115748/40816380-dff2f988-654c-11e8-904a-d00c991aeb78.png)

**Comment by Kmohamed** [comment]
I just upload application with and without Instabug and here are the result
![screen shot 2018-06-01 at 3 36 21 am](https://user-images.githubusercontent.com/1115748/40816430-31a1c232-654d-11e8-8cc9-3f047e293fb4.png)
![screen shot 2018-06-01 at 3 36 26 am](https://user-images.githubusercontent.com/1115748/40816431-320567f6-654d-11e8-85a2-e73a58abd107.png)

**Comment by Kmohamed** [comment]
average 4.5MB download size and 7.5MB Install size
