### ISSUE TITLE
Console polluted with "Saved IBGLog IBGLog"

### ISSUE THREAD

**Issue by dafurman** [Instabug/Instabug-iOS#258]
### Steps to Reproduce the Problem

In my app delegate startup:
```
Instabug.start(withToken: INSTABUG_KEY_BETA, invocationEvent: .shake)
Instabug.setSDKDebugLogsLevel(IBGSDKDebugLogsLevel.verbose)
Instabug.setIBGLogPrintsToConsole(false)
```
Call 

> Instabug.log___()

### Expected Behavior
I would expect Instabug.setIBGLogPrintsToConsole(false) to not show any indication of logging in the console.
Two logs are demonstrated:

✳️ NotificationCenterExtensions.swift:  postAndLog(name:object:): 13 - serverUserLocationUpdateDidSucceed (**This line is my own printed log using print()**)
✳️ MatchManager.swift:  requestNearbyUsers(count:completionHandler:): 79 - Requesting nearby users with cursor "[:]" ... (**This line is my own printed log using print()**)

### Actual Behavior
It seems that the logging is hidden, but I'm still shown a message of IBGLogs being saved, which takes up 9 lines of the console per message.

✳️ NotificationCenterExtensions.swift:  postAndLog(name:object:): 13 - serverUserLocationUpdateDidSucceed (**This line is my own printed log using print()**)
[Instabug] Saved IBGLog IBGLog (
    date: 2018-05-30 16:20:59 +0000
    level: d
    message: ✳️ NotificationCenterExtensions.swift:  postAndLog(name:object:): 13 - serverUserLocationUpdateDidSucceed
    sessionId: 54DDFB2F-CEE1-4B03-85D9-416004D8DD83
    hash: 1324941368
    superclass: NSManagedObject

}
✳️ MatchManager.swift:  requestNearbyUsers(count:completionHandler:): 79 - Requesting nearby users with cursor "[:]" ... (**This line is my own printed log using print()**)
[Instabug] Saved IBGLog IBGLog (
    date: 2018-05-30 16:20:59 +0000
    level: d
    message: ✳️ MatchManager.swift:  requestNearbyUsers(count:completionHandler:): 79 - Requesting nearby users with cursor "[:]" ...
    sessionId: 54DDFB2F-CEE1-4B03-85D9-416004D8DD83
    hash: 385417272
    superclass: NSManagedObject
}

### Summation of issue
I'd like to have the capability of performing Instabug logging to view logs online, but when debugging, it's hard to scan logs when each Instabug log takes up 9 lines.

### Instabug integration code
N/A
### SDK Version
7.13
### iOS Version
11.4
### Device Type
iPhone 6S

**Comment by Kmohamed** [comment]
Actually this not the functionality of printing instabug log to console 
It’s verbose logging which it’s enable by default in debugging mode
You can disbale it by setSDKDebuglevel to none

**Comment by dafurman** [comment]
Oh I see, upon rereading the documentation "used to debug the Instabug SDK itself", that seems clear now. Still, just to make sure, this won't affect that actual logging that's being done, just the debugging of IB logging itself, so I'll still be able to see logs for a user in production, even if setSDKDebugLevel is set to .none?

I had 
> Instabug.setSDKDebugLogsLevel(IBGSDKDebugLogsLevel.error)
set for production and
> Instabug.setSDKDebugLogsLevel(IBGSDKDebugLogsLevel.verbose)
set for non production, but I can safely set it as none in either case and still receive logs?
