### ISSUE TITLE
Crash after a few minutes

### ISSUE THREAD

**Issue by LFabien** [Instabug/Instabug-iOS#259]
### Description

A few users are complaining that the app is crashing after a few minutes. I can confirm that it is from Instabug because they don't have this issue when disabling the SDK.

It seems to be similar to the issue on `v7.12.5` with `InstabugDataModel.sqlite`  which was growing very quickly until taking all memory and crash the app. Unfortunately, I don't see any crash reports on Crashlytics and I'm not able to reproduce on my devices.

@Kmohamed Please let me know if you have received similar reports and if you have a workaround. Reinstalling the app, or resetting the iPad doesn't work. For now, I added a way to disable Instabug in the app settings. 

### Instabug integration code

```
    [Instabug startWithToken:@"XXX" invocationEvent:IBGInvocationEventScreenshot];
    [Instabug setCrashReportingEnabled:NO];
    [Instabug setIntroMessageEnabled:NO];
    [Instabug setPromptOptionsEnabledWithBug:YES feedback:YES chat:NO];
    [Instabug setSessionProfilerEnabled:NO];
```

*Logs & Errors*
```
    [Instabug reportError:error];
    [Instabug logVerbose:logMsg]; and similar methods
    [Instabug IBGLog:logMsg];
```
*Invocation*
```
    [Instabug invokeWithInvocationMode:IBGInvocationModeNewBug];
```

### SDK Version

v7.13

### iOS Version

iOS 9.3 to iOS 11 

### Device Type

iPad

**Comment by Kmohamed** [comment]
Actually I didn’t receive any similar issue but we add a lot of enhancements on coreData in the latest release 
Could you give it a try ?

**Comment by LFabien** [comment]
Sounds good. I'm planning to send a new update by the end of the week. I'll let you know if I receive more reports. Thanks.

**Comment by Kmohamed** [comment]
@LFabien I will close it now and feel free to open it again if you face a similar problem.
