### ISSUE TITLE
Beta Welcome Message appears even when disabled together with surveys

### ISSUE THREAD

**Issue by Vadimkomis** [Instabug/Instabug-iOS#260]
### Steps to Reproduce the Problem
First launch app, when welcome message disabled

Instabug.setWelcomeMessageMode(IBGWelcomeMessageMode.disabled)
### Expected Behavior
Not to show welcome message and not not show surveys, unless they get triggered
### Actual Behavior
Welcome message appears, and right after that we see surveys, without triggering either of them.
![img_6114](https://user-images.githubusercontent.com/6124787/41063202-fee52afc-69a5-11e8-856b-4cc26d6db7a4.JPG)

### Instabug integration code
*Make sure to remove your app token.*
//This method is inside AppDelegate
    func initializeInstabug() {
        Instabug.setWelcomeMessageMode(IBGWelcomeMessageMode.disabled)
        
        let env = fl_enviornment().env
        var config = fl_config(enviornment: env)
        #if DEVELOPMENT
        Instabug.start(withToken: config.instabug_DEMO, invocationEvent: .shake)
        #else
        Instabug.start(withToken: config.instabug_PRODUCTION, invocationEvent: .none)
        #endif
    }

### SDK Version
7.14.2
### iOS Version
Tested on 10.3.1 & 11.3.1
### Device Type
iPhone 7 simulator and iPhone X device

**Comment by alyakan** [comment]
I believe what you're trying to achieve is to disable the survey's welcome message, if so, then the API you want is `Instabug.setShouldShowSurveysWelcomeScreen(false)`. Let me know if that helps @Vadimkomis

**Comment by yousefhamza** [comment]
Hi @Vadimkomis 
The problem is you try are calling the API to disable welcome message **before** `Instabug.start(withToken: config.instabug_DEMO, invocationEvent: .shake)`

Any configuration to Instabug should be done after `Instabug.start(withToken:invocationEvent:)`

**Comment by yousefhamza** [comment]
Also I want to point out that `Instabug.setWelcomeMessageMode(IBGWelcomeMessageMode.disabled)` isn't related to surveys.

To get your expected surveys behavior call `Instabug.setAutoShowingSurveysEnabled(false)`

**Comment by Vadimkomis** [comment]
@yousefhamza this solved our issue. Thanks!
