### ISSUE TITLE
App Rejection - Private API Usage

### ISSUE THREAD

**Issue by aarona-wm** [Instabug/Instabug-iOS#261]
### Steps to Reproduce the Problem
Link via Carthage Instabug.framework v 7.12.5 and submit to AppStore/iTunes Connect. App rejected for private api use.

### Expected Behavior
App is not rejected.

### Instabug integration code
*Make sure to remove your app token.*
n/a

### SDK Version
7.12.5

### iOS Version
10/11

### Device Type
iOS

// Appstore Error
Non-public API usage:

The app references non-public selectors in Frameworks/Instabug.framework/Instabug: animationName, setLabelText:, showWithCompletionHandler:
//

**Comment by Kmohamed** [comment]
@aarona-wm I think it's a bug from iTunesConnect `setLabelText:` and `showWithCompletionHandler:` is not a private API it's Instabug method. 
Feel free to open it again if you face a similar issue.
