### ISSUE TITLE
Method has been deprecated but no actual replacement

### ISSUE THREAD

**Issue by michaeleustace** [Instabug/Instabug-iOS#264]
### Steps to Reproduce the Problem
When setting up Instabug, I had the following option set (in version 7.12.5):
`[Instabug setCommentFieldRequired:NO];`

Having updated to version 7.14.3 I now get a `'setCommentFieldRequired:' is deprecated: Use setEmailFieldRequired:forAction: instead` warning.

It seems that this deprecation warning is directing me to set the email field requirement (when I want to set the comment field requirement).

I thought this was just a documentation mistake, but I cannot find any other method for setting comment field requirement.

Therefore, I am stuck with a build warning that I cannot overcome.

**Comment by alyakan** [comment]
@michaeleustace It appears that this is a mistake on our end, as you said, this method `setCommentFieldRequired` should not be deprecated. There will be a release with the fix very soon.

**Comment by Kmohamed** [comment]
@michaeleustace fixed in the latest release 7.14.4
