### ISSUE TITLE
Can't move cursor properly in problem description field

### ISSUE THREAD

**Issue by hjo** [Instabug/Instabug-iOS#265]
### Steps to Reproduce the Problem
Open app
Report a problem
Enter an email
Enter a few words in the problem description field
Attempt to tap down in order to move cursor within the problem description field and the cursor sticks to the top left of the screen instead

### Expected Behavior
Moving the cursor works as expected in the email field but not in the problem description field. It should work there too

### Actual Behavior
![image](https://user-images.githubusercontent.com/1050070/41493059-ebda7fea-7146-11e8-83cd-4892211dde8b.jpeg)

### Instabug integration code
Instabug.start(withToken: "xxx", invocationEvent: .screenshot)

### SDK Version
7.14.4

### iOS Version
11.4

### Device Type
iPhone X

**Comment by Kmohamed** [comment]
@hjo The bug is Fixed. are you interested in a custom build using cocoapods ?

**Comment by Kmohamed** [comment]
@hjo fix released in SDK version 7.15.4

**Comment by Kmohamed** [comment]
Anytime 💪💪
