### ISSUE TITLE
Deleting device logs hangs app

### ISSUE THREAD

**Issue by gilroykilroy** [Instabug/Instabug-iOS#266]
### Steps to Reproduce the Problem

1) Use Xcode to view device logs
2) Select all logs and delete
3) Launch an app with Instabug
4) Put app in background
5) Bring it to foreground

### Expected Behavior

App should not hang

### Actual Behavior

App hangs

### SDK Version

7.14.4

### iOS Version

11.4

### Device Type

iPhone X

My guess is you are looking for a log file that doesn't exist and you are not checking that this may be the case.

Using Xcode and pausing a hung device shows the following stack trace:

Thread 1 Queue : com.apple.main-thread (serial)
#0	0x0000000184bf67c8 in kevent_id ()
#1	0x0000000108b8afb8 in _dispatch_kq_poll ()
#2	0x0000000108b8b964 in _dispatch_event_loop_wait_for_ownership ()
#3	0x0000000108b7f740 in _dispatch_sync_wait ()
#4	0x0000000105e743ac in -[IBGDeviceStateLogger fetchBatteryLogsWithDate:] at /Users/distiller/project/InstabugCore/InstabugSessionProfiler/Logger/Loggers/IBGDeviceStateLogger.m:232
#5	0x0000000105e73cdc in -[IBGDeviceStateLogger fetchLogsWithDate:] at /Users/distiller/project/InstabugCore/InstabugSessionProfiler/Logger/Loggers/IBGDeviceStateLogger.m:201
#6	0x0000000105dc9fe0 in -[IBGSessionProfileLogger fetchLogsWithDate:] at /Users/distiller/project/InstabugCore/InstabugSessionProfiler/Logger/IBGSessionProfileLogger.m:68
#7	0x0000000105dc9e70 in -[IBGSessionProfileLogger loadProfilerLogsSynchronously:date:withCompletionHandler:] at /Users/distiller/project/InstabugCore/InstabugSessionProfiler/Logger/IBGSessionProfileLogger.m:61
#8	0x0000000105e24b5c in -[InstabugSessionProfiler loadProfilerLogsSynchronously:date:withCompletionHandler:] at /Users/distiller/project/InstabugCore/InstabugSessionProfiler/InstabugSessionProfiler.m:82
#9	0x0000000105e7e7a0 in -[IBGSnapshotManager takePreSendingSnapshotWithScreenShot:synchronously:shouldFetchLogs:shouldFetchVisualUserSteps:] at /Users/distiller/project/InstabugCore/InstabugCore/Logging/IBGSnapshotManager.m:162
#10	0x0000000105e4c464 in -[IBGSession requestParametersDict] at /Users/distiller/project/InstabugCore/InstabugCore/Caching/IBGSession.m:76
#11	0x0000000105e4d00c in -[IBGSession send] at /Users/distiller/project/InstabugCore/InstabugCore/Caching/IBGSession.m:143
#12	0x0000000105dbffdc in -[IBGSessionManager sendPreviousSessionIfExistThenInitializeNewOne] at /Users/distiller/project/InstabugCore/InstabugCore/Managers/IBGSessionManager.m:110
#13	0x0000000185100c3c in __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ ()
#14	0x00000001851001b8 in _CFXRegistrationPost ()
#15	0x00000001850fff14 in ___CFXNotificationPost_block_invoke ()
#16	0x000000018517d84c in -[_CFXNotificationRegistrar find:object:observer:enumerator:] ()
#17	0x0000000185036f38 in _CFXNotificationPost ()
#18	0x0000000185aa7bbc in -[NSNotificationCenter postNotificationName:object:userInfo:] ()
#19	0x000000018f134518 in -[UIApplication _sendWillEnterForegroundCallbacks] ()
#20	0x000000018ed45d94 in -[__UICanvasLifecycleMonitor_Compatability activateEventsOnly:withContext:completion:] ()
#21	0x000000018f9db84c in __82-[_UIApplicationCanvas _transitionLifecycleStateWithTransitionContext:completion:]_block_invoke ()
#22	0x000000018ed451ec in -[_UIApplicationCanvas _transitionLifecycleStateWithTransitionContext:completion:] ()
#23	0x000000018f7c0ac8 in __125-[_UICanvasLifecycleSettingsDiffAction performActionsForCanvas:withUpdatedScene:settingsDiff:fromSettings:transitionContext:]_block_invoke ()
#24	0x000000018f90ebf8 in _performActionsWithDelayForTransitionContext ()
#25	0x000000018ed44c0c in -[_UICanvasLifecycleSettingsDiffAction performActionsForCanvas:withUpdatedScene:settingsDiff:fromSettings:transitionContext:] ()
#26	0x000000018ed445a8 in -[_UICanvas scene:didUpdateWithDiff:transitionContext:completion:] ()
#27	0x000000018ed82334 in -[UIApplicationSceneClientAgent scene:handleEvent:withCompletion:] ()
#28	0x000000018796ff24 in __80-[FBSSceneImpl updater:didUpdateSettings:withDiff:transitionContext:completion:]_block_invoke.362 ()
#29	0x0000000108b6d19c in _dispatch_client_callout ()
#30	0x0000000108b797cc in _dispatch_block_invoke_direct ()
#31	0x00000001879a3878 in __FBSSERIALQUEUE_IS_CALLING_OUT_TO_A_BLOCK__ ()
#32	0x00000001879a351c in -[FBSSerialQueue _performNext] ()
#33	0x00000001879a3ab8 in -[FBSSerialQueue _performNextFromRunLoopSource] ()
#34	0x0000000185117404 in __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ ()
#35	0x0000000185116c2c in __CFRunLoopDoSources0 ()
#36	0x000000018511479c in __CFRunLoopRun ()
#37	0x0000000185034da8 in CFRunLoopRunSpecific ()
#38	0x0000000187019020 in GSEventRunModal ()
#39	0x000000018f051758 in UIApplicationMain ()
#40	0x0000000102b59b44 in main at /WherePrayer/WherePrayer/App/WherePrayer/AppDelegate.swift:23
#41	0x0000000184ac5fc0 in start ()

**Comment by Kmohamed** [comment]
@gilroykilroy what do you mean by device logs ? do you mean Instabug log files ?

**Comment by gilroykilroy** [comment]
1) Plug your device into Xcode
2) Window -> Devices and Simulators
3) Select connected device on left
4) Tap the View Device Logs button (top section, middle button)
5) Tap on This Device at top of left pane
6) Tap on any log in the left pane
7) Select All (Cmd-A)
8) Delete

**Comment by gilroykilroy** [comment]
It happens consistently on second launch.

**Comment by Kmohamed** [comment]
@gilroykilroy I can not reproduce on my side but I think this custom build should fix this issue. could you give it a try ?
[Instabug.zip](https://github.com/Instabug/Instabug-iOS/files/2108427/Instabug.zip)
[InstabugCore.zip](https://github.com/Instabug/Instabug-iOS/files/2108428/InstabugCore.zip)

**Comment by Kmohamed** [comment]
🎊  🎉  🎉 will be release soon

**Comment by Kmohamed** [comment]
@gilroykilroy fix released in SDK version 7.15.4
