### ISSUE TITLE
substringWithRange warning printed in console when appending certain tags

### ISSUE THREAD

**Issue by bdolman** [Instabug/Instabug-iOS#267]
### Steps to Reproduce the Problem

1. Instabug.appendTags(["org:Hello-World"])

The problem seems to be when you have a tag that contains a colon ":" followed later by a dash "-". If you only have one of them it's not a problem and if their order is reversed it's also not a problem.

For example:

"org:HelloWorld" - No problem
"org-Hello:World" - No problem
"org-HelloWorld" - No problem
"org:Hello-World" - PROBLEM

### Expected Behavior

Works without incident

### Actual Behavior

I get a warning printed to the console: 

```
*** -[__NSCFString substringWithRange:]: Range {10, 18446744073709551609} out of bounds; string length 15. This will become an exception for apps linked after 10.10 and iOS 8. Warning shown once per app execution.
```

In earlier versions of the SDK (7.12.5) it would actually crash the app after printing that warning. In the latest (7.14.5) it no longer seems to crash the app, but still prints the warning, which continues to concern me that the bug isn't really fixed, it's just being masked by slightly different code.

### Instabug integration code

```swift
        Instabug.start(withToken: ThirdPartyKeys.Instabug, invocationEvent: .shake)
        Instabug.resetTags()
        Instabug.setIntroMessageEnabled(false)
        
        let environmentTag: String
        switch ServerEnvironment.current {
        case .development:
            environmentTag = "Development"
        case .production:
            environmentTag = "Production"
        }
        let appNameTag = AppEnvironment.currentEnvironment.productName
        Instabug.appendTags([appNameTag, environmentTag])
        
        Instabug.setPrimaryColor(Theme.current.tintColor)
        Instabug.setNetworkLoggingEnabled(false)
        Instabug.setCrashReportingEnabled(false)
        Instabug.setPromptOptionsEnabledWithBug(true, feedback: true, chat: false)
        
        Instabug.setPreSendingHandler {
            Instabug.clearFileAttachments()
            let bundleIdentifiers = [AppIdentifiers.mainApp, AppIdentifiers.shareExtension, AppIdentifiers.notificationServiceExtension]
            for identifier in bundleIdentifiers {
                let logDirectory = FilePaths().logDirectory(forBundleIdentifier: identifier)
                if let latestLogFile = ConsoleRedirection.orderedLogFiles(logDirectory).last {
                    Instabug.addFileAttachment(with: latestLogFile)
                }
            }
        }
    }
```

### SDK Version

7.14.5

### iOS Version

11.4

### Device Type

Various (iPhone X, iPhone 7, Simulator, etc.)

**Comment by Kmohamed** [comment]
@bdolman a very strange bug let me check it and get back to you.

**Comment by Kmohamed** [comment]
@bdolman Yes I can confirm it's a bug and I will release it very soon.

**Comment by Kmohamed** [comment]
@bdolman I am sorry for being late here is a custom build for the issue and we will release it very soon.
 
The root cause was we are doing some string manipulation before we use this tag.
`pod 'Instabug', :git => 'https://github.com/Instabug/Instabug-iOS.git', :branch => 'fix-append-tags'`

**Comment by Kmohamed** [comment]
@bdolman Did the custom build fix the issue ?
