### ISSUE TITLE
iOS 9 support

### ISSUE THREAD

**Issue by OlegAnghelov** [Instabug/Instabug-iOS#27]
Hi guys!

Thanks for the work you are doing.

But are you planning on supporting iOS 9?

So far it gives our errors like this:
http://stackoverflow.com/questions/32096130/unexpected-cfbundleexecutable-key

And even after I implemented the new bundle as suggested in the comments, it worked with Xcode beta 5.
But now, after installing Xcode 7 beta 6, it gives a new error that says that the key `CFBundleSupportedPlatforms` should be removed because it contains `iPhoneSimulator` value.

**Comment by msoliman** [comment]
@OlegAnghelov ​Can you try this bundle instead ([here](https://www.dropbox.com/s/zzs7q2eygfa6wms/Instabug.bundle.zip?dl=0))? 
Let me know how it goes

**Comment by OlegAnghelov** [comment]
It went fine, I was able to submit it successfully.

**Comment by msoliman** [comment]
Sounds good, I'll make sure to update it in our next release.

**Comment by OlegAnghelov** [comment]
@msoliman 
Could you please share your next release date?

**Comment by msoliman** [comment]
@OlegAnghelov It should be later next month, we're planning a major release that's why it's taking longer.
Is this blocking you?

**Comment by OlegAnghelov** [comment]
Since we use pods, the CI runs pod install, and gets the Instabug version that is with old bundle, and when we do it for Xcode 7 and ios 9 it fails.
So now we are forced to do a  "drag and drop" Instabug integration, which we would like to revert as soon as possible :)

**Comment by msoliman** [comment]
Makes sense, I'll make sure that we push a hot-fix for this during the weekend. Should be out by Monday.

**Comment by msoliman** [comment]
@OlegAnghelov we've just pushed this to Cocoapods.
