### ISSUE TITLE
Carthage build not working

### ISSUE THREAD

**Issue by gilroykilroy** [Instabug/Instabug-iOS#270]
With the latest 8.0.3 change the Carthage install is not matching the current framework (i.e. the Instabug.h file refers to InstabugCore which is now gone.)

Edit: Looks like the /Instabug.json file may not have gotten updated

**Comment by chuganzy** [comment]
I also faced to this issue - they changed the JSON file location.
Also I noticed that they get rid of `InstabugCore`. Does it mean you combined them so we no longer need it?

**Comment by Kmohamed** [comment]
@gilroykilroy @chuganzy Sorry for that updated now.

**Comment by chuganzy** [comment]
@Kmohamed We no longer need `InstabugCore`, correct?

**Comment by Kmohamed** [comment]
Exactly

**Comment by chuganzy** [comment]
BTW, it would be pretty helpful if you could keep the backward compatibility AFAP.
Since https://raw.githubusercontent.com/Instabug/Instabug-iOS/master/InstabugCore/InstabugCore.json was removed, Carthage now fails to run `bootstrap` so I had to upgrade Instabug to the latest..

**Comment by Kmohamed** [comment]
@chuganzy I am totally agree with you but If keep InstabugCore with Instabug it will make the project failed due to duplicate symbols. If you can help me to keep the backward compatibility I will be thankful

**Comment by Kmohamed** [comment]
If you are using old versions it will work fine 
But if you upgrade and download InstabugCore with the new framework it will cause a lot of crashes so the best solution is to break the build to prevent any crashes

**Comment by joelkraut** [comment]
It actually doesn't work fine even using an old version, because the JSON resource listed in my Cartfile is no longer there. This is a problem with keeping that specification in the same repo as your code, I suppose--you can't move it.

**Comment by Kmohamed** [comment]
If you can suggest a solution it will be great

**Comment by joelkraut** [comment]
Restore this file: https://raw.githubusercontent.com/Instabug/Instabug-iOS/master/InstabugCore/InstabugCore.json. That's all that's needed.

**Comment by Kmohamed** [comment]
Do you think this will cause a problem for people using sdk versions above 8.x ?

**Comment by joelkraut** [comment]
If they're successfully building today with a higher version, then they're not linking against InstabugCore anymore, or else their Carthage installs would be failing like mine. So I think it would be ok. But of course the best thing to do would be to test it!

**Comment by Kmohamed** [comment]
I did not understand you could you elaborate more please 🙏

**Comment by joelkraut** [comment]
The missing InstabugCore.json file is only a problem if the Cartfile includes InstabugCore, and the Xcode project links against InstabugCore. You said [here](https://github.com/Instabug/Instabug-iOS/issues/270#issuecomment-404945790) that including InstabugCore on new versions will cause build failures. Therefore anyone who is using a new SDK version is either seeing issues already, or is not linking against InstabugCore. That means that restoring the file won't break them, because they won't look at it. Make sense?

**Comment by Kmohamed** [comment]
@joelkraut could you check these crashes https://github.com/Instabug/Instabug-iOS/issues/274 , https://github.com/Instabug/Instabug-iOS/issues/273
If these crashes does not happened local someone will release with it.

**Comment by Kmohamed** [comment]
Also this change will not happened again so If you migrate to use SDK 8.x it will not be broken again
also if you have any problems with migration I can help you also we have link to assist devs in [migration](https://docs.instabug.com/docs/ios-migration-guide)

**Comment by joelkraut** [comment]
I don't know what you're asking me to do. But I think I've given you everything you need; at this point you'll have to take on the QA effort yourself. If you're comfortable with having released a breaking change unnecessarily, so be it.
