### ISSUE TITLE
Carthage broken again 8.0.4

### ISSUE THREAD

**Issue by gilroykilroy** [Instabug/Instabug-iOS#271]
A shell task (/usr/bin/env unzip -uo -qq -d /var/folders/mt/5c87hjvx1db1xxlhtr0h1trh0000gn/T/carthage-archive.hzyGjX /Users/a/Library/Caches/org.carthage.CarthageKit/binaries/Instabug/8.0.4/Instabug.zip) failed with exit code 9:
[/Users/a/Library/Caches/org.carthage.CarthageKit/binaries/Instabug/8.0.4/Instabug.zip]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /Users/a/Library/Caches/org.carthage.CarthageKit/binaries/Instabug/8.0.4/Instabug.zip or
        /Users/a/Library/Caches/org.carthage.CarthageKit/binaries/Instabug/8.0.4/Instabug.zip.zip, and cannot find /Users/a/Library/Caches/org.carthage.CarthageKit/binaries/Instabug/8.0.4/Instabug.zip.ZIP, period.

**Comment by Kmohamed** [comment]
@gilroykilroy I think you tried it in a middle of the release could you give it another try ?

**Comment by gilroykilroy** [comment]
OK, I had to remove the /Users/a/Library/Caches/org.carthage.CarthageKit/binaries/Instabug* folder and it worked.

**Comment by Kmohamed** [comment]
Great 👍
