### ISSUE TITLE
Unrecognized Selector crash after report

### ISSUE THREAD

**Issue by scalbatty** [Instabug/Instabug-iOS#274]
### Steps to Reproduce the Problem

Send a crash report

### Expected Behavior

Crash report is sent

### Actual Behavior

Application crashes with log:

```
-[IBGSnapshotView captureScreenshotWithScaleFactor:]: unrecognized selector sent to instance 0x281936b40
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[IBGSnapshotView captureScreenshotWithScaleFactor:]: unrecognized selector sent to instance 0x281936b40'
```

### SDK Version

3.0.4 integrated through Carthage

### iOS Version

10.3.3 & 12.0 (16A5318d)

### Device Type

iPhone 6 plus & iPhone X

**Comment by Kmohamed** [comment]
how do you send crash report ?
