### ISSUE TITLE
Deprecated APIs warning

### ISSUE THREAD

**Issue by keith** [Instabug/Instabug-iOS#277]
### Steps to Reproduce the Problem

Call `+[Instabug startWithToken:invocationEvent:]`

### Expected Behavior

No logs

### Actual Behavior

```
+---------------------------------------------------------------------------------------+
|                           [Instabug] Our APIs have changed!                           |
+---------------------------------------------------------------------------------------+
| To make our APIs more intuitive and easily reachable, we renamed some of them,        |
| and restructured them into different classes.                                         |
|                                                                                       |
| Starting from version 8.0 of the SDK, you'll need to migrate to our new APIs. Old     |
| APIs are currently deprecated, and while they still function, they will be completely |
| removed in a future release.                                                          |
|                                                                                       |
| To adopt the new changes, please refer to our migration guide at:                     |
| https://docs.instabug.com/                                                            |
+---------------------------------------------------------------------------------------+
```

### Instabug integration code

```swift
Instabug.start(withToken: key, invocationEvents: .screenshot)
```

### SDK Version

8.0.6

### iOS Version

11.4.1

### Device Type

Simulator

### Other

It looks like calling the deprecated version (`invocationEvent` without the `s`) causes this log, and the new implementation just calls the old one.

**Comment by Kmohamed** [comment]
Hello @keith 
Actually we rewrote all Instabug apis so if you call any deprecated api it will print the same message so could you double check all deprecated apis not just startWithToken

**Comment by keith** [comment]
Shouldn't this only print this message if there we are actually using APIs that are deprecated?

Alternatively I think this can be removed all together since you also truly marked them as deprecated so they already have warnings with this URL 😄

**Comment by Kmohamed** [comment]
I am totally agree with you but whenever we want to remove an api we check the analytics about the usage of this api we found that people still you this api however it’s deprecated. So we need to push developers to use the new api in order to remove it. And Unfortunately not all people turns warning into error 😞

**Comment by keith** [comment]
I think if people are ignoring warnings added by your SDK, and then you drop the APIs that you were warning about, it's on them 😄

**Comment by keith** [comment]
If this isn't going to be fixed can you please add some configuration to never log to the console?

**Comment by Kmohamed** [comment]
This means you are gone use deprecated apis 😅😅

**Comment by keith** [comment]
We have warnings as errors ¯\\_(ツ)_/¯

**Comment by Kmohamed** [comment]
One more thing if you’re using un deprecated apis you should not see this message if you see it so it’s a bug

**Comment by keith** [comment]
> One more thing if you’re using un deprecated apis you should not see this message if you see it so it’s a bug

We aren't using deprecated APIs, but you're calling the deprecated version of `start` from the new one 😄

**Comment by Kmohamed** [comment]
You need to use statWithToken:invocationEvents (without s)

**Comment by keith** [comment]
We are calling the version with the `s`. According to hopper, the implementation of that method calls the deprecated one, which ends up printing this log:

```
+(void)startWithToken:(void *)arg2 invocationEvents:(long long)arg3 {
    [self startWithToken:arg2 invocationEvent:arg3];
    return;
}```

**Comment by Kmohamed** [comment]
@keith Since you are only using the static version of Instabug I update the latest release with the fix and will be included in the next release. sorry for misunderstanding

**Comment by keith** [comment]
You changed the binary that's being hosted on that release?

**Comment by Kmohamed** [comment]
Yes

**Comment by keith** [comment]
For future reference I wouldn't do that if I were you. Most good dependency management systems verify that the binary being download is the same sha as it was last time, to combat this exact problem of the binary changing out from under you. Ours does this as well, but luckily we re-host this binary internally. We'll wait for the next release for the fix.

**Comment by Kmohamed** [comment]
make sense

**Comment by keith** [comment]
Thanks for fixing though!

**Comment by Kmohamed** [comment]
@keith we released a hot fix for this bug https://github.com/Instabug/Instabug-iOS/releases/tag/8.0.7
feel free to reopen it again if you face it.

**Comment by keith** [comment]
This is fixed thanks!
