### ISSUE TITLE
Warning when linking static version

### ISSUE THREAD

**Issue by keith** [Instabug/Instabug-iOS#278]
### Steps to Reproduce the Problem

Archive an app that links the static instabug version and generates dsyms

### Expected Behavior

No warnings

### Actual Behavior

You get this warning:

```
note: Linking a static library that was built with -gmodules, but the module cache was not found.  Redistributable static libraries should never be built with module debugging enabled.  The debug experience will be degraded due to incomplete debug information.
```

### SDK Version

8.0.6 static (before replacement)

### iOS Version

iOS 10 deployment target

**Comment by Kmohamed** [comment]
We fix it in the latest release could you [check](https://github.com/Instabug/Instabug-iOS/releases/tag/8.0.7) it

**Comment by keith** [comment]
This is fixed thanks!

**Comment by Kmohamed** [comment]
Thanks a lot keith for your support 🙏🙏🙏
