### ISSUE TITLE
[IBGDeviceStateLogger getWifiSSID] crashed app

### ISSUE THREAD

**Issue by nab0y4enko** [Instabug/Instabug-iOS#281]
### Steps to Reproduce the Problem
1) Open the app
2) Working with the app

### Expected Behavior
The application does not crashes

### Actual Behavior
Crash detected

### Instabug integration code
?

### SDK Version
8.0.4

### iOS Version
11.4.1 (15G77)

### Device Type
iPhone X

[com.dartfleet.mobile_issue_53_crash_42d9fe4de7534833b40f91d28170b00c_DNE_0_v2.txt](https://github.com/Instabug/Instabug-iOS/files/2266390/com.dartfleet.mobile_issue_53_crash_42d9fe4de7534833b40f91d28170b00c_DNE_0_v2.txt)

**Comment by Kmohamed** [comment]
Is this occurs consistent?

**Comment by nab0y4enko** [comment]
Hello @Kmohamed! Yes, today reports on crashes were sent again.

**Comment by Kmohamed** [comment]
let me check it and get back to you.

**Comment by nab0y4enko** [comment]
Hello @Kmohamed! Any updates?

**Comment by Kmohamed** [comment]
@nab0y4enko any updates ?

**Comment by Kmohamed** [comment]
@nab0y4enko fixed on SDK version [8.0.18](https://github.com/Instabug/Instabug-iOS/releases/tag/8.0.18)
