### ISSUE TITLE
Still get "Could not successfully update network info during initialization." spam in SDK 8.0.7

### ISSUE THREAD

**Issue by brianbrantner** [Instabug/Instabug-iOS#282]
### Steps to Reproduce the Problem
Integrate Instabug framework 8.0.7 into project.
Run on device (iPadPro 9.7)
Start Instabug with:
[Instabug startWithToken:@"mytoken" invocationEvents:IBGInvocationEventNone];

### Expected Behavior
No "Could not successfully update network info during initialization." spam in console

### Actual Behavior
Continuous ""Could not successfully update network info during initialization." spam in console

### Instabug integration code
[Instabug startWithToken:@"mytoken" invocationEvents:IBGInvocationEventNone];

### SDK Version
8.0.7

### iOS Version
11.4

### Device Type
iPadPro 9.7

**Comment by brianbrantner** [comment]
When I comment out:
//[Instabug startWithToken:@"myToken" invocationEvents:IBGInvocationEventNone];

the "Could not successfully update network info during initialization." spamming stops, so I don't think it is the Facebook SDK

**Comment by Kmohamed** [comment]
We are very sorry for facing this issue again I will check it and get back to you again.

**Comment by Kmohamed** [comment]
@brianbrantner we just released a hot fix for this issue could you check it please.

**Comment by rdiaa** [comment]
@brianbrantner 

The problem is fixed in V. 8.0.8, can you please update it the SDK and tell me if you are still facing the same problem.

**Comment by rdiaa** [comment]
@brianbrantner,

glad to hear that, we are always available if you need anything
