### ISSUE TITLE
error while archiving the project

### ISSUE THREAD

**Issue by amitkumar3968** [Instabug/Instabug-iOS#284]
I am not able to archive using latest binary.
after adding new libararies, project is running fine on device,
but when i go to archive , it shows linker warnings and error in run script phase.

**Comment by Kmohamed** [comment]
Could you share with me the script in build phase ?

**Comment by Korazy** [comment]
@amitkumar3968 would you be able to share with us the script in the build phase?

**Comment by amitkumar3968** [comment]
ya sure, give me sometime, currently busy on other project.
if you want , can close the issue .
