### ISSUE TITLE
Crash after setting IBGLog.printsToConsole to false

### ISSUE THREAD

**Issue by nizarjak** [Instabug/Instabug-iOS#285]
### Steps to Reproduce the Problem

`IBGLog.printsToConsole = false`

### Expected Behavior

App should run without problem and not crash at start.

### Actual Behavior

App crashes at start because of:

```
+[IBGLog setPrintsToConsole:]: unrecognized selector sent to class 0x10246e188
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '+[IBGLog setPrintsToConsole:]: unrecognized selector sent to class 0x10246e188'
```

I'm not using objective c, just Swift 4.

### Instabug integration code

```
Instabug.start(withToken: "TOKEN", invocationEvents: [.shake, .screenshot])
Instabug.setLocale(.czech)
CrashReporting.enabled = false
IBGLog.printsToConsole = false
BugReporting.promptOptions = [.bug, .feedback]
```

### SDK Version

8.0.9

### iOS Version

Device version: 11.4.1
Base SDK: iOS SDK 11.4

### Device Model

iPhone 7

**Comment by nizarjak** [comment]
Its not crashing now, thank you so much 👏 . 
I would specify that step in migrating docs to ensure me being the last one asked.

Have a nice day

**Comment by Kmohamed** [comment]
Sure I will
