### ISSUE TITLE
Can I use BugReporting as regular UIViewController to push it using a UINavigtionController

### ISSUE THREAD

**Issue by 0xacdc** [Instabug/Instabug-iOS#287]
It would be great if there is a way to present BugReporting as a usual ViewController without creating it's own window calling BugReporting.invoke()

is it possible ?
Thanks

**Comment by Kmohamed** [comment]
@0xacdc for now it's not possible but can you provide us with more details about your use-case why you want it as a `viewController`?

**Comment by 0xacdc** [comment]
I want to allow user to "send a suggestion" and "report a bug" from a settings TableViewController  from where the BugReporting will be pushed like all others cells

**Comment by 0xacdc** [comment]
One more thing, in App extensions creation of Windows is impossible, so I can't use your SDK in iOS12 password extension. 

Can you make public access to View-controllers directly ? or provide me other solution 
Thanks

**Comment by Korazy** [comment]
@0xacdc at the moment, Instabug isnt designed to work in app extensions. Allowing public access or any similar solution at the moment is also quite difficult at the moment.
