### ISSUE TITLE
ChatList hide new chat button

### ISSUE THREAD

**Issue by 0xacdc** [Instabug/Instabug-iOS#288]
Is it possible to restrict users to not create new chat from ChatListVC? hide the button or something like this ?

I'd like to allow users to ask their questions trough sending bugs or suggestions, and use ChatListVC just to monitor all conversations

Thanks

**Comment by Korazy** [comment]
Hi @0xacdc 

Thanks for reaching out with this. That's not possible at the moment but i'll make sure to discuss with the team internally and update you if it is released :)

**Comment by Korazy** [comment]
Hey @0xacdc 

I just thought I'd reach out to you to let you know that we've implemented this feature in our latest release of version 8.1.

You can now prevent users from starting new chats while allowing you to start chats with them and for them to view existing chats. You can find all the details regarding this new feature [here](https://docs.instabug.com/docs/ios-chat-workflow).

Please feel free to reach out if you have any questions at all.
