### ISSUE TITLE
Cannot disable welcome message

### ISSUE THREAD

**Issue by goa** [Instabug/Instabug-iOS#289]
### Expected Behavior

Welcome screen **should not appear**.

### Actual Behavior

Welcome screen **does appear** on first launch.

### Instabug integration code
```
	let invocationEvents: IBGInvocationEvent = [.shake]
	let token = <my_token>
	Instabug.welcomeMessageMode = .disabled
	Instabug.setPushNotificationsEnabled(false)
	BugReporting.enabledAttachmentTypes = [.screenShot, .extraScreenShot]
	Instabug.start(withToken: token, invocationEvents: invocationEvents)
```

### SDK Version
8.0.12

### iOS Version
12.0 and 11.3

### Device Model
iPhone 7, iPhone 5s

**Comment by Kmohamed** [comment]
@goa could you add it after `startWithToken:` ?

**Comment by goa** [comment]
Tried it there as well, but the result was the same.

**Comment by Kmohamed** [comment]
I just tried it and it works fine. if you disable welcome message it will not be shown after 30 sec from the first launch of the app but if you call `showWelcomeMessageWithMode` it will works

**Comment by goa** [comment]
I think I found out what was happening... not sure...

I had an asynchronous call to `Instabug.setUserAttribute` which took place before `Instabug.welcomeMessageMode = .disabled`.

Now that I've removed the `Instabug.setUserAttribute` call, the welcome screen does not appear anymore... not sure if that is expected behaviour.

**Comment by ramiimagdi** [comment]
Hey @goa, 
My apologies for the late reply here. I'm glad that everything is working fine now at your end. Please don't hesitate to reach out to us again if you need help with anything at all.
