### ISSUE TITLE
Instabug IBGInvocationEventFloatingButton interferes with SVProgressHUD 

### ISSUE THREAD

**Issue by fatuhoku** [Instabug/Instabug-iOS#29]
https://github.com/TransitApp/SVProgressHUD is a wildly popular HUD solution for iOS.

I love using the Instabug floating button, but when I do, the Instabug floating button overlay causes this sort of thing to happen:

![ios simulator screen shot 19 sep 2015 13 17 12](https://cloud.githubusercontent.com/assets/430233/9976116/c30ffc56-5ed0-11e5-8f58-a9c229643163.png)

They're probably fighting over the root view controller's view or something.

**Comment by msoliman** [comment]
@fatuhoku I guess we've found and fixed this issue. Can you replace the framework that you have with the one linked below. Let me know how it goes.
https://www.dropbox.com/s/cuhi6kr9plgcifj/Instabug.framework.zip?dl=0

**Comment by msoliman** [comment]
@fatuhoku we've just pushed this fix to master. Let me know if you're still seeing this.

**Comment by fatuhoku** [comment]
@msoliman Sure. Will do.
