### ISSUE TITLE
Instabug logging doesn't work for multipart/form-data image upload 

### ISSUE THREAD

**Issue by steven851007** [Instabug/Instabug-iOS#291]
### Steps to Reproduce the Problem

1: Have `sessionConfiguration` set up the following way where Instabug enable logging is called for the configuration:
```
- (NSURLSessionConfiguration *)sessionConfiguration {
	NSURLSessionConfiguration *urlSessionConfiguration = [NSURLSessionConfiguration ephemeralSessionConfiguration];
	urlSessionConfiguration.requestCachePolicy = NSURLRequestReloadIgnoringLocalCacheData;
	urlSessionConfiguration.URLCache = nil;
	[Instabug enableLoggingForURLSessionConfiguration:urlSessionConfiguration];
	return urlSessionConfiguration;
}

```

2: Use the session configuration to make a multi part image uploading request (we use AFNetworking):

```
@property (strong, nonatomic) AFURLSessionManager *sessionManager;
...
- (void)executeRequest:(NSURLRequest *) urlRequest {
   self.sessionManager = [[AFURLSessionManager alloc] initWithSessionConfiguration:self.sessionConfiguration];
	self.sessionManager.responseSerializer = [AFHTTPResponseSerializer new];

   NSURLSessionDataTask * dataTask = [self.sessionManager dataTaskWithRequest:urlRequest uploadProgress:nil downloadProgress:nil completionHandler:^(NSURLResponse * _Nonnull response, id  _Nullable responseObject, NSError * _Nullable error) {
      [self handleResponse:response];
    }

   [dataTask resume];
}
```

### Expected Behavior
The upload is successful and the data is not compromised

Successful log of an upload request when `enableLoggingForURLSessionConfiguration` is not called for the session configuration:

```
2018-10-03 15:16:33.707253+0200 - POST 'https://service-int.****.ch/smartphone/file/v1/documents/content?docType=IDENTIFICATION&ownerId=90070afe-d5ed-4d64-8e10-1cd3ec4e35a2&ownerType=PC&name=photo&contentType=JPEG':
	head = {
	    Accept = "text/javascript, application/json, text/json";
	    "Accept-Language" = "en;q=1";
	    "Content-Length" = 1371377;
	    "Content-Type" = "multipart/form-data; boundary=Boundary+D88345E0CD23F985";
	    Cookie = "Navajo=5a1cbd0a05e4Ck8EneHCQFvtbUNFWsheoa28HLztC9xII2jRhdn1dVAHtK";
	}
	body = 
	--Boundary+D88345E0CD23F985
	
	Content-Disposition: form-data; name="contentType"
	
	
	
	JPEG
	
	--Boundary+D88345E0CD23F985
	
	Content-Disposition: form-data; name="docType"
	
	
	
	IDENTIFICATION
	
	--Boundary+D88345E0CD23F985
	
	Content-Disposition: form-data; name="name"
	
	
	
	photo
	
	--Boundary+D88345E0CD23F985
	
	Content-Disposition: form-data; name="ownerId"
	
	
	
	90070afe-d5ed-4d64-8e10-1cd3ec4e35a2
	
	--Boundary+D88345E0CD23F985
	
	Content-Disposition: form-data; name="ownerType"
	
	
	
	PC
	
	--Boundary+D88345E0CD23F985
	
	Content-Disposition: form-data2018-10-03 15:16:33.707 POST 'https://service-int.****.ch/smartphone/file/v1/documents/content?docType=IDENTIFICATION&ownerId=90070afe-d5ed-4d64-8e10-1cd3ec4e35a2&ownerType=PC&name=photo&contentType=JPEG':
	head = {
	    Accept = "text/javascript, application/json, text/json";
	    "Accept-Language" = "en;q=1";
	    "Content-Length" = 1371377;
	    "Content-Type" = "multipart/form-data; boundary=Boundary+D88345E0CD23F985";
	    Cookie = "Navajo=5a1cbd0a05e4Ck8EneHCQFvtbUNFWsheoa28HLztC9xII2jRhdn1dVAHtK";
	}
	body = 
	--Boundary+D88345E0CD23F985
	
	Content-Disposition: form-data; name="contentType"
	
	
	
	JPEG
	
	--Boundary+D88345E0CD23F985
	
	Content-Disposition: form-data; name="docType"
	
	
	
	IDENTIFICATION
	
	--Boundary+D88345E0CD23F985
	
	Content-Disposition: form-data; name="name"
	
	
	
	photo
	
	--Boundary+D88345E0CD23F985
	
	Content-Disposition: form-data; name="ownerId"
	
	
	
	90070afe-d5ed-4d64-8e10-1cd3ec4e35a2
	
	--Boundary+D88345E0CD23F985
	
	Content-Disposition: form-data; name="ownerType"
	
	
	
	PC
	
	--Boundary+D88345E0CD23F985
	
	Content-Disposition: form-data; name="bytes"; filename="photo.jpg"
	
	Content-Type: image/jpeg
	
	
	
	ÿ; name="bytes"; filename="photo.jpg"
	
	Content-Type: image/jpeg
	
	
	
	ÿØÿà\^PJFIF\^A\^AHHÿáXExifMM*\^H\^B\^A\^R\^C\^A\^Ai\^D\^A&\^C \^A\^C\^A\^A \^B\^D\^A
	¸ \^C\^D\^A\^GÒÿí8Photoshop 3.08BIM\^D\^D8BIM\^D<percentChar>\^PÔ\^]Ù²\^Dé	ìøB~ÿÀ\^Q\^H\^GÒ
	¸\^C\^A"\^B\^Q\^A\^C\^Q\^AÿÄ\^_\^A\^E\^A\^A\^A\^A\^A\^A\^A\^B\^C\^D\^E\^F\^G\^H	
	
	ÿÄµ\^P\^B\^A\^C\^C\^B\^D\^C\^E\^E\^D\^D\^A}\^A\^B\^C\^D\^Q\^E\^R!1A\^F\^SQa\^G"q\^T2¡\^H#B±Á\^URÑð$3br	
	\^V\^W\^X\^Y\^Z<percentChar>&'()*456789:CDEFGHIJSTUVWXYZcdefghijstuvwxyz
	¢£¤¥¦§¨©ª²³´µ¶·¸¹ºÂÃÄÅÆÇÈÉÊÒÓÔÕÖ×ØÙÚáâãäåæçèéêñòóôõö÷øùúÿÄ\^_\^A\^C\^A\^A\^A\^A\^A\^A\^A\^A\^A\^A\^B\^C\^D\^E
	...
	Only the first 1024 bytes are shown.
	request created in: [OnboardingWebService uploadImageWithInformation:withCredentials:onSuccess:onFailure:]
	request executed: [OnboardingWebService uploadImageWithInformation:withCredentials:onSuccess:onFailure:]
ØÿàJFIFHHÿáXExifMM*i&  
	¸ Òÿí8Photoshop 3.08BIM8BIM<percentChar>ÔÙ²é	ìøB~ÿÀÒ
	¸"ÿÄ	
	
	ÿÄµ}!1AQa"q2¡#B±ÁRÑð$3br	
	<percentChar>&'()*456789:CDEFGHIJSTUVWXYZcdefghijstuvwxyz
	¢£¤¥¦§¨©ª²³´µ¶·¸¹ºÂÃÄÅÆÇÈÉÊÒÓÔÕÖ×ØÙÚáâãäåæçèéêñòóôõö÷øùúÿÄ
	...
	Only the first 1024 bytes are shown.
	request created in: [OnboardingWebService uploadImageWithInformation:withCredentials:onSuccess:onFailure:]
	request executed: [OnboardingWebService uploadImageWithInformation:withCredentials:onSuccess:onFailure:]
	
2018-10-03 15:16:34.164 200 for POST 'https://service-int.****.ch/smartphone/file/v1/documents/content' [0.465 s]:
	head = {
	    "Cache-Control" = "no-cache, no-store, must-revalidate";
	    Connection = "Keep-Alive";
	    "Content-Type" = "application/json";
	    Date = "Wed, 03 Oct 2018 13:16:33 GMT";
	    Expires = 0;
	    "Keep-Alive" = "timeout=5, max=10";
	    Pragma = "no-cache";
	    Server = Apache;
	    "Transfer-Encoding" = Identity;
	}
	body = {
	  "uuid" : "d0cc79fc-3394-4ac2-ba0f-09ed8e59a2fe"
	}
``` 

### Actual Behavior
The upload fails with the error: `messageKey":"org.jvnet.mimepull.MIMEParsingException","reason":"Missing start boundary`

Failed request of the same multipart image upload when `enableLoggingForURLSessionConfiguration` is called. Nothing else changed only this one line is added:
```


2018-10-03 15:14:04.538768+0200 - POST 'https://service-int.****.ch/smartphone/file/v1/documents/content?docType=IDENTIFICATION&ownerId=275bd7e7-062c-4a00-afdb-ab6d42ecaebc&ownerType=PC&name=photo&contentType=JPEG':
	head = {
	    Accept = "text/javascript, application/json, text/json";
	    "Accept-Language" = "en;q=1";
	    "Content-Length" = 1371377;
	    "Content-Type" = "multipart/form-data; boundary=Boundary+40422749773409A9";
	    Cookie = "Navajo=5a1cbd0a05e4RGc0DZFbn6iIuxjNGNgk3LIzjGUjVcSnVDMe5cvE85ANeR";
	}
	body = 
	--Boundary+40422749773409A9
	
	Content-Disposition: form-data; name="contentType"
	
	
	
	JPEG
	
	--Boundary+40422749773409A9
	
	Content-Disposition: form-data; name="docType"
	
	
	
	IDENTIFICATION
	
	--Boundary+40422749773409A9
	
	Content-Disposition: form-data; name="name"
	
	
	
	photo
	
	--Boundary+40422749773409A9
	
	Content-Disposition: form-data; name="ownerId"
	
	
	
	275bd7e7-062c-4a00-afdb-ab6d42ecaebc
	
	--Boundary+40422749773409A9
	
	Content-Disposition: form-data; name="ownerType"
	
	
	
	PC
	
	--Boundary+40422749773409A9
	
	Content-Disposition: form-data; name="bytes"; filename="photo.jpg"
	
	Content-Type: image/jpeg
	
	
	
	ÿØÿà\^PJFIF\^A\^AHHÿáXExifMM*\^H\^B\^A\^R\^C\^A\^Ai\^D\^A&\^C \^A\^C\^A\^A \^B\^D\^A
	¸ \^C\^D\^A\^GÒÿí8Photoshop 3.08BIM\^D\^D8BIM\^D<percentChar>\^PÔ\^]Ù²\^Dé	ìøB~ÿÀ\^Q\^H\^GÒ
	¸\^C\^A"\^B\^Q\^A\^C\^Q\^AÿÄ\^_\^A\^E\^A\^A\^A\^A\^A\^A\^A\^B\^C\^D\^E\^F\^G\^H	
	
	ÿÄµ\^P\^B\^A\^C\^C\^B\^D\^C\^E\^E\^D\^D\^A}\^A\^B\^C\^D\^Q\^E\^R!1A\^F\^SQa\^G"q\^T2¡\^H#B±Á\^URÑð$3br	
	\^V\^W\^X\^Y\^Z<percentChar>&'()*456789:CDEFGHIJSTUVWXYZcdefghijstuvwxyz
	¢£¤¥¦§¨©ª²³´µ¶·¸¹ºÂÃÄÅÆÇÈÉÊÒÓÔÕÖ×ØÙÚáâãäåæçèéêñòóôõö÷øùúÿÄ\^_\^A\^C\^A\^A\^A\^A\^A\^A\^A\^A\^A\^A\^B\^C\^D\^E
	...
	Only the first 1024 bytes are shown.
	request created in: [OnboardingWebService uploadImageWithInformation:withCredentials:onSuccess:onFailure:]
	request executed: [OnboardingWebService uploadImageWithInformation:withCredentials:onSuccess:onFailure:]
2018-10-03 15:14:04.539 POST 'https://service-int.****.ch/smartphone/file/v1/documents/content?docType=IDENTIFICATION&ownerId=275bd7e7-062c-4a00-afdb-ab6d42ecaebc&ownerType=PC&name=photo&contentType=JPEG':
	head = {
	    Accept = "text/javascript, application/json, text/json";
	    "Accept-Language" = "en;q=1";
	    "Content-Length" = 1371377;
	    "Content-Type" = "multipart/form-data; boundary=Boundary+40422749773409A9";
	    Cookie = "Navajo=5a1cbd0a05e4RGc0DZFbn6iIuxjNGNgk3LIzjGUjVcSnVDMe5cvE85ANeR";
	}
	body = 
	--Boundary+40422749773409A9
	
	Content-Disposition: form-data; name="contentType"
	
	
	
	JPEG
	
	--Boundary+40422749773409A9
	
	Content-Disposition: form-data; name="docType"
	
	
	
	IDENTIFICATION
	
	--Boundary+40422749773409A9
	
	Content-Disposition: form-data; name="name"
	
	
	
	photo
	
	--Boundary+40422749773409A9
	
	Content-Disposition: form-data; name="ownerId"
	
	
	
	275bd7e7-062c-4a00-afdb-ab6d42ecaebc
	
	--Boundary+40422749773409A9
	
	Content-Disposition: form-data; name="ownerType"
	
	
	
	PC
	
	--Boundary+40422749773409A9
	
	Content-Disposition: form-data; name="bytes"; filename="photo.jpg"
	
	Content-Type: image/jpeg
	
	
	
	ÿØÿàJFIFHHÿáXExifMM*i&  
	¸ Òÿí8Photoshop 3.08BIM8BIM<percentChar>ÔÙ²é	ìøB~ÿÀÒ
	¸"ÿÄ	
	
	ÿÄµ}!1AQa"q2¡#B±ÁRÑð$3br	
	<percentChar>&'()*456789:CDEFGHIJSTUVWXYZcdefghijstuvwxyz
	¢£¤¥¦§¨©ª²³´µ¶·¸¹ºÂÃÄÅÆÇÈÉÊÒÓÔÕÖ×ØÙÚáâãäåæçèéêñòóôõö÷øùúÿÄ
	...
	Only the first 1024 bytes are shown.
	request created in: [OnboardingWebService uploadImageWithInformation:withCredentials:onSuccess:onFailure:]
	request executed: [OnboardingWebService uploadImageWithInformation:withCredentials:onSuccess:onFailure:]
	
2018-10-03 15:14:04.794 500 for POST 'https://service-int.****.ch/smartphone/file/v1/documents/content' [0.265 s]:
	head = {
	    "Cache-Control" = "no-cache, no-store, must-revalidate";
	    Connection = close;
	    "Content-Type" = "application/json";
	    Date = "Wed, 03 Oct 2018 13:14:04 GMT";
	    Expires = 0;
	    "Monexio-Error" = technical;
	    Pragma = "no-cache";
	    Server = Apache;
	    "Transfer-Encoding" = Identity;
	}
	body = {
	  "httpStatus" : 500,
	  "message" : "Exception ID: ERR-42hehifg internal technical error",
	  "messageKey" : "org.jvnet.mimepull.MIMEParsingException",
	  "reason" : "Missing start boundary"
	}
	error = -1011 Request failed: internal server error (500) (com.alamofire.error.serialization.response)
	actual data = {"httpStatus":500,"message":"Exception ID: ERR-42hehifg internal technical error","messageKey":"org.jvnet.mimepull.MIMEParsingException","reason":"Missing start boundary"}
```

### Instabug integration code
```
[Instabug startWithToken:@"" invocationEvent:IBGInvocationEventShake];
[Instabug setPromptOptionsEnabledWithBug:YES feedback:NO chat:NO];
[DDLog addLogger:[DDInstabugLogger sharedInstance]];
```

### SDK Version
AFNetworking (3.2.1)
Instabug (7.13)
Instabug-CocoaLumberjack (1.0.2)
### iOS Version
11.4 (seems to happen on all version)

### Device Mode
iPhone 6s (but it happens on all version)

**Comment by FadyDerias** [comment]
Hello @steven851007 
Thanks for reaching out.

If you're executing your image upload requests via AFNetworking, can you please share with us a sample of the code you're using?

If relying on a dedicated `NSURLSessionTask` instance, can you share with us how do you execute the upload image request?  There are many ways to do that in this case. For instance, you might be using any of the `NSURLSession` equivalent functions `dataTaskWithRequest` or `uploadTaskWithRequest` 

Thanks!

**Comment by steven851007** [comment]
Hello @FadyDerias,

Sure, we use `AFNetworking` and I've updated the ticket with the sample code. Let me know if you need anything else! 

Thanks!

**Comment by FadyDerias** [comment]
@steven851007 Thank you for the updates.

I did test uploading a `PNG` image via a multipart/form-data POST request and did enable Instabug network logging with an `NSURLSessionConfiguration ` instance equivalent to the one you're using and everything seemed to be operating quite well. 

I used the following [StackOverflow thread](https://bit.ly/2P70lzj) to construct a multipart/form-data image post `NSMutableURLRequest`  that you'll find in the sample below alongside the instructions you sent.

First thing I recommend before proceeding with the code is to update Instabug SDK to the most recent version, as we have updated our APIs (check the migration guide [here](https://bit.ly/2OEyBVC) ) and added numerous enhancements that will definitely be of great help to you.

Please notice that I used [this](https://bit.ly/2g84osK) Fake online REST API for the post request.

`- (void)executeMultiPartRequestViaAFNetworking {
    NSURLSessionConfiguration *urlSessionConfiguration = [NSURLSessionConfiguration ephemeralSessionConfiguration];
    urlSessionConfiguration.requestCachePolicy = NSURLRequestReloadIgnoringLocalCacheData;
    urlSessionConfiguration.URLCache = nil;

    //API Updated..
    [IBGNetworkLogger enableLoggingForURLSessionConfiguration:urlSessionConfiguration];
    
    AFURLSessionManager *sessionManager = [[AFURLSessionManager alloc] initWithSessionConfiguration:urlSessionConfiguration];
    sessionManager.responseSerializer = [AFHTTPResponseSerializer new];
    
    NSDictionary *params = @{@"userName"     : @"rob",
                             @"userEmail"    : @"rob@email.com",
                             @"userPassword" : @"password"};
    
    NSString *path = [[NSBundle mainBundle] pathForResource:@"avatar" ofType:@"png"];
    
    NSURL *url = [[NSURL alloc] initWithString:@"https://jsonplaceholder.typicode.com/posts"];
    NSMutableURLRequest *request = [[NSMutableURLRequest alloc] initWithURL:url];
    [request setHTTPMethod:@"POST"];

    //Setting Boundary
    NSString *boundary = [self generateBoundaryString];
    NSString *contentType = [NSString stringWithFormat:@"multipart/form-data; boundary=%@", boundary];
    [request setValue:contentType forHTTPHeaderField: @"Content-Type"];
    
    //Setting the HTTP Body
    NSData *httpBody = [self createBodyWithBoundary:boundary parameters:params paths:@[path] fieldName:@"avatar"];
    [request setHTTPBody:httpBody];
    
    //HTTP POST request execution
    NSURLSessionDataTask * dataTask = [sessionManager dataTaskWithRequest:request uploadProgress:nil downloadProgress:nil completionHandler:^(NSURLResponse * _Nonnull response, id  _Nullable responseObject, NSError * _Nullable error) {
        if (error == nil) {
            NSLog(@"MIME REQUEST SUCCESSFUL !!");
        }
    }];
    
    [dataTask resume];
}

- (NSString *)generateBoundaryString {
    return [NSString stringWithFormat:@"Boundary-%@", [[NSUUID UUID] UUIDString]];
}

- (NSData *)createBodyWithBoundary:(NSString *)boundary
                        parameters:(NSDictionary *)parameters
                             paths:(NSArray *)paths
                         fieldName:(NSString *)fieldName {
    NSMutableData *httpBody = [NSMutableData data];
    
    // add params (all params are strings)
    
    [parameters enumerateKeysAndObjectsUsingBlock:^(NSString *parameterKey, NSString *parameterValue, BOOL *stop) {
        [httpBody appendData:[[NSString stringWithFormat:@"--%@\r\n", boundary] dataUsingEncoding:NSUTF8StringEncoding]];
        [httpBody appendData:[[NSString stringWithFormat:@"Content-Disposition: form-data; name=\"%@\"\r\n\r\n", parameterKey] dataUsingEncoding:NSUTF8StringEncoding]];
        [httpBody appendData:[[NSString stringWithFormat:@"%@\r\n", parameterValue] dataUsingEncoding:NSUTF8StringEncoding]];
    }];
    
    // add image data
    
    for (NSString *path in paths) {
        NSString *filename  = [path lastPathComponent];
        NSData   *data      = [NSData dataWithContentsOfFile:path];
        NSString *mimetype  = [self mimeTypeForPath:path];
        
        [httpBody appendData:[[NSString stringWithFormat:@"--%@\r\n", boundary] dataUsingEncoding:NSUTF8StringEncoding]];
        [httpBody appendData:[[NSString stringWithFormat:@"Content-Disposition: form-data; name=\"%@\"; filename=\"%@\"\r\n", fieldName, filename] dataUsingEncoding:NSUTF8StringEncoding]];
        [httpBody appendData:[[NSString stringWithFormat:@"Content-Type: %@\r\n\r\n", mimetype] dataUsingEncoding:NSUTF8StringEncoding]];
        [httpBody appendData:data];
        [httpBody appendData:[@"\r\n" dataUsingEncoding:NSUTF8StringEncoding]];
    }
    
    [httpBody appendData:[[NSString stringWithFormat:@"--%@--\r\n", boundary] dataUsingEncoding:NSUTF8StringEncoding]];
    
    return httpBody;
}

- (NSString *)mimeTypeForPath:(NSString *)path {
    // get a mime type for an extension using MobileCoreServices.framework
    
    CFStringRef extension = (__bridge CFStringRef)[path pathExtension];
    CFStringRef UTI = UTTypeCreatePreferredIdentifierForTag(kUTTagClassFilenameExtension, extension, NULL);
    assert(UTI != NULL);
    
    NSString *mimetype = CFBridgingRelease(UTTypeCopyPreferredTagWithClass(UTI, kUTTagClassMIMEType));
    assert(mimetype != NULL);
    
    CFRelease(UTI);
    
    return mimetype;
}`

If the above sample didn't work for you, please update me with the `MIME` type your application supports.

Thank you

**Comment by steven851007** [comment]
Hi @FadyDerias,

It turned the problem was in our network logger class, that was somehow conflicting with Instabug's network logger (both reading the request's `HTTPBodyStream`). I managed to fix it on our side, thank you for the help! 
Cheers 🍻
