### ISSUE TITLE
InputAccessoryView Displays When We dismiss Instabug 

### ISSUE THREAD

**Issue by vishalgspaceo** [Instabug/Instabug-iOS#293]
Steps 
1. If you use input accessory view for any controller lets say A
2. Present another controller B on controller A
3. Shake device will open instabug dialogue
4. Dismiss instabug dialogue with click on anywhere in screen
5. It will display input accessory view on controller B.

### Steps to Reproduce the Problem
Step 1
![img_0364](https://user-images.githubusercontent.com/28976977/46675170-70882300-cbfb-11e8-8f04-54ec3fd12dee.PNG)
Step 2
![img_0365](https://user-images.githubusercontent.com/28976977/46675171-70882300-cbfb-11e8-83a1-55d5fafc3423.PNG)
Step 3
![img_0366](https://user-images.githubusercontent.com/28976977/46675173-7120b980-cbfb-11e8-8997-35f119f33c10.PNG)

### Expected Behavior
It should not display input accessory view
### Actual Behavior
It displays input accessory view

### SDK Version
8.0.15

### iOS Version
iOS 12 (It happens with iOS 10 and iOS 11 too)

### Device Model
iPhone 6S (it happens with each iPhone)

**Comment by ramiimagdi** [comment]
Hey @vishalgspaceo, thank you do reaching out to us. We'll be investigating the case here and get back to you as fast as possible.

**Comment by yousefhamza** [comment]
Hi @vishalgspaceo , I need more info here to reproduce and fix your issue

* In your screenshots I see the same viewcontroller I assume A not B? 
* Also which view is the the `firstResponser` in the controller? and which is the input accessory view?

**Comment by ramiimagdi** [comment]
Hello again @vishalgspaceo,
Please check the custom build we attached its URL here: https://www.dropbox.com/s/d7julf9alpi1q1v/InstabugSample.zip?dl=0
And please, tell us what you do differently.

**Comment by ramiimagdi** [comment]
Hello again @vishalgspaceo, I was wondering if you had a chance to check the previous sample app I shared with you. 

Please let me know if I can help you with anything at all :)

**Comment by vishalgspaceo** [comment]
> Hello again @vishalgspaceo, I was wondering if you had a chance to check the previous sample app I shared with you.
> 
> Please let me know if I can help you with anything at all :)

@ramiimagdi  sorry for late reply . I really appreciate quick reply from you guys .
I made changes in demo given by you and regenerate issue . you can refer attached video for same.

Updated Code - https://www.dropbox.com/s/2zkt8gvpdv1a3lz/InstabugSample_UpdateByVishal.zip?dl=0

[InstabugIssue.mov.zip](https://github.com/Instabug/Instabug-iOS/files/2498018/InstabugIssue.mov.zip)

Thank you guys for amazing support . hope you fix this issue quickly :)

**Comment by vishalgspaceo** [comment]
Hello @ramiimagdi 

Are you able to regenerate issue by the given sample app ? 
Let me know if you need anything from my end .

**Comment by ramiimagdi** [comment]
Hello again @vishalgspaceo, thank you so much for your kind words, we do really appreciate it!

The sample application you shared with us is really more than helpful. We're currently on investigating the case, and I'll make sure I get back to you as fast as possible 😊

**Comment by vishalgspaceo** [comment]
Hi @ramiimagdi 
This solution worked . Thank you so much for your kind support 👍
