### ISSUE TITLE
When using carthage, can't use debugger due to "error: Couldn't IRGen expression, no additional error" 

### ISSUE THREAD

**Issue by bennichols** [Instabug/Instabug-iOS#294]
### Steps to Reproduce the Problem

Use Instabug framework via Carthage
Add a breakpoint and stop execution of the app
Try to print out the value of a variable

### Expected Behavior

I'd see the value of the variable.

### Actual Behavior

I get the error "error: Couldn't IRGen expression, no additional error"

This looks like it may be an issue with using pre-compiled binaries. https://stackoverflow.com/questions/52420272/error-couldnt-irgen-expression-no-additional-error

### Instabug integration code
Instabug.start(withToken: "", invocationEvents: [.screenshot])

### SDK Version
12.0

### iOS Version
12.0
### Device Model
Simulator

**Comment by Kmohamed** [comment]
@bennichols I can not understand how `Carthage` will build a framework like `Instabug` since Instabug is not `open source` framework.

**Comment by bennichols** [comment]
Ok, that's unfortunate. Is your build system up to date? Maybe a solution is to have the build system use the current version of Xcode.

**Comment by Kmohamed** [comment]
I will send you a custom build and give it a try if it works fine.

**Comment by Kmohamed** [comment]
@bennichols could you give this [version](https://www.dropbox.com/s/2t9mj6mga6j1518/Instabug-SDK.zip?dl=0) a try ?

**Comment by bennichols** [comment]
That worked, thanks!

**Comment by olejnjak** [comment]
@bennichols could I please ask what changed in the binary? I've got a similar problem on my libraries so it would be nice to be able to solve it. Thanks

**Comment by Kmohamed** [comment]
@olejnjak issue fixed on SDK version `8.0.17`.
