### ISSUE TITLE
warning from GitHub regarding storage file

### ISSUE THREAD

**Issue by romk1n** [Instabug/Instabug-iOS#295]
### Steps to Reproduce the Problem

update to latest instabug using cocoapods and submit to the GitHub repo.

### Expected Behavior

no warnings or issues

### Actual Behavior

GitHub gives a following warnings
`remote: warning: File Pods/Instabug/Instabug.framework/Instabug is 59.46 MB; this is larger than GitHub's recommended maximum file size of 50.00 MB`

### Instabug integration code
*Make sure to remove your app token.*

### SDK Version
8.0.15
### iOS Version
iOS 12
### Device Model
iPhone 
### [Optional] Project That Reproduces the Issue

**Comment by Kmohamed** [comment]
Hello @romk1n 
I am sorry for that. Also we are working hard to decrease our framework size
