### ISSUE TITLE
.

### ISSUE THREAD

**Issue by Majed1224** [Instabug/Instabug-iOS#296]
### Instabug integration code
*Make sure to remove your app token.*

**Comment by Majed1224** [comment]
.

**Comment by ramiimagdi** [comment]
Hey @Majed1224, thank you for reaching out!
However, it seems here that the issue you have open is missing data, can you please fill these data so that we can investigate on our side?

**Comment by ramiimagdi** [comment]
Hello again @Majed1224,

I was wondering if you had a chance to catch my previous message, please feel free to reopen the issue again, as soon as you fill the missing data.

Thank you!
