### ISSUE TITLE
Getting random crash in IBGCache.m file

### ISSUE THREAD

**Issue by somparkash2835** [Instabug/Instabug-iOS#297]
Fatal Exception: NSGenericException
*** Collection <__NSArrayM: 0x2803b4660> was mutated while being enumerated

CoreFoundation | __exceptionPreprocess
Foundation | +[NSKeyedArchiver archivedDataWithRootObject:]
InstabugCore | IBGCache.m line 181-[IBGCache writeModels:toPath:]
InstabugCore | IBGCache.m line 104__22-[IBGCache persistAll]_block_invoke_2
libdispatch.dylib | _dispatch_call_block_and_release
libsystem_pthread.dylib | start_wqthread

**Comment by Kmohamed** [comment]
@somparkash2835 We are sorry for experience this crash But could you provide us with SDK version because we already fixed this crash from a while.

**Comment by somparkash2835** [comment]
@Kmohamed we are using "Bundle versions 7.6"

**Comment by Kmohamed** [comment]
@somparkash2835 Could you please update to the latest version ?

**Comment by somparkash2835** [comment]
Sure. let me check with lates version :) @Kmohamed Thanks

**Comment by Kmohamed** [comment]
@somparkash2835 Anytime :) I will close it and if you still experience this crash please feel free to open it again.
