### ISSUE TITLE
Fatal Exception: NSInvalidArgumentException-[IBGSurvey initWithDictionary:]: 

### ISSUE THREAD

**Issue by bkovaly** [Instabug/Instabug-iOS#299]
### Steps to Reproduce the Problem
Ever since updating our app to the latest 8.0.15 iOS SDK, we've started seeing crashes with a callstack that looks like this:

Fatal Exception: NSInvalidArgumentException-[IBGSurvey initWithDictionary:]: unrecognized selector sent to instance 0x28046a4c0 Raw Text
--
0 | CoreFoundation | __exceptionPreprocess
4 | CoreFoundation | _CF_forwarding_prep_0
5 | Instabug | IBGCacheDecoder.m line 27+[IBGCacheDecoder getModelsFrom:]
6 | Instabug | IBGCache.m line 212-[IBGCache readModelsFromPath:]
7 | Instabug | IBGCache.m line 143-[IBGCache getCache]
8 | Instabug | IBGCache.m line 122-[IBGCache unpersistAll]
9 | Instabug | IBGCacheManager.m line 84__67-[IBGCacheManager registerCaches:forClasses:withCompletionHandler:]_block_invoke
10 | Foundation | __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__
21 | libsystem_pthread.dylib | start_wqthread

The only repro I've got of this in a staging environment is to install a build of our app that uses 8.0.15, then install an older version that uses the older SDK over the top without doing a clean install. While I understand that a version downgrade isn't something I would generally expect to be supported, the crash has been happening in the wild where a version downgrade shouldn't be possible. Do not have a repro for that scenario. 

### Expected Behavior
App doesn't crash
### Actual Behavior
App crashes
### SDK Version
8.0.15

**Comment by yousefhamza** [comment]
Can you give us the last version you u were on?

**Comment by bkovaly** [comment]
7.14.5

**Comment by yousefhamza** [comment]
Hi @bkovaly 

Upgrading to 8.0.15 and downgrading shouldn't cause any crash as we handle both with a migration, but migrations process can be broken If you are clearing the `NSUserDefaults`, Is this your case?

**Comment by bkovaly** [comment]
Yeah, we're definitely clearing user defaults in some cases. Is everything instabug stores in a specific key? Perhaps we can exempt instabug stuff from getting cleared.

**Comment by yousefhamza** [comment]
That's why, we will investigate how to improve this on our end.

Answering your questions, our keys are prefixed with `IBG`.

**Comment by yousefhamza** [comment]
@bkovaly We will implement a fix for this that will prevent this from happening again soon, will notify you then.
