### ISSUE TITLE
Bitcode support?

### ISSUE THREAD

**Issue by erwinl** [Instabug/Instabug-iOS#30]
Hello, 

I'm currently using v4.1.6 (https://github.com/Instabug/Instabug-iOS/releases/tag/4.1.6), installed via cocoapods, which says that there's Bitcode support. However when archiving I got this error:

```objc
ld: warning: full bitcode bundle could not be generated because '/Users/Est/Documents/Works/cheese/Pods/Instabug/Instabug.framework/Instabug(IBGLineLimitedString.o)' was built only with bitcode marker. The library must be generated from Xcode archive build with bitcode enabled (Xcode setting ENABLE_BITCODE)
```

Am I doing something wrong? Or is it true that Instabug doesn't have support for Bitcode yet?

**Comment by msoliman** [comment]
@erwinl can you please try this framework instead. Please let me know how it goes.
https://www.dropbox.com/s/fxur386528o9yyx/Instabug.framework.zip?dl=0

**Comment by erwinl** [comment]
@msoliman, thanks for the fast reply, and sorry for the late reply.

The framework you gave works, any idea why? and are you going to update the cocoapod version ?

**Comment by msoliman** [comment]
@erwinl yes, looks like it's a problem from our build script. I'll make sure to update the cocoapods version today. I'll let you know.

**Comment by erwinl** [comment]
Thank you very much @msoliman :+1:

**Comment by msoliman** [comment]
@erwinl we've just pushed this to master

**Comment by erwinl** [comment]
Thank you very much @msoliman

**Comment by heupel** [comment]
I see this issue with what I pulled from CocoaPods just yesterday (2016-02-02).  Help?  Thanks!

**Comment by m619** [comment]
Hi @heupel, can you confirm you're running Instabug 5.0.1 (maybe with `pod outdated`) and that you've cleaned the build folder before trying to build/archive?

**Comment by heupel** [comment]
I had version `5.0.0`.  After updating to `5.0.1` it seems to work.  Thanks!
