### ISSUE TITLE
Microphone access permission every time app is run on simulator

### ISSUE THREAD

**Issue by khurram18** [Instabug/Instabug-iOS#303]
![screenshot 2018-12-10 at 12 35 00 pm](https://user-images.githubusercontent.com/7508106/49718071-d126f100-fc7a-11e8-9646-dc5d041ac9e4.png)
Whenever I run app on simulator it asks me for permission to access microphone even though I had granted it multiple times. See attached screenshot

### Expected Behavior
It should not ask me for microhpone access permission every time I run app in simulator

### SDK Version
Latest 
### iOS Version
12.1
### Device Model
iPhone X Simulator

### macOS version
10.14.1

**Comment by Kmohamed** [comment]
@khurram18 I think this a bug in simulator not in Instabug I can only show alert once if the permission is not granted or canceled. Btw are you on Xcode beta version ?

**Comment by khurram18** [comment]
I am using xcode `Version 10.1 (10B61)`

**Comment by Kmohamed** [comment]
is this happened consistently? after restart the Xcode and clean the build ?
Did you try to this (`Hardware` -> `Erase All content and settings` ) for the simulator ?

**Comment by khurram18** [comment]
I had tried erasing all content, re-starting simulator/xcode etc but no luck

**Comment by Kmohamed** [comment]
I think it's not related to Instabug I am not allowed to show alert every-time

**Comment by Petr003** [comment]
> 
> ![screenshot 2018-12-10 at 12 35 00 pm](https://user-images.githubusercontent.com/7508106/49718071-d126f100-fc7a-11e8-9646-dc5d041ac9e4.png)
> Whenever I run app on simulator it asks me for permission to access microphone even though I had granted it multiple times. See attached screenshot
> 
> ### Expected Behavior
> It should not ask me for microhpone access permission every time I run app in simulator
> 
> ### SDK Version
> Latest 
> ### iOS Version
> 12.1
> ### Device Model
> iPhone X Simulator
> 
> ### macOS version
> 10.14.1
>

**Comment by yousefhamza** [comment]
It seems to be a problem with Xcode 10.1 and MacOS 10.14

This prompt is for `Simulator` app on your mac not for your app on the simulator, If you do not want to allow the Simulator to use the microphone go to: 
`System Preferences` > `Security & Privacy` > `Privacy` > `Microphone` > Remove Xcode selection

![screen shot 2018-12-30 at 10 39 41 am](https://user-images.githubusercontent.com/3893067/50545539-91bb4700-0c1f-11e9-8004-3b35a8ffceba.png)

**Comment by Petr003** [comment]
> 
> ![screenshot 2018-12-10 at 12 35 00 pm](https://user-images.githubusercontent.com/7508106/49718071-d126f100-fc7a-11e8-9646-dc5d041ac9e4.png)
> Whenever I run app on simulator it asks me for permission to access microphone even though I had granted it multiple times. See attached screenshot
> 
> ### Expected Behavior
> It should not ask me for microhpone access permission every time I run app in simulator
> 
> ### SDK Version
> Latest 
> ### iOS Version
> 12.1
> ### Device Model
> iPhone X Simulator
> 
> ### macOS version
> 10.14.1
>

**Comment by yousefhamza** [comment]
There's an open radar for this issue, please check it for updates: https://openradar.appspot.com/45938209
