### ISSUE TITLE
Exception - [NSNull length] unrecognized selector

### ISSUE THREAD

**Issue by dosaSpace** [Instabug/Instabug-iOS#304]
I'm new at React Native, I apologize in advance. 
Sometimes, but not everytime when the app is loaded for the first time and the main screen is showen, I get this error -
this is the screenshot  - 
[https://imgur.com/a/jOggPw1](url)

The function that made the error -
`async componentDidMount() {

     await this.allSongs();

  }

  allSongs = () => {
    console.log("allSongs function begin!");
    fetch(URL + "/SongsList", 
    {
      body: null,
      method: "POST",
      headers: {
        Accept: "application/json",
        "Content-type": "application/json; charset=UTF-8"
      }
    })
      .then(res => {
        return res.json();
      }) 
      .then(songsResult => {
        AsyncStorage.setItem("@Ye-Music:songs", songsResult.d);
      })
      .catch(err => {
        console.error(err);
      });
  };
`

Can anyone please tell me why is this erorr happening and how should I fix it?

**Comment by Kmohamed** [comment]
Hello @dosaSpace,
First, please do not post any questions that do not relate to Instabug.  you can use something like [StackOverflow](https://stackoverflow.com).
Second, you are passing null to the body please remove it and add empty `Dictionary`.

**Comment by dosaSpace** [comment]
@Kmohamed it's not a null that i'm passing its a json object.

**Comment by Kmohamed** [comment]
Could you try to pass empty object {}?

**Comment by dosaSpace** [comment]
@Kmohamed nope, that imposible this is the object im trying to pass - 
http://ruppinmobile.tempdomain.co.il/site15/WebService.asmx/SongsList

**Comment by Kmohamed** [comment]
If you are trying to fetch the content of the file. So why you are using a POST request you should use a GET request.

**Comment by Kmohamed** [comment]
You should remove the body from the request.

**Comment by dosaSpace** [comment]
@Kmohamed  o.k it's working good so far. but on the other function which is similar to this one (that I have on other screen) its has the same error.

**Comment by Kmohamed** [comment]
I think you may need to subscribe to Instabug for this kind of support. 🤔

**Comment by dosaSpace** [comment]
o.k but it's very complected to explain the bug. it's happening only after I send with another function a new string and then fethc it back...

**Comment by Kmohamed** [comment]
Let’s move this conversation over email in order not to add unrelated questions on our public repo.
Please email contactus@instabug.com and we could continue the conversation over there.
Happy New Year 💥🎉

**Comment by dosaSpace** [comment]
@Kmohamed  o.k ill will send an email for you now, thanks
