### ISSUE TITLE
Instabug: err: script not found

### ISSUE THREAD

**Issue by danipralea** [Instabug/Instabug-iOS#307]
Hello all. I continuously have issue trying to install Instabug in my project.

### Steps to Reproduce the Problem
just install cocoapods

### Expected Behavior
run the app

### Actual Behavior
error encountered

### SDK Version
8.0.17

### iOS Version
12.1.2

### Device Model
iPhone 6S Plus

### [Optional] Project That Reproduces the Issue

Note: Cocoapods version is 1.5.3
Architectures:
<img width="640" alt="screenshot 2019-01-21 15 02 50" src="https://user-images.githubusercontent.com/768893/51476254-aa85cb00-1d8d-11e9-9af6-a02a1f9a8b05.png">
Bitcode is enabled

Thank you so much in advance for any help on this!
Cheers.

**Comment by Kmohamed** [comment]
@danipralea please remove your integration code?

**Comment by Kmohamed** [comment]
@danipralea I will check it and get back to you again?

**Comment by danipralea** [comment]
done @Kmohamed 
thank you. your help is very much appreciated. I tried doing so many setups and hacks etc. it just won't work. I am currently disabling the script

**Comment by Kmohamed** [comment]
@danipralea could you tell me which script that you are using?

**Comment by danipralea** [comment]
```#--- SCRIPT BEGIN ---
# SKIP_SIMULATOR_BUILDS=1
SCRIPT_SRC=$(find "$PROJECT_DIR" -name 'Instabug_dsym_upload.sh' | head -1)
if [ ! "${SCRIPT_SRC}" ]; then
echo "Instabug: err: script not found. Make sure that you're including Instabug.bundle in your project directory"
exit 1
fi
APP_TOKEN="21c3406e1c0602a1a90f649a9c8f7c6d"
source "${SCRIPT_SRC}"
#--- SCRIPT END ---```

**Comment by Kmohamed** [comment]
@danipralea please remove you integration code? 😅

**Comment by danipralea** [comment]
> @danipralea please remove you integration code 😅

yeah, I did it afterwards 😄

**Comment by Kmohamed** [comment]
@danipralea If you are using Xcode 10 please see the related section [here](https://docs.instabug.com/docs/ios-crash-reporting#section-automatically).

**Comment by danipralea** [comment]
thank you for your reply @Kmohamed 
I did added it, but I am still getting an error.

PS: I am using Xcode 10. Do I need to add it only for the scheme or for both? (in Build Phases + Scheme) ?

**Comment by Kmohamed** [comment]
No, just the scheme but could you share with me the error?

**Comment by Kmohamed** [comment]
@danipralea could you please share with me script error? 🙏

**Comment by danipralea** [comment]
And I also think it's because I wasn't checking "Run script only when installing". not sure though, it may have just been the post-build stuff

**Comment by Kmohamed** [comment]
Great, I happy that is worked fine on Xcode 10 🎉

**Comment by danipralea** [comment]
yes. many many thanks!
really awesome support!

**Comment by tirthpatelflynn** [comment]
![Screen Shot 2020-03-27 at 1 14 07 PM](https://user-images.githubusercontent.com/44585584/77781962-dacd9700-702c-11ea-8f38-98af86b4af46.png)

So, I found it bit confusing as the. information written by hand says that put it in Archive>post-action but then the image right below it shows the Build>post-action. Can you please confirm the accurate place to put it? Thanks.

**Comment by Kmohamed** [comment]
I am very sorry for confusion @tirthpatelflynn, I will make sure to fix it.
If `Debug Information format` in build settings marked as `Dwarf` only in debug mode so you need to add this script in release mode only. If it is marked as `Dwarf with DSYM` file you need to add the script in both sections (post-archive and post-build)

**Comment by tirthpatelflynn** [comment]
Thank you so much for the prompt response will follow this instructions. @Kmohamed

**Comment by Kmohamed** [comment]
Anytime 🙏
