### ISSUE TITLE
Shake doesn't work on iPhone 7+

### ISSUE THREAD

**Issue by FrancoSabadini** [Instabug/Instabug-iOS#308]
### Steps to Reproduce the Problem

Start Instabug in iOS with the following code:

```
Instabug.start(withToken: Bundle.instabugToken, invocationEvents: .shake)
CrashReporting.enabled = false
```

### Expected Behavior

When shaking the device, the Instabug dialog should appear.

### Actual Behavior

When shaking the device, nothing happens.

### Instabug integration code

```
Instabug.start(withToken: Bundle.instabugToken, invocationEvents: .shake)
CrashReporting.enabled = false
```

I also tried adding `BugReporting.shakingThresholdForiPhone = 10.0` but nothing changed.

### SDK Version

8.0.17

### iOS Version

12.1.2

### Device Model

iPhone 7 Plus

**Comment by Kmohamed** [comment]
Could you make sure you entered the correct integration code?

**Comment by FrancoSabadini** [comment]
@Kmohamed if you mean the token, I checked and it's correct. When I invoke the dialog via code it appears correctly.

**Comment by Kmohamed** [comment]
@FrancoSabadini could please contact the support maybe you have a problem with the token?

**Comment by FrancoSabadini** [comment]
@Kmohamed as I mentioned, force invoking the dialog works, so wouldn't that fail as well if the token had an issue?

**Comment by Kmohamed** [comment]
Only 7plus?

**Comment by FrancoSabadini** [comment]
I contacted support just now. 

I only have a 7 plus to test, so can't guarantee whether it works on other devices or not.

**Comment by FrancoSabadini** [comment]
@Kmohamed setting the threshold to 1 made it work. Seems like I misread the documentation and thought that higher values made it more sensitive, instead of lower ones. 

Sorry for the confusion and thanks for the help, you can close the ticket now.

**Comment by Kmohamed** [comment]
@FrancoSabadini great no worries
