### ISSUE TITLE
Instabug-iOS SDK v8.0.19 - Disable background screenshots of view controllers with Repro Steps.

### ISSUE THREAD

**Issue by racer1988** [Instabug/Instabug-iOS#309]
## Instabug-iOS SDK v8.0.19

* Disable the auto screen recording API.
* Disable background screenshots of view controllers with Repro Steps.

Hello.
I can see this in the changelog, and in my project instabug ReproSteps with screenshots have stopped working.

Has been set to disabled by default?

The code and web documentation are saying:
"User Steps tracking is enabled by default if it's available in your current plan."

However the compiler gives a warning on `.enable` saying it is deprecated.

Should the Documentation be updated to reflect any change done?
Is this related to Apple checks on screen recordings?

Same question goes for

`Instabug.autoScreenRecordingEnabled = true`
That says to contact support

Thanks

**Comment by racer1988** [comment]
Additional related question:

### Instabug-iOS SDK v8.0.20

* Disable the view hierarchy.

However the documentation is not updated and there is no warning for:

`Instabug.shouldCaptureViewHierarchy = true`

Should this also get a warning?

**Comment by Kmohamed** [comment]
@racer1988 You are totally right, and here are more [details](https://instabug.com/blog/updates-to-our-terms-of-service/) about the latest release of SDK.
