### ISSUE TITLE
Please rebuild SDK with Xcode 7 to support BITCODE

### ISSUE THREAD

**Issue by SPopenko** [Instabug/Instabug-iOS#31]
Guys could you push new release please?

**Comment by Taarna** [comment]
Wasn't Bitcode added in v4.1.6 and fixed in v4.1.7?

**Comment by SPopenko** [comment]
I don't know but with last sdk my compilation was failed... If you could check than it will be nice.

**Comment by Taarna** [comment]
I'm not from Instabug, sorry for the misunderstanding :)

My team is using the latest SDK and we had no problems, except for one person who's still clinging to XCode 6. The compilation was failing for him when he tried to start the app on the simulator, but that's a known issue and not related to Instabug.

**Comment by msoliman** [comment]
@Taarna thanks for the reply.

@SPopenko Indeed, Bitcode should be working fine in v4.1.7. Are you having any problem with it?

**Comment by SPopenko** [comment]
@msoliman thanks, I could confirm that it works from 4.1.7. Thank you!
