### ISSUE TITLE
The Crash associated with IBGFeatures callback block

### ISSUE THREAD

**Issue by yz06276** [Instabug/Instabug-iOS#310]
### Steps to Reproduce the Problem
The error can not reproduce steadily.
### Expected Behavior
Crash randomly
### Actual Behavior
I found this crash stack in my
### Instabug integration code
```
- (void)setupInstabug {
    [Instabug startWithToken:@"" invocationEvents:IBGInvocationEventNone];
    if ([[AccountUtil getAccount] length] > 0) {
        [Instabug setUserAttribute:[AccountUtil getAccount] withKey:@"Account"];
    }
    if ([[ShopUtil getShopId] integerValue] > 0) {
        [Instabug setUserAttribute:[[ShopUtil getShopId] description] withKey:@"KDTID"];
    }
    if ([[ShopUtil getOfflineId] length] > 0) {
        [Instabug setUserAttribute:[ShopUtil getOfflineId] withKey:@"OfflineID"];
    }
    NSArray *actions = @[@{kShakeActionTitle: @"Report", kShakeActionHandler: ^{
        [IBGBugReporting invokeWithMode:IBGInvocationModeNewBug options:IBGBugReportingInvocationOptionEmailFieldHidden];
    }}];
    [XXXShake registerCustomAction:actions];
    [XXXShake getShakeIfOn];
    NSNumber *flag = [[NSUserDefaults standardUserDefaults] objectForKey: kInstabugShakeConfigExcuteFlag];
    if (!flag) {
        [XXXShake setShakeOn:true];
        [[NSUserDefaults standardUserDefaults] setObject:@(true) forKey:kInstabugShakeConfigExcuteFlag];
    }
}

```
### SDK Version
8.0.17
### iOS Version
iOS 11 or newer
### Device Model
iPhone 6 or newer 
### [Optional] Project That Reproduces the Issue

The following is crash stack.
```
#0 Thread
NSInvalidArgumentException
*** -[__NSPlaceholderArray initWithObjects:count:]: attempt to insert nil object from objects[3]

0 CoreFoundation	___exceptionPreprocess + 228
1 libobjc.A.dylib	objc_exception_throw + 56
2 CoreFoundation	_CFArgv + 0
3 CoreFoundation	-[__NSPlaceholderArray initWithObjects:count:] + 284
4 CoreFoundation	+[NSArray arrayWithObjects:count:] + 52
5 CoreFoundation	-[NSDictionary allKeys] + 256
6 InstabugCore	-[IBGFeatures featuresRequestDone:isSuccess:response:error:] + 1380
7 InstabugCore	-[IBGFeaturesRequest serverExecutionDone:statusCode:error:response:] + 252
8 InstabugCore	__57-[IBGServerManager URLSession:task:didCompleteWithError:]_block_invoke_2 + 64
9 libdispatch.dylib	0x00000001841db000 + 6816
10 libdispatch.dylib	0x00000001841db000 + 6752
11 libdispatch.dylib	0x00000001841db000 + 58972
12 CoreFoundation	___CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 12
13 CoreFoundation	___CFRunLoopRun + 2272
14 CoreFoundation	CFRunLoopRunSpecific + 552
15 GraphicsServices	GSEventRunModal + 100
16 UIKit	UIApplicationMain + 236
17 Koudaitong	main (main.m:16)
18 libdyld.dylib	_start + 4

```
This Crash will happen randomly , rarely On iOS 11 or newer version iOS. All the error stack message is same. Wanna get some help to find out what's happened?

**Comment by Kmohamed** [comment]
Let me check it and get back to you

**Comment by Kmohamed** [comment]
But are you sure that this crash occurs on sdk 8.0.17 because we merge Instabug and InstabugCore in one binary from a while so I think this crash from an old SDK version.

**Comment by Kmohamed** [comment]
Did you manage to check the SDK version?

**Comment by yz06276** [comment]
There's no version specified in my podfile. I upload a new version to App Store every two weeks, in development progress , pod dependency will be update (pod update). This error had surfaced at least half a year. Maybe it has little to do with the Instabug version.

**Comment by Kmohamed** [comment]
I am sure that you will not find this crash on the latest versions of SDK, 
also can you share with me the number of occurrences?

**Comment by yz06276** [comment]
all right , I'll try 😎
The error affected about 150 users, with hundreds of thousands of active users in the past six months.

**Comment by Kmohamed** [comment]
@yz06276 perfect, I will close it for now and feel free to open it again if you see this crash on the latest versions.
