### ISSUE TITLE
Taptic Engine support

### ISSUE THREAD

**Issue by arguiot** [Instabug/Instabug-iOS#312]
Apple introduced Taptic Engine on its phones with the iPhone 7 in 2016. It makes the app "feels" better by vibrating the device in a satisfying way, and it would be great to use it when Instabug is invoked.

For reference, here is a medium article explaining how to use Apple's Taptic Engine API: https://medium.com/@sdrzn/make-your-ios-app-feel-better-a-comprehensive-guide-over-taptic-engine-and-haptic-feedback-724dec425f10

It should be used on primary interactions such as invoking the alert, letting the user know that the issue was sent, etc.

**Comment by Kmohamed** [comment]
Hi @arguiot, Thanks for suggesting this to us, but why do you think` it would be great to use it when Instabug is invoked.` will be helpful?

**Comment by arguiot** [comment]
@Kmohamed It just feels "more native" to me. I tried Instabug, but it just doesn't feel right to me and many of my colleagues who are iPhone users like me.

I believe I have this feeling because Apple uses it when you shake the phone for undoing something.

**Comment by Kmohamed** [comment]
@arguiot I agree with you for shake only but not for all invocations right?

**Comment by arguiot** [comment]
@Kmohamed yes. And also for primary actions like clicking the record button or the send button.

**Comment by Kmohamed** [comment]
Thanks a lot 🙏🙏 I will make sure to send this to the product team
