### ISSUE TITLE
Poor UI performance during screen recording

### ISSUE THREAD

**Issue by kennygoff** [Instabug/Instabug-iOS#313]
UI thread performance drops significantly in screen record mode. Starting screen recording in an app makes the UI framerate drop from 60fps to ~30fps immediately, and down to below 10fps if you start scrolling or interacting with the app, even in sections that aren't doing any data loading or heavy calculations, as the JS thread stays performant. It's certainly usable, just not smooth.

Based on [this issue](https://github.com/Instabug/Instabug-iOS/issues/238) from the iOS framework for Instabug, Instabug will drop the framerate of the main thread for auto-recording feature. Is it the same for manual recording? Is there any way to get this to perform better for react native apps?

![screen shot 2018-08-22 at 2 09 22 pm](https://user-images.githubusercontent.com/1051880/44482074-6f803f80-a615-11e8-9c0f-5a65c2b6262f.png)

### SDK Version

- `instabug-reactnative`: `8.0.10`

### React Native, iOS and Android Versions

- `react-native`: `0.55`
- `iOS`: `11.4`
- `Android`: `6.0`

### Device Model

- `iOS Simulator`: `iPhone 6`
- `Android`: `Emulator running 6.0`
- Plus various other iOS devices

**Comment by HeshamMegid** [comment]
Just transferring the issue to our iOS repo for some housekeeping. 

In the meantime, since the API we depend on to capture screenshots is still broken in the latest versions of iOS, please feel free to dupe [this radar](http://openradar.appspot.com/45225596) to get Apple's attention.
