### ISSUE TITLE
Calling Instabug.show() on iOS in React Native app crashes

### ISSUE THREAD

**Issue by hiddentao** [Instabug/Instabug-iOS#314]
### Steps to Reproduce the Problem

* Add Instabug to React Native app via Cocoapods
* Expose a native-side Swift function to Javascript that internally calls `Instabug.show()`
* Run the app until this function gets called

### Expected Behavior

App shouldn't crash, and the Instabug dialog should show.

### Actual Behavior

The app UI becomes frozen, clicking anywhere crashes it

In logs:

```
void _WebThreadLock(), 0x143ae0000: Tried to obtain the web lock from a thread other than the main thread or the web thread. This may be a result of calling to UIKit from a secondary thread. Crashing now...
```

XCode screenshot:

<img width="1275" alt="Screenshot 2019-03-26 at 10 56 39" src="https://user-images.githubusercontent.com/266594/54991914-e28bd300-4fb5-11e9-8227-b9e598d4d3ea.png">

### Instabug integration code

```objectivec
  NSString* instabugToken = @"....";
  [Instabug startWithToken:instabugToken invocationEvents: IBGInvocationEventShake | IBGInvocationEventScreenshot];
  IBGBugReporting.bugReportingOptions = IBGBugReportingOptionEmailFieldHidden;
  [Instabug setColorTheme:IBGColorThemeLight];
  Instabug.tintColor = [UIColor colorWithRed:0.13 green:0.13 blue:0.13 alpha:1.0];
  [Instabug setWelcomeMessageMode:IBGWelcomeMessageModeDisabled];
  [Instabug setValue:@"Report app bug" forStringWithKey:kIBGReportBugStringName];
  [Instabug setValue:@"Get support" forStringWithKey:kIBGAskAQuestionStringName];
```

### SDK Version

8.1

### iOS Version

12.1

### Device Model

Simulator - Iphone 7 Plus

**Comment by Kmohamed** [comment]
@hiddentao are you calling` Instabug.show()` from a background thread?

**Comment by hiddentao** [comment]
@Kmohamed Yep that was the issue, I wasn't aware of how RN did its threads. I've now got it working by adding the following to my bridge `.m` file:

```
- (dispatch_queue_t)methodQueue
{
  return dispatch_get_main_queue();
}
```

Further reference: 

* https://stackoverflow.com/questions/50773748/difference-requiresmainqueuesetup-and-dispatch-get-main-queue
* https://hackernoon.com/react-native-bridge-for-ios-and-android-43feb9712fcb

**Comment by Kmohamed** [comment]
Perfect 👍
