### ISSUE TITLE
8.2  Access UI on background thread

### ISSUE THREAD

**Issue by seanliu1** [Instabug/Instabug-iOS#315]
Main Thread Checker: UI API called on a background thread: -[UIApplication applicationState]
PID: 8138, TID: 1352270, Thread name: com.apple.CoreMotion.MotionThread, Queue name: com.apple.root.default-qos.overcommit, QoS: 0

shake is registered off main thread. 

### Instabug integration code
Instabug.start(withToken: "xx", invocationEvents: [.shake, .screenshot])

### SDK Version
8.2
### iOS Version
12.1
### Device Model
iPhone X

**Comment by Kmohamed** [comment]
It’s an issue from apple, for more details, please check this issue.
https://github.com/Instabug/Instabug-iOS/issues/298
