### ISSUE TITLE
8.2 crashes

### ISSUE THREAD

**Issue by maurovc** [Instabug/Instabug-iOS#316]
### Steps to Reproduce the Problem

Update pod to 8.2

### Expected Behavior

Initialise Instabug after passing an appToken

### Actual Behavior

Crash

### Instabug integration code
```
Instabug.start(withToken: AppSettings.Instabug.appToken, invocationEvents: .screenshot)
BugReporting.bugReportingOptions = [.emailFieldHidden, .commentFieldRequired]
```

### SDK Version

8.2

### iOS Version

12.1

### Device Model

iPhone XS Max

### Crash trace

<img width="1637" alt="Screenshot 2019-03-28 at 16 59 14" src="https://user-images.githubusercontent.com/10012427/55172774-d9982e80-517a-11e9-961c-cd179590d98a.png">

**Comment by Kmohamed** [comment]
Could you provide us with an exception name?

**Comment by maurovc** [comment]
Hey @Kmohamed thanks for the fast reply. Here's the whole stack trace:

<img width="1638" alt="Screenshot 2019-03-28 at 17 45 36" src="https://user-images.githubusercontent.com/10012427/55176457-72ca4380-5181-11e9-9b99-ba9a01097519.png">

This is everything that I can get from Hockeyapp.

Thanks,

Mauro

**Comment by Kmohamed** [comment]
First are you using cocoapods or not?
And are you able to reproduce it in a sample app?

**Comment by Kmohamed** [comment]
If you able to reproduce it on sample app. Please send it to me, 🙏

**Comment by maurovc** [comment]
Hey @Kmohamed we use cocoa pods for this. I'm trying to reproduce it there using the same team key but I can't 😞 . I'll keep trying. Thanks!

**Comment by Kmohamed** [comment]
Thanks a lot for your collaboration, another question are you able to reproduce it on your app only right?

**Comment by maurovc** [comment]
Yeah, I can pass you the example project in which I'm not doing anything different to what I do in the main app. Could this be a conflict with any other pod?

[InstabugTest.zip](https://github.com/Instabug/Instabug-iOS/files/3019475/InstabugTest.zip)

Just run `pod install` as I can't include the Pods folder here because of the size.

**Comment by Kmohamed** [comment]
I will check the sample app. But since you are able to reproduce it on your app I will send you a custom build to give it a try.

**Comment by Kmohamed** [comment]
Here is custom build could you give it a try?
`pod 'Instabug', :git => 'https://github.com/Instabug/Instabug-iOS.git', :branch => 'fix/missing_coredata_model'`

**Comment by maurovc** [comment]
Hey @kmohamed now I’m out of the office. I’ll check in a few hours once I’m back home. Thanks!

**Comment by Kmohamed** [comment]
Sure thing, and Thanks a lot for your collaboration 🙏

**Comment by Kmohamed** [comment]
we just released a hotfix to fix this issue so please update to SDK version [8.2.1](https://github.com/Instabug/Instabug-iOS/releases/tag/8.2.1) and feel free to open it again if you face this issue.
And thanks again for your patience.

**Comment by Kmohamed** [comment]
@maurovc is everything works fine with you?

**Comment by maurovc** [comment]
hey @Kmohamed I'll check later today and I'll let you know. Yesterday it was impossible for me to check. Thank you for your help!

**Comment by Kmohamed** [comment]
@maurovc Thanks a lot 🙏
