### ISSUE TITLE
Feature Request: While showing bug reporting screen allow us to pre-fill the email field

### ISSUE THREAD

**Issue by dineshflock** [Instabug/Instabug-iOS#318]
I want my users to avoid filling up the email if possible. Please expose an api so that we can pre-fill the email address.

**Comment by Kmohamed** [comment]
@dineshflock we do not have API to fill the email but you can ignore it and also do a lot of customization. check the [docs](https://docs.instabug.com/docs/ios-bug-report-content#section-bug-report-fields), please

**Comment by dineshflock** [comment]
Ok seems I can use to `BugReporting.bugReportingOptions = [.emailFieldOptional]` hide the email field and set the user email id via `Instabug.identifyUser(withEmail:"user.email.com", name: nil)`.
Will try out this, thanks.

**Comment by Kmohamed** [comment]
@dineshflock the problem with `Instabug.identifyUser(withEmail:"user.email.com", name: nil).` is we will treat all users that using your app as one user. So If you are using `Chats product` they can see all other user threads.

**Comment by Kmohamed** [comment]
@dineshflock Ohhh I forget to explain it in details this behavior will occur only if you call `Instabug.identifyUser(withEmail:"user.email.com", name: nil)` with static email.

**Comment by BNGriffin** [comment]
Ok

**Comment by dineshflock** [comment]
> @dineshflock Ohhh I forget to explain it in details this behavior will occur only if you call `Instabug.identifyUser(withEmail:"user.email.com", name: nil)` with static email.

Oh, I would not hardcode this email id, it was just to communicate the idea :) Anyways thanks.

**Comment by Kmohamed** [comment]
@dineshflock Perfect 👍
