### ISSUE TITLE
IBGLogs missing for some bugs

### ISSUE THREAD

**Issue by phlippieb** [Instabug/Instabug-iOS#319]
### SDK Version

8.2.2

### iOS Version

12.2

### Device Model

iPhone X

Simply put, for some of the bugs on our dashboard, the instabug log (i.e. those logged with `IBGLog.logError`, for example) are completely absent.

Unfortunately, I am not sure what the repro steps here would be, but I suspect it has to do with connectivity and/or volume of instabug logs.

We do log quite a lot, but we make use of the different log levels. So if our logs fail to upload due to a combination of volume and poor internet, I would like to suggest that the logs be split by level, and uploaded in order of priority -- in other words, first try to upload errors, then warnings, then info, then verbose, then debug. In this way, if the upload would fail due to the large amount of verbose logs logged, users might still be able to see error logs, which might be enough to solve a bug.

It would also be helpful if the cause of the missing logs could be reported somewhere on the dashboad.

**Comment by Kmohamed** [comment]
Hello @phlippieb,
Let me explain how Instabug logs work. We sent only 1K logs from the app in one single request. So If your Instabug logs exceed the 1K we sent only the latest 1K and not based on log level.

**Comment by Kmohamed** [comment]
@phlippieb is this explains why some logs are not on the dashboard if you do log a lot?

**Comment by phlippieb** [comment]
> @phlippieb is this explains why some logs are not on the dashboard if you do log a lot?

@Kmohamed In these instances, we're not just missing *some* logs; we're missing *all* logs. As in, if I filter by Instabug logs, I see nothing. So I don't think this explains what I'm seeing. 

I'm guessing what happened is that the entire 1K upload failed (which could be likely if a user has poor internet). Do you know if there are any retry mechanisms and/or error reporting in place that would pick this up?

**Comment by Kmohamed** [comment]
@phlippieb absolutely we have retry mechanism. But can you tell me how many bugs did not have logs?

**Comment by phlippieb** [comment]
Do you mean how many as in as a percentage of all bugs logged, or total? Not sure I can easily tell you.

I can say that we don't see this problem often. We usually use Instabug internally to keep track of bugs, so we (the developers) log them ourselves in the office, on good WiFi, and our client also usually logs them on good WiFi or on a good cellular connection. However, at the moment, our client is traveling and is using our app under various less-than-ideal network conditions. So we are seeing quite a few of these instances where the logs are missing, and even some where the bugs have no screenshots, user actions, or anything other than the bug title.

So obviously, if poor internet is the cause, these are circumstances outside your control. Just wondering whether you could put something on the dashboard to indicate what went wrong.

**Comment by Kmohamed** [comment]
If the case because of a poor internet connection whenever these users have a good internet connection the request will be sent. so don't worry.

**Comment by phlippieb** [comment]
Ah ok, cool. Thanks!

**Comment by Kmohamed** [comment]
Anytime.
