### ISSUE TITLE
Image Picker not showing in BugReporting

### ISSUE THREAD

**Issue by mgogor** [Instabug/Instabug-iOS#321]
### Steps to Reproduce the Problem
I am trying to invoke the Bug Reporter in Instabug through a button action in a viewcontroller. I have set 
`BugReporting.enabledAttachmentTypes = [.galleryImage]`
However, the imagePicker view does not show up in the Bug Reporter form. Any help is appreciated. Thanks!

![Simulator Screen Shot - iPhone Xs - 2019-05-24 at 10 54 52](https://user-images.githubusercontent.com/48553126/58299641-60cbf080-7e12-11e9-9b74-52727f31be78.png)

### Expected Behavior
Image Picker View should be visible
### Actual Behavior
Image Picker View is not visible
### Instabug integration code
AppDelegate

```
Instabug.start(withToken: APP_TOKEN, invocationEvents: [.none])
Instabug.welcomeMessageMode = .disabled
```

ViewController
```
BugReporting.enabledAttachmentTypes = [.galleryImage]
BugReporting.bugReportingOptions = [.emailFieldHidden, .commentFieldRequired]
BugReporting.show(with: .feedback , options: BugReporting.bugReportingOptions)
```

### SDK Version
8.3.1
### iOS Version
12.2
### Device Model
iPhone 8 Plus, XS, XR

**Comment by Kmohamed** [comment]
Are you sure that you are using the correct token?

**Comment by mgogor** [comment]
> Are you sure that you are using the correct token?

Yes, the Bug Report form submitted is correctly shown in the web console. The "gallery button" in the form is however not visible, making attaching images impossible.

**Comment by Kmohamed** [comment]
Could enable verbose logging and send me the logs but make sure that you remove the token.

**Comment by mgogor** [comment]
> Could you enable verbose logging and send me the logs but make sure that you remove the token.

I have added the line `Instabug.sdkDebugLogsLevel = .verbose`
in AppDelegate before `Instabug.start(withToken: APPID, invocationEvents: [.none])
`
Below is the printed log :
```
[Instabug] Starting version 8.3.1 (4) of the Instabug SDK
[Instabug] App token: APP_ID
[Instabug] Setting invocation event to IBGInvocationEventNone
[Instabug] Setting invocation event to IBGInvocationEventNone
[Instabug] Called public method: intializeInstabugWithToken:invocationEvents:
[Instabug] Called public method: setWelcomeMessageMode:
...
[Instabug] *** video cache unpresist done (
) (
)
[Instabug] Instabug crash reporting is disabled because debugger is attached to this session. Crashes and NSErrors will not be reported to Instabug. To detach debugger, click the Stop button in Xcode, then run the app manually from the simulator.
[Instabug] Instabug crash reporting is disabled because debugger is attached to this session. Crashes and NSErrors will not be reported to Instabug. To detach debugger, click the Stop button in Xcode, then run the app manually from the simulator.
[Instabug] Current conditions for survey {
    "app_version" = "2.0.11";
    country = HK;
    date = "2019-05-24 09:55:11 +0000";
    "ios_version" = "12.2";
    "last_seen" = 0;
    "sessions_count" = 1;
    "user_events" =     (
    );
}
[Instabug] No survey is ready to be shown now.
[Instabug] Called public method: setEnabledAttachmentTypes:
[Instabug] Called public method: setBugReportingOptions:
[Instabug] Called public method: showWithReportType:options:
[Instabug] Hierarchy for window 1: 
<UIWindow: 0x7fcfb890a340; frame = (0 0; 414 896); autoresize = W+H; gestureRecognizers = <NSArray: 0x6000037912f0>; layer = <UIWindowLayer: 0x6000039e16a0>>
   | <UIView: 0x7fcfb5c0c810; frame = (0 0; 414 896); autoresize = W+H; layer = <CALayer: 0x600003990da0>>
   |    | <UIButton: 0x7fcfb5d102a0; frame = (164.5 433; 85 30); opaque = NO; layer = <CALayer: 0x6000039ac880>>
   |    |    | <UIButtonLabel: 0x7fcfb5e03c70; frame = (0 6; 85 18); text = 'report a bug'; alpha = 0.2; opaque = NO; userInteractionEnabled = NO; layer = <_UILabelLayer: 0x600001a89950>>
[Instabug] Hierarchy for window 2: 
<IBGMainWindow: 0x7fcfb5e11170; baseClass = UIWindow; frame = (0 0; 414 896); hidden = YES; gestureRecognizers = <NSArray: 0x600003779bc0>; layer = <UIWindowLayer: 0x60000394b1c0>>
```

**Comment by Kmohamed** [comment]
Could you contact the customer happiness on instabug.com and I will follow up with you

**Comment by Kmohamed** [comment]
@mgogor it seems that you are on a free plan and the trial version is over.

**Comment by nezhyborets** [comment]
So I can only attach photos from gallery on plans above Free? Don't see a doc pinpoint that

**Comment by yousefhamza** [comment]
@nezhyborets 
During trial you can attach photos from gallery but after the trial starts, the whole SDK will be SDK disabled
