### ISSUE TITLE
"ipatool failed with an exception" when packaging up ipa file

### ISSUE THREAD

**Issue by curtismartintransloc** [Instabug/Instabug-iOS#322]
### Steps to Reproduce the Problem
1. Run xcodebuild to produce an archive of your app with Instabug as a dependency. Example: `xcodebuild "-workspace" "YourApp.xcworkspace" "-scheme" "Your Scheme" "COMPILER_INDEX_STORE_ENABLE=NO" "archive" "-archivePath" "/Users/someperson/YourApp.xcarchive"`
2. Generate a plist file to specify the provisioning profile to use when exporting your archive. In this example, I named it `export_options.plist`.
3. Run xcodebuild with the `-exportArchive` argument. Example: `xcodebuild "-exportArchive" "-archivePath" "/Users/someperson/YourApp.xcarchive" "-exportPath" "/Users/someperson/exported" "-exportOptionsPlist" "/Users/someperson/export_options.plist"`

### Expected Behavior
Your app is able to be packaged up successfully.

### Actual Behavior
Archiving fails with the following errors in the terminal:
```
Error Domain=IDEFoundationErrorDomain Code=1 "ipatool failed with an exception: #<CmdSpec::NonZeroExcitException: Command exited with pid 18230 exit 1:
/Applications/Xcode.app/Contents/Developer/usr/bin/bitcode-build-tool -v -t /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin --sdk /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk -o /var/folders/2q/hcp0pvm53476bjw33yf1xr7c0000gq/T/ipatool20190528-15703-9bprxu/thinned-out/armv7/Payload/YourApp.app/Frameworks/Instabug.framework/Instabug --generate-dsym /var/folders/2q/hcp0pvm53476bjw33yf1xr7c0000gq/T/ipatool20190528-15703-9bprxu/thinned-out/armv7/Payload/YourApp.app/Frameworks/Instabug.framework/Instabug.dSYM --strip-swift-symbols /var/folders/2q/hcp0pvm53476bjw33yf1xr7c0000gq/T/ipatool20190528-15703-9bprxu/thinned-in/armv7/Payload/YourApp.app/Frameworks/Instabug.framework/Instabug
```

```
"/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang" "-cc1" "-triple" "thumbv7-apple-ios9.0.0" "-emit-obj" "-disable-llvm-passes" "-target-abi" "apcs-gnu" "-mfloat-abi" "soft" "-Os" "-mllvm" "-arm-bitcode-compatibility" "-mllvm" "-fast-isel=0" "-x" "ir" "201" "-o" "201.o"
    -= Output =-
    error: error reading '201'
    1 error generated.
    Exited with 1
    
    
    error: Failed to compile bundle: /var/folders/2q/hcp0pvm53476bjw33yf1xr7c0000gq/T/InstabugCb5601/Instabug.armv7.xar
```

```
"/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang" "-cc1" "-triple" "thumbv7-apple-ios9.0.0" "-emit-obj" "-disable-llvm-passes" "-target-abi" "apcs-gnu" "-mfloat-abi" "soft" "-Os" "-mllvm" "-arm-bitcode-compatibility" "-mllvm" "-fast-isel=0" "-x" "ir" "005" "-o" "005.o"
    -= Output =-
    Intrinsic has incorrect argument type!
    void (i8*, i8*, i32, i1)* @llvm.memcpy.p0i8.p0i8.i32
    Intrinsic has incorrect argument type!
    void (i8*, i8*, i32, i1)* @llvm.memcpy.p0i8.p0i8.i32
    Intrinsic has incorrect argument type!
    void (i8*, i8*, i32, i1)* @llvm.memcpy.p0i8.p0i8.i32
    Intrinsic has incorrect argument type!
    void (i8*, i8*, i32, i1)* @llvm.memcpy.p0i8.p0i8.i32
    fatal error: error in backend: Broken module found, compilation aborted!
    Exited with 70
    
    
    error: Failed to compile bundle: /var/folders/2q/hcp0pvm53476bjw33yf1xr7c0000gq/T/InstabugCb5601/Instabug.armv7.xar
```

### SDK Version
8.3.1, 8.4

### Other Notes
We're still using Xcode 10.1 here, and we have bitcode enabled in our project. Version 8.1.0 of the Instabug SDK does not have this problem. We originally updated to 8.3.1 and saw this happen, and 8.4.0 still has the same issue. Not sure about any releases between 8.1.0 and 8.3.1.

**Comment by yousefhamza** [comment]
Hi @curtismartintransloc 

I will investigate this issue and get back to you.

**Comment by yousefhamza** [comment]
Meanwhile, Can you try with Xcode 10.2?

**Comment by yousefhamza** [comment]
Can you try this custom build?

`pod 'Instabug', :git => 'https://github.com/Instabug/Instabug-iOS.git', :branch => 'fix/bitcode_build'`

**Comment by curtismartintransloc** [comment]
@yousefhamza I didn't get a chance to try Xcode 10.2, but I did try that custom build and it worked.

**Comment by yousefhamza** [comment]
Great 🎉

We will include that fix in our next release.

**Comment by tarunj370** [comment]
Hi @yousefhamza, could you please explain what did you do to fix this issue as i am also facing this issue for my framework. Thanks in advance.

**Comment by yousefhamza** [comment]
The fix was changing the Xcode version we were using to build the SDK from 10.0.2 to 9.3.1, we are using version 12.3 now because 12.5 used to cause other issues with the debugger e.g. https://github.com/Instabug/Instabug-iOS/issues/422

**Comment by tarunj370** [comment]
Thanks @yousefhamza, I'll also try downgrading xcode version.
