### ISSUE TITLE
No Attachment sent

### ISSUE THREAD

**Issue by timhilgenstoehler** [Instabug/Instabug-iOS#323]
Hey Guys,

I have updated to 8.4.0 and everything is working expect the bugs are not sending the attachments (video and images). 

Any Ideas why?

Kind Regards,
Tim

**Comment by yousefhamza** [comment]
Hi @timhilgenstoehler, this is Yousef from iOS team.

We are receiving similar reports related to reporting from iOS 12.3.1 and are investigating them.

Will keep you posted with any updates 👍

**Comment by timhilgenstoehler** [comment]
I upgraded my RN to Version 0.57.7 (from 0.57.5) and now its working on iOS 12.3.1 again. Maybe It helps you.

**Comment by yousefhamza** [comment]
This issue should be solved please re-open If you encountered it again.
