### ISSUE TITLE
Support AFHTTPSessionManager

### ISSUE THREAD

**Issue by manezgz** [Instabug/Instabug-iOS#324]
It's possible to support logging for AFHTTPSessionManager?

Regards.

**Comment by yousefhamza** [comment]
Hi @manezgz 

Have you tried this https://docs.instabug.com/docs/ios-logging#section-afnetworking?

**Comment by manezgz** [comment]
Yes I've tried. But my problem is that I'm using AFHTTPSessionManager instead AFURLSessionManager.
Do u have any idea about how to deal with this class?

Regards.

**Comment by yousefhamza** [comment]
`AFHTTPSessionManager` is a subclass from `AFURLSessionManager`

http://cocoadocs.org/docsets/AFNetworking/2.0.0/Classes/AFHTTPSessionManager.html
> Inherits from | AFURLSessionManager : NSObject
