### ISSUE TITLE
XCode warning for integrating in app extensions

### ISSUE THREAD

**Issue by kacper1703** [Instabug/Instabug-iOS#325]
### Steps to Reproduce the Problem
- In Xcode project add a Siri Extension or any other app extension target
- Add Instabug to Cocoapods' `podfile` and run `pod install`

### Expected Behavior
No warnings.

### Actual Behavior
Xcode produces a warning:
```
ld: warning: linking against a dylib which is not safe for use in application extensions: /Users/.../Pods/Instabug//Instabug.framework/Instabug
````

### Instabug integration code
```
target 'App' do
 pod 'Instabug', '8.4'
end

target 'AppExtension' do
 pod 'Instabug', '8.4'
end
```

### SDK Version
8.4

**Comment by Kmohamed** [comment]
Hello @kacper1703,
Actually, we do not support any app extension or Apple watch. I am sorry for that but could you give me more details about your use case.

**Comment by kacper1703** [comment]
I have an embedded framework which I created for networking purposes. Inside, I use the Instabug-provided Alamofire SessionManager to be able to see network activity. 

I would like to use the same framework inside the Siri Intents extension since I'll be communicating with same servers. 

I just thought, maybe I could just add a pre-processor flag to use Alamofire's or Instabug's session manager depending on whether it's run from an extension or not... And somehow silence the warning.

**Comment by Kmohamed** [comment]
I think this will not be allowed since we are using APIs should not be used inside extension target

**Comment by Kmohamed** [comment]
@kacper1703 Our Product team thought that this might be a valid use-case. We will add it to our backlog and tell you once we started working on this feature to get more details from you.

Thanks

**Comment by IsaiahJTurner** [comment]
2021 any updates?

**Comment by hassaanelgarem** [comment]
@IsaiahJTurner Sadly this got deprioritized and we currently have no plans of supporting this in the near future. We will update this thread if this ever changes 👍
