### ISSUE TITLE
macCatalyst support 

### ISSUE THREAD

**Issue by marcosgriselli** [Instabug/Instabug-iOS#327]
Adding this for reference. Are there any plans to add `macCatalyst` support?

**Comment by Kmohamed** [comment]
Yes, we are currently working on it and will update you very soon.

**Comment by Kmohamed** [comment]
@marcosgriselli  I would like to inform you that we will delay the support of macCatalyst for a while after the official release. 
Thanks.

**Comment by ghubaddole** [comment]
Any ETA on when this will be? I'm severely blocked due to this, but would like to have instabug as part of the app.

**Comment by Kmohamed** [comment]
Sorry for being late. it’s in our backlog and will share ETA once we have once.

**Comment by quantamrhino** [comment]
+1.
It's been an year since it was announced. I'd really like to take my app to mac but this one library is blocking my ability.

**Comment by onelogapp** [comment]
Any news on this? Our app is not released yet, we're looking to get the Premium + Surveys pack but if Instabug doesn't have Mac support then we will 100% release without Instabug on both platforms and implement our own custom surveys solution as we don't want the experience on Mac and iOS to be different

**Comment by parachutemind** [comment]
Ditto. Any news? Either for catalyst or multiplatform app. Basically, support for macOS.

**Comment by esstheevau** [comment]
+1 for this. Would be great if you could share some update on that topic. Thank you!

**Comment by yousefhamza** [comment]
As of 2021, we don't have plans to support to MacCatalyst in the near future.

**Comment by yousefhamza** [comment]
@rehatkathuria 
We don't have plans to support MacCatalyst
