### ISSUE TITLE
Instabug causes crashes 

### ISSUE THREAD

**Issue by Vadimkomis** [Instabug/Instabug-iOS#329]
### Steps to Reproduce the Problem
I just launch the app and try to access the surveys with this code:
```
                let availableSurveys = Surveys.availableSurveys
                if let surveys = availableSurveys {
                    if surveys.count > 0 {
                        if let firstSurvey = surveys.first {
                            firstSurvey.show()
                        }
                    }
                }
```
### Expected Behavior
The app is working and not crashing
### Actual Behavior
There is a crash in the app. This is a copy of the stack trace 
for key IBGFeaturesLatestFeaturesResponse'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000107df6b0b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x000000010f98f141 objc_exception_throw + 48
	2   CoreFoundation                      0x0000000107e5f625 +[NSException raise:format:] + 197
	3   CoreFoundation                      0x0000000107d49729 _CFPrefsValidateValueForKey + 249
	4   CoreFoundation                      0x0000000107db6afc -[CFPrefsPlistSource sendMessageSettingValue:forKey:] + 572
	5   CoreFoundation                      0x0000000107e60daa -[CFPrefsPlistSource alreadylocked_setValues:forKeys:count:] + 794
	6   CoreFoundation                      0x0000000107e1dc58 -[CFPrefsSource setValues:forKeys:count:removeValuesForKeys:count:] + 264
	7   CoreFoundation                      0x0000000107d49620 -[CFPrefsSource setValues:forKeys:count:] + 32
	8   CoreFoundation                      0x0000000107e57af6 -[CFPrefsSearchListSource alreadylocked_setValues:forKeys:count:] + 454
	9   CoreFoundation                      0x0000000107e1dc58 -[CFPrefsSource setValues:forKeys:count:removeValuesForKeys:count:] + 264
	10  CoreFoundation                      0x0000000107d49620 -[CFPrefsSource setValues:forKeys:count:] + 32
	11  CoreFoundation                      0x0000000107d8cfe9 -[CFPrefsSource setValue:forKey:] + 57
	12  CoreFoundation                      0x0000000107e59a4f __108-[_CFXPreferences(SearchListAdditions) withSearchListForIdentifier:container:cloudConfigurationURL:perform:]_block_invoke + 319
	13  CoreFoundation                      0x0000000107e5924d normalizeQuintuplet + 317
	14  CoreFoundation                      0x0000000107e59909 -[_CFXPreferences(SearchListAdditions) withSearchListForIdentifier:container:cloudConfigurationURL:perform:] + 105
	15  CoreFoundation                      0x0000000107e43c15 -[_CFXPreferences setValue:forKey:appIdentifier:container:configurationURL:] + 261
	16  CoreFoundation                      0x0000000107d8cf34 _CFPreferencesSetAppValueWithContainer + 68
	17  Foundation                          0x0000000109072790 -[NSUserDefaults(NSUserDefaults) setObject:forKey:] + 55
	18  Instabug                            0x000000010979f283 -[IBGFeatures setRecentFeatureResponse:] + 105
	19  Instabug                            0x000000010979e2e2 -[IBGFeatures featuresRequestDone:isSuccess:response:shouldUpdateFeatures:] + 124
	20  Instabug                            0x0000000109785f2b -[IBGFeaturesRequest networkDone:URLSessionDataTask:response:error:responseDictionary:] + 505
	21  Instabug                            0x0000000109750a38 __51-[IBGNetwork URLSession:task:didCompleteWithError:]_block_invoke_2 + 132
	22  libdispatch.dylib                   0x0000000110cbc585 _dispatch_call_block_and_release + 12
	23  libdispatch.dylib                   0x0000000110cdd792 _dispatch_client_callout + 8
	24  libdispatch.dylib                   0x0000000110cc5247 _dispatch_main_queue_callback_4CF + 1041
	25  CoreFoundation                      0x0000000107dbb909 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	26  CoreFoundation                      0x0000000107d81ae4 __CFRunLoopRun + 2164
	27  CoreFoundation                      0x0000000107d81016 CFRunLoopRunSpecific + 406
	28  GraphicsServices                    0x000000011299ca24 GSEventRunModal + 62
	29  UIKit                               0x000000010d453134 UIApplicationMain + 159
	30  Freshly Dev                         0x0000000104b9222b main + 75
	31  libdyld.dylib                       0x0000000110d2665d start + 1
	32  ???                                 0x0000000000000002 0x0 + 2
)
libc++abi.dylib: terminating with uncaught exception of type NSException

### Instabug integration code
*Make sure to remove your app token.*
```
        let env = fl_enviornment().env
        var config = fl_config(enviornment: env)
        #if DEVELOPMENT
        Instabug.start(withToken: config.instabug_DEMO, invocationEvents: .shake)
        #else
        Instabug.start(withToken: config.instabug_PRODUCTION, invocationEvent: .none)
        #endif
        Surveys.shouldShowWelcomeScreen = true
        Surveys.autoShowingEnabled = false
```
### SDK Version
8.6
### iOS Version
10.3.1
### Device Model
iPhone 7
### [Optional] Project That Reproduces the Issue

**Comment by Kmohamed** [comment]
Let me check it and get back to you very soon.

**Comment by Kmohamed** [comment]
@Vadimkomis could you add the exception name?

**Comment by Vadimkomis** [comment]
@Kmohamed it's in the stack trace above

**Comment by Kmohamed** [comment]
I mean the sentence before this
for key IBGFeaturesLatestFeaturesResponse'

**Comment by Kmohamed** [comment]
@Vadimkomis It will give me more visibility about the exception name.

**Comment by Vadimkomis** [comment]
@Kmohamed this is the exception:
```
Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Attempt to insert non-property list object {
```

**Comment by Kmohamed** [comment]
are you able to reproduce it?

**Comment by Vadimkomis** [comment]
@Kmohamed I'm able to reproduce it every time.

**Comment by Kmohamed** [comment]
Can you contact the happiness team and give them your token please

**Comment by Kmohamed** [comment]
@Vadimkomis I got your token thanks a lot but I can reproduce the issue could you please share with me the full stack trace with exception name.
Exception name should be like this

```
Attempt to set a non-property-list object (
   **"<Object: 0x8f3c140>"**
) as an NSUserDefaults value for key MyKey
```

I need to know what object.

**Comment by Kmohamed** [comment]
@Vadimkomis did you manage to catch my previous message?

**Comment by Vadimkomis** [comment]
@Kmohamed I just saw this. Will look today

**Comment by Kmohamed** [comment]
@Vadimkomis Thanks 🙏

**Comment by Kmohamed** [comment]
@Vadimkomis any updates regarding the crash?

**Comment by Vadimkomis** [comment]
@Kmohamed just got back from vacation yesterday. Will look at this tomorrow.
