### ISSUE TITLE
SPM Support

### ISSUE THREAD

**Issue by fabstu** [Instabug/Instabug-iOS#330]
Adding this for reference. Is Swift Package Manager support planned already?

**Comment by Kmohamed** [comment]
Yes, will update you very soon.

**Comment by Kmohamed** [comment]
@fabstu I would like to inform you that we will delay the support of SPM for a while after the official release. 
Thanks.

**Comment by abeazam** [comment]
now that it is officially in Xcode 11 any word on when we will get this?

thanks

**Comment by hassaanelgarem** [comment]
@abeazam Sadly it looks like Binary dependancies are not yet supported by SPM. SPM currently supports source-only packages. We'll keep an eye out and once binary dependancies support is added we'll release this feature.

**Comment by jdtzmn** [comment]
@hassaanelgarem I think Sentry was having similar issues with their Binary dependencies. They have since fixed the issue [here](https://github.com/getsentry/sentry-cocoa/pull/352/files). I have not looked through their PR thoroughly, but I thought I would share it since it might help.

**Comment by Kmohamed** [comment]
@jdtzmn Thanks a lot for your help. But I think it works with Sentry because it's open-source. am I right?

**Comment by jdtzmn** [comment]
@Kmohamed I honestly don't know — I'm no expert. I just saw that they were having similar issues so I thought you might be able to get some ideas.

**Comment by Kmohamed** [comment]
@jdtzmn could you check this [thread](https://forums.swift.org/t/pitch-support-for-binary-dependencies/27620/64)?

**Comment by jdtzmn** [comment]
@Kmohamed Ahh. Thank you for sharing the link. I now understand what you mean when you said Sentry only worked because it's open-source.

Oh well. I hope this issue is fixed soon.

**Comment by andrew-muzmatch** [comment]
@Kmohamed Looks like they're good to go on the SPM side: https://github.com/apple/swift-package-manager/pull/2514

**Comment by Kmohamed** [comment]
@andrew-muzmatch Thanks a lot for your collaborations. I will check it and get back to you.

**Comment by kcam** [comment]
@Kmohamed any update on this, just about to bring instabug into our project and we have some enterprise level security issues around cocoapods.  Thanks

**Comment by Kmohamed** [comment]
Hi @kcam We are still working on it but supporting SPM should include Catalyst also so it may be delayed. But I interested to know about `security issues around cocoapods.`

**Comment by RamblinWreck77** [comment]
FYI, Swift 5.3 has 4 upgrades to SPM marked as "Implemented", so they'll definitely be releasing with 5.3:

https://github.com/apple/swift-evolution/blob/master/proposals/0278-package-manager-localized-resources.md

https://github.com/apple/swift-evolution/blob/master/proposals/0273-swiftpm-conditional-target-dependencies.md

https://github.com/apple/swift-evolution/blob/master/proposals/0272-swiftpm-binary-dependencies.md

https://github.com/apple/swift-evolution/blob/master/proposals/0271-package-manager-resources.md

**Comment by Kmohamed** [comment]
Than you @RamblinWreck77 🙏

**Comment by dannyhertz** [comment]
Any update on this? We only use SPM and would love to start using Instabug once support is added!

**Comment by Kmohamed** [comment]
We are very sorry for being late 🙏. We will release it shortly.

**Comment by ismyhc** [comment]
Hi @Kmohamed just checking on the status of SPM support? :)

**Comment by AhmedOS** [comment]
Hi @ismyhc ,
Unfortunately there are [issues](https://forums.swift.org/t/swiftpm-binarytarget-dependency-and-code-signing/38953) with SPM and binary dependencies which delaying us from supporting it, but we are still working on it. We just want to make sure that the package is stable without issues before releasing it.
Thanks for understanding.

**Comment by RamblinWreck77** [comment]
@AhmedOS were these issues resolved with this workaround?

https://pspdfkit.com/guides/ios/current/knowledge-base/library-not-found-swiftpm/

**Comment by mjohnson12** [comment]
Binary SPM package signing is working now with Xcode 12.2.

**Comment by Kmohamed** [comment]
Thanks, @mjohnson12  for the heads-up. SPM will be released next week 🎉.

**Comment by ismyhc** [comment]
Eagerly waiting for this.... :) @Kmohamed is the support for SPM still happening this week?

**Comment by RamblinWreck77** [comment]
@ismyhc Given that they just did a release that appears to not have SPM support (unless I missed something) it looks like it is not. Oh well :/

**Comment by Kmohamed** [comment]
@RamblinWreck77 Unfortunately, we did not. We faced some issues and working on them. But the good news that we will do an exceptional release only for SPM Next week.

**Comment by RamblinWreck77** [comment]
@Kmohamed Any chance this is coming today? We're going to be cutting a release and would love to get this included :)

**Comment by yousefhamza** [comment]
@RamblinWreck77
Good news! Instabug SPM is out with simulator arm64 arch too 🎉. You can get it at `https://github.com/Instabug/Instabug-SP.git`

Hope we caught your release 😄

**Comment by RamblinWreck77** [comment]
@YoumnaElhassany Just missed it, but I will try this out ASAP and let you know if I find anything weird! 

I'm curious, what was the motivation for an entirely separate repo?

**Comment by yousefhamza** [comment]
@RamblinWreck77 SPM deep clones the repo to work, but our original repo has gotten too big that cloning will take a long time now.

**Comment by RamblinWreck77** [comment]
@yousefhamza Hmmm, so the app builds and runs fine but when I try to export/archive the app store kicks back saying instabug is in the wrong place and that there are two of them. Screen shots:
<img width="627" alt="Screen Shot 2020-12-05 at 11 49 54 AM" src="https://user-images.githubusercontent.com/22692130/101258545-23c40800-36f1-11eb-82fe-f99eb9cc2db6.png">

**Comment by RamblinWreck77** [comment]
@yousefhamza 

As you can see above, there are somehow two instabug frameworks in my project. I removed instabug from my podfile, ran pod install, cocoapods said it removed the dependency. Then I added the new git repo to SPM and it appeared to integrate properly like everything else. The only indication of any failure was at upload time

**Comment by RamblinWreck77** [comment]
Odd... so I removed the instabug SPM package and attempted to re-add it and got the following:

<img width="728" alt="Screen Shot 2020-12-05 at 12 05 22 PM" src="https://user-images.githubusercontent.com/22692130/101258688-4276ce80-36f2-11eb-94cf-55f8aab16978.png">

**Comment by RamblinWreck77** [comment]
Hmmm... nuking derived data and the module cache has let me re-add it. Probably just an Xcode bug.

**Comment by RamblinWreck77** [comment]
Digging into the exported app it appears that Instabug.framework shows up in _both_ /Frameworks and /PlugIns. I suspect this is the root issue. 

Expanding the Instabug package in the Swift Package Dependencies browser in Xcode shows a folder "Referenced Binaries" that is not present in any other SPM package I have.

**Comment by yousefhamza** [comment]
Hi @RamblinWreck77 

> Expanding the Instabug package in the Swift Package Dependencies browser in Xcode shows a folder "Referenced Binaries" that is not present in any other SPM package I have.

This is because we are shipping Instabug as a binary, and that's why we were only able to do it in 2020.

> Digging into the exported app it appears that Instabug.framework shows up in both /Frameworks and /PlugIns. I suspect this is the root issue.

I think this can be the root cause as well, and I was able to create the same setup, will investigate this and get back to you 🙏

**Comment by yousefhamza** [comment]
@RamblinWreck77 

I found out that `Instabug.framework` as SPM package will be copied to _all_ "Copy Files" build phases in your app target, this is maybe a bug in SPM so I will be open an issue there to discuss this issue further with them.

Meanwhile, your best option is to delete that extra copy with a "Run Script" build phase and add the following snippet as shown in the attached photos:
```
rm -rf "${TARGET_BUILD_DIR}/${PLUGINS_FOLDER_PATH}/Instabug.framework"
PLUSGIN_INSTABUG="${TARGET_BUILD_DIR}/${PLUGINS_FOLDER_PATH}/Instabug.framework"
if [ -f $PLUSGIN_INSTABUG ]; then
   echo "Removing Instabug from plugins at $PLUSGIN_INSTABUG."
   rm -rf $PLUSGIN_INSTABUG
else
   echo "Instabug does not exist at $PLUSGIN_INSTABUG."
fi
```

![Screen Shot 2020-12-06 at 11 01 39 AM](https://user-images.githubusercontent.com/3893067/101275946-75809700-37b2-11eb-9e66-ad3be92b71c0.png)

**Comment by RamblinWreck77** [comment]
Thanks! I actually manually edited the archive output then signed/delivered it without the PlugIns folder. This script definitely makes it quicker though!

Any timeline on an update to resolve the root issue?

**Comment by yousefhamza** [comment]
There's no timeline at the moment, make sure to follow the thread on Swift forums for updates 🙏

**Comment by Kmohamed** [comment]
Since we supported SPM, I will close this issue and please feel free to reach out to us if you need any help.

**Comment by arturgrigor** [comment]
Is it really supported, because I'm getting the following error for the last 2 Instabug releases?

>https://github.com/Instabug/Instabug-iOS has no Package.swift manifest for version 10.4.0

**Comment by arturgrigor** [comment]
My bad, I was using https://github.com/Instabug/Instabug-iOS instead of https://github.com/Instabug/Instabug-SP.
