### ISSUE TITLE
Dependency "Instabug-iOS" has no shared framework schemes for any of the platforms: iOS

### ISSUE THREAD

**Issue by Bhanualopa** [Instabug/Instabug-iOS#333]
Am getting following error while updating through Carthage

**Dependency "Instabug-iOS" has no shared framework schemes for any of the platforms: iOS**

Please find the following image for the reference

<img width="591" alt="Screenshot 2019-08-23 at 12 45 18 PM" src="https://user-images.githubusercontent.com/54078824/63574526-94e7b680-c5a5-11e9-9016-69b065bff46b.png">

**Comment by Kmohamed** [comment]
Hi @Bhanualopa,
I will investigate in this error but could you tell me how do you integrate Instabug. are you following these [integration](https://docs.instabug.com/docs/ios-integration#section-carthage) steps?

**Comment by Kmohamed** [comment]
Could you share with me how do you integrate Instabug inside your `cartfile`?
make sure to add binary keyword before the path like this:
`binary "https://raw.githubusercontent.com/Instabug/Instabug-iOS/master/Instabug.json"`

**Comment by Bhanualopa** [comment]
@Kmohamed 
this is how I integrated 
github "Instabug/Instabug-iOS" "dynamic_framework"

**Comment by Kmohamed** [comment]
@Bhanualopa could you change it to
`binary "https://raw.githubusercontent.com/Instabug/Instabug-iOS/master/Instabug.json"` because we are a compiled framework

**Comment by Bhanualopa** [comment]
Okay. Will try it out @Kmohamed
