### ISSUE TITLE
Is Instabug disabled when hooked into the xcode debugger?

### ISSUE THREAD

**Issue by nickthedude** [Instabug/Instabug-iOS#334]
I can't seem to invoke it at all.

**Comment by nickthedude** [comment]
I'm on iPad 3rd gen 12.9" and iPhone X

**Comment by yousefhamza** [comment]
Hi @nickthedude,

Can you share with us: 
* Your Instabug invocation code
* iOS Version
* SDK Version

**Comment by yousefhamza** [comment]
Please feel free to open it If you still have this problem.
