### ISSUE TITLE
Running Live / Beta not working on iOS

### ISSUE THREAD

**Issue by uddinr** [Instabug/Instabug-iOS#341]
### Steps to Reproduce the Problem

we have implemented the suggested code to switch between live and beta for the app store version and our dev and testflight versions:

```
func isRunningLive() -> Bool {
     #if targetEnvironment(simulator)
    return false
    #else
    let isRunningTestFlightBeta  = (Bundle.main.appStoreReceiptURL?.lastPathComponent == "sandboxReceipt")
    let hasEmbeddedMobileProvision = Bundle.main.path(forResource: "embedded", ofType: "mobileprovision") != nil
    if (isRunningTestFlightBeta || hasEmbeddedMobileProvision) {
        return false
    } else {
        return true
    }
    #endif
}

if (self.isRunningLive()) {
Instabug.start(withToken: "YOUR-LIVE-TOKEN-HERE", invocationEvents: [.shake, .screenshot])
} else {
Instabug.start(withToken: "YOUR-BETA-TOKEN-HERE", invocationEvents: [.shake, .screenshot])

}
```

taken from your documentation here:

https://docs.instabug.com/docs/ios-integration

however it is just not working for us, all issues are always reported against the beta environment, it doesn't seem to have worked for us at all since we implemented it around a year ago.

**Comment by Kmohamed** [comment]
Let me check and get back to you

**Comment by Kmohamed** [comment]
are you face this issue on iOS 13 only or all iOS versions?

**Comment by uddinr** [comment]
Issue occurs on all ios versions our minimum deployment is ios 12

**Comment by Kmohamed** [comment]
@uddinr Thanks a lot for your collaboration I currently trying to test it within our App and will get back to you once Appstore publishes it.

**Comment by Kmohamed** [comment]
@uddinr I tried it on our App and works fine

```
func isRunningLive() -> Bool {
         #if targetEnvironment(simulator)
        return false
        #else
        let isRunningTestFlightBeta  = (Bundle.main.appStoreReceiptURL?.lastPathComponent == "sandboxReceipt")
        let hasEmbeddedMobileProvision = Bundle.main.path(forResource: "embedded", ofType: "mobileprovision") != nil
        if (isRunningTestFlightBeta || hasEmbeddedMobileProvision) {
            return false
        } else {
            return true
        }
        #endif
    }
```

```
if (self.isRunningLive()) {
            Instabug.showWelcomeMessage(with: .live)
        } else {
            Instabug.showWelcomeMessage(with: .beta)
        }
```

**Comment by Kmohamed** [comment]
I can invite you to our Testflight to try it.

**Comment by uddinr** [comment]
hmm may be its something we are doing wrong, we have isRunningLive as a static method in a util class as follows:

```
    static func isRunningLive() -> Bool {
        #if targetEnvironment(simulator)
        return false
        #else
        let isRunningTestFlightBeta  = (UIKit.Bundle.main.appStoreReceiptURL?.lastPathComponent == "sandboxReceipt")
        let hasEmbeddedMobileProvision = !(UIKit.Bundle.main.path(forResource: "embedded", ofType: "mobileprovision") != nil);
        if (isRunningTestFlightBeta || hasEmbeddedMobileProvision) {
            return false
        } else {
            return true
        }
        #endif
    }
```

and in our AppDelegate we call the following:

`Instabug.start(withToken: Util.isRunningLive() ? AppConstants.ServiceConstants.INSTABUG_LIVE_KEY : AppConstants.ServiceConstants.INSTABUG_BETA_KEY, invocationEvents: [.screenshot])`

is there something obvious we are doing incorrectly?

**Comment by Kmohamed** [comment]
Don't know if `UIKit.Bundle` is correct or not. Also, you add `!` before the bracket could you remove it.

**Wrong one:**
  `let hasEmbeddedMobileProvision = !(UIKit.Bundle.main.path(forResource: "embedded", ofType: "mobileprovision") != nil);`

**Correct one:**
  `let hasEmbeddedMobileProvision = (UIKit.Bundle.main.path(forResource: "embedded", ofType: "mobileprovision") != nil);`

**Comment by uddinr** [comment]
we had to use the fully qualifying name as we have an object called Bundle in our project, which i have now changed.

the ! is odd not sure where it came from but changed it now, we'll see how that goes.

thanks for the response

**Comment by Kmohamed** [comment]
Happy to help 😊

**Comment by Kmohamed** [comment]
@uddinr I will close it for now and feel free to open it if you face any issues
