### ISSUE TITLE
Informative changelogs

### ISSUE THREAD

**Issue by krin-san** [Instabug/Instabug-iOS#344]
Starting from version 8.7.3 release changelogs are not informative anymore and doesn't explain what exactly this release contains, which bugs were fixed and contains no links to (possibly) related issues opened on GitHub. And there are no changelogs available on official website.

That is not a good practice for the private/binary framework. Software company paying for your service should know how important framework bufix releases are in order to distribute resources (development time) accordingly.

Please, rewrite changelogs for the releases from 8.7.3 and briefly describe what was fixed there.

**Comment by Kmohamed** [comment]
Totally agree with you. I will make sure to fix this in the next releases.
Thanks a lot 🙏.
