### ISSUE TITLE
Instabug is not work (IOS 13.2.2) 

### ISSUE THREAD

**Issue by macchamps** [Instabug/Instabug-iOS#345]
### Actual Behavior
IBGCrashReporting - Instabug crash reporting is disabled because debugger is attached to this session. Crashes and NSErrors will not be reported to Instabug. To detach debugger, click the Stop button in Xcode, then run the app manually from the simulator.
### Instabug integration code
*Make sure to remove your app token.*

### SDK Version
9.0.1
### iOS Version
13.2.2
### XCODE Version
11.2.1
### Device Model
iPhone 8

**Comment by Kmohamed** [comment]
Not sure what’s the issue here. Could you provide me with more details about the issue?

**Comment by Kmohamed** [comment]
Related to crash reporting this is the actual behavior: We can not make our crash reporting works with Xcode because Xcode is the one who catches crash in the development time.

**Comment by macchamps** [comment]
can i provide send Demo App?

**Comment by Kmohamed** [comment]
@macchamps I need to know the issue first 😅

**Comment by macchamps** [comment]
[Instabug] - IBGUser Steps - Couldn't save userstep to CoreData in addStep. Error: Error Domain=PersistentStore not intialized Code=500 "(null)"
[Instabug] - IBGCrashReporting - Instabug crash reporting is disabled because debugger is attached to this session. Crashes and NSErrors will not be reported to Instabug. To detach debugger, click the Stop button in Xcode, then run the app manually from the simulator.
[Instabug] - IBGUser Steps - Couldn't save userstep to CoreData in addStep. Error: Error Domain=PersistentStore not intialized Code=500 "(null)"
[Instabug] - IBGUser Steps - Captured screenshot using currentImageContext = <UIImage:0x600000ce9ef0 anonymous {375, 667}>
[Instabug] - IBGUser Steps - Couldn't save userstep to CoreData in addStep. Error: Error Domain=PersistentStore not intialized Code=500 "(null)"
[Instabug] - IBGCrashReporting - Instabug crash reporting is disabled because debugger is attached to this session. Crashes and NSErrors will not be reported to Instabug. To detach debugger, click the Stop button in Xcode, then run the app manually from the simulator.



That is log.

**Comment by Kmohamed** [comment]
Yes that’s normal at start but after initializing CoreData. We will saving all pending data. These logs are for debugging only. We will fix it in the next release

**Comment by Kmohamed** [comment]
Are you able to see user steps on dashboard?

**Comment by macchamps** [comment]
No,There are nothing to showing me on Dashboard.

**Comment by Kmohamed** [comment]
So, did you send a bug and you can not find any user steps inside this bug?

**Comment by macchamps** [comment]
yes! did you give me solution about it?

**Comment by Kmohamed** [comment]
@macchamps could you open a ticket on Instabug.com and send them a bug link?

**Comment by macchamps** [comment]
how can i open ticket ?

**Comment by Kmohamed** [comment]
From Intercom button. Bottom right corner
