### ISSUE TITLE
Instabug UI not displayed correctly for iOS 13

### ISSUE THREAD

**Issue by OnyekachiSamuel** [Instabug/Instabug-iOS#347]
### Steps to Reproduce the Problem
Install Instabug and invoke Instabug.show() where you want to show the UI in the latest Xcode 11 and iOS 13
### Expected Behavior
When I call Instabug.show() method, it should display the UI with the Report a Bug and Suggest an Improvement section properly displayed to view.
### Actual Behavior
When I call Instabug.show() method, the UI is not displayed properly and I am left with this error message:
**Warning once only: UITableView was told to layout its visible cells and other contents without being in the view hierarchy (the table view or one of its superviews has not been added to a window). This may cause bugs by forcing views inside the table view to load and perform layout without accurate information (e.g. table view bounds, trait collection, layout margins, safe area insets, etc), and will also cause unnecessary performance overhead due to extra layout passes. Make a symbolic breakpoint at UITableViewAlertForLayoutOutsideViewHierarchy to catch this in the debugger and see what caused this to occur, so you can avoid this action altogether if possible, or defer it until the table view has been added to a window. Table view: <IBGResizableTableView: 0x7f845f0fa600; baseClass = UITableView; frame = (0 0; 319 88); clipsToBounds = YES; gestureRecognizers = <NSArray: 0x60000033e7c0>; layer = <CALayer: 0x600000dfb700>; contentOffset: {0, 0}; contentSize: {319, 88}; adjustedContentInset: {0, 0, 0, 0}; dataSource: <IBGPromptVC: 0x7f845df58920>>**

### Instabug integration code
Instabug.start(withToken: "*******", invocationEvents: [])

### SDK Version
9.0.1
### iOS Version
iOS 13
### Device Model
iPhone 7

**Comment by Kmohamed** [comment]
Hello @OnyekachiSamuel Yes we are aware of this bug. This symbolic break point is introduced in Xcode 11. We will release the fix in the next release. But it should shown correctly. Could you provide us with a screenshot of the UI?

**Comment by OnyekachiSamuel** [comment]
Thanks, @Kmohamed  for responding back. Check out the screenshots below:

![Simulator Screen Shot - iPhone X - 2019-11-30 at 06 18 39](https://user-images.githubusercontent.com/11311182/69898953-45611580-1360-11ea-9b4b-34f96820aea9.png)
![Simulator Screen Shot - iPhone X - 2019-11-30 at 10 55 22](https://user-images.githubusercontent.com/11311182/69898957-4d20ba00-1360-11ea-9f99-1efc9e87eb2a.png)

**Comment by Kmohamed** [comment]
Related to second screenshot are you overriding NavigationBar appearance?

**Comment by OnyekachiSamuel** [comment]
I did the configuration for the UINavigationBar in the AppDelegate

**Comment by Kmohamed** [comment]
@OnyekachiSamuel If you remove it inside 
https://docs.instabug.com/docs/ios-bug-reporting-event-handlers#section-before-invoking-instabug

and add it again inside
https://docs.instabug.com/docs/ios-bug-reporting-event-handlers#section-after-dismissing-instabug
it should work fine.
Note:` UINavigationBar.appearance()` will affect native viewControllers like gallery

**Comment by Kmohamed** [comment]
Related to the first screenshot do you have any extension on `UILabel`?

**Comment by OnyekachiSamuel** [comment]
@Kmohamed Yes, I do have one, though I have removed the extension for the UILabel because I don't have a need for it again. I tried to comment out settings in the appearance proxy for UINavigationBar and the UI for Instabug was rendered correctly.

The part I don't get is adding it in 
```
        Instabug.willSendReportHandler = { report in
            
            return report
        }
```
And removing it in
```
        BugReporting.willInvokeHandler = {

        }
```

These are what I set for the appearance proxy in the AppDelegate
```
        UINavigationBar.appearance().isTranslucent = true
        UINavigationBar.appearance().barTintColor = .white
        UINavigationBar.appearance().prefersLargeTitles = true
```

Help me get this last piece, I really appreciate your support. Thanks.

**Comment by Kmohamed** [comment]
Sure, could you add this solution?

```
BugReporting.willInvokeHandler = {
      UINavigationBar.appearance().prefersLargeTitles = false
      UINavigationBar.appearance().barTintColor = .clear
 }
```
        
```
 BugReporting.didDismissHandler = { (dismissType, reportType) in
      UINavigationBar.appearance().isTranslucent = true
      UINavigationBar.appearance().barTintColor = .white
      UINavigationBar.appearance().prefersLargeTitles = true
   }
```

**Comment by OnyekachiSamuel** [comment]
Perfect, problem solved. Thanks, I really appreciate. 😀

**Comment by Kmohamed** [comment]
Perfect 👌
However I will make sure to implement these fixes inside Instabug

**Comment by OnyekachiSamuel** [comment]
Cool 👌
