### ISSUE TITLE
Requests with custom `Accept` header and responses with custom `Content-Type` header are not reported.

### ISSUE THREAD

**Issue by Skoti** [Instabug/Instabug-iOS#349]
### Steps to Reproduce the Problem
Change `Accept` header in a request and then `Content-Type` in its response to a custom value, i.e. `application/custom+json`.
Integration is correct as all other requests and responses are logged.

### Expected Behavior

as in the docs:
> Instabug automatically logs all network requests performed by your app. Requests details, along with their responses, are sent with each report.

### Actual Behavior
Requests with custom `Accept` header and responses with custom `Content-Type` header are not reported.

### Instabug integration code
```
class IBGSessionManager: Alamofire.SessionManager {
    static let logged: IBGSessionManager = {
        let configuration = URLSessionConfiguration.default
        NetworkLogger.enableLogging(for: configuration)
        configuration.httpAdditionalHeaders = Alamofire.SessionManager.defaultHTTPHeaders
        return IBGSessionManager(configuration: configuration)
    }()
}
```
### SDK Version
8.5.2

**Comment by Kmohamed** [comment]
Yes, this is expected. We support specific content type.
But I am curious to know your use cases

**Comment by Skoti** [comment]
For me it is unexpected as it is not mentioned anywhere in the docs.

The case is that I happened to use a backend with a requirement to use custom values in headers - and I do not think it can be changed.

1. Is there any particular reason Instabug requires `application/json`?
2. Is there any workaround to force Instabug to log such requests?
3. I can see `text/plain` requests/responses are logged but what about other `Content-Type`'s like: `application/x-www-form-urlencoded` or `multipart/form-data`?

**Comment by Kmohamed** [comment]
We support only
1- `application/json`
2-`application/xml`
3- `text/xml`
4- `text/html`
5- `text/plain`
The reason behind this is the size of the network log. Let me discuss this with the product team and get back to you.

**Comment by Skoti** [comment]
Any news?

**Comment by Kmohamed** [comment]
@Skoti let me check and get back to you very soon.

**Comment by Kmohamed** [comment]
@Skoti I am very sorry for being late. Finally, we implemented a solution I would like to send you a custom build to get your feedback and to make sure that there is no concern from your side.

**Comment by Skoti** [comment]
@Kmohamed great news! Will it be a part of official release if it all works?
Can I contact you via email you have listed on your GitHub profile?

**Comment by Kmohamed** [comment]
you can use this custom build.
 `pod 'Instabug', :git => 'https://github.com/Instabug/Instabug-iOS.git', :branch => 'support/all-content-types'`

**Comment by Kmohamed** [comment]
Hi @Skoti
I am interested to know your feedback about the custom build. Does it fixes your issue?

**Comment by Skoti** [comment]
@Kmohamed 
It works with this custom build :) Thanks!
Is this going to be a part of an official release?

**Comment by Kmohamed** [comment]
@Skoti Sorry for being late but it's finally released to production.
Thank you 🙏
