### ISSUE TITLE
CLANG_CXX_LANGUAGE_STANDARD merge problem with Realm

### ISSUE THREAD

**Issue by mladjan** [Instabug/Instabug-iOS#35]
When I want to install Instabug and Realm in the same project, I'm getting the warning:
[!] Can't merge user_target_xcconfig for pod targets: ["Instabug", "Realm", "Headers"]. Singular build setting CLANG_CXX_LANGUAGE_STANDARD has different values.

**Comment by msoliman** [comment]
Thanks @mladjan for reporting this. There's a conflict between both pod specs, we'll be fixing it in our next version. In the meantime, you should be able to use the SDK by manually importing it in your project.
