### ISSUE TITLE
Error: arrow "Back" does not inherit the color of the other elements

### ISSUE THREAD

**Issue by lisindima** [Instabug/Instabug-iOS#352]
### Steps to Reproduce the Problem
1. Install Instabug via Cocoapods
2. Change color through InstaBug.tintColor
### Actual Behavior
![IMG_B1F812233C17-1](https://user-images.githubusercontent.com/43087859/73823909-d2768e00-482b-11ea-8106-3353dfbb8221.jpeg)
![IMG_B1F812233C17-2](https://user-images.githubusercontent.com/43087859/73823915-d4d8e800-482b-11ea-8cad-572b0aa3aeb8.jpeg)
### SDK Version
Instabug 9.0.7
### iOS Version
iOS 13.3.1
### Device Model
iPhone 11 Pro

**Comment by Kmohamed** [comment]
We are sorry for this bug 😬. I will make sure that this bug will be fixed in the next release.

**Comment by Kmohamed** [comment]
@lisindima If you want a custom build I can provide it for you.

**Comment by lisindima** [comment]
Thanks for solving the problem with the latest update!)

**Comment by Kmohamed** [comment]
You are more than welcome 🙏
