### ISSUE TITLE
Update the manual installation guide in README.md

### ISSUE THREAD

**Issue by HassanElDesouky** [Instabug/Instabug-iOS#353]
### Steps to Reproduce the Problem
Add Instabug with a manual installation, **not through CocoaPods.**

### Expected Behavior
I expected it to work!

### Actual Behavior
The project compiles successfully, however, when running the app it crashes with the following error in the console:
```
dyld: Library not loaded: @rpath/Instabug.framework/Instabug
Reason: image not found
```
### How I solved the problem
I googled the error and found out this accepted solution on [StackOverflow](https://stackoverflow.com/a/58144452/5025731) It seemed that this is the new way to add the library in Xcode 11. Therefore, I suggest updating your README.md file with this new step.

Thanks!

### SDK Version
v9.0.10

### iOS Version
iOS 13.3, Xcode 11.3.1

**Comment by Kmohamed** [comment]
@HassanElDesouky Thanks for reporting this. could you help us with updating the readme?

**Comment by Kmohamed** [comment]
PR merged.
