### ISSUE TITLE
[Crash] After shake, it may crash due to insert nil to an array 

### ISSUE THREAD

**Issue by seanliu1** [Instabug/Instabug-iOS#357]
- Instabug (9.0.1)

Fatal Exception: NSInvalidArgumentException
*** -[__NSPlaceholderArray initWithObjects:count:]: attempt to insert nil object from objects[119]
_hidden#12731_

Fatal Exception: NSInvalidArgumentException
0  CoreFoundation                 0x18ed0aa48 __exceptionPreprocess
1  libobjc.A.dylib                0x18ea31fa4 objc_exception_throw
2  CoreFoundation                 0x18ed60360 -[__NSCFString characterAtIndex:].cold.1
3  CoreFoundation                 0x18ed63318 -[__NSPlaceholderArray initWithCapacity:].cold.1
4  CoreFoundation                 0x18ebeb2a4 -[__NSPlaceholderArray initWithObjects:count:]
5  CoreFoundation                 0x18ebe38ac -[NSArray initWithArray:range:copyItems:]
6  Instabug                       0x1038d685c _hidden#12731_ + 273 (__hidden#12802_:273)
7  libdispatch.dylib              0x18e9d7184 _dispatch_client_callout
8  libdispatch.dylib              0x18e9badc8 _dispatch_lane_barrier_sync_invoke_and_complete
9  Instabug                       0x1038d6654 _hidden#12730_ + 272 (__hidden#12802_:272)
10 Instabug                       0x1038d5be8 _hidden#12727_ + 226 (__hidden#12802_:226)
11 Instabug                       0x103810f90 _hidden#6213_ + 81 (__hidden#6226_:81)
12 Instabug                       0x103810e2c _hidden#6212_ + 71 (__hidden#6226_:71)
13 Instabug                       0x103802654 _hidden#5604_ + 80 (__hidden#5614_:80)
14 Instabug                       0x1037d2fc8 _hidden#3837_ + 164 (__hidden#3910_:164)
15 Instabug                       0x1038156e0 _hidden#6348_ + 155 (__hidden#6357_:155)
16 Instabug                       0x10389eb10 _hidden#11007_ + 83 (__hidden#11034_:83)
17 Instabug                       0x1038ed9f0 _hidden#13593_ + 224 (__hidden#13627_:224)
18 UIKitCore                      0x192f5a948 -[UITableView _selectRowAtIndexPath:animated:scrollPosition:notifyDelegate:isCellMultiSelect:]
19 UIKitCore                      0x192f5a464 -[UITableView _selectRowAtIndexPath:animated:scrollPosition:notifyDelegate:]
20 UIKitCore                      0x192f5ab64 -[UITableView _userSelectRowAtPendingSelectionIndexPath:]
21 UIKitCore                      0x192d99c84 _runAfterCACommitDeferredBlocks
22 UIKitCore                      0x192d897d4 _cleanUpAfterCAFlushAndRunDeferredBlocks
23 UIKitCore                      0x192db9744 _afterCACommitHandler
24 CoreFoundation                 0x18ec87e68 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__
25 CoreFoundation                 0x18ec82d54 __CFRunLoopDoObservers
26 CoreFoundation                 0x18ec83320 __CFRunLoopRun
27 CoreFoundation                 0x18ec82adc CFRunLoopRunSpecific
28 GraphicsServices               0x198c23328 GSEventRunModal
29 UIKitCore                      0x192d9063c UIApplicationMain
30 Quibi                          0x1021e07fc main + 15 (NetworkSession+following.swift:15)
31 libdyld.dylib                  0x18eb0c360 start

**Comment by Kmohamed** [comment]
We are very sorry for experiencing this crash. We are already aware of this one And will release it very soon. it should be next week.

**Comment by Kmohamed** [comment]
Issue fixed in SDK v[9.0.11](https://github.com/Instabug/Instabug-iOS/releases/tag/9.0.11).
If you faced this issue again please do not hesitate to open it again.
