### ISSUE TITLE
Module compiled with Swift 5.1 cannot be imported by the Swift 4.2.1 compiler

### ISSUE THREAD

**Issue by Skoti** [Instabug/Instabug-iOS#358]
### Steps to Reproduce the Problem
Try to build a project in Xcode 10.1 using Instabug SDK in version 9.0.8.

### Expected Behavior
Build succeeds

### Actual Behavior
Build fails with error:
```
Module compiled with Swift 5.1 cannot be imported by the Swift 4.2.1 compiler: /Pods/Instabug/Instabug.framework/Modules/Instabug.swiftmodule/arm64.swiftmodule
```
### SDK Version
9.0.8

It works when using Instabug SDK in version 9.0.7.
Seems like a significant change for a patch version update.

**Comment by Kmohamed** [comment]
@Skoti, Thanks for reporting it. It's already fixed on SDK [v9.0.10](https://github.com/Instabug/Instabug-iOS/releases/tag/9.0.10)

**Comment by Kmohamed** [comment]
It was not a significate change but was a miss configuration in our build settings.

**Comment by Skoti** [comment]
@Kmohamed  It seems like it is not. Same issue for all versions above 9.0.7.

**Comment by Kmohamed** [comment]
@Skoti let me give you more details. SDK version 9.0.8 contains fixes related to our crash reporting. But we started to use Swift in our binary since the module stability was released in Swift 5.1. But unfortunately, we missed this flag [Build Libraries for Distribution ](https://developer.apple.com/videos/play/wwdc2019/416/)

**Comment by Kmohamed** [comment]
please le me know if you need more details. Thanks

**Comment by Skoti** [comment]
Well if you have started to use Swift then it is a breaking (major) change as it introduces binary incompatibility.
The `Build Libraries for Distribution` flag means, among many other things, that I could use 9.0.10 Instabug SDK with my `Swift 4.2` project (even though SDK is compiled with Swift 5.1) but still it is **required to use** at least `Xcode 11` - and because of some other dependencies I cannot use it right now.

Anyway, thanks for explanations, I will keep using Instabug SDK in version 9.0.7 for now.

**Comment by Kmohamed** [comment]
@Skoti I totally agree with you. And this why we moved from SDK version 8.7.3 to [9.0](https://github.com/Instabug/Instabug-iOS/releases/tag/9.0)
`⚠️ This release drops support for Xcode 10. To use this version of the SDK, you have to use Xcode 11.⚠️`
We dropped support for Xcode 10 to support iOS 13 features like dark mode and iPadOS

**Comment by Skoti** [comment]
I've missed that. Thanks. Closing the issue.

**Comment by Kmohamed** [comment]
@Skoti Thanks for your understanding 🙏
