### ISSUE TITLE
Carthage Support

### ISSUE THREAD

**Issue by ollieatkinson** [Instabug/Instabug-iOS#36]
To support Carthage you can provide a pre built framework

https://github.com/Carthage/Carthage

**Comment by msoliman** [comment]
@ollieatkinson thanks for the heads up. We do plan to add this soon, we'll get to work on it once we're done with the next version of the SDK

**Comment by minhoryang** [comment]
+1

**Comment by walsht** [comment]
+1

**Comment by bithavoc** [comment]
:+1:

**Comment by KiqueDev** [comment]
+1

**Comment by VPTeamMobile** [comment]
+1
Really waiting the Carhage support.

**Comment by maciekish** [comment]
Well?

**Comment by pnull** [comment]
+1

**Comment by degterev** [comment]
+1

**Comment by Quarezz** [comment]
+1

**Comment by Figo0o** [comment]
Guys, 

We are happy to announce supporting Carthage, add `github "Instabug/Instabug-iOS" "dynamic_framework"` to your Cartfile and enjoy :) .. 

Please let us know if there is any feedback. 

Thanks,

**Comment by txaiwieser** [comment]
Can't this be merged to the master repo?

**Comment by mcany** [comment]
How can we access to a specific version with Carthage ?

**Comment by HeshamMegid** [comment]
@mcany what do you currently have in your Cartfile?

**Comment by mcany** [comment]
Hi @HeshamMegid 
currently I have: github "Instabug/Instabug-iOS" "dynamic_framework"
but I want to checkout to a specific version, not to master everytime

**Comment by HeshamMegid** [comment]
Oh, I guess you've missed that we now have better Carthage support.

You should add this to your Cartfile:

`binary "https://raw.githubusercontent.com/Instabug/Instabug-iOS/master/Carthage.json" == 7.2.2`.

The currently supported versions are available [here](`https://github.com/Instabug/Instabug-iOS/blob/master/Carthage.json).

**Comment by mcany** [comment]
@HeshamMegid  

CartFile: After some internal framework we have InstaBug:

![screen shot 2017-04-11 at 5 53 57 pm](https://cloud.githubusercontent.com/assets/8954435/24915543/1c796860-1ee0-11e7-9cc3-d4f86949bedd.png)

Error:

<img width="568" alt="screen shot 2017-04-11 at 5 53 32 pm" src="https://cloud.githubusercontent.com/assets/8954435/24915514/07339d0e-1ee0-11e7-801f-70ceaf0005f5.png">

**Comment by HeshamMegid** [comment]
@mcany let us check on that and get back to you.

**Comment by maxydon** [comment]
any news?

**Comment by Kmohamed** [comment]
@maxydon are you still facing this error ?

**Comment by maxydon** [comment]
I'm not really using it but i'm thinking to and I was wondering about @HeshamMegid comment: `let us check on that and get back to you.`. Is this not still an issue?

**Comment by Kmohamed** [comment]
@maxydon I think @HeshamMegid forget to update this thread but I tried it a lot and it works fine could you give it a try ?

**Comment by maxydon** [comment]
I'll be happy to do that tomorrow (Monday), today I can't.
