### ISSUE TITLE
Network logging doesn't support Protobuf

### ISSUE THREAD

**Issue by alex-vasenin** [Instabug/Instabug-iOS#360]
Our network requests are not appearing in Instabug, despite I added my `URLSessionConfiguration` with `NetworkLogger.enableLogging(for:)` to config. We're using Protobuf, and in #151 I found that only _JSON, XML, HTML, PlainText_ is supported, but `application/x-protobuf` is not. 

Is it possible to add this content type to the list?

**Comment by Kmohamed** [comment]
fortunately, we are going to release an enhancement on network logger which will support all network logs. I can send you custom build to give it a try before the release.

**Comment by alex-vasenin** [comment]
That would be awesome, you can find my email in my profile

**Comment by Kmohamed** [comment]
You can use this custom build.
pod 'Instabug', :git => 'https://github.com/Instabug/Instabug-iOS.git', :branch => 'support/all-content-types'

**Comment by alex-vasenin** [comment]
Yes, it works! Hope you'll release it soon. Thanks!

**Comment by Kmohamed** [comment]
Awesome  🎉. It will be released very soon maximum of two weeks.

**Comment by Kmohamed** [comment]
@alex-vasenin Sorry for being late but it's finally released to production.
Thank you 🙏
