### ISSUE TITLE
Xamarin.iOS  error build last version 9.1.0

### ISSUE THREAD

**Issue by moreirawebmaster** [Instabug/Instabug-iOS#361]
Native linking failed, undefined symbol: _kIBGSurveyIntroDismissButtonText. This symbol was referenced by the managed member InstabugLib.IBGStringKey.IBGSurveyIntroDismissButtonText. Please verify that all the necessary frameworks have been referenced and native libraries linked.

**Comment by AliAbdelfattah** [comment]
@moreirawebmaster Thanks for reporting this. We're working on a fix.

**Comment by AliAbdelfattah** [comment]
Closing the issue as it's been fixed in the latest Xamarin version.
