### ISSUE TITLE
NetworkLogger breaks SSL pinning

### ISSUE THREAD

**Issue by TheStalwart** [Instabug/Instabug-iOS#363]
### Steps to Reproduce the Problem
Configure Alamofire with custom SessionManager and ServerTrustPolicyManager configurations for SSL pinning:

                              trustPolicy: ServerTrustPolicy.pinCertificates(
                                certificates: ServerTrustPolicy.certificates(),
                                validateCertificateChain: true,
                                validateHost: true

### Expected Behavior
Requests failing if server's SSL certificate is not included in app's bundle

### Actual Behavior
Enabling request logging completely disables SSL pinning
                        NetworkLogger.enableLogging(for: sessionConfiguration)

### Instabug integration code
                        NetworkLogger.enableLogging(for: sessionConfiguration)

### SDK Version
9.1

### iOS Version
12.3.1, 13.4

### Device Model
iPhone 6S 12.3.1
iPhone SE 13.4

**Comment by Kmohamed** [comment]
Hello @TheStalwart,
You have to handle SSL pining throughout our APIs in `IBGNetworkLogger`.
`+ (void)setCanAuthenticateAgainstProtectionSpaceHandler:(BOOL(^_Nonnull)(NSURLProtectionSpace * _Nonnull protectionSpace))protectionSpaceHandler;
`

`+ (void)setDidReceiveAuthenticationChallengeHandler:(NSURLCredential* _Nullable (^_Nonnull)(NSURLAuthenticationChallenge * _Nonnull challenge))reciveChallengeHandler;
`

**Comment by TheStalwart** [comment]
Is this documented anywhere?

**Comment by Kmohamed** [comment]
unfortunately No. But we are working on it now.

**Comment by TheStalwart** [comment]
@Kmohamed i've read official Apple docs and quite a few threads on stackoverflow, and i can't get certificate-pinned hosts to work through IB NetworkLogger.

`Task <D1587C90-35C8-4C57-8064-9018C3848480>.<3> finished with error - code: -999
`
Pinning is configured using Alamofire 4 and works correctly unless IB NetworkLogger is enabled for this session:

```
ServerTrustPolicy.pinCertificates(
        certificates: ServerTrustPolicy.certificates(),
        validateCertificateChain: true,
        validateHost: true
    )
```

Please provide example implementation of setCanAuthenticateAgainstProtectionSpaceHandler and setDidReceiveAuthenticationChallengeHandler that would work for cert-pinned hosts, or is there a bug in NetworkLogger after all?

**Comment by Kmohamed** [comment]
Hello @TheStalwart
Sure I can provide you implementation for this.

If you are implementing SSL pining using `URLSession` or `Alamofire` you need to implement these two methods
`setCanAuthenticateAgainstProtectionSpaceHandler`
`setDidReceiveAuthenticationChallengeHandler`

You need to implement them inside our NetworkLogger. Then once we capture a network request we will call your implementation inside these two methods.

**Comment by TheStalwart** [comment]
Yes i did implement them. Yes they're called. I can't get NetworkLogger to accept the request, it fails it no matter what i do in the handler and what values i return

**Comment by Kmohamed** [comment]
Can we go step by step?
1- could you return `true` inside `setCanAuthenticateAgainstProtectionSpaceHandler`
2- could you return `.performDefaultHandling` inside the completion handler.

to make sure that the request will succeed without any logic.

**Comment by TheStalwart** [comment]
```
        NetworkLogger.setCanAuthenticateAgainstProtectionSpaceHandler { (urlProtectionSpace) -> Bool in
            return urlProtectionSpace.authenticationMethod == NSURLAuthenticationMethodServerTrust
        }
```
This seems to return true for the calls i'm concerned about.

For setDidReceiveAuthenticationChallengeHandler, however, neither `urlAuthenticationChallenge.proposedCredential` or ```
URLCredential(trust: urlAuthenticationChallenge.protectionSpace.serverTrust,
                    Backend.serverTrustPolicy.evaluate(serverTrust, forHost: urlAuthenticationChallenge.protectionSpace.host)) 
``` seem to let NetworkLogger accept the connection.

Can you elaborate on .performDefaultHandling ?

**Comment by Kmohamed** [comment]
could you share with me your implementation inside `setDidReceiveAuthenticationChallengeHandler`

**Comment by Kmohamed** [comment]
Oh, I think I found what missed here. You need return to the completion handler the URLCredential and the `completionHandler(.useCredential, credential)`

```
func urlSession(_ session: URLSession, didReceive challenge: URLAuthenticationChallenge, completionHandler: @escaping (URLSession.AuthChallengeDisposition, URLCredential?) -> Void) {

        guard let serverTrust = challenge.protectionSpace.serverTrust else {
            completionHandler(.performDefaultHandling, nil)
            return
        }
        if checkValidity(of: serverTrust) {
            let credential = URLCredential(trust: serverTrust)
            completionHandler(.useCredential, credential)
        } else {
            completionHandler(.cancelAuthenticationChallenge, nil)
        }
    }
```

**Comment by Kmohamed** [comment]
Is this match your implementation?

**Comment by TheStalwart** [comment]
Yes, i posted brief version of my setDidReceiveAuthenticationChallengeHandler previously. I create URLCredential according to all the docs i could find on the topic and return it. NetworkLogger still breaks the request

**Comment by Kmohamed** [comment]
I can not find it. 
I need to know your implementation inside `setDidReceiveAuthenticationChallengeHandler ` and what value do you return?

**Comment by Kmohamed** [comment]
Hello @TheStalwart,
I would like to check if you managed to make it work or not?. If not could you send me a sample app and I can apply it in the sample app.

**Comment by Kmohamed** [comment]
Hello @TheStalwart,
Feel free to open it again if you face any issues.

**Comment by jonchui** [comment]
I was having the same problem, and figured it out by only using 

```
NetworkLogger.setCanAuthenticateAgainstProtectionSpaceHandler { (protectionSpace) -> Bool in
            let (isServerTrusted, _) = SSLCertPinToGlooSessionDelegate.isServerTrusted(protectionSpace: protectionSpace)
            
            if isServerTrusted {
                return true
            } else {
                Toast.error(GlooErrorStrings.uhOhLooksLikeYouDoNotHaveASecureConnection)
                return false
            }
        }
```

I basically refactored my `SSLCertPinToGlooSessionDelegate` which implements sample from https://stackoverflow.com/questions/34223291/ios-certificate-

to let me know if that URLProtectionSpace was trusted

**Comment by Kmohamed** [comment]
Great, 👍 
But, Are you using `setDidReceiveAuthenticationChallengeHandler`?

**Comment by jonchui** [comment]
Nope
