### ISSUE TITLE
Incompatible with Xcode 11.4/Swift 5.2

### ISSUE THREAD

**Issue by sam-w** [Instabug/Instabug-iOS#364]
### Steps to Reproduce the Problem
- Use Xcode 11.4
- `carthage update`

### Expected Behavior
- Successfully build the framework

### Actual Behavior
> Incompatible Swift version - framework was built with 5.1 (swiftlang-1100.0.270.13 clang-1100.0.33.7) and the local version is 5.2 (swiftlang-1103.0.32.1 clang-1103.0.32.29).

### SDK Version
9.1.1

### iOS Version
iOS 13, Swift 5.2

**Comment by Kmohamed** [comment]
Hello @sam-w.
I tried this version and with Xcode 11.4 and Swift 5.2  and works fine with me but using Cocoapods let me check Carthage and get back to you.

**Comment by Kmohamed** [comment]
@sam-w I think it's an issue in Carthage could you check this?
https://github.com/Carthage/Carthage/issues/2887

**Comment by sam-w** [comment]
@Kmohamed yes, it is indeed a Carthage issue - thanks for the pointer. Workaround for now:

```sh
cd <somewhere>
git clone https://github.com/Carthage/Carthage.git master
cd master
make install
cd <project dir>
carthage update
```

**Comment by sam-w** [comment]
Will close this issue now, but would perhaps suggest sticking something in the readme for the next hapless person who's expecting Carthage to have gotten their s**t together by now

**Comment by Kmohamed** [comment]
@sam-w I just tried [0.35.0](https://github.com/Carthage/Carthage/releases/tag/0.35.0) Carthage release and works fine.

**Comment by sam-w** [comment]
Awesome, thanks Khaled
