### ISSUE TITLE
IBGUserStepsListener retains dismissed view controllers

### ISSUE THREAD

**Issue by ngocholo** [Instabug/Instabug-iOS#366]
### Steps to Reproduce the Problem
- Present a screen modally
- Dismiss that screen
- Observe that view controller is still kept around in memory after dismissal
- It only gets released when user navigates to a new screen

<img width="619" alt="Screen Shot 2020-04-23 at 3 35 49 PM" src="https://user-images.githubusercontent.com/4305661/80271785-8abc1180-8678-11ea-8032-0374e88d61e4.png">

### Expected Behavior
- View controllers are properly released and deallocated after dismissal

### Actual Behavior
- View controllers are retained and kept around in memory after dismissal

### SDK Version
`9.0.7`
### iOS Version
`13.4.1`
### Device Model
`iPhone X Simulator`

**Comment by Kmohamed** [comment]
Hello @ngocholo,
We are very sorry for this bug. we are working on a hotfix and will be released very soon.

**Comment by ngocholo** [comment]
@Kmohamed thanks for the quick response. 

When using the .pageSheet modal presentation style, the presenting view controller’s viewDidAppear does not get called after dismissing the top view controller. Therefore, the top view controller that was presented does not get deallocated.

**Comment by Kmohamed** [comment]
make sense 👍. I can provide you a custom build if this blocks you.

**Comment by ngocholo** [comment]
@Kmohamed No need for custom build, but really appreciate the offer!

**Comment by Kmohamed** [comment]
This has been fixed in 9.1.3 Please feel free to reopen if you encountered the same issue again.
Thank You.
