### ISSUE TITLE
Instabug crashes the debugger

### ISSUE THREAD

**Issue by arturgrigor** [Instabug/Instabug-iOS#368]
Integrating the Instabug framework will crash the debugger so whenever you want to just print the description of a variable the debugger will respond with "Couldn't IRGen expression, no additional error".

I filled a bug report on Swift's JIRA (https://bugs.swift.org/browse/SR-12783) to ask for a better error reporting when this problem happens but meanwhile there's a reply from one of the developers which explains what the problem is and how to fix it.

Here's the reply:

> LLDB could clearly do a better job of surfacing the error — I had to dig it out of the types log:
> SwiftASTContext("Instabug")::GetASTContext() – failed to initialize ClangImporter: error: virtual filesystem overlay file '/Users/khaledElMorabea/Library/Developer/Xcode/DerivedData/Instabug-ccnahiryvffhsohhjpovgyeazflu/Build/Intermediates.noindex/ArchiveIntermediates/Instabug/IntermediateBuildFilesPath/Instabug.build/Release-iphonesimulator/Instabug.build/all-product-headers.yaml' not found
> The problem here is with the binary Instabug framework that you are using. The .dSYM files that are generated from Swift code are not (yet) as portable as the ones generated from Clang code. The binary Swift module encode a hardcoded path to a yaml file that only exists on the original developer's machine. You should let them know that they need to compile their binary framework with -no-serialize-debugging-options if they are planning to distribute them to another machine.

There is also a sample project attached to that ticket in which you can reproduce the problem.

**Comment by Kmohamed** [comment]
Thanks a lot, for reporting this. Let me check it and get back to you.

**Comment by Kmohamed** [comment]
@arturgrigor I am sorry but I am not aware of this flag `-no-serialize-debugging-options`. do you have any documentation for this flag?

**Comment by arturgrigor** [comment]
@Kmohamed I don't but maybe you can get in touch with the Swift developer in the comments section from this ticket https://bugs.swift.org/browse/SR-12783

**Comment by Kmohamed** [comment]
Thanks 🙏.
I will try it and check if it works fine or not

**Comment by Kmohamed** [comment]
@arturgrigor I tried the solution on the sample project and works fine for me.
Could you check this [custom build](https://www.dropbox.com/s/h7rhol5ubapltio/Instabug-SDK-LLDB.zip?dl=0) and confirm that it works fine?

**Comment by arturgrigor** [comment]
I tried it with the demo project attached to this ticket (https://bugs.swift.org/browse/SR-12783) and with the app that I'm working on and it still doesn't work.

**Comment by Kmohamed** [comment]
This is weird. What’s your Xcode version?

**Comment by Kmohamed** [comment]
Also, did you clear the build folder and clear the derived data

**Comment by arturgrigor** [comment]
I'm using the latest version, Xcode 11.4.1 (11E503a) and cleaned the project and also deleted the Derived Data. Have you tried it with the demo project from that ticket?

**Comment by Kmohamed** [comment]
Yes.
<img width="1440" alt="Screen Shot 2020-05-13 at 3 05 36 PM" src="https://user-images.githubusercontent.com/1115748/81816394-8ecaa900-952b-11ea-89ca-90780ff60342.png">

**Comment by arturgrigor** [comment]
Can you double check that you sent me the right framework, the one that you used in that demo project?

**Comment by arturgrigor** [comment]
Or maybe can you send me a ZIP with the working demo project and I’ll copy the framework from there into the project that I’m working on?

**Comment by Kmohamed** [comment]
Sure, you can download it from [here](https://www.dropbox.com/s/rncjz0k1ye8yyue/LLDB%20Crash.zip?dl=0).

**Comment by arturgrigor** [comment]
It's working! Both the demo project and the app that I'm working on with the framework from the demo project included now works.

**Comment by Kmohamed** [comment]
So I sent the wrong framework. Sorry 😐.

**Comment by arturgrigor** [comment]
Yeah, no worries 😅

**Comment by Kmohamed** [comment]
@arturgrigor Thanks for your help 🙏. I really appreciate it.

**Comment by arturgrigor** [comment]
Glad I could help. ✌️

**Comment by arturgrigor** [comment]
@Kmohamed There are some new details about the compiler flags in this ticket if you're still interested in reading about them https://bugs.swift.org/browse/SR-12783

**Comment by Kmohamed** [comment]
@arturgrigor Thanks a lot 🙏

**Comment by Kmohamed** [comment]
This has been fixed in 9.1.3 Please feel free to reopen if you encountered the same issue again.
Thank You.
