### ISSUE TITLE
API endpoints returning incorrect `Content-Type`

### ISSUE THREAD

**Issue by rebello95** [Instabug/Instabug-iOS#372]
### Context

We are consuming the Instabug API without the SDK on both iOS and Android. It appears that a change was deployed on or before 6/21/2020 that changed the response `Content-Type` header from `application/json` (which was correct) to `text/plain` (which incorrectly describes the JSON payload).

Our clients expect `application/json` (given that the response is a JSON dictionary) in order to deserialize responses. Because of this change, we're unable to use the API.

### Requested fix

Revert the change that resulted in `Content-Type` being sent as `text/plain` (and change it back to `application/json`).

### Steps to Reproduce the Problem

Send a request to one of the following endpoints with the required payload:

`https://api.instabug.com/api/sdk/v3/bugs`

`https://api.instabug.com/api/sdk/v3/bugs/<string:report_id>/state_logs`

### Expected Behavior

Receive a 200 with a dictionary containing an `id` and **headers with `Content-Type: application/json`**

### Actual Behavior

Receive a 200 with a dictionary containing an `id` and headers with **`Content-Type: text/plain; charset=utf-8`**

**Comment by Kmohamed** [comment]
Hi @rebello95 
I just reproduced the scenario and forwarded this to the BE team. I will keep you updated and sorry for the inconvenience.

**Comment by rebello95** [comment]
Thanks @Kmohamed. Did this break the SDK as well or does the SDK not validate `Content-Type`?

**Comment by Kmohamed** [comment]
Yes. We are not validating the `Content-Type`.

**Comment by rebello95** [comment]
Got it, thanks for clarifying. Please keep us posted on the fix so we can verify.

**Comment by Kmohamed** [comment]
Sure,

**Comment by Kmohamed** [comment]
@rebello95 It should be fixed now.

**Comment by rebello95** [comment]
Looks like it's working now. Thanks!

**Comment by Kmohamed** [comment]
You are welcome 🙏
