### ISSUE TITLE
Connectivity always displays as WiFi

### ISSUE THREAD

**Issue by csfelipe** [Instabug/Instabug-iOS#373]
### Steps to Reproduce the Problem
1. Shake device
2. Select Report a Bug
3. Select any type of report
4. Send report

### Expected Behavior
When a Bug report is filed we should get the current type of Connectivity available for the device.

### Actual Behavior
When a Bug report is filed it always returns Connectivity type as `WiFi`.

<img width="1090" alt="Screen Shot 2020-07-13 at 5 06 30 PM" src="https://user-images.githubusercontent.com/2163863/87365960-627fd880-c52c-11ea-9873-115b2bd11f65.png">

### Instabug integration code
*Make sure to remove your app token.*

On `func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey : Any]?) -> Bool`:
```
let token = fetchToken()
Instabug.start(withToken: token, invocationEvents: [.shake, .screenshot])
setup()

...

  func setup() {

    BugReporting.promptOptionsEnabledReportTypes = [.bug]

    Surveys.autoShowingEnabled = true

    BugReporting.willInvokeHandler = {
         ...
    }
  }

```
### SDK Version
`9.0.3`

### iOS Version
Multiple, last tested on a `13.5.1`

### Device Model
Multiple, last test on iPhone X (MQAU2LL/A)

**Comment by Kmohamed** [comment]
Hello @csfelipe,
To understand you well. Do you mean the wifi name when you mentioned the current type of Connectivity available for the device? If so this was changed in iOS 12 you need to provide a permission to access WiFi name from capabilities. You need to add `access to WiFi information`.

**Comment by csfelipe** [comment]
@Kmohamed could you please point me into the right direction on how to do that? I've browsed around a lot but I couldn't find it.

**Comment by Kmohamed** [comment]
Sure, I think you need to add `access to WiFi information from ` from `signing and capabilities`.
<img width="690" alt="Screen Shot 2020-07-14 at 10 22 45 PM" src="https://user-images.githubusercontent.com/1115748/87472734-b53abc80-c620-11ea-879e-70010bd2090b.png">

**Comment by csfelipe** [comment]
Thanks you so much @Kmohamed !

**Comment by Kmohamed** [comment]
Anytime
