### ISSUE TITLE
Main Thread Checker: UI API called on a background thread: -[UIApplication connectedScenes]

### ISSUE THREAD

**Issue by goa** [Instabug/Instabug-iOS#374]
Starting Instabug takes about 130 milliseconds on an iPhone 8.
We'd like to get that delay off the main thread when our application starts, by starting Instabug from a background thread.

Although that works properly, it would be nice for Instabug to future-proof things by calling [UIApplication connectedScenes] on the main queue and take care of the warning.

### Steps to Reproduce the Problem
Attempt to initialize Instabug from a background queue.
For example:
`DispatchQueue.global(qos: .background).async { Instabug.start(withToken: token, invocationEvents: invocationEvents) }`

### Expected Behavior
Initialization should complete without warnings.

### Actual Behavior
Main Thread checker warns that a UI API ( [UIApplication connectedScenes] ) is called on a background thread.

[reports] Main Thread Checker: UI API called on a background thread: -[UIApplication connectedScenes]
PID: 484, TID: 47966, Thread name: (none), Queue name: com.apple.root.background-qos, QoS: 9

### SDK Version
9.6.1

### iOS Version
13.1

### Device Model
All models

**Comment by Kmohamed** [comment]
Hello @goa, 
I understand your concern about the launch time. Unfortunately, `Instabug.startWithToken` is designed to be called from the Main thread inside `didFinishedLaunchWithOptions`. We are going to optimize our impact on App launch. But could you share with me which phase inside the app life cycle that Instabug affects?

**Comment by goa** [comment]
Hi @Kmohamed, thanks for your prompt response.

We are calling `Instabug.startWithToken` inside `application:didFinishLaunchingWithOptions:` in a background queue. For the time being, we don't see any problems with that, besides the warning. No crashes or anything.

However, we would feel much safer if we knew that Instabug itself makes sure to call all UIKit APIs on the main thread.

100ms might not seem too much, but we are really trying to make our apps as quick launching and snappy as possible :)

**Comment by Kmohamed** [comment]
Yes, I agree with you that it's risky. What about `dispatch_asyn` on `main-thread`.  It should work.

> 100ms might not seem too much, but we are really trying to make our apps as quick launching and snappy as possible :)
totally agree with you 👍

**Comment by goa** [comment]
> Yes, I agree with you it's risky. What about `dispatch_asyn` on `main-thread`. It should work.

I guess that if Instabug could call all related UIKit APIs using dispatch_async, that would be great for us :) We can keep the performance gains and get rid of the warning.

**Comment by goa** [comment]
Hi @Kmohamed :) Are there any updates on this? An estimate perhaps? Thanks :)

**Comment by Kmohamed** [comment]
Hi, @goa. I am sorry for not getting back to you. Actually, we made a lot of improvements to our launch time. Could you please update to our latest version and tell me if it works fine or you still need to do Instabug works in the background thread?

**Comment by yousefhamza** [comment]
@goa we have even more app launch time overhead optimizations coming up, feel free to ping us If you still have any problems with app launch time.
