### ISSUE TITLE
App crashes at runtime when Instabug is in embedded library

### ISSUE THREAD

**Issue by kacper1703** [Instabug/Instabug-iOS#377]
### Steps to Reproduce the Problem

- Create a project in **Xcode 12 (beta 6)**
- Add embedded library to project (with unit tests)
- Initialize Cocoapods
- Add Instabug **only to the embedded library**
- `pod install`
- Build and run the embedded tests

### Expected Behavior

Tests run successfully.

### Actual Behavior

App crashes with following message:
```
Warning: Error creating LLDB target at path /Users/USER/Library/Developer/Xcode/DerivedData/InstabugPodTest-giyaxgqskectlsejpwuoquhdwgjz/Build/Products/Debug-iphonesimulator/InstabugPodTestUITests-Runner.app'- using an empty LLDB target which can cause slow memory reads from remote devices.
dyld: Library not loaded: @rpath/Instabug.framework/Instabug
  Referenced from: /Users/USER/Library/Developer/Xcode/DerivedData/InstabugPodTest-giyaxgqskectlsejpwuoquhdwgjz/Build/Products/Debug-iphonesimulator/ExtensionKit.framework/ExtensionKit
  Reason: image not found
dyld: launch, loading dependent libraries
DYLD_SHARED_CACHE_DIR=/Users/USER/Library/Developer/CoreSimulator/Caches/dyld/19G2021/com.apple.CoreSimulator.SimRuntime.iOS-14-0.18A5357e
DYLD_ROOT_PATH=/Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot
DYLD_LIBRARY_PATH=/Users/USER/Library/Developer/Xcode/DerivedData/InstabugPodTest-giyaxgqskectlsejpwuoquhdwgjz/Build/Products/Debug-iphonesimulator
DYLD_INSERT_LIBRARIES=/Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/libMainThreadChecker.dylib
DYLD_FALLBACK_FRAMEWORK_PATH=/Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks
DYLD_FALLBACK_LIBRARY_PATH=/Applicati
```

### SDK Version
9.1.7

### iOS Version
14.0

### Project That Reproduces the Issue
https://github.com/kacper1703/InstabugPodTest

**Comment by Kmohamed** [comment]
Hi @kacper1703 
So you are adding Instabug inside two targets the project and the test target?

**Comment by kacper1703** [comment]
@Kmohamed yes, it's in both:
```
target 'ExtensionKit' do
  use_frameworks!
  pod 'Instabug', '9.1.7'

  target 'ExtensionKitTests' do
    inherit! :search_paths
  end
end
```
I've just added an example project to run locally.

**Comment by Kmohamed** [comment]
@kacper1703 I do not think this will work. But I am very curious to know more about your use case.

**Comment by kacper1703** [comment]
@Kmohamed Based on your question I would assume attaching a pod to both framework and its tests is not required if I don't use a pod (in this case Instabug) inside the test?

**Comment by kacper1703** [comment]
Okay so weird thing: I have tried replacing Instabug with Alamofire (just swapping the pods in Podfile) **in my main project** and tests run as expected. In the example project doing the same does not fix the issue. That's why I created an issue here as I thought it's Instabug-specific. I suppose I will take this over to the Cocoapods' Github.

**Comment by Kmohamed** [comment]
> I have tried not attaching Instabug to the tests (only the framework) but the app still crashes with the same error.

If you are using Cocopods. I suggest the following:
1- update Cocopods
2- Clear derived data
3- `pod deintegrate`
4- `pod install`
5- Clean build folder

**Comment by Kmohamed** [comment]
>That's why I created an issue here as I thought it's Instabug-specific. I suppose I will take this over to the Cocoapods' Github.
As you said it's something related to CocoaPods. So I will close it and feel free to open it again.
