### ISSUE TITLE
Instabug breaks SwiftUI Previews in Xcode 12

### ISSUE THREAD

**Issue by sam-w** [Instabug/Instabug-iOS#378]
### Steps to Reproduce the Problem
- Create a new project in Xcode 12 GM
- Add Instabug as a dependency (I followed the manual steps from the Readme)
- Add a `PreviewProvider` to any file, e.g.
```
import SwiftUI

struct ContentView_Previews: PreviewProvider {

    static var previews: some View {
        Text("This is a preview")
    }
}
```
- Confirm that the project compiles successfully for a normal Build/Run.
- Build for Previews:
    - Make sure the Previews canvas is visible
    - Click `Resume` to trigger the build
<img width="201" alt="Screen Shot 2020-09-24 at 11 09 27 am" src="https://user-images.githubusercontent.com/8063477/94089514-ae1cff80-fe56-11ea-9f62-5e55bc26c2af.png">
<img width="424" alt="Screen Shot 2020-09-24 at 11 09 34 am" src="https://user-images.githubusercontent.com/8063477/94089537-bd03b200-fe56-11ea-8245-9770b918f4a9.png">

### Expected Behavior
Project builds correctly and displays Previews.

### Actual Behavior
Project fails to compile:
```
<unknown>:0: error: unable to load standard library for target 'arm64-apple-ios9.0'
/somePath/ReviewView.swift:11:8: error: failed to build module 'Instabug' from its module interface; the compiler that produced it, 'Apple Swift version 5.2.4 (swiftlang-1103.0.32.9 clang-1103.0.32.53)', may have used features that aren't supported by this compiler, 'Apple Swift version 5.3 (swiftlang-1200.0.29.2 clang-1200.0.30.1)'
import Instabug
```

### Instabug integration code
N/a

### SDK Version
9.1.7

### iOS Version
iOS14

### Device Model
All

**Comment by sam-w** [comment]
# Possible Workaround

**Comment by AhmedOS** [comment]
Hello @sam-w ,
We are working currently on this issue.
In the meantime, would you try this workaround as a temporary fix? This configuration disables building the project for simulators running on Apple’s new Macs processor. You may need to add this setting for Release config also if you have faced same issue with Release build for simulator, to profile the app for example.
![Screen Shot 2020-09-09 at 12 23 20 PM](https://user-images.githubusercontent.com/21817835/94154748-817cde00-fe7e-11ea-97a0-d5e11964fc77.png)

**Comment by sam-w** [comment]
@AhmedOS yep, that works for me. Thanks for the tip!

**Comment by jadonbaker** [comment]
@AhmedOS was this fixed in 10.0.2?

**Comment by sam-w** [comment]
This is now fixed in Xcode 12.2, I'm going to close the issue

**Comment by Kmohamed** [comment]
Perfect 👌. Feel free to open it again if you face any problems.

**Comment by mloigeret** [comment]
Pro tip for cocoapods users: update cocoapods to the latest version. I struggled with this for hours :)

**Comment by Kmohamed** [comment]
Thank you 🙏🙏
