### ISSUE TITLE
Umbrella header missing 'InstabugCore.h'

### ISSUE THREAD

**Issue by kevinfarst-earnin** [Instabug/Instabug-iOS#379]
### Steps to Reproduce the Problem

1. Upgraded SDK from version 9.1.3 to 10.0
2. When building the project with the updated Cocoapod, received the build failure `/<module-includes>:1:1: Umbrella header for module 'Instabug' does not include header 'InstabugCore.h'`
3. When explicitly adding `#import InstabugCore.h` into the `Instabug.h` file, received the compilation error `'InstabugDefaults/InstabugDefaults.h' file not found` originating from the `InstabugCore.h` header file
4. After removing the `#import <InstabugDefaults/InstabugDefaults.h>` statement, the SDK compiled as expected

### Expected Behavior

SDK compiles without errors.

### Actual Behavior

SDK requires multiple modifications to compile correctly.

### Instabug integration code

```
public class InstabugWorker  {
   ...
    func configUpdated(_ launchOptions: [AnyHashable: Any]?) {
        guard !betaToken.isEmpty && !prodToken.isEmpty else {
            return
        }
        let isRunningLive = launchOptions?[.isRunningLive] as? Bool ?? false
        let token = isRunningLive ? prodToken: betaToken

        Instabug.start(withToken: token, invocationEvents: [
            IBGInvocationEvent(rawValue: invocation)
        ])
        Instabug.welcomeMessageMode = .disabled
        Instabug.enabled = true
       ...
    }
   ...
}
```

### SDK Version

10.0.0

### iOS Version

14.0

### Device Model

iPhone 11 Simulator

**Comment by Kmohamed** [comment]
Hello @kevinfarst-earnin 
Could you please double check if you are excluding `Simulator arm64` inside build settings?
`"EXCLUDED_ARCHS[sdk=iphonesimulator*]" = arm64;`

**Comment by kevinfarst-earnin** [comment]
@Kmohamed We actually are excluding the `Simulator arm64` architecture within our build settings:

<img width="522" alt="Screen Shot 2020-10-05 at 10 59 24 AM" src="https://user-images.githubusercontent.com/58189473/95115167-e398d700-06f9-11eb-89f2-44e13f461889.png">

**Comment by Kmohamed** [comment]
@kevinfarst-earnin  Could you please share with me the Swift version?

**Comment by kevinfarst-earnin** [comment]
@Kmohamed We are currently using `SWIFT_VERSION` 5.0.

**Comment by Kmohamed** [comment]
@kevinfarst-earnin 
could you ask them to open `module.modulemap`
`Instabug.framework/Modules/module.modulemap` and send me a screenshot from it.
Also, could you ask them to clear derived data and clean the build folder?

**Comment by Kmohamed** [comment]
We are suspecting something, but to make sure it 100% fixes the problem, would you mind trying out the following custom build? If it works for you we will include the fix in the official SDK.
`pod 'Instabug', :git => 'https://github.com/Instabug/Instabug-iOS.git', :branch => 'InstabugCore-module'`

**Comment by kevinfarst-earnin** [comment]
@Kmohamed The `module.modulemap` file contains the following:

```
framework module Instabug {
  umbrella header "Instabug.h"

  export *
  module * { export * }
}

module Instabug.Swift {
    header "Instabug-Swift.h"
    requires objc
}
```

Additionally, testing out the `InstabugCore-module` branch seems to fix the build and run the app successfully with correct behavior from the SDK features. Thank you for looking into this! If you have any follow-up questions or need any additional info, please let me know.

**Comment by stegiorgi** [comment]
Hi @Kmohamed,
i'm having the same issue with the missing header file.
Unfortunately, I've just noticed that using the _10.0_ version the crash occurrences are not being symbolicated in the Instabug portal because the SDK version it's not recognised correctly. (see the attached screenshot)
Can you please schedule a new SDK release as soon as possible to fix this issue?
We just released a brand new app, so it's really important for us keep the dashboard updated, especially for the crash data.

Thanks.

**Comment by Kmohamed** [comment]
@stegiorgi We are very sorry for the inconvenience. We will release a new version very soon, But I did not get what you mean by `the SDK version it's not recognized correctly. `

**Comment by stegiorgi** [comment]
@Kmohamed I'm sorry, I wasn't able to attach the screenshot.
This is the message that I'm getting on the Crash section: `This crash had been reported from an older version of the SDK that doesn't support symbolication of linked dynamic frameworks. To be able to get fully symbolicated crashes, please update to the latest version.`

**Comment by Kmohamed** [comment]
@stegiorgi Let me check this with the BE team and get back to you. But related to the symbolication. Do you face any problems?

**Comment by stegiorgi** [comment]
[https://pasteboard.co/JurhoJ3.png](url)

**Comment by Kmohamed** [comment]
@stegiorgi could you please reach out support on Instabug.com so That I can follow up with you. I need to check this crash closely 🙏

**Comment by Kmohamed** [comment]
Hi @stegiorgi & @kevinfarst-earnin , We released a fix. Could you please update to SDK version 10.0.1? Feel free to open it again if you reencounter this issue.
@stegiorgi, your issue should be fixed now 👍
