### ISSUE TITLE
Action-sheet appears behind the keyboard (iPhone, iOS 9)

### ISSUE THREAD

**Issue by vahan-harutyunyan** [Instabug/Instabug-iOS#38]
When there is a keyboard in a view, the actionsheet would appear behind the keybaord (basically doesn't not appear) and the user can't really interact with it.

**Comment by msoliman** [comment]
@vahan-harutyunyan thanks for reporting this. We're fixing this in our next release.
Is this blocking you? I can send you a custom build with that fix if you want.

**Comment by vahan-harutyunyan** [comment]
@msoliman Thanks for getting back on this. I would really appreciate if you could give me an early access to the fix. Currently we can't use instabug on most of the screens. Thank you.

**Comment by msoliman** [comment]
@vahan-harutyunyan Sure, here's the link to the framework (https://www.dropbox.com/s/tru23cjlaiozk0v/Instabug.framework.zip?dl=0).

You'll need to integrate it manually now, not through Cocoapods. Don't forget to include the .bundle file as well. You can use the one in the current live version.

Let me know how it goes.

**Comment by vahan-harutyunyan** [comment]
@msoliman Thank you for the link and instractions. Had to add CoreMotion framework too.
 It worked and the actionsheet is visible now. Thanks again.

**Comment by msoliman** [comment]
Fixed in https://github.com/Instabug/Instabug-iOS/commit/ca78786441ddbcf14ffb6a23a3dec2fce1c2482f
