### ISSUE TITLE
App crashes with another framework swizzling UIViewController methods

### ISSUE THREAD

**Issue by dchohfi** [Instabug/Instabug-iOS#380]
### Steps to Reproduce the Problem

After updating the library to 10.0 my app started crashing at a point where another library is also swizzling a method.
Have a framework that swizzles `viewDidAppear:` `UIViewController` method, in my case I use RxSwift which also do the same, but after upgrading the app started crashing.

### Expected Behavior

Not crash

### Actual Behavior

Crashes

### Instabug integration code
*Make sure to remove your app token.*

### SDK Version
10.0

### iOS Version
14.0.1

### Device Model
iPhone XR

**Comment by dchohfi** [comment]
Amazing @Kmohamed, thank you

**Comment by Kmohamed** [comment]
Hi @dchohfi, We released a fix. Could you please update to SDK version 10.0.1? Feel free to open it again if you reencounter this issue.
