### ISSUE TITLE
Not able to track Network logs

### ISSUE THREAD

**Issue by karthikdamodara** [Instabug/Instabug-iOS#381]
### Steps to Reproduce the Problem
We are not able to see network logs for issues reported by Instabug although we use non customised URLSession

### Expected Behavior
We should be able to see network logs by default if we use non customised URLSession

### SDK Version
We are using 9.1.6

**Comment by Kmohamed** [comment]
Hi @karthikdamodara 
It should work without any effort if you're using URLSession.shared, but if you create SessionConfiguration, you need to pass it to Instabug.

**Comment by karthikdamodara** [comment]
Hi @Kmohamed 

We use default SessionConfiguration, Do you still think we need to pass it to Instabug?

**Comment by Kmohamed** [comment]
Yes, please

**Comment by karthikdamodara** [comment]
Ok, thank you

**Comment by Kmohamed** [comment]
No, the implementation did not change. Could you give it a try and tell me if it works fine?

**Comment by Kmohamed** [comment]
@karthikdamodara, Are you still facing any issues here?

**Comment by karthikdamodara** [comment]
@Kmohamed The issue has been resolved. Thanks

**Comment by Kmohamed** [comment]
Perfect 🎉 , Please don't hesitate to reach out to us if you need any help.
