### ISSUE TITLE
Cannot turn off crash reporting in Instabug 10.0.2

### ISSUE THREAD

**Issue by alex-vasenin** [Instabug/Instabug-iOS#383]
### Steps to Reproduce the Problem
1. Embed Instabug into a project
2. Turn off Instabug crash reporting with `CrashReporting.enabled = false`
3. Run the app with debugger
4. Run the app without debugger

### Expected Behavior
Crash reporting is turned off (with or without debugger)

### Actual Behavior

With debugger attached I see in the console
`[Instabug] - IBGCrashReporting - Instabug crash reporting is disabled because debugger is attached to this session. Crashes and NSErrors will not be reported to Instabug. To detach debugger, click the Stop button in Xcode, then run the app manually from the simulator.`

Without the debugger Crashlytics complains to console
`[Crashlytics] The signal SIGABRT has a non-Crashlytics handler (IBGplcrash_signal_handler).  This will interfere with reporting.`

Clearly, crash reporting is not turned off, despite `CrashReporting.enabled = false`

### Instabug integration code
```
Instabug.start(withToken: accessToken, invocationEvents: [.shake])
CrashReporting.enabled = false
```

### SDK Version
10.0.2

### iOS Version
14.2

### Device Model
iPhone 11 Pro

**Comment by Kmohamed** [comment]
Hi @alex-vasenin 
We are very sorry for the inconvenience, But when you report a crash on your device, you can see it on the dashboard.

**Comment by alex-vasenin** [comment]
@Kmohamed How can I fully turn off crash reporting?

**Comment by Kmohamed** [comment]
@alex-vasenin  I think it's just a misleading error message. Because if it's enabled on your plan, it will be automatically turned on. Then when you turned it off, it's turned off. If you crash the app wee will not see and did not get reported on the dashboard.

**Comment by Kmohamed** [comment]
And the reason behind turning on automatically, to catch crash at launch.

**Comment by alex-vasenin** [comment]
Is there a way to start Instabug with crash reporting turned off?

**Comment by Kmohamed** [comment]
Definitely, we can do this, But To understand your use-case. Does this affect your app?

**Comment by alex-vasenin** [comment]
Truth is, I don't know. We do have some crash reports missing and I was investigating the issue and found this warning. 

If framework A sets signal handler, then framework B sets its own handler for the same signal and then removes it, it might well mean that the first handler is gone.

**Comment by Kmohamed** [comment]
Make sense. We will work on this and get back to you very soon.

**Comment by alex-vasenin** [comment]
Any updates on the issue?

**Comment by Kmohamed** [comment]
@alex-vasenin it will be included in the next release.

**Comment by alex-vasenin** [comment]
Thank you! 👍

**Comment by Kmohamed** [comment]
We are very sorry for being late. We released the [fix](https://github.com/Instabug/Instabug-iOS/releases/tag/10.1.1).
You can turn off crash reporting before `startWithToken`.
