### ISSUE TITLE
Can't hide sensitive data for the presented view controller

### ISSUE THREAD

**Issue by akabel92** [Instabug/Instabug-iOS#384]
### Steps to Reproduce the Problem
1- Create two view controllers and make the first viewController presents the second viewController modally
2- make the first viewController as a privateView 
3- Add two textFields to the second view controller and make the first textField only as a privateView

### Expected Behavior
The first textField should be only has a black box when the user tries to create a bug report
### Actual Behavior
The second viewController has a black box for all the view 

### SDK Version
10.0.3
### iOS Version
14.0
### Device Model
iPhone 11 pro
### [Optional] Project That Reproduces the Issue

[Instabug.zip](https://github.com/Instabug/Instabug-iOS/files/5554685/Instabug.zip)

**Comment by Kmohamed** [comment]
Hello, @akabel92 We are very sorry for the inconvenience, Will check it and get back to you soon.

**Comment by Kmohamed** [comment]
The fix will be included in the next release, but if you need a custom build, I will be happier to provide it.

**Comment by akabel92** [comment]
No need for a custom build. I will wait for the next release. Thanks @Kmohamed!

**Comment by Kmohamed** [comment]
The [release](https://github.com/Instabug/Instabug-iOS/releases/tag/10.1.1) is finally out 🎉
We are very sorry for being late 🙏.
