### ISSUE TITLE
Memory leaks upon launch

### ISSUE THREAD

**Issue by mrobert** [Instabug/Instabug-iOS#385]
### Steps to Reproduce the Problem
`pod 'Instabug'`
_installed Instabug (10.0.3)_
Basic setup as per your setup documentation.
This line from '_didFinishLaunchingWithOptions_' flagged in Instruments Leaks:
`Instabug.start(withToken: [APP TOKEN], invocationEvents: [.shake, .screenshot])`

### Expected Behavior
No memory leaks.

### Actual Behavior
Instabug seems to be working as expected but unfortunately with memory leaks upon launch.  Please see attached screenshots.
<img width="1421" alt="InstabugLeakUponLaunch" src="https://user-images.githubusercontent.com/484596/99601435-7fd13000-2a53-11eb-8948-32cec15ca8c2.png">
<img width="988" alt="InstabugLeaks" src="https://user-images.githubusercontent.com/484596/99601456-88c20180-2a53-11eb-87ce-ecf99f4faeac.png">

### Instabug integration code
`Instabug.start(withToken: [APP TOKEN], invocationEvents: [.shake, .screenshot])`

### SDK Version
Instabug (10.0.3)

### iOS Version
iOS 14.2 (device and simulator)
### Device Model
iPhone 7 Plus

**Comment by Kmohamed** [comment]
Hello @mrobert 
It seems to be memory leaks, but it does not. Instruments trigger these warnings for every object that didn't deallocate,  for example, singletons. I would recommend if you can use memory allocation and check the behaviors of memory consumption.

**Comment by mrobert** [comment]
Hi @Kmohamed, thanks for getting back.  Not seeing anything obvious as far as memory consumption.

But these are 4 types that come up from your sample demo app.  
<img width="1135" alt="InstabugDemoLeaksMemoryGraph" src="https://user-images.githubusercontent.com/484596/99649153-f13ace00-2aa7-11eb-9b8c-2c4d38d958a3.png">
All just warnings?

**Comment by Kmohamed** [comment]
Yes, We have a singleton that owns an NSOperationQueue 👍.

**Comment by Kmohamed** [comment]
I will close this issue, but please feel free to open it again if you face any memory issues.

**Comment by mrobert** [comment]
Alright, thank you @Kmohamed .  👍
