### ISSUE TITLE
Instabug fails when a podspec dependency

### ISSUE THREAD

**Issue by Ironworks** [Instabug/Instabug-iOS#386]
Using Instabug as a dependency to for a private pod(cocoapods) causes pod repo lint to fail while attempting to compile the Instabug dependency.

### Steps to Reproduce the Problem
Incorporate Instabug as a dependency in your podspec file
Run 'pod spec lint'
   
### Expected Behavior
Lint should successfully validate the podspec

### Actual Behavior
Lint process fails while compiling Instabug with the following error:

```
error: failed to build module 'Instabug' from its module interface; the compiler that produced it, 'Apple Swift version 5.3 (swiftlang-1200.0.29.2 clang-1200.0.30.1)', may have used features that aren't supported by this compiler, 'Apple Swift version 5.3.1 (swiftlang-1200.0.41 clang-1200.0.32.8)
```

### SDK Version
10.0.3

### XCODE/Build tools version
XCODE 12.2

**Comment by Kmohamed** [comment]
Hello @Ironworks 
Hmm, first time to see this error, but do you mind if you give it a try using Xcode 11.x?

**Comment by Ironworks** [comment]
Hi @Kmohamed  It works fine in XCODE 11.x. I'm using this as a workaround at the moment. I think it might be something to do with not setting 's.swift_versions' in your podspec?

**Comment by Kmohamed** [comment]
@Ironworks Will do it in the next release and update you to give it a try 👍

**Comment by Ironworks** [comment]
@Kmohamed Thanks, I'l give it a go when it is available.

**Comment by phlippieb** [comment]
Hi! I'm experiencing this same issue when using Instabug v10.1.1 (the latest release at this time) with Xcode 12.2 (12B45b).

**Comment by yousefhamza** [comment]
Hi @phlippieb, we still cannot reproduce this issue but we are still on it.

Meanwhile, can you try:
1. Quit Xcode
2. Delete "Derived Data"
3. Open Xcode and Build again
