### ISSUE TITLE
License file not available for SDK 10.0.3

### ISSUE THREAD

**Issue by kacper1703** [Instabug/Instabug-iOS#388]
When installing the SDK 10.0.3 via CocoaPods (v10.0) a warning is shown in the console:

> [!] Unable to read the license file `LICENSE.md` for the spec `Instabug (10.0.3)`

I can see in the git diff that both the License and Readme are being removed when updating from SDK 10.0.0.

<img width="255" alt="Screenshot 2020-11-24 at 12 43 56" src="https://user-images.githubusercontent.com/12765428/100089926-bb546b80-2e52-11eb-9f45-a4f01547f979.png">

This results in the Instabug license not being included in the app and shown to the user.

**Comment by Kmohamed** [comment]
This is very weird. I still can see it inside the repo. Let me double-check and get back to you.

**Comment by Kmohamed** [comment]
Could you please run `pod install --verbose`?

**Comment by kacper1703** [comment]
I did and I think the relevant part of the verbose log is:
> Resolving dependencies of `Podfile`
> CDN: trunk Relative path: CocoaPods-version.yml exists! Returning local
> because checking is only perfomed in repo update

Running `pod install --repo-update` also results in the same message.

**Comment by Kmohamed** [comment]
Could you try it again now?

**Comment by kacper1703** [comment]
It's still occuring. I think it may after all be related to Cocoapods. I will transfer the issue there.

**Comment by Kmohamed** [comment]
I think it's related to ours. Could you please clean the cocoa-pods cache?
```
rm -rf "${HOME}/Library/Caches/CocoaPods"
rm -rf "`pwd`/Pods/"
pod update
```

**Comment by kacper1703** [comment]
Okay, that worked. But I also have fixed my `Podfile`, I had a leftover `source 'https://github.com/CocoaPods/Specs.git'` inside.

Thank you very much :)
