### ISSUE TITLE
Instabug binary not compiling on a M1 host

### ISSUE THREAD

**Issue by AndrewSB** [Instabug/Instabug-iOS#391]
Hey! I'm trying to compile my app which includes the vended Instabug.framework v10.1. I get the following error:

<img width="751" alt="Screen Shot 2020-11-30 at 2 14 19 PM" src="https://user-images.githubusercontent.com/3814772/100672269-89da1500-3316-11eb-89a9-b6e2217b1693.png">

could you to re-compile and include an arm64 simulator slice in the built xcframework?

If I `#if` out my Instabug code, I get this linker error instead

<img width="1092" alt="Screen Shot 2020-11-30 at 2 19 21 PM" src="https://user-images.githubusercontent.com/3814772/100672652-1b498700-3317-11eb-8f1f-eb200253921a.png">

**Comment by AndrewSB** [comment]
Versions:

machine: MacBook Air (M1, 2020)
macOS: 11.0.1 (20B29)
Xcode: Version 12.2 (12B45b)
Instabug: v10.1 binary

**Comment by Kmohamed** [comment]
Unfortunately, We can’t do this with the dynamic framework because it already has arm64 architecture for iOS devices. We can not add two arm64 architectures in the same binary. You need to use XCFramework from our GitHub until we release SPM very soon.

**Comment by AndrewSB** [comment]
I haven't been able to succeed with the XCFramework yet, for now I've taken it out

**Comment by AndrewSB** [comment]
that worked! thank you

**Comment by yousefhamza** [comment]
Hi @AndrewSB We just released Instabug in SPM! you can consume it at `https://github.com/Instabug/Instabug-SP.git`

We are shipping XCFramework so Instabug should work fine now with M1 macs' simulators 🎉

**Comment by AndrewSB** [comment]
continuing over at https://github.com/Instabug/Instabug-SP/issues/5

**Comment by yousefhamza** [comment]
Thanks for the new issue reference @AndrewSB 🙏 
I will close this issue now.
