### ISSUE TITLE
"No such file or directory" for extra attachment

### ISSUE THREAD

**Issue by AlexeyKolmyk** [Instabug/Instabug-iOS#392]
Good day. I want to attach my custom logs using https://docs.instabug.com/docs/ios-bug-report-content#extra-attachments.  it's working, but I noticed one problem - my file didn't attach when I tried to post a bug after fresh app install. Here my code:

```
NSURL *logFileURL = [NSURL fileURLWithPath:logFilePath];
BOOL isFileExist = [[NSFileManager defaultManager] fileExistsAtPath:logFileURL.path];
NSLog(@"File exist: %d", isFileExist);
[Instabug addFileAttachmentWithURL:logFileURL];
```

and here verbose logs:

```
...
[Instabug] - InstabugReporting - show Prompt
[Instabug] - IBGCore - Called public method: addFileAttachmentWithURL:
[Instabug] - IBGFile Attachements - File added to path: my_report 2020-12-08--14-53-45-008.log
2020-12-08 16:54:01.597192+0200 MyAppDev[830:115502] File exist: 1
2020-12-08 16:54:01.601961+0200 MyAppDev[830:115957] open on /var/mobile/Containers/Data/Application/5A4E74E1-EA0E-4C9D-AFDD-6B177A209BE1/Library/IBGCache/IBGFileStorage/188E8951-CAA0-4794-8E21-102CEFD16A56/my_report 2020-12-08--14-53-45-008.log: No such file or directory
[Instabug] - IBGUser Steps - Captured screenshot using currentImageContext = <UIImage:0x283bcce10 anonymous {375, 812}>
[Instabug] - IBGCore - Screenshot taken: <UIImage:0x283bcce10 anonymous {375, 812}>
...
```

I also tried to use `addFileAttachmentWithData:` or use `setWillSendReportHandler`  but result the same.
I want to notice that my log file exists when I invoke `[Instabug addFileAttachmentWithURL:logFileURL]`.

### Steps to Reproduce the Problem
1. Install a fresh application. 
2. Invoke "Report a bug"

### Expected Behavior
Attachments are visible in admin panel.

### Actual Behavior
No attachments in admin panel.

### Instabug integration code
*Make sure to remove your app token.*

### SDK Version
10.1

### iOS Version
14.0
### Device Model
iPhone X

**Comment by Kmohamed** [comment]
Hello @AlexeyKolmyk, Thanks a lot for a detailed bug report. This kind of report makes our life more easy 🙏.
I succeed to reproduce the bug, and I will keep you updated.

**Comment by AlexeyKolmyk** [comment]
Good day @Kmohamed ! Do you have some news about this issue? I can provide additional info/logs if you need it

**Comment by Kmohamed** [comment]
Yes, will be fixed next release.

**Comment by AlexeyKolmyk** [comment]
Ok, thanks!

**Comment by Kmohamed** [comment]
We released a [fix](https://github.com/Instabug/Instabug-iOS/releases/tag/10.1.1).
Please do hesitate to reach out to us if you need any help, and thanks again for the detailed report🙏.
