### ISSUE TITLE
Invalid JSON in Instabug.json on version 10.1.1

### ISSUE THREAD

**Issue by GeorgiDamyanov** [Instabug/Instabug-iOS#394]
It appears that the following [commit](https://github.com/Instabug/Instabug-iOS/commit/0d3838645a1a6226247894ea6f23482585c608c0) broke the Instabug.json file.

There is a comma missing on the second to last line:
`"10.1.1" : "https:\/\/github.com\/Instabug\/Instabug-iOS\/releases\/download\/10.1.1\/Instabug.zip"`

**Comment by Kmohamed** [comment]
We are very sorry for that. It's fixed now. could you give it another try?

**Comment by GeorgiDamyanov** [comment]
Thank you for the quick fix, it works now =)

**Comment by Kmohamed** [comment]
Anytime
