### ISSUE TITLE
Building for iOS, but the linked and embedded framework 'Instabug.framework' was built for iOS + iOS Simulator.

### ISSUE THREAD

**Issue by gunyduny** [Instabug/Instabug-iOS#401]
Building for iOS, but the linked and embedded framework 'Instabug.framework' was built for iOS + iOS Simulator.

I upgraded from 10 to 10.2 and know I am getting the error above. 

I am on the most updated Xcode and IOS 14.4 Image.

I have done every step listed on this Github and your webpage, and nothing, i am pretty much loading my app to the App store without Instabug, cause that is the only way I can build it.

**Comment by yousefhamza** [comment]
It looks like you are still using an older version that do doesn’t yet use Instabug.**xcframework**

you can confirm this by checking the “Pods/Instabug” directory.

_Make sure_ you are using the latest version “10.2” because it’s using the XCFramework.

**Comment by gunyduny** [comment]
I have tried pod install, pod update, deleted the Instabug directory in the PODS folder, I have done nothing different this time than I did in the past to update my PODs.



Dr. Andrew L. Dunn
www.dunn-carabali.com
andrew@dunn-carabali.com
832.494.8080

**Comment by yousefhamza** [comment]
Can add this to your podfile to make sure that Cocoapods update Instabug:
`pod 'Instabug', '~> 10.2' `

Also please make sure you are using Cocoapods version 1.10 or above.

**Comment by Kmohamed** [comment]
@gunyduny Did you manage to make it work?
