### ISSUE TITLE
Private View redacting for SwiftUI ?

### ISSUE THREAD

**Issue by ismyhc** [Instabug/Instabug-iOS#402]
How would one handle redacting or hiding certain views when using SwiftUI?

Looking at the docs, I see that for UIKit there is:

`view.instabug_privateView = true`

For instance, I have some TextFields that I have sensitive information that I don't want to capture in a video or screenshot.

Any guidance much appreciated :)

**Comment by hassaanelgarem** [comment]
@ismyhc Sorry for the late reply.
Unfortunately we don't support SwiftUI yet, but we're working on it.

**Comment by MartinW** [comment]
@Kmohamed Any updates on SwiftUI support please?

**Comment by MartinW** [comment]
@ismyhc Did you find any workaround for this? Thanks

**Comment by ahmedsalah196** [comment]
This has been released in `12.9.0`
