### ISSUE TITLE
Views marked as private are still visible in screenshots

### ISSUE THREAD

**Issue by lizbarrett** [Instabug/Instabug-iOS#403]
### Steps to Reproduce the Problem
`instabug_privateView = true`

### Expected Behavior
The views marked as private would be private in screenshots

### Actual Behavior
Calling `instabug_privateView = true` does *not* actually make the view private from screenshots

### Instabug integration code
*Make sure to remove your app token.*

### SDK Version
10.1.1, 10.1.2, 10.3

### iOS Version
iOS 14.3

### Device Model
iPhone SE, iPad Pro

**Comment by Kmohamed** [comment]
Hello @lizbarrett 
We are sorry for the inconvenience. Actually, I tried it several times, and it worked well. So, could you please contact the happiness team and share more information about the bug so that we can debug it deeply.

**Comment by Kmohamed** [comment]
@lizbarrett Did you manage to do this?

**Comment by Kmohamed** [comment]
If you faced this issue again, please don't hesitate to reach out to us.
