### ISSUE TITLE
Failed building on Xcode randomly 

### ISSUE THREAD

**Issue by ziadghali2** [Instabug/Instabug-iOS#404]
ld: warning: ignoring file /Users/ziad/Documents/shift-customer-app-ios/Pods/Instabug/Instabug.xcframework/ios-arm64_armv7/Instabug.framework/Instabug, missing required architecture x86_64 in file /Users/ziad/Documents/shift-customer-app-ios/Pods/Instabug/Instabug.xcframework/ios-arm64_armv7/Instabug.framework/Instabug (2 slices)

Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_IBGNetworkLogger", referenced from:
      objc-class-ref in MiddlewareService.o
  "_OBJC_CLASS_$_Instabug", referenced from:
      objc-class-ref in CrashReport.o

ld: symbol(s) not found for architecture x86_64

clang: error: linker command failed with exit code 1 (use -v to see invocation)

i just build and this error for clang happen 
my build version for instabug IOS SDK is 10.3

and case archive no issue appear which make me try to upload the build to testflight which send me email for bitcode failure

**Comment by hassaanelgarem** [comment]
@ziadghali2 Hello ziad, sorry for the late reply
Can you tell the method you use for integrating Instabug?
Also can you make sure you choose "Any iOS Device" when you archive your app and try again?

**Comment by yousefhamza** [comment]
@ziadghali2 
Feel free to ping us if you still have any problems
