### ISSUE TITLE
Instabug 10.4.0 not working

### ISSUE THREAD

**Issue by yusufkildan** [Instabug/Instabug-iOS#408]
Hi, latest Instabug build not working. You can see the errors below: 
![Screen Shot 2021-02-19 at 13 01 06](https://user-images.githubusercontent.com/7632833/108490026-4f4b9d00-72b3-11eb-95ec-b6fe70ac7c1c.png)

### Xcode Version
12.4
### SDK Version
10.4.0
### iOS Version
iOS 14
### Device Model
iPhone XR

**Comment by Kmohamed** [comment]
How do you integrate our framework?

**Comment by yusufkildan** [comment]
I'm using CocoaPods.

**Comment by Kmohamed** [comment]
What's your cocoa pods version?

**Comment by yusufkildan** [comment]
It is the latest version: **1.10.1**

**Comment by vasiliylisin** [comment]
I had the same error for Instabug **10.4.1** when tried to build a branch, which was previously updated and succesfully built by another dev in my project.
Running `pod deintegrate` and `pod install` fixed it for me.

Doesn't seem like it's a problem for this specific pod.

**Comment by Kmohamed** [comment]
This is actually a good point. @yusufkildan Could you give it a try?

**Comment by yusufkildan** [comment]
It's working now. Thanks a lot!
