### ISSUE TITLE
Instabug 10.4.1 - Xcode 12

### ISSUE THREAD

**Issue by jacob753** [Instabug/Instabug-iOS#409]
### Steps to Reproduce the Problem
Building the Xcode project fails, and gives the error: 'Instabug/Instabug.h' file not found
The newest Instabug framework that works is 9.1.7. Updating to the newer versions stops compiling and gives the error above.

We need to get off the 9.1.7 framework asap, as 9.1.7 seems to cause the memory to continue to go up until the app crashes. This crash doesn't occur when Instabug is disabled.

### Expected Behavior
The project should run on the simulator.

### Actual Behavior
The project doesn't compile. It gives the error: 'Instabug/Instabug.h' file not found

### SDK Version
10.4.1

### iOS Version
14.4

### Device Model
iPad Air 4th Gen Simulator

Xcode 12.4

Using Cocoapods to integrate Instabug.
Cocoapods version: 1.10.1

Steps taken:
Product Clean
Quit Xcode
Delete Derived Data
Build

![Screen Shot 2021-02-22 at 1 42 38 PM](https://user-images.githubusercontent.com/79482960/108774142-22e28b80-7514-11eb-9379-be2688298bff.png)

**Comment by yousefhamza** [comment]
Can you try to delete the “Pods/“ directory to _reinstall_ the pods?

**Comment by jacob753** [comment]
> Can you try to delete the “Pods/“ directory to _reinstall_ the pods?

Yes, doing that gives the same error.

**Comment by yousefhamza** [comment]
@jacob753 Can you try running `pod deintegrate` and `pod install` 🙏

**Comment by jacob753** [comment]
> @jacob753 Can you try running `pod deintegrate` and `pod install` 🙏

Same error.

**Comment by yousefhamza** [comment]
@jacob753 The change we have is that for 10.4.1 we are using XCFrameworks instead of `.framework`
we will have to dig in a little deeper, can you verify that `Pods/Instabug` exists, and that it has `Instabug.xcframework`? Also, can you please verify that you are on Xcode 12?

**Comment by jacob753** [comment]
> @jacob753 The change we have is that for 10.4.1 we are using XCFrameworks instead of `.framework`
> we will have to dig in a little deeper, can you verify that `Pods/Instabug` exists, and that it has `Instabug.xcframework`? Also, can you please verify that you are on Xcode 12?

I am using Xcode Version 12.4 (12D4e).
Items under Pods/Instabug:
Instabug.framework.dSYM
Instabug.xcframework
LICENSE.md

**Comment by yousefhamza** [comment]
That all looks very good, and you mentioned that the cocoapods version is 1.10 here which is fine.

Can you reproduce this issue in a sample project and send it to us for investigation?

**Comment by jacob753** [comment]
Switching to Swift Packages to install Instabug instead of CocoaPods resolved the issue.
Thank you for your time.

**Comment by yousefhamza** [comment]
Excellent, happy it works 👍
