### ISSUE TITLE
Grepping for APP_TOKEN in Instabug_dsym_upload.sh takes a long time and mostly fails when DerivedData is relative to project path

### ISSUE THREAD

**Issue by ldiqual** [Instabug/Instabug-iOS#41]
Since my DerivedData folder is relative to my iOS project path, grepping for the app token in Instabug_dsym_upload.sh takes a very long time and fails for some files that cannot open

![](https://www.dropbox.com/s/l5jt5nw7ct2e6ce/Screenshot%202015-11-21%2015.25.00.png?raw=1)

A solution would be to not grep the DerivedData folder.

**Comment by msoliman** [comment]
@ldiqual you can disable this `grep` by adding this to the top of your build script:
```
APP_TOKEN = "{your_token_here}"
```

That way, the script won't `grep` for the token.
