### ISSUE TITLE
IBGSessionManager unavailable

### ISSUE THREAD

**Issue by AndrewSB** [Instabug/Instabug-iOS#413]
Hey! I'm using the latest release through Carthage, and I'm trying to enable networking logging for my Alamofire session (https://docs.instabug.com/docs/ios-logging#alamofire)
I'm supposed to use `let manager = IBGSessionManager(configuration: configuration)`, but it doesn't seem like that class is shipped with the SDK. 

Could I get some assistance please?

**Comment by yousefhamza** [comment]
Hi @AndrewSB 

The example in the docs shows a _declaration_ of “IBGSessionManager” as an example for a class that you would create in your own app to handle network requests using Alamo fire.

**Comment by AndrewSB** [comment]
🤦‍♂️
