### ISSUE TITLE
PrivateView not working when alert is presented

### ISSUE THREAD

**Issue by mfernandez94** [Instabug/Instabug-iOS#415]
### Steps to Reproduce the Problem
- Start screen recording 
- Record a screen that has `instabug_privateView = true`
- Present an `UIAltertViewController` from that screen

### Expected Behavior
- When the alert is presented the redacted information from the presenting view should still be redacted

### Actual Behavior
- When the alert is presented the redacted information from the pressing view is now visible

### Instabug integration code
```            Instabug.start(withToken: token, invocationEvents: invocationEvents)
            Instabug.welcomeMessageMode = .disabled
            Instabug.tintColor = Colors.primary
            Instabug.setValue(NSLocalizedString("Send Feedback", comment: ""), forStringWithKey: kIBGReportFeedbackStringName)

            Replies.enabled = false
            CrashReporting.enabled = false

            BugReporting.enabled = true
            BugReporting.promptOptionsEnabledReportTypes = [.bug, .feedback]
            BugReporting.enabledAttachmentTypes = [.galleryImage, .screenRecording]
```

### SDK Version
 10.4.3

### iOS Version
14.4

### Device Model
iPhone 11 Pro Max

**Comment by hassaanelgarem** [comment]
@mfernandez94 We're sorry for this inconvenience! We were able to reproduce this issue and we have a fix for it. We will release this in an official release but that will be about 2 weeks from from now. If that's too far for you, I can provide you with a custom build including this fix if you want 👍

**Comment by hassaanelgarem** [comment]
@mfernandez94 This issue has been fixed in the latest release
