### ISSUE TITLE
Crash on 10.4.3 in production on ibg_writeJSONObject:toDirectory:completion:

### ISSUE THREAD

**Issue by alessiolapenna** [Instabug/Instabug-iOS#416]
### Steps to Reproduce the Problem
Not sure how to reproduce this crash. We see multiple instances on our app in production environment. 

### Expected Behavior
The app should run normally

### Actual Behavior
App crashes for users.
The crash is reported by XCode Organizer
![Schermata 2021-04-30 alle 08 49 06](https://user-images.githubusercontent.com/3438105/116632409-1e15da00-a992-11eb-9d93-44f01056d224.png)

### Instabug integration code

        Instabug.start(withToken: "TOKEN", invocationEvents: .none)
        Instabug.welcomeMessageMode = .live
        Instabug.tintColor = StyleManager.Color.seafoamBlue.get()

        CrashReporting.enabled = true
        CrashReporting.oomEnabled = false

### SDK Version
10.4.3

### iOS Version
14.4.2

### Device Model
iPhone11

**Comment by hassaanelgarem** [comment]
We're very sorry for this inconvenience! We'll be working on a fix for this crash and will update you once it's released.
