### ISSUE TITLE
Dismissing feedback window

### ISSUE THREAD

**Issue by huragan** [Instabug/Instabug-iOS#42]
Hi,

is there a way to programmatically dismiss feedback window ?

**Comment by msoliman** [comment]
@huragan we're adding this in our next release. But in the moment, there's this branch (https://github.com/Instabug/Instabug-iOS/tree/add-dismiss-method) in which we've added this method. Feel free to use it.

**Comment by keith** [comment]
@msoliman has this been added to a release?

**Comment by msoliman** [comment]
Yes, its been added in bc4b46756ecb78e0f1ccfb94f4f25533f37460fc

**Comment by keith** [comment]
Thanks! Just saw that this was closed before that was pushed.
