### ISSUE TITLE
Carthage + xcframework

### ISSUE THREAD

**Issue by marcelofabri** [Instabug/Instabug-iOS#421]
### Steps to Reproduce the Problem

Open https://raw.githubusercontent.com/Instabug/Instabug-iOS/master/Instabug.json

### Expected Behavior

xcframeworks to be available as supported by [Carthage 0.38.0](https://github.com/Carthage/Carthage/releases/tag/0.38.0)

### Actual Behavior

Only .framework is available 

### SDK Version

10.5.2

### iOS Version

All

### Device Model

All

**Comment by husseinkishk** [comment]
Hi @marcelofabri 
We're working on it and you will find the fix in the next release.
I will update you once it's released.

**Comment by yousefhamza** [comment]
Starting 10.7.1 Carthage is available as xcframework 🙏
