### ISSUE TITLE
Feature Request: Add a way to hide a view from Repro steps tab

### ISSUE THREAD

**Issue by kaiengelhardt** [Instabug/Instabug-iOS#424]
Our app has a relatively complex view hierarchy. Some of our views are what we call passthrough views. These are transparent views, which pass on all touches to the views below.

The problem is that this makes the repro steps tab in Instabug less useful, because all taps and swipes are reported to happen in these "passthrough views".

### Steps to Reproduce the Problem
1. Take this view controller:
```
class PassthroughView: UIView {
    
    override func hitTest(_ point: CGPoint, with event: UIEvent?) -> UIView? {
        let view = super.hitTest(point, with: event)
        if view == self {
            return nil
        }
        return view
    }
}

class TestViewController {
    
    override func loadView() {
        view = PassthroughView()
    }
}
```
2. Add it as a child view controller on top of another view controller.
3. Do some taps in `TestViewController`.

### Expected Behavior
I would like to have a way to treat TestViewController as invisible to Instabug, because all taps inside of it are being passed on to the view controller below it.

### Actual Behavior
Currently there is no way to do that. This causes all our crash reports to say that the taps and swipes in the repro steps tab happened in TestViewController, which is unintuitive, since it's just an overlay on top of the rest.

### Instabug integration code
Does not apply.

### SDK Version
10.5.1

### iOS Version
Does not apply.

### Device Model
Does not apply.

**Comment by Kmohamed** [comment]
Hi @kaiengelhardt 
So sorry for being late. I am interesting to know your use-case. you are you adding this `PassthroughView`?
