### ISSUE TITLE
Crash of the application while having another UIScene opened at the same time

### ISSUE THREAD

**Issue by pytouzain** [Instabug/Instabug-iOS#426]
### Steps to Reproduce the Problem
Having the Carplay App (or maybe just another UIScene) opened at the same time as the App on the phone, open on the phone a view controller that is presented 

### Expected Behavior
The view controller is opened without issues

### Actual Behavior
The app crash at the end of the presentation

### Additional Infos
It appears that the swizzling of the method viewDidAppear occurs a series of call leading to the crash, which is why I'm reporting this issue
Something to be noted is that if I disable Instabug (which is done anyway for our Prod Builds), I dont have the crash at all
(I just have to disable the call `Instabug.start(withToken:)`)

### SDK Version
10.5.2

### iOS Version
14.2

### Device Model
iPhone 12 Pro (Simulator)

### Crashlog
![Screenshot 2021-06-11 at 14 35 08](https://user-images.githubusercontent.com/2435819/121687199-5dbbff80-cac2-11eb-8e98-d28c199de42d.png)

**Comment by husseinkishk** [comment]
Hi @pytouzain 
We received this issue, it's fixed and will be included in our next release next week.

**Comment by pytouzain** [comment]
Hi @husseinkishk,
Awesome to hear, well play to you and your team ! 😄
