### ISSUE TITLE
Upload script uses ping, which is not always supported

### ISSUE THREAD

**Issue by davecrumbacher** [Instabug/Instabug-iOS#43]
In your upload script you are using ping to determine if the API is available:

https://github.com/Instabug/Instabug-iOS/blob/master/Instabug.bundle/Instabug_dsym_upload.sh#L46

Ping is not supported on all networks, including mine, so I had to fork the code and use a different approach.  I submitted a pull request that changes this check to use curl instead of ping:

https://github.com/Instabug/Instabug-iOS/pull/34

This approach will also be a better indicator of whether the API service is actually running rather than ping, which is doing a check at a lower level on the network stack.

**Comment by msoliman** [comment]
@davecrumbacher thanks for the PR, I'll check it and add it in our next release
