### ISSUE TITLE
Undefined symbol: _OBJC_CLASS_$_IBGCrashReporting

### ISSUE THREAD

**Issue by hardeverick** [Instabug/Instabug-iOS#432]
### Steps to Reproduce the Problem

Include Instabug as a cocoapod

### Expected Behavior

Compile for simulator on an Intel Mac

### Actual Behavior

Compiling for simulator yields the following error:

```
ld: warning: ignoring file Pods/Instabug/Instabug.xcframework/ios-arm64_armv7/Instabug.framework/Instabug, missing required architecture x86_64 in file Pods/Instabug/Instabug.xcframework/ios-arm64_armv7/Instabug.framework/Instabug (2 slices)
ld: warning: Could not find or use auto-linked framework 'Firebase'
ld: warning: Could not find or use auto-linked framework 'FBLPromises'
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_IBGCrashReporting", referenced from:
      objc-class-ref in HARAppDelegate.o
  "_OBJC_CLASS_$_IBGBugReporting", referenced from:
      objc-class-ref in HARAppDelegate.o
      objc-class-ref in HARSupportViewController.o
  "_OBJC_CLASS_$_Instabug", referenced from:
      objc-class-ref in HARAppDelegate.o
      objc-class-ref in HARSupportViewController.o
      objc-class-ref in HARAppHelper.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

### Instabug integration code

Used cocoapods

### SDK Version

Instabug 10.7.4
Xcode 12.4

### iOS Version
14.4

### Device Model
iOS Simulator 14.4

### Comments

I've seen other people have a similar issue, specifically issue #399 where @yousefhamza points out that Xcode is looking for the iOS Simulator slice in the iOS Device framework. What setting do I need to change to make Xcode look for the x86_64 slice in the correct place?

**Comment by ahmedsalah196** [comment]
What version of cocoapods are you using?
Can you make sure it’s >= 1.10 if that’s not the case

**Comment by hardeverick** [comment]
Cocoapod v1.10.1

**Comment by ahmedsalah196** [comment]
May you send a sample project?

**Comment by hardeverick** [comment]
I haven't been able to reproduce the issue in a clean sample project and I'm not able to share the original project. But I can share the build settings which is where I think the problem is.

[buildSettings.txt](https://github.com/Instabug/Instabug-iOS/files/6804237/buildSettings.txt)

Thanks for your help

**Comment by hardeverick** [comment]
I've further narrowed down the issue to an invalid path being added to the final `clang` command. If you see in the command below the path **-FPods/Instabug/Instabug.xcframework/ios-arm64_armv7** is being added even though this is a simulator build. I'm not sure what setting is causing this path to be added. 

> ```/Applications/Xcode\ 12.4.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -target x86_64-apple-ios12.1-simulator -isysroot /Applications/Xcode\ 12.4.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.4.sdk -L/Users/erick/Library/Developer/Xcode/DerivedData/HAR-fwqlekvkaskeaicfqkooobhtufmp/Build/Products/Debug-iphonesimulator -F/Users/erick/Library/Developer/Xcode/DerivedData/HAR-fwqlekvkaskeaicfqkooobhtufmp/Build/Products/Debug-iphonesimulator -F. -FAuth0 -FHAR -FHAR\ Tests -FHAR\ UITests -FHAR.xcworkspace -FPods -FSlideInPresentationAnimator -FUniversal_Links -Fscripts -FHAR/API -FHAR/Categories -FHAR/Controllers -FHAR/Extensions -FHAR/Fonts -FHAR/HAR.xcdatamodeld -FHAR/Helpers -FHAR/JSON -FHAR/Models -FHAR/Plists -FHAR/Protocols -FHAR/Redesign-v4 -FHAR/Resources -FHAR/Storyboards -FHAR/Views -FHAR.xcworkspace/xcshareddata -FHAR.xcworkspace/xcuserdata -FPods/AlignedCollectionViewFlowLayout -FPods/Auth0 -FPods/Headers -FPods/Instabug -FPods/JSQMessagesViewController -FPods/JSQSystemSoundPlayer -FPods/JWTDecode -FPods/Local\ Podspecs -FPods/OpenTok -FPods/SimpleKeychain -FPods/SwiftSimplify -FPods/Target\ Support\ Files -FPods/_Prebuild -FHAR/Controllers/Agent -FHAR/Controllers/Agent\ Branding -FHAR/Controllers/CMA -FHAR/Controllers/Chat -FHAR/Controllers/DrivingMode -FHAR/Controllers/Edit\ MLS -FHAR/Controllers/Favorites -FHAR/Controllers/Home\ Values -FHAR/Controllers/Live -FHAR/Controllers/Login -FHAR/Controllers/Multiple\ Selection -FHAR/Controllers/My\ Listings -FHAR/Controllers/Notification\ Center -FHAR/Controllers/QR\ Code -FHAR/Controllers/Refine -FHAR/Controllers/Search -FHAR/Controllers/Tablet -FHAR/Controllers/Tutorials -FHAR/Controllers/Virtual\ Showings -FHAR/HAR.xcdatamodeld/HAR\ 2.xcdatamodel -FHAR/HAR.xcdatamodeld/HAR\ 3.xcdatamodel -FHAR/HAR.xcdatamodeld/HAR\ 4.xcdatamodel -FHAR/HAR.xcdatamodeld/HAR\ 5.xcdatamodel -FHAR/HAR.xcdatamodeld/HAR\ 6.xcdatamodel -FHAR/HAR.xcdatamodeld/HAR\ 7.xcdatamodel -FHAR/HAR.xcdatamodeld/HAR.xcdatamodel -FHAR/Models/Agent -FHAR/Models/Agent\ Branding -FHAR/Models/Archive\ Report -FHAR/Models/Broker -FHAR/Models/CMA -FHAR/Models/Chat -FHAR/Models/Collection\ View\ Layouts -FHAR/Models/DrivingMode -FHAR/Models/Listing\ Details -FHAR/Models/Login -FHAR/Models/Map -FHAR/Models/Neighborhoods -FHAR/Models/Notification\ Center -FHAR/Models/Quick\ Search -FHAR/Models/Realtor -FHAR/Redesign-v4/API -FHAR/Redesign-v4/Controllers -FHAR/Redesign-v4/Enums -FHAR/Redesign-v4/Extensions -FHAR/Redesign-v4/Helpers -FHAR/Redesign-v4/Models -FHAR/Redesign-v4/Protocols -FHAR/Redesign-v4/Views -FHAR/Views/Agent\ Branding -FHAR/Views/Agent\ Broker\ Info -FHAR/Views/Agent\ Details -FHAR/Views/Archive\ Report -FHAR/Views/CMA -FHAR/Views/Chat -FHAR/Views/DrivingMode -FHAR/Views/Edit\ MLS -FHAR/Views/Email\ Agent -FHAR/Views/Favorites -FHAR/Views/Find\ a\ Pro -FHAR/Views/Home -FHAR/Views/Labels -FHAR/Views/Loading -FHAR/Views/Login -FHAR/Views/MLS\ Subscriber\ Info -FHAR/Views/Map -FHAR/Views/Members\ Only\ Portal -FHAR/Views/Multiple\ Selection -FHAR/Views/My\ Leads -FHAR/Views/My\ Listings -FHAR/Views/Notifications -FHAR/Views/Open\ House -FHAR/Views/Property\ Tax -FHAR/Views/Refine -FHAR/Views/Search\ Bars -FHAR/Views/Search\ Settings -FHAR/Views/Similar\ Listings -FHAR/Views/Sold\ Info -FHAR/Views/Success -FHAR/Views/Tablet -FHAR.xcworkspace/xcuserdata/erick.xcuserdatad -FPods/AlignedCollectionViewFlowLayout/AlignedCollectionViewFlowLayout -FPods/Auth0/Auth0 -FPods/Headers/Private -FPods/Headers/Public -FPods/Instabug/Instabug.xcframework -FPods/JSQMessagesViewController/JSQMessagesViewController -FPods/JSQSystemSoundPlayer/JSQSystemSoundPlayer -FPods/JWTDecode/JWTDecode -FPods/SimpleKeychain/SimpleKeychain -FPods/SwiftSimplify/Pod -FPods/Target\ Support\ Files/AlignedCollectionViewFlowLayout -FPods/Target\ Support\ Files/Auth0 -FPods/Target\ Support\ Files/Instabug -FPods/Target\ Support\ Files/JSQMessagesViewController -FPods/Target\ Support\ Files/JSQSystemSoundPlayer -FPods/Target\ Support\ Files/JWTDecode -FPods/Target\ Support\ Files/OpenTok -FPods/Target\ Support\ Files/Pods-HAR -FPods/Target\ Support\ Files/Pods-HAR\ Tests -FPods/Target\ Support\ Files/Pods-HAR\ UITests -FPods/Target\ Support\ Files/SimpleKeychain -FPods/Target\ Support\ Files/SwiftSimplify -FPods/_Prebuild/GeneratedFrameworks -FHAR/Controllers/Agent\ Branding/Client -FHAR/Controllers/Edit\ MLS/Status -FHAR/Controllers/Live/Cell -FHAR/Controllers/Live/Helpers -FHAR/Controllers/Live/Models -FHAR/Controllers/Live/Protocols -FHAR/Controllers/Live/Views -FHAR/Controllers/Login/Non-MLS -FHAR/Redesign-v4/Controllers/Agent -FHAR/Redesign-v4/Controllers/Branded\ App -FHAR/Redesign-v4/Controllers/CMA -FHAR/Redesign-v4/Controllers/Common -FHAR/Redesign-v4/Controllers/Explore -FHAR/Redesign-v4/Controllers/Favorites -FHAR/Redesign-v4/Controllers/Listing\ Details -FHAR/Redesign-v4/Controllers/Login -FHAR/Redesign-v4/Controllers/Menu -FHAR/Redesign-v4/Controllers/More -FHAR/Redesign-v4/Controllers/My\ Leads -FHAR/Redesign-v4/Controllers/Notifications -FHAR/Redesign-v4/Controllers/Onboarding -FHAR/Redesign-v4/Controllers/Photo\ Gallery -FHAR/Redesign-v4/Controllers/Presentation -FHAR/Redesign-v4/Controllers/Search -FHAR/Redesign-v4/Controllers/Tax\ Record -FHAR/Redesign-v4/Models/Collection\ View\ Layouts -FHAR/Redesign-v4/Models/Filters -FHAR/Redesign-v4/Views/Annotations -FHAR/Redesign-v4/Views/Cells -FHAR/Redesign-v4/Views/Onboarding -FHAR/Views/Tablet/Account\ Settings -FHAR/Views/Tablet/Grid -FHAR.xcworkspace/xcuserdata/erick.xcuserdatad/xcdebugger -FPods/AlignedCollectionViewFlowLayout/AlignedCollectionViewFlowLayout/Classes -FPods/Auth0/Auth0/ObjectiveC -FPods/Instabug/Instabug.xcframework/ios-arm64_armv7 -FPods/Instabug/Instabug.xcframework/ios-arm64_i386_x86_64-simulator -FPods/JSQMessagesViewController/JSQMessagesViewController/Assets -FPods/JSQMessagesViewController/JSQMessagesViewController/Categories -FPods/JSQMessagesViewController/JSQMessagesViewController/Controllers -FPods/JSQMessagesViewController/JSQMessagesViewController/Factories -FPods/JSQMessagesViewController/JSQMessagesViewController/Layout -FPods/JSQMessagesViewController/JSQMessagesViewController/Model -FPods/JSQMessagesViewController/JSQMessagesViewController/Views -FPods/JSQSystemSoundPlayer/JSQSystemSoundPlayer/Classes -FPods/SwiftSimplify/Pod/Classes -FPods/_Prebuild/GeneratedFrameworks/Auth0 -FPods/_Prebuild/GeneratedFrameworks/JSQMessagesViewController -FPods/_Prebuild/GeneratedFrameworks/JSQSystemSoundPlayer -FPods/_Prebuild/GeneratedFrameworks/JWTDecode -FPods/_Prebuild/GeneratedFrameworks/OpenTok -FPods/_Prebuild/GeneratedFrameworks/SimpleKeychain -FPods/_Prebuild/GeneratedFrameworks/SwiftSimplify -FHAR/Controllers/Live/Helpers/Tokbox -FHAR/Redesign-v4/Controllers/Search/Annotations -FHAR/Redesign-v4/Controllers/Search/Filters -FHAR/Redesign-v4/Views/Cells/Filter -FPods/Instabug/Instabug.xcframework/ios-arm64_armv7/BCSymbolMaps -FPods/Instabug/Instabug.xcframework/ios-arm64_armv7/dSYMs -FPods/Instabug/Instabug.xcframework/ios-arm64_i386_x86_64-simulator/dSYMs -FPods/JSQMessagesViewController/JSQMessagesViewController/Assets/JSQMessagesAssets.bundle -FHAR/Redesign-v4/Controllers/Search/Filters/Panels -FPods/Instabug/Instabug.xcframework/ios-arm64_armv7/dSYMs/Instabug.framework.dSYM -FPods/Instabug/Instabug.xcframework/ios-arm64_i386_x86_64-simulator/dSYMs/Instabug.framework.dSYM -FPods/JSQMessagesViewController/JSQMessagesViewController/Assets/JSQMessagesAssets.bundle/Images -FPods/JSQMessagesViewController/JSQMessagesViewController/Assets/JSQMessagesAssets.bundle/Sounds -FPods/Instabug/Instabug.xcframework/ios-arm64_armv7/dSYMs/Instabug.framework.dSYM/Contents -FPods/Instabug/Instabug.xcframework/ios-arm64_i386_x86_64-simulator/dSYMs/Instabug.framework.dSYM/Contents -FPods/Instabug/Instabug.xcframework/ios-arm64_armv7/dSYMs/Instabug.framework.dSYM/Contents/Resources -FPods/Instabug/Instabug.xcframework/ios-arm64_i386_x86_64-simulator/dSYMs/Instabug.framework.dSYM/Contents/Resources -FPods/Instabug/Instabug.xcframework/ios-arm64_armv7/dSYMs/Instabug.framework.dSYM/Contents/Resources/DWARF -FPods/Instabug/Instabug.xcframework/ios-arm64_i386_x86_64-simulator/dSYMs/Instabug.framework.dSYM/Contents/Resources/DWARF -F/Users/erick/apps/HAR-iOS/HAR/../Vendor -F/Users/erick/Library/Developer/Xcode/DerivedData/HAR-fwqlekvkaskeaicfqkooobhtufmp/Build/Products/Debug-iphonesimulator/AlignedCollectionViewFlowLayout -F/Users/erick/Library/Developer/Xcode/DerivedData/HAR-fwqlekvkaskeaicfqkooobhtufmp/Build/Products/Debug-iphonesimulator/Auth0 -F/Users/erick/Library/Developer/Xcode/DerivedData/HAR-fwqlekvkaskeaicfqkooobhtufmp/Build/Products/Debug-iphonesimulator/JSQMessagesViewController -F/Users/erick/Library/Developer/Xcode/DerivedData/HAR-fwqlekvkaskeaicfqkooobhtufmp/Build/Products/Debug-iphonesimulator/JSQSystemSoundPlayer -F/Users/erick/Library/Developer/Xcode/DerivedData/HAR-fwqlekvkaskeaicfqkooobhtufmp/Build/Products/Debug-iphonesimulator/JWTDecode -F/Users/erick/Library/Developer/Xcode/DerivedData/HAR-fwqlekvkaskeaicfqkooobhtufmp/Build/Products/Debug-iphonesimulator/SimpleKeychain -F/Users/erick/Library/Developer/Xcode/DerivedData/HAR-fwqlekvkaskeaicfqkooobhtufmp/Build/Products/Debug-iphonesimulator/SwiftSimplify -F/Users/erick/apps/HAR-iOS/HAR/Pods/Instabug -F/Users/erick/apps/HAR-iOS/HAR/Pods/OpenTok -F/Users/erick/Library/Developer/Xcode/DerivedData/HAR-fwqlekvkaskeaicfqkooobhtufmp/Build/Products/Debug-iphonesimulator/XCFrameworkIntermediates/Instabug -F/Users/erick/apps/HAR-iOS/HAR/Pods/Instabug/ -F/Users/erick/apps/HAR-iOS/HAR/Pods/OpenTok -filelist /Users/erick/Library/Developer/Xcode/DerivedData/HAR-fwqlekvkaskeaicfqkooobhtufmp/Build/Intermediates.noindex/HAR.build/Debug-iphonesimulator/HAR.build/Objects-normal/x86_64/HAR\ Test.LinkFileList -Xlinker -rpath -Xlinker /usr/lib/swift -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks -Xlinker -rpath -Xlinker @executable_path/Frameworks -dead_strip -Xlinker -object_path_lto -Xlinker /Users/erick/Library/Developer/Xcode/DerivedData/HAR-fwqlekvkaskeaicfqkooobhtufmp/Build/Intermediates.noindex/HAR.build/Debug-iphonesimulator/HAR.build/Objects-normal/x86_64/HAR\ Test_lto.o -Xlinker -export_dynamic -Xlinker -no_deduplicate -Xlinker -objc_abi_version -Xlinker 2 -fobjc-arc -fobjc-link-runtime -L/Applications/Xcode\ 12.4.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphonesimulator -L/usr/lib/swift -Xlinker -add_ast_path -Xlinker /Users/erick/Library/Developer/Xcode/DerivedData/HAR-fwqlekvkaskeaicfqkooobhtufmp/Build/Intermediates.noindex/HAR.build/Debug-iphonesimulator/HAR.build/Objects-normal/x86_64/HAR.swiftmodule -ObjC -lc++ -lz -framework AVFoundation -framework AlignedCollectionViewFlowLayout -framework AudioToolbox -framework Auth0 -framework CoreData -framework CoreFoundation -framework CoreGraphics -framework CoreLocation -framework CoreMedia -framework CoreMotion -framework CoreTelephony -framework CoreVideo -framework Foundation -framework GLKit -framework Instabug -framework JSQMessagesViewController -framework JSQSystemSoundPlayer -framework JWTDecode -framework LocalAuthentication -framework MapKit -framework OpenGLES -framework OpenTok -framework QuartzCore -framework SafariServices -framework SimpleKeychain -framework SwiftSimplify -framework SystemConfiguration -framework UIKit -framework VideoToolbox -weak_framework AuthenticationServices -ObjC -Xlinker -sectcreate -Xlinker __TEXT -Xlinker __entitlements -Xlinker /Users/erick/Library/Developer/Xcode/DerivedData/HAR-fwqlekvkaskeaicfqkooobhtufmp/Build/Intermediates.noindex/HAR.build/Debug-iphonesimulator/HAR.build/HAR\ Test.app-Simulated.xcent -framework FirebaseCrashlytics -framework FirebaseDynamicLinks -weak_framework Speech -framework FirebaseInstanceID -framework WebKit -weak_framework UserNotifications -framework MediaPlayer -framework Realm -framework Social -framework Accounts -lsqlite3 -lz -framework CoreMedia -framework AssetsLibrary -framework EventKit -framework FirebaseMessaging -framework AWSCore -framework SDWebImage -framework PromisesObjC -framework GoogleAppMeasurement -framework AWSS3 -framework FloatingPanel -framework EventKitUI -framework TagListView -framework JLRoutes -framework AdSupport -framework StoreKit -framework FIRAnalyticsConnector -framework CoreFoundation -framework GLKit -framework OpenGLES -framework AudioToolbox -framework TPKeyboardAvoidingKit -framework AVFoundation -framework CoreTelephony -framework GoogleUtilities -framework XLPagerTabStrip -framework FirebaseInstallations -framework RealmSwift -framework CoreMotion -framework Security -framework Twitter -framework SVProgressHUD -framework QuartzCore -framework GoogleMobileAds -framework CFNetwork -framework CoreText -framework MessageUI -framework MobileCoreServices -framework FirebaseAnalytics -framework nanopb -framework SystemConfiguration -framework Alamofire -framework CoreLocation -framework MapKit -framework CoreGraphics -framework UserMessagingPlatform -framework GoogleDataTransport -framework FirebaseCoreDiagnostics -framework AlamofireImage -framework SwiftHash -framework UIKit -framework FirebaseCore -framework YouTubeiOSPlayerHelper -framework Protobuf -framework Foundation -framework Pods_HAR -Xlinker -no_adhoc_codesign -Xlinker -dependency_info -Xlinker /Users/erick/Library/Developer/Xcode/DerivedData/HAR-fwqlekvkaskeaicfqkooobhtufmp/Build/Intermediates.noindex/HAR.build/Debug-iphonesimulator/HAR.build/Objects-normal/x86_64/HAR\ Test_dependency_info.dat -o /Users/erick/Library/Developer/Xcode/DerivedData/HAR-fwqlekvkaskeaicfqkooobhtufmp/Build/Products/Debug-iphonesimulator/HAR\ Test.app/HAR\ Test ```

**Comment by ahmedsalah196** [comment]
It’s showing it’s building for real device not simulator here `EFFECTIVE_PLATFORM_NAME = -iphoneos`

**Comment by hardeverick** [comment]
@ahmedsalah196 that might've been because I got the settings from the command line and it defaulted to that.

We figured out the setting that was causing the issue. The framework search path had a recursive entry that was causing all subdirectories to be included, even the `arm64` one which was not needed. The error message didn't help to pinpoint the issue. Thanks for your help.
