### ISSUE TITLE
Xcode 13 Instabug navigation bar has white background in dark mode. 

### ISSUE THREAD

**Issue by Anhtastic** [Instabug/Instabug-iOS#437]
Please see the image attached. This is an issue with Xcode 13. It appears Apple has changed the way navigation bar works and it's forcing the background color to be set, otherwise it looks like the image below. 

![2021102003322915394050](https://user-images.githubusercontent.com/4810274/138331996-af4e4a92-d4c3-4106-ab7f-7ed245e0c7a1.jpg)
.

**Comment by Anhtastic** [comment]
Sorry, I've been busy working on a project. I'll try to work on this next week. Thanks.

**Comment by HassanElDesouky** [comment]
Sure, take your time! :)

**Comment by Anhtastic** [comment]
@HassanElDesouky In order for me to create a sample app, I need an app token. Can you provide one for me or should I create a free 14 days free trial for this token? Thanks.

Anh.

**Comment by Anhtastic** [comment]
Hello @HassanElDesouky , link to the example app https://drive.google.com/drive/folders/1-VDAqrO7WcBiEEJfTUpU2dbIH_6BU9Qe?usp=sharing

 Specifically this part of the code is the cause of the issue: 

`let appearance = UINavigationBarAppearance()`
`appearance.configureWithOpaqueBackground()`
`UINavigationBar.appearance().standardAppearance = appearance`
`UINavigationBar.appearance().scrollEdgeAppearance = appearance`

We recently added that code because of this: https://stackoverflow.com/questions/69111478/ios-15-navigation-bar-transparent

**Comment by HassanElDesouky** [comment]
@Anhtastic Thank you so much for your help! I'm investigating this and will come back to you as soon as possible.

**Comment by HassanElDesouky** [comment]
@Anhtastic Here's the custom build. Please, let me know how it goes. :) https://drive.google.com/file/d/18STF6-8UfMRjdrX3c0sXKvOiIvXA188e/view?usp=sharing

**Comment by Anhtastic** [comment]
Hi @HassanElDesouky , 

I've tested with our app and it works great. Thank you sir!

Anh.

**Comment by HassanElDesouky** [comment]
Glad that it worked! Thank you so much for your help @Anhtastic.
