### ISSUE TITLE
Main thread stalls during initialization of Instabug after launching after a crash

### ISSUE THREAD

**Issue by nirajignited** [Instabug/Instabug-iOS#44]
pod 'Instabug'  (updated to 4.1.10)
iOS Base SDK - 9.2
Target iOS 9.2
After launching app after a crash, the app freezes every time we try to launch it. Please see the attached  screenshots showing backtrace taken by pausing the debugger when the app was frozen. It seems on the main thread it is waiting in [IBGReachability init]  while on the com.IBG.ServerQueue thread it is waiting in [IBGServersQueue init].

<img width="535" alt="instabug-main-thread" src="https://cloud.githubusercontent.com/assets/864806/11942916/d491c3e4-a7ee-11e5-956c-83e6591c555a.png">
<img width="427" alt="intabug-ibg-serial-thread" src="https://cloud.githubusercontent.com/assets/864806/11942917/d4e9edb2-a7ee-11e5-983b-7993fd2bb312.png">

**Comment by msoliman** [comment]
@nirajignited Are you able to consistently reproduce this?
Can you replace the framework you're using with this one (https://www.dropbox.com/s/572m45jximku2sc/Instabug.framework.zip?dl=0) and let me know how it goes?

**Comment by nirajignited** [comment]
@msolinman Yes, I am able to consistently reproduce this.
The custom framework worked. Is it good to be used in production?
Thanks!

**Comment by msoliman** [comment]
@nirajignited yes you can use it. We'll be adding this fix in our next release.

**Comment by nirajignited** [comment]
that's great. Thanks
