### ISSUE TITLE
Crash on Swizzling on 10.10.0

### ISSUE THREAD

**Issue by henawey-t** [Instabug/Instabug-iOS#440]
### Steps to Reproduce the Problem
Just run the app with Instabug 10.10.0 and NewRelicAgent 6.11.0
### Expected Behavior
Works as expected
### Actual Behavior
Crash on 
```swift
*** Terminating app due to uncaught exception 'NRInvalidArgumentException', reason: 'New Relic detected an unrecognized selector, 'ibg_viewDidAppear:', sent to 'UINavigationController'. It's possible _cmd was renamed by an unsafe method_exchangeImplementations().'
```

### Instabug integration code
```swift
Instabug.start(withToken: InstabugConstants.token, invocationEvents: [.shake, .screenshot])
Instabug.showWelcomeMessage(with: EnvironmentHelper.isAlphaEnvironment() ? .beta : .disabled )
```

### SDK Version
1.10.10
### iOS Version
iOS 15.1
### Device Model
iPhone x
### [Optional] Project That Reproduces the Issue

When we called `disableMethodSwizzling()` it did works fine however, the Repro steps on the dashboard went empty
More details below: 
@Kmohamed 
We face this issue again, I just upgrade from 9.1.7 to 10.10.0, with NewRelicAgaent (6.11.0) and I just did a workaround as mentioned [here](https://discuss.newrelic.com/t/new-relic-conflicts-with-aspects-library-detected-an-unrecognized-selector/35759/3) and it did work. however, they mentioned the author of the library should fix it.
What do you think about this?

_Originally posted by @henawey-t in https://github.com/Instabug/Instabug-iOS/issues/185#issuecomment-962661196_

**Comment by HassanElDesouky** [comment]
Hi @henawey-t! Thank you for taking the time to report this. We have a fix for that and it’ll be released soon.

**Comment by henawey-t** [comment]
Great, happy to hear. please let me know once it fixed so we can update the version pn our side

**Comment by HassanElDesouky** [comment]
@henawey-t Sure! We will let you know.

**Comment by ahmedsalah196** [comment]
Hello @henawey-t,
Sorry that it took us this long to get back to you.
Anyway, the good news is that the fix is now released and you shouldn't be facing this issue any longer on the latest version. 
I'll be closing this issue but please feel free to reopen it if the issue persists. Your feedback is really valuable for us
