### ISSUE TITLE
Attachments options is not shown with V 10.10.0

### ISSUE THREAD

**Issue by meetmandar** [Instabug/Instabug-iOS#441]
BugReporting.enabledAttachmentTypes = [.galleryImage, .extraScreenShot, .screenRecording]
 BugReporting.invocationEvents = [.none]
 BugReporting.show(with: .feedback, options: [.commentFieldRequired])

With latest version attachment option is missing.
![Uploading MicrosoftTeams-image (2).png…]()

**Comment by HassanElDesouky** [comment]
Hi @meetmandar! I tried to use the integration code you provided and it looks normal at my end. Can you please clarify more what the issue exactly?
