### ISSUE TITLE
Add target x86_64-apple-ios13.0-macabi (Mac Catalyst)

### ISSUE THREAD

**Issue by jafri** [Instabug/Instabug-iOS#444]
arch: x86_64
target: x86_64-apple-ios13.0-macabi

Please add the "x86_64-apple-ios13.0-macabi" target to the list of available targets, which would enable Mac Catalyst support.

**Comment by ahmedsalah196** [comment]
Hello @jafri
Thank you for taking the time to send this but unfortunately supporting Mac Catalyst would require much more than that, we don't officially support Mac Catalyst right now, will keep you updated if we have any updates
