### ISSUE TITLE
Instabug replaces LaunchScreen

### ISSUE THREAD

**Issue by zalogatomek** [Instabug/Instabug-iOS#447]
### Steps to Reproduce the Problem
1. Launch app
2. Move app to background
3. Kill app and launch again
4. On a Launch screen, on a notched iPhone, swipe slightly home indicator (so the app is inactive for a moment)

For easier reproduction, you can add `sleep(5)` in `application: didFinishLaunchingWithOptions:` AppDeleagte's method, so the launch is long enough.

Please note, that the above steps require the app to be installed via an Xcode, however, users are reporting they saw this issue in other builds too - so other reproduction steps probably also exists.

### Expected Behavior
Nothing unusual should happen

### Actual Behavior
Launch screen gets replaced by a screenshot of the app when it was moved to background (reproduction step 2)

### Instabug integration code
None, just add Instabug to the project

### SDK Version
Latest available by manual download on 07 Feb 2022

### iOS Version
iOS 15

### Device Model
Confirmed on iPhone 8 and iPhone XR, probably any device.

### Example video - showing 4 step
White - launch screen
Orange - cached screen (last session)
Green - real first screen of the app
https://user-images.githubusercontent.com/19666393/152803087-5866d513-3aaa-4b80-9145-5958a077350e.mov

### Project That Reproduces the Issue
The sample project can be found [here](https://github.com/kolibree-git/InstabugLaunchScreen)

**Comment by ahmedsalah196** [comment]
@zalogatomek I was able to reproduce the issue using another app as using the sample app provided wasn't reproducing it on iPhone 11 & 12.

The point is that the issue is reproducible by enabling or disabling Instabug. So, I don't believe Instabug is the root cause for this issue

**Comment by zalogatomek** [comment]
@ahmedsalah196 Thank you for verifying this.
As I wrote In the report - integration with the Instabug framework was not required. It was enough to just add the framework to a project to make the issue reproducible.

Is there any chance that some code is run automatically regardless of whether Instabug is enabled or not? (for example by using `load` from Obj-C)

**Comment by ahmedsalah196** [comment]
@zalogatomek Yes, we use the `load` but it's only 1 line of code that we don't think it'll be causing this issue.
