### ISSUE TITLE
Version 10.4.4 crash

### ISSUE THREAD

**Issue by AndriiHanets** [Instabug/Instabug-iOS#449]
### Steps to Reproduce the Problem
App is crashed after calling `Instabug.start(withToken: <...>, invocationEvents: [.shake])`
App was in release for a while and worked fine. Crash stared today. No updates were added.
### Expected Behavior
App is not crashed
### Actual Behavior
App is crashed
### Instabug integration code
```
Instabug.start(withToken: <...>, invocationEvents: [.shake])
Instabug.sessionProfilerEnabled = true
Instabug.welcomeMessageMode = .disabled
```

### SDK Version
10.4.4
### iOS Version
All
### Device Model
All

**Comment by somsin** [comment]
yes we are facing same issue , our badly impacting

**Comment by AndriiHanets** [comment]
Same, app is live and thousands of people having issue

**Comment by HeshamMegid** [comment]
The issue has been fixed from our side. It may take a few minutes for the configuration that caused this to propagate. There’s no action needed from your side.

**Comment by yousefhamza** [comment]
@AndriiHanets @dltmd6262 @somsin @AndriiHanets 
The issue should be resolved now

**Comment by AndriiHanets** [comment]
@yousefhamza I confirm the problem is solved. Thanks for the quick reply.

**Comment by yousefhamza** [comment]
Thank you for the confirmation 🙏

**Comment by somsin** [comment]
thanks for the confirmation
