### ISSUE TITLE
Cocoapod install not adding header files

### ISSUE THREAD

**Issue by Vidyaranigrao** [Instabug/Instabug-iOS#451]
Hi Team,

I was trying to update Instabug version from 8.7.3 to the latest and I am having some issues with that. 
I tried with `pod 'Instabug', '10.13.0'` and it's giving me below error - 
```
[!] Error installing Instabug
[!] /usr/bin/curl -f -L -o /var/folders/ph/n039f34d45ddzhsd4gh_k6w40000gn/T/d20220401-11127-1fckhrn/file.zip https://ios-releases.instabug.com/release/10.0/archive.zip --create-dirs --netrc-optional --retry 2 -A 'CocoaPods/1.11.3 cocoapods-downloader/1.4.0'
```
I also tried with `pod 'Instabug', :git => 'https://github.com/Instabug/Instabug-iOS.git'`. In this case installation was successful but it didn't generate any header files and also the target for Instabug was not created in Pods project. I have attached screenshots for reference. Could you please guide me on how do I fix this?

<img width="208" alt="Screen Shot 2022-04-01 at 11 40 00 am" src="https://user-images.githubusercontent.com/56629984/161172531-d1670907-5201-4c50-a393-f665811163b6.png">
<img width="159" alt="Screen Shot 2022-04-01 at 11 40 21 am" src="https://user-images.githubusercontent.com/56629984/161172539-61382452-bd8f-4671-84e1-f1bd625003e9.png">

**Comment by husseinkishk** [comment]
Hi @Vidyaranigrao, Thanks for sharing this. I've tried installing our latest sdk after running `pod update` and it's working fine. Can you please clean your pods folder, make sure you have a stable connection (try using a vpn) and if the problem persists would you please reach out to us at support@instabug.com to schedule a debugging call.
