### ISSUE TITLE
Improve Instabug 9.1.x - We still require support for iOS 9

### ISSUE THREAD

**Issue by goa** [Instabug/Instabug-iOS#452]
### Steps to Reproduce the Problem
Use Instabug 9.1.7 (the latest version to support iOS 9) in an iOS project.

### Expected Behavior
We need:
1. Instabug to support iOS 9.
2. Instabug to support Apple M1.
3. Instabug warnings on newer Xcode versions to be fixed.

The last Instabug version to support iOS 9 was 9.1.7 and that does not support Apple M1. 
We also assume it is being phased out and won't be supported by the Instabug console in the coming days.

### Actual Behavior
Latest versions of Instabug do not support either of the above mentioned things.
We at least would expect a newer version of Instabug 9.x which stlil provides iOS 9.x support.

### SDK Version
9.1.7.

### iOS Version
9.x

**Comment by abdullahsalah96** [comment]
Hello @goa,

Thank you for sharing this with us, can you please elaborate more about what you mean by

> The last Instabug version to support iOS 9 was 9.1.7 and that does not support Apple M1.

I have tried integrating Instabug `9.1.7` to a project using an M1 Mac and it builds successfully.

If you're facing an error like this `projectName.xcodeproj The linked framework 'Pods_projectName.framework' is missing one or more architectures required by this target: arm64.`, Try any of these solutions that should fix it:

1. Open Xcode using Rosetta as follows:
- Quit Xcode
- Open Finder -> Applications -> Right Click on Xcode -> Get Info
- Check Open using Rosetta
- Re-launch Xcode and build your app again

2. Add arm64 in the Excluded Architectures as explained in this [thread](https://developer.apple.com/forums/thread/660782)

I hope this helps 🙏
