### ISSUE TITLE
Rejection after Appstore submission

### ISSUE THREAD

**Issue by mohadel92** [Instabug/Instabug-iOS#453]
After using of instabug package in my app
apple has refused my app twice
```
Guideline 4.0 - Design



We noticed that your app offers a custom screenshot-initiated interface when the user takes a screenshot in the app.

Next Steps

To resolve this issue, please ensure your app only displays the iOS system-provided screenshot interface. 

The iOS Human Interface Guidelines include more details about [screenshot best practices](https://developer.apple.com/ios/human-interface-guidelines/system-capabilities/screenshots/).

Please see attached screenshot for details.
```
### SDK Version
latest 

### Flutter, iOS and Android Versions
iOS 15 flutter 2.5.1

**Comment by mohadel92** [comment]
@AliAbdelfattah  its this issue closed?

**Comment by HassanElDesouky** [comment]
Hi @mohadel92,

The rejection happened because screenshot invocation wasn't meant to be used on production builds I.e. (App Store). Therefore, please note that enabling this invocation event may get your app to be rejected from the store. [For more information check out this warning on our docs](https://docs.instabug.com/docs/ios-invocation#invocation-events).

**Comment by mohadel92** [comment]
Then how to prevent this behavior

**Comment by ahmedsalah196** [comment]
Hello @mohadel92,
You need to remove the screenshot from Instabug's invocation events when releasing

**Comment by ahmedsalah196** [comment]
@mohadel92 
A sample of what you need to do, would be something like this
`if (kReleaseMode) {
      Instabug.start('TOKEN', [InvocationEvent.shake]);
    } else {
      Instabug.start('TOKEN', [InvocationEvent.screenshot, InvocationEvent.shake]);
    }`

Please feel free to reopen the ticket if the issue persists.

**Comment by yousefhamza** [comment]
We are very sorry to hear that, but we are still very excited to help you with any integration issues, please do not hesitate to get in contact with us.

**Comment by mohadel92** [comment]
His attitude is not accepted , we have discarded the usage of instabug due to lack of support
Thanks we don't feel interested with such poorly supported plug-in
