### ISSUE TITLE
App crashes PLCrashMachExceptionServer.m line 683

### ISSUE THREAD

**Issue by Mohsenkhodadadzadehthelist** [Instabug/Instabug-iOS#455]
Hi,
we got a crash with the instabug SDK on our live version

(it seems the app crashed on PLCrashMachExceptionServer.m:683)

### CrashLytics detail:
```
Thread
0  libsystem_kernel.dylib         0x14a0 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x1ae4 mach_msg + 76
2  Instabug                       0x2ffea8 exception_server_thread + 683 (PLCrashMachExceptionServer.m:683)
3  libsystem_pthread.dylib        0x19ac _pthread_start + 148
4  libsystem_pthread.dylib        0xe68 thread_start + 8
```

### SDK Version
'Instabug', '10.11.8'

### Device Info
Device Model:iPhone XS Max
Orientation: Face Up
RAM free: 118.95 MB
Disk free: 138.15 GB
Operating system Version: 15.5.0
Orientation: Portrait
Jailbroken:No

**Comment by HassanElDesouky** [comment]
Hi @Mohsenkhodadadzadehthelist,

It’s not the thread responsible for the crash as it’s not marked as crashed thread. This thread is always running to listen for any crash.

**Comment by Mohsenkhodadadzadehthelist** [comment]
Hi @HassanElDesouky, I got it, I had to check the other threads, thanks.
