### ISSUE TITLE
Status Bar Style doesn't change while Instabug w/ Floating Button is on

### ISSUE THREAD

**Issue by kwstasna** [Instabug/Instabug-iOS#456]
### Steps to Reproduce the Problem
Following this Apple Developer Guide [here](https://developer.apple.com/documentation/technotes/tn3105-customizing-uistatusbar-syle) Section: **Set a style for each view controller**

Run the project **without** Instabug -> Working as expected.

Run the project **with** Instabug -> Status Bar Bug detected.

### Expected Behavior

I would expect the status bar style to change reflecting my preferences.

### Actual Behavior

Changing the Status Bar Style doesn't affect our preferences, but it remains `.blackContent`

### Instabug integration code

        Instabug.start(
            withToken: betaToken,
            invocationEvents: [.floatingButton]
        )
        Instabug.reproStepsMode = .enable

### SDK Version
Instabug (11.0.3)

### iOS Version
15.2

### Device Model
Simulator && Device

### Project That Reproduces the Issue

https://github.com/kwstasna/StatusBarInstabugBug

**Comment by KerollosNabil** [comment]
@kwstasna we have figured out the bug and we are working on fixing it and will notify you once we fix it 
and thank you for your helpful contribution to finding the bug

**Comment by KerollosNabil** [comment]
@kwstasna  we are sorry for the late and we thank you for your contribution 
here is a custom build that have the fix for this issue
`pod 'Instabug', :podspec => 'https://ios-releases.instabug.com/custom/fix-statusBar_prefered_theme_bug/Instabug.podspec'`

**Comment by kwstasna** [comment]
Thanks a lot for this one, is there by any chance any ETA for this to be merged in the newest version ? We are not so fun of specific branches 😁

**Comment by KerollosNabil** [comment]
@kwstasna let me check with the team and get back to you

**Comment by EyadHeikal** [comment]
@kwstasna This will be merged into the next version to be released on September 4th.
