### ISSUE TITLE
IBGWelcomeMessageModeDisabled Not Working

### ISSUE THREAD

**Issue by bdaz** [Instabug/Instabug-iOS#457]
### Steps to Reproduce the Problem
1. Set `welcomeMessageMode` to `IBGWelcomeMessageModeDisabled`
2. Start Instabug with `startWithToken::`

### Expected Behavior
No Instabug welcome message appears

### Actual Behavior
A welcome message appears approximately after 10 seconds during the user's first session.

### Instabug integration code
```
Instabug.tintColor = [UIColor blackColor];
    Instabug.trackUserSteps = NO;
    Instabug.welcomeMessageMode = IBGWelcomeMessageModeDisabled;
    Instabug.reproStepsMode = IBGUserStepsModeDisable;
    IBGCrashReporting.enabled = NO;
    
    [Instabug startWithToken:XYZ invocationEvents:IBGInvocationEventShake];
```

### SDK Version
10.11.9

### iOS Version
15.6.x, 16.x

### Device Model
iPhone 13 Pro

**Comment by EyadHeikal** [comment]
Hello @bdaz 
Instabug integration should start with a call to startWithToken method and any configuration code should come after it. 
`
    [Instabug startWithToken:@"Token" invocationEvents:IBGInvocationEventShake];
    Instabug.tintColor = [UIColor blackColor];
    Instabug.trackUserSteps = NO;
    Instabug.welcomeMessageMode = IBGWelcomeMessageModeDisabled;
    Instabug.reproStepsMode = IBGUserStepsModeDisable;
    IBGCrashReporting.enabled = NO;
`
Hope this was helpful.

**Comment by bdaz** [comment]
@EyadHeikal Thanks. This is probably worth documenting on the API reference. I would expect it to work regardless of the order otherwise.

(For what it's worth, the reason I was guessed it might need to be done prior to initialization was the fact, documented [here](https://docs.instabug.com/docs/ios-disabling-enabling-crash-reporting)  that Crash Reporting needs to be set to disabled prior to initialization. I assumed all other configuration followed the same rule.)
