### ISSUE TITLE
Crash on application close - InstabugUserDefaults.ibg_secureSetObject(_:forKey:)

### ISSUE THREAD

**Issue by MattRapchat** [Instabug/Instabug-iOS#458]
### Steps to Reproduce the Problem
Seemingly, instabug is causing a crash while our app is closing.

Stacktrace from project organizer crash report (1298 devices reporting crash with 99% iPhone)
<img width="694" alt="Screen Shot 2022-09-12 at 10 00 04 AM" src="https://user-images.githubusercontent.com/84141572/189687800-b08391da-c3a6-486b-ba26-d6df714be7a7.png">

Stack Trace from firebase (only 9 events and they were all iPad showed up here):
<img width="831" alt="Screen Shot 2022-09-12 at 9 57 44 AM" src="https://user-images.githubusercontent.com/84141572/189687512-9ab168cf-dfb8-417e-be52-4f1e120163b8.png">

### Expected Behavior
Application will close without causing a crash.

### Actual Behavior
Application crashes while closing.

### Instabug integration code
*Make sure to remove your app token.*

Called in app delegate's didFinishLaunchingWithOptions:
`[Instabug startWithToken:@"<TOKEN-REMOVED>" invocationEvents:IBGInvocationEventShake];`
`[Instabug setColorTheme:IBGColorThemeDark];`

### SDK Version
11.2.0

### iOS Version
Various versions (we support >= iOS 14)

### Device Model
Various

**Comment by EyadHeikal** [comment]
This is a duplicate of this [One-Signal-SDK issue](https://github.com/OneSignal/OneSignal-iOS-SDK/issues/1116)
