### ISSUE TITLE
Instabug invoke from ActionSheet causes crash

### ISSUE THREAD

**Issue by YBthebest** [Instabug/Instabug-iOS#46]
```
-(void)actionSheet:(UIActionSheet *)actionSheet clickedButtonAtIndex:(NSInteger)buttonIndex{
    if(buttonIndex == 1){
        [Instabug invoke];
    }
}
```

With this simple code, what happens is that the Instabug menu is displayed above the existing ActionSheet (which doesn't have enough time to dismiss), and whenever I quit instabug (click on cancel or submit a bug for instance), the app crashes. I can use Instabug all I want, but whenever I dismiss it, it crashes.

Any way to prevent this?

**Comment by YBthebest** [comment]
A temporary fix is to do this:
```
        dispatch_after(dispatch_time(DISPATCH_TIME_NOW, 0.5 * NSEC_PER_SEC), dispatch_get_main_queue(), ^{
            [Instabug invoke];
        });
```

But I think another solution must be found!

**Comment by msoliman** [comment]
@YBthebest maybe you can try to use `[Instabug invokeFeedbackSender]` or `[Instabug invokeBugReporter]` instead?
This won't show the action sheet and will go directly to the reporting screen.

**Comment by YBthebest** [comment]
Same error happening. Have you tried it?

**Comment by msoliman** [comment]
@YBthebest That's weird, it's working fine for me. Can you please send me the crash that you get?

**Comment by YBthebest** [comment]
That's the weird part: I get no crash at all. It just completely freezes my app.

**Comment by msoliman** [comment]
@YBthebest can you check it in the latest version 5.0.2? Please re-open it if you can still reproduce this.
