### ISSUE TITLE
Network logs are missing when logging is enabled for Custom URLSessionConfiguration

### ISSUE THREAD

**Issue by nsinghInfogain** [Instabug/Instabug-iOS#463]
### Steps to Reproduce the Problem
Use both the custom URLsessionConfiguration and the default URLSession for making the request , at times the network logs are not appearing on the dashboard

### Expected Behavior
All the network requests must be listed 

### Actual Behavior
Network logs are going missing

### Instabug integration code
 urlSessionConfig = URLSessionConfiguration.ephemeral
        urlSessionConfig.timeoutIntervalForRequest = 60 * 4
        NetworkLogger.enableLogging(for: urlSessionConfig)

### SDK Version
'Instabug', '11.4.1'

### iOS Version
iOS 15.5

### Device Model
iPhone 13 Pro

**Comment by EyadHeikal** [comment]
Hi @nsinghInfogain ,

**Comment by EyadHeikal** [comment]
Hi @nsinghInfogain, 
Are you having the same issue with other `URLSessionConfiguration`?
May you reach out to [support@instabug.com](mailto:support@instabug.com) to further investigate this?
