### ISSUE TITLE
App crashing on ios16 when app switch from Arabic language to arabic language and when you press "Report a bug"

### ISSUE THREAD

**Issue by shahbazxische** [Instabug/Instabug-iOS#464]
Fatal Exception: CALayerInvalidGeometry
CALayer position contains NaN: [nan 16.5]. Layer: <CALayer:0x282523960; position = CGPoint (1.79769e+308 16.5); bounds = CGRect (1.79769e+308 0; 0 17); delegate = <_UITextLayoutFragmentView: 0x121c09260; frame = (1.79769e+308 8; 0 17); opaque = NO; layer = <CALayer: 0x282523960>>; needsDisplayOnBoundsChange = YES; allowsGroupOpacity = YES; contentsScale = 3; rasterizationScale = 3; >

Fatal Exception: CALayerInvalidGeometry
0  CoreFoundation                 0x9e88 __exceptionPreprocess
1  libobjc.A.dylib                0x178d8 objc_exception_throw
2  CoreFoundation                 0xf9c58 __CFDictionaryCreateGeneric
3  QuartzCore                     0x27a48 CA::Layer::set_position(CA::Vec2<double> const&, bool)
4  QuartzCore                     0xee28 -[CALayer setPosition:]
5  QuartzCore                     0xeda0 -[CALayer setFrame:]
6  UIKitCore                      0x9b9d5c -[UIView _backing_setFrame:]
7  UIKitCore                      0x4404 -[UIView(Geometry) setFrame:]
8  UIKitCore                      0x508700 -[_UITextLayoutCanvasView textViewportLayoutController:configureRenderingSurfaceForTextLayoutFragment:]
9  UIFoundation                   0xb3ff4 __48-[NSTextViewportLayoutController layoutViewport]_block_invoke_4
10 UIFoundation                   0x5f958 __80-[NSTextLayoutManager enumerateViewportElementsFromLocation:options:usingBlock:]_block_invoke
11 UIFoundation                   0x36f1c __83-[NSTextLayoutManager enumerateTextLayoutFragmentsFromLocation:options:usingBlock:]_block_invoke_2
12 CoreFoundation                 0xa3a0 __NSARRAY_IS_CALLING_OUT_TO_A_BLOCK__
13 CoreFoundation                 0x3752c -[__NSSingleObjectArrayI enumerateObjectsWithOptions:usingBlock:]
14 UIFoundation                   0x36bec __83-[NSTextLayoutManager enumerateTextLayoutFragmentsFromLocation:options:usingBlock:]_block_invoke
15 UIFoundation                   0x20360 -[NSTextLayoutManager enumerateTextLayoutFragmentsFromLocation:options:usingBlock:]
16 UIFoundation                   0x200c0 -[NSTextLayoutManager enumerateViewportElementsFromLocation:options:usingBlock:]
17 UIFoundation                   0x1fbd8 -[NSTextViewportLayoutController layoutViewport]
18 UIKitCore                      0x31564 +[UIView(Animation) performWithoutAnimation:]
19 UIKitCore                      0x8e28 -[_UITextLayoutCanvasView layoutSubviews]
20 UIKitCore                      0x5020 -[UIView(CALayerDelegate) layoutSublayersOfLayer:]
21 QuartzCore                     0x99ec CA::Layer::layout_if_needed(CA::Transaction*)
22 QuartzCore                     0x1d0a0 CA::Layer::layout_and_display_if_needed(CA::Transaction*)
23 QuartzCore                     0x2e5b0 CA::Context::commit_transaction(CA::Transaction*, double, double*)
24 QuartzCore                     0x635ec CA::Transaction::commit()
25 UIKitCore                      0x449a08 _afterCACommitHandler
26 CoreFoundation                 0x91d60 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__
27 CoreFoundation                 0x1a2d0 __CFRunLoopDoObservers
28 CoreFoundation                 0x7bc7c __CFRunLoopRun
29 CoreFoundation                 0x80ed4 CFRunLoopRunSpecific
30 GraphicsServices               0x1368 GSEventRunModal
31 UIKitCore                      0x3a23d0 -[UIApplication _run]
32 UIKitCore                      0x3a2034 UIApplicationMain
34 ???                            0x1c7df8960 (Missing)

### Instabug integration code
*Make sure to remove your app token.*

### SDK Version
11.6.0

### iOS Version
16

### Device Model
All iOS devices

**Comment by KerollosNabil** [comment]
Hi @shahbazxische 
thank you for communicating this with us

can you please clarify the steps to reproduce this crash as a list 
thank you in advance

**Comment by shahbazxische** [comment]
hi @KerollosNabil 
We have two languages(English and Arabic) in the app. We are saving the language locally and doing swizzling when user switches the app. Now when user is using app in arabic language and it is switching it to English then when user shake his/her phone and trying to press on Report a bug then app crashing and above mentioned log is appearing in the firebase.
This crash not happening when user is on English language and switches to Arabic and try to do the same scenario.
This issue only happening in ios 16 devices.
Please let me know if you need more help from my side.
Thanks

**Comment by KerollosNabil** [comment]
hi @shahbazxische 
if you are able to reproduce the crash can you reproduce it in a sample app and send it to us to investigate it more?

**Comment by KerollosNabil** [comment]
hi @shahbazxische 
if you are able to reproduce the crash can you send us a sample app that reproduces the crash to investigate it more?
