### ISSUE TITLE
Undocumented SPM support.

### ISSUE THREAD

**Issue by OMV-Sunshine** [Instabug/Instabug-iOS#466]
The README for this repository should include a "Swift Package Manager" entry in the "Installation" section that points users to https://github.com/Instabug/Instabug-SP

### Steps to Reproduce the Problem

Difficult to know that Instabug supports SPM

### Expected Behavior

Documentation on how to install Instabug using SPM easy to find.

### Actual Behavior

Only found out by looking at past github issues.

**Comment by yousefhamza** [comment]
Hi @OMV-Sunshine.

Thanks for taking the time to point that out, we will add it to our README 👍
