### ISSUE TITLE
Warnings about invalid documentation - Xcode 14.3

### ISSUE THREAD

**Issue by bdaz** [Instabug/Instabug-iOS#469]
### Steps to Reproduce the Problem
Build a project that imports the Instabug module with Xcode 14.3

### Expected Behavior
Build should succeed without errors.

### Actual Behavior
Warnings are produced, like this one:

`IBGBugReporting.h:58:9: Parameter 'didSelectPromptOptionHandler' not found in the function declaration`
`Instabug.h:102:9: Parameter 'willSendReportHandler' not found in the function declaration`
`Instabug.h:138:9: Parameter 'didDismissWelcomeMessageHandler' not found in the function declaration`

### SDK Version
11.9.1

### iOS Version
16.4

**Comment by EyadHeikal** [comment]
@bdaz 
The fix for this issue will be included in the upcoming release.
Thank you for reaching out to us.
