### ISSUE TITLE
No network logs after the report while using the Proxyman

### ISSUE THREAD

**Issue by kolyan94** [Instabug/Instabug-iOS#472]
### Steps to Reproduce the Problem
1. Setup the proxyman on your mac
2. Connect your iPhone via proxy
3. Start your app with Instabug
4. Make some requests in your app
5. Send a report via Instabug
6. Disable the Proxyman or use LTE
7. Retry 3-5 steps multiple times
### Expected Behavior
You should see the network logs or somehow reset the Instabug and see the network logs after that
### Actual Behavior
No network logs from this device. 
We tried to remove app and make a fresh install. The network logs could come back after the fresh install but when you run app next time they gone =(
### Instabug integration code
            Instabug.start(withToken: Environment.instabugToken, invocationEvents: [.shake, .screenshot])
            Instabug.welcomeMessageMode = .disabled
### SDK Version
11.10.2
### iOS Version
16.4.1 - latest
### Device Model
Multiple iPhones (iOS 16.3+)

**Comment by ahmedsalah196** [comment]
Hello @kolyan94 
Sorry for the late reply. Can I ask you to clarify what exactly that you expect to see but it's not showing? The network logs for Instabug or network logs from your app?

**Comment by ahmedsalah196** [comment]
@kolyan94 If you're not using Proxyman the logs are showing normally? If yes, can you make sure that the network requests are actually successful when connecting to Proxyman?

**Comment by kolyan94** [comment]
@ahmedsalah196 No, you could try it. Use proxyman once - no logs forever. I tried to reinstall the app/reboot the phone, but nothing can't fix it. Seems you use some kind of caching from the server side.

**Comment by ahmedsalah196** [comment]
@kolyan94 Can you please reach out to us at support@instabug.com to further investigate this issue?

**Comment by kolyan94** [comment]
Sorry, I've provided steps that work for all my teammates. Please try it and send me feedback. Looks like @jserrafindster has this issue as well. I'm busy with my job and can't spend a lot of time with that =(
The issue is frash, so you could investigate your latest changes (few weeks).
