### ISSUE TITLE
App got crashed at launching time

### ISSUE THREAD

**Issue by santoso8118** [Instabug/Instabug-iOS#476]
### Steps to Reproduce the Problem
Just launch app
This issue happen sometimes in user's device and we can not reproduce it.

### Expected Behavior
App should not get crashed

### Actual Behavior
App got crashed

### Instabug integration code
   
        Instabug.start(withToken:"apptoken", invocationEvents: [.screenshot]) 
        Surveys.appStoreURL = "app link from appstore"
        BugReporting.shouldCaptureViewHierarchy = true
        BugReporting.enabledAttachmentTypes = [.extraScreenShot,.galleryImage,.screenRecording,]
        
        Instabug.setColorTheme(.light)
        Instabug.tintColor = .brandPurpleColor
        Instabug.welcomeMessageMode = IBGWelcomeMessageMode.disabled
        
        Custom values for some below keys:
        kIBGReportBugStringName
        kIBGReportBugDescriptionStringName
        kIBGReportFeedbackStringName
        kIBGReportFeedbackDescriptionStringName
        kIBGAskAQuestionStringName
        kIBGReportQuestionDescriptionStringName
        kIBGCommentFieldPlaceholderForBugReportStringName
        kIBGCommentFieldPlaceholderForFeedbackStringName
        kIBGCommentFieldPlaceholderForQuestionStringName

        BugReporting.willInvokeHandler = {
            getInstabugCustomAttribute()
        }
  

### Crashed logs
Crashed: com.apple.main-thread
0  QuartzCore                     0x4281c CA::Transaction::unlock() + 4
1  QuartzCore                     0xf754 CA::Layer::get_frame_transform(CA::Mat4<double>&, bool, CA::Mat4<double> const*) + 480
2  QuartzCore                     0xabe0 CA::Layer::map_geometry(CALayer*, CALayer*, void (*)(void*, CA::Mat4<double> const&), void (*)(void*, CA::Mat4<double> const&), void*) + 248
3  QuartzCore                     0x8cf90 -[CALayer convertRect:toLayer:] + 180
4  UIKitCore                      0xcc174 -[UIView(Geometry) convertRect:toView:] + 128
5  Instabug                       0xea534 -[UIViewController(IBGUtilities) ibg_mostVisibleChildViewController] + 420
6  Instabug                       0x11a65c -[IBGWindowState getTopViewControllerWithRootViewControllerDispatched:] + 316
7  Instabug                       0x11a404 -[IBGWindowState getTopViewControllerWithRootViewController:] + 120
8  Instabug                       0x722c8 +[IBGInspector topViewControllerInWindow:] + 284
9  Instabug                       0x19dd0 -[IBGViewController getVisibileViewController] + 64
10 Instabug                       0x1a0c8 -[IBGViewController prefersStatusBarHidden] + 104
11 Instabug                       0x1a0e0 -[IBGViewController prefersStatusBarHidden] + 128
12 Instabug                       0x1a0e0 -[IBGViewController prefersStatusBarHidden] + 128
13 Instabug                       0x1a0e0 -[IBGViewController prefersStatusBarHidden] + 128
14 Instabug                       0x1a0e0 -[IBGViewController prefersStatusBarHidden] + 128
15 Instabug                       0x1a0e0 -[IBGViewController prefersStatusBarHidden] + 128
16 Instabug                       0x1a0e0 -[IBGViewController prefersStatusBarHidden] + 128
17 Instabug                       0x1a0e0 -[IBGViewController prefersStatusBarHidden] + 128
18 Instabug                       0x1a0e0 -[IBGViewController prefersStatusBarHidden] + 128
19 Instabug                       0x1a0e0 -[IBGViewController prefersStatusBarHidden] + 128
20 Instabug                       0x1a0e0 -[IBGViewController prefersStatusBarHidden] + 128
21 Instabug                       0x1ef480 -[IBGSplitViewController prefersStatusBarHidden] + 48
22 UIKitCore                      0x3c5e8 -[UIViewController _preferredStatusBarVisibility] + 48
23 UIKitCore                      0x3c34c +[UIWindow(StatusBarManager) _prefersStatusBarHiddenInWindow:targetOrientation:animationProvider:] + 224
24 UIKitCore                      0x3c24c +[UIWindow(StatusBarManager) _prefersStatusBarHiddenInWindow:animationProvider:] + 72
25 UIKitCore                      0x3bc44 -[UIApplication _isStatusBarEffectivelyHiddenForContentOverlayInsetsForWindow:] + 132
26 UIKitCore                      0x3b89c -[UIWindow _sceneSafeAreaInsetsIncludingStatusBar:] + 220
27 UIKitCore                      0x3b54c -[UIWindow _normalizedSafeAreaInsets] + 64
28 UIKitCore                      0x3b4cc -[UIWindow safeAreaInsets] + 76
29 UIKitCore                      0xe11e0 +[UIViewController _horizontalContentMarginForView:ofWidth:] + 80
30 UIKitCore                      0xe0f84 +[UIViewController _horizontalContentMarginForView:] + 68
31 UIKitCore                      0xe0f10 -[UISplitViewControllerPanelImpl _contentMarginForChildViewController:] + 192
32 UIKitCore                      0xdf810 -[UIViewController __updateContentOverlayInsetsWithOurRect:inBoundsOfAncestorViewController:viaImmediateChildOfAncestor:] + 308
33 UIKitCore                      0x728e0 -[UIViewController _updateContentOverlayInsetsFromParentIfNecessary] + 800
34 UIKitCore                      0x3c82c -[UINavigationController _layoutViewController:] + 84
35 UIKitCore                      0x3c7d4 -[UINavigationController _layoutTopViewControllerLookForNested:] + 436
36 UIKitCore                      0x1a22ac __105-[UINavigationController _repositionPaletteWithNavigationBarHidden:duration:shouldUpdateNavigationItems:]_block_invoke + 452
37 UIKitCore                      0x174b88 -[UINavigationController _repositionPaletteWithNavigationBarHidden:duration:shouldUpdateNavigationItems:] + 328
38 UIKitCore                      0x17234c -[UINavigationController _updateBarsForCurrentInterfaceOrientationAndForceBarLayout:] + 128
39 UIKitCore                      0xe54c -[UINavigationController viewDidAppear:] + 40
40 UIKitCore                      0xcc74 -[UIViewController _setViewAppearState:isAnimating:] + 1148
41 UIKitCore                      0x7edb2c __52-[UIViewController _setViewAppearState:isAnimating:]_block_invoke_2 + 168
42 UIKitCore                      0x2457dc __52-[UIViewController _setViewAppearState:isAnimating:]_block_invoke + 192
43 CoreFoundation                 0xa1cc __NSARRAY_IS_CALLING_OUT_TO_A_BLOCK__ + 24
44 CoreFoundation                 0x376b8 -[__NSSingleObjectArrayI enumerateObjectsWithOptions:usingBlock:] + 92
45 UIKitCore                      0xcdd4 -[UIViewController _setViewAppearState:isAnimating:] + 1500
46 UIKitCore                      0x22085c -[UIViewController __viewDidAppear:] + 164
47 UIKitCore                      0x2206d8 -[UIViewController _endAppearanceTransition:] + 212
48 UIKitCore                      0x220060 __48-[UIPresentationController transitionDidFinish:]_block_invoke + 100
49 UIKitCore                      0x278260 -[UIPresentationController transitionDidFinish:] + 1100
50 UIKitCore                      0x14d72c -[_UICurrentContextPresentationController transitionDidFinish:] + 44
51 UIKitCore                      0x764a08 __56-[UIPresentationController runTransitionForCurrentState]_block_invoke.110 + 320
52 UIKitCore                      0x2b1d10 -[_UIViewControllerTransitionContext completeTransition:] + 116
53 UIKitCore                      0x2b2ea0 -[UITransitionView notifyDidCompleteTransition:] + 180
54 UIKitCore                      0x2b2aa0 -[UITransitionView _didCompleteTransition:] + 832
55 UIKitCore                      0x1060598 __UIVIEW_IS_EXECUTING_ANIMATION_COMPLETION_BLOCK__ + 36
56 UIKitCore                      0xce148 -[UIViewAnimationBlockDelegate _didEndBlockAnimation:finished:context:] + 636
57 UIKitCore                      0xcd0a4 -[UIViewAnimationState sendDelegateAnimationDidStop:finished:] + 436
58 UIKitCore                      0xcc7c0 -[UIViewAnimationState animationDidStop:finished:] + 196
59 UIKitCore                      0xcc8d4 -[UIViewAnimationState animationDidStop:finished:] + 472
60 QuartzCore                     0x134e0 CA::Layer::run_animation_callbacks(void*) + 232
61 libdispatch.dylib              0x3eac _dispatch_client_callout + 20
62 libdispatch.dylib              0x126a4 _dispatch_main_queue_drain + 928
63 libdispatch.dylib              0x122f4 _dispatch_main_queue_callback_4CF + 44
64 CoreFoundation                 0x98c28 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 16
65 CoreFoundation                 0x7a560 __CFRunLoopRun + 1992
66 CoreFoundation                 0x7f3ec CFRunLoopRunSpecific + 612
67 GraphicsServices               0x135c GSEventRunModal + 164
68 UIKitCore                      0x39cf58 -[UIApplication _run] + 888
69 UIKitCore                      0x39cbbc UIApplicationMain + 340
70 MyApp                         0x145e8 main + 45 (AppDelegate.swift:45)
71 ???                            0x1b2844dec (Missing)

### SDK Version
Instabug (11.1.0)

### iOS Version
16.6.0

### Device Model
iPhone 11 Pro

**Comment by EyadHeikal** [comment]
@santoso8118 We've implemented a fix for this issue that resolves this. Can you update to the latest SDK version?

**Comment by santoso8118** [comment]
Hi @EyadHeikal 
Thanks for your quick answer could you specify what version we should update ?
How about Instabug SDK version 11.14.0 ? Does it include the fixes for this issue ?
