### ISSUE TITLE
Method swizzling breaks Ktor data form request

### ISSUE THREAD

**Issue by tfcporciuncula** [Instabug/Instabug-iOS#477]
### Steps to Reproduce the Problem

- Clone https://github.com/tfcporciuncula/ktor-instabug
- Run the Ktor server from the project on the `ktor-sample` folder
- Update the IP address [here](https://github.com/tfcporciuncula/ktor-instabug/blob/main/shared/src/commonMain/kotlin/com/fredporciuncula/ktorinstabug/KtorClient.kt#L30) to point to the machine running the Ktor service
- Run the iOS app and tap on the “Trigger data form request” button
- Observe the app crashes with:

>REQUEST http://192.168.1.189:8080/upload failed with exception: kotlinx.coroutines.JobCancellationException: Parent job is Cancelling; job=JobImpl{Cancelled}@954f220

If we disable [method swizzling](https://docs.instabug.com/docs/swizzling), then nothing breaks when the call is made. There’s nothing special about the project other than being a Kotlin Multiplatform project using [Ktor](https://ktor.io/). Any data form call will fail like that — other requests like simple GET or POSTs won’t fail, though. I’m including a Ktor server application just to make it easier to test everything end to end, but any data form request will fail the same way (be it hosted by Ktor or anywhere else).

### Expected Behavior
No crash.

### Actual Behavior
Crash.

### Instabug integration code
It’s all [here](https://github.com/tfcporciuncula/ktor-instabug/blob/main/iosApp/iosApp/iOSApp.swift#L7-L11). The token there is from a dedicated test project with the sole purpose of reproducing this issue, so it’s all good.

```swift
// Instabug.disableMethodSwizzling() // Everything works fine when this is uncommented
Instabug.start(withToken: "", invocationEvents: .shake)
Instabug.welcomeMessageMode = .disabled // This doesn’t really affect anything
```

### SDK Version
12.1.0

### Device Model & iOS Version
iPhone 11 running iOS 16.2, iPhone 8 running iOS 16.7, iPhone 14 Pro running 17.0.3

### Project That Reproduces the Issue
https://github.com/tfcporciuncula/ktor-instabug

**Comment by EyadHeikal** [comment]
@tfcporciuncula @marcorighini  We're looking into it and will get back to you as soon as possible.

**Comment by tfcporciuncula** [comment]
I don't think this should be closed as the issue still exists.

**Comment by marcorighini** [comment]
Why is this closed @EyadHeikal ?
