### ISSUE TITLE
Add support of async-await in event handlers

### ISSUE THREAD

**Issue by ashalva** [Instabug/Instabug-iOS#480]
### Steps to Reproduce the Problem

Trying to use async-await inside `willSendReportHandler`. I have an actor which holds the information which I want to attach to the logs before user submits the report.

```swift
import Instabug

class InstabugTesting {
    private let featureProvider = SomeFeatureProvider()
    
    func setupWillSendReportObserver() {
        Instabug.willSendReportHandler = { [weak self] report in  // <-- Invalid conversion from 'async' function of type '(IBGReport) async -> IBGReport' to synchronous function type '(IBGReport) -> IBGReport'
            guard let self else { return report }
            
            let features = await self.featureProvider.features
            for feature in features {
                IBGLog.logInfo(feature)
            }
            
            return report
        }
    }
}

actor SomeFeatureProvider {
    var features: [String] = []
    
    func addFeature(_ feature: String) {
        features.append(feature)
    }
}
```

The error makes sense from current API standpoint, but having the async callbacks or any other ways support async-await calls would ease developers' lives.

### Expected Behavior

Ideally support of async-await for event handlers 🥺 

### Actual Behavior

Compiler error 👇 

<img width="700" alt="image" src="https://github.com/Instabug/Instabug-iOS/assets/9494262/e8765f82-7201-47f7-ac75-0cbd20dffa3d">

### Instabug integration code
*Make sure to remove your app token.*

### SDK Version

12.2.0

### iOS Version

Any

### Device Model

Any

### [Optional] Project That Reproduces the Issue

Reproducable with attached code snippet

**Comment by michallaskowski** [comment]
Same situation here. Either allowing to allow async operations to finish before sending a report;
or exposing an additional handler to inform that the user is starting to open a bug report, so that we can start fetching needed data and then just attach them in a synchronous `willSendReportHandler`
