### ISSUE TITLE
Network Logs not appearing when using Swift Concurrency APIs

### ISSUE THREAD

**Issue by xmollv** [Instabug/Instabug-iOS#482]
I've Integrated Instabug in a new app that's fully using Swift's Concurrency (async/await) model. I'm not being able to see the network logs being sent by my app's code (I do see the ones sent from an SDK we integrate - Socket.io). I've looked at the documentation and it states that networks logs are captured by default, but if for some reason they're not, you can enable it by passing the `URLSessionConfiguration`. I've done that and still they don't show up. Here's the code that does that:

<img width="564" alt="Screenshot 2023-12-05 at 09 13 16" src="https://github.com/Instabug/Instabug-iOS/assets/8229382/f373deb8-66e0-4a5e-8715-c41be4430395">

And on `InstabugManager`:
<img width="633" alt="Screenshot 2023-12-05 at 09 13 24" src="https://github.com/Instabug/Instabug-iOS/assets/8229382/6ec3cd74-72cb-4960-a7b8-eb38b917e7a8">

⚠️ The `DataProvider` class lives in a different module. That class is part of a local SPM package, while the code that you're seeing in the screenshots lives on the main app target. Could that be the issue? To make it clearer:

1. Instabug is integrated on the app target
2. The networking happens on a local SPM package

The funny thing is that I see some network logs, the ones coming from Socket.io, and that dependency resides on the local SPM package where my networking code works too, that's why the title talks about Swift's concurrency. I'm at a loss here, I've tried everything from the documentation and doesn't seem to work.

### Steps to Reproduce the Problem

- Have your URLSession networking code on an SPM package
- Integrate Instabug on the app target
- From the app target, create the session & configuration and inject it into the SPM package
- Perform network requests on the SPM package using async/await APIs like this:

<img width="613" alt="image" src="https://github.com/Instabug/Instabug-iOS/assets/8229382/b3a24a90-83b0-4a16-8d4e-036e91230aa6">

Generate a report and see how no network logs show on Instabug.

### Expected Behavior

Networks logs show on Instabug.

### Actual Behavior

Network logs for that session don't show on Instabug. Other network logs from other session (whatever Socket.io uses) do show up.

### Instabug integration code

<img width="989" alt="Screenshot 2023-12-05 at 09 21 49" src="https://github.com/Instabug/Instabug-iOS/assets/8229382/20e41fae-9429-4259-8a2e-b2f0d8a3fd9d">

### SDK Version
12.3.0

### iOS Version
17.1.2

### Device Model
iPhone 15 Pro

**Comment by EyadHeikal** [comment]
@xmollv Thank you for reaching out. We are aware of this and we are currently investigating how we can support it. We will get back to you with an ETA as soon as possible.

**Comment by xmollv** [comment]
> @xmollv Thank you for reaching out. We are aware of this and we are currently investigating how we can support it. We will get back to you with an ETA as soon as possible.

That's great news! For now we've been logging the requests as a cURL string on the logs, which is far from ideal. I'd love to be able to remove that workaround and use the proper network logger!

**Comment by jeannustre** [comment]
Hello @EyadHeikal, any ETA updates ? Thanks.

**Comment by xmollv** [comment]
@EyadHeikal @ahmedsalah196 any updates on this? It has become a frustrating issue on our team to not be able to inspect the request/response from the logs 😭

**Comment by EyadHeikal** [comment]
@xmollv @jeannustre  Can you use this build `pod 'Instabug', :podspec => 'https://ios-releases.instabug.com/custom/support_modern_swift_concurrency_apis/12.7.0/Instabug.podspec'` ?

**Comment by xmollv** [comment]
> @xmollv You can integrate it now using this branch `support_modern_swift_concurrency_apis_spm`. Note: You should be able to see all request data on the dashboard without the response body.

@EyadHeikal I've just tested it and seems to work as expected, I can see the network logs as I use to see on other apps that didn't use Swift's concurrency! When can we expect the change to be included in the stable release? 🙏🏼

**Comment by EyadHeikal** [comment]
@xmollv It will be included in the mid-march release

**Comment by xmollv** [comment]
> @xmollv It will be included in the mid-march release

Awesome, I'll keep an eye out. Thanks for solving it! ❤️
