### ISSUE TITLE
Crash: [InstabugScreenCapturer takeScreenshotWithAnnotator:shouldUseRenderInContext:lastTouchedPoints:shouldApplyMaskingRules:]

### ISSUE THREAD

**Issue by Patczuk** [Instabug/Instabug-iOS#486]
### Steps to Reproduce the Problem
The crash happens in various scenarios of using the application

### Expected Behavior
The App is crashing

### Actual Behavior
The App doesn't crash

### Instabug integration code

0 | CoreFoundation | __exceptionPreprocess + 164
-- | -- | --
1 | libobjc.A.dylib | objc_exception_throw + 59
2 | Foundation | -[NSAssertionHandler handleFailureInFunction:file:lineNumber:description:] + 171
3 | UIKitCore | _UIGraphicsBeginImageContextWithOptions + 567
4 | Instabug | -[InstabugScreenCapturer takeScreenshotWithAnnotator:shouldUseRenderInContext:lastTouchedPoints:shouldApplyMaskingRules:] + 303
5 | Instabug | -[IBGVisualUserStepsLogger updateVisualUserStepsTopViewWithTopViewName:eventName:canTakeScreenshot:completionHandler:] + 1819
6 | Instabug | -[IBGVisualUserStepsLogger updateTopViewWithTopViewName:topViewChanged:isValidwindow:canTakeScreenshot:eventName:completionHandler:] + 319
7 | Instabug | -[IBGUserStepsLoggingDispatcher updateTopViewWithTopViewName:topViewChanged:isValidwindow:canTakeScreenshot:eventName:] + 463
8 | Instabug | -[IBGUserStepsListener updateTopViewChangedWithViewController:] + 95
9 | Instabug | -[IBGUserStepsListener viewController:calledMethod:invocation:] + 115
10 | Instabug | __63-[IBGSwizzler newImpelementationViewArg:selector:swizzlerInfo:]_block_invoke_4 + 75
11 | CoreFoundation | __NSARRAY_IS_CALLING_OUT_TO_A_BLOCK__ + 23
12 | CoreFoundation | -[__NSArrayI_Transfer enumerateObjectsWithOptions:usingBlock:] + 283
13 | Instabug | -[NSArray(Enumerate) ibg_enumerateWithStop:] + 95
14 | Instabug | -[NSArray(Enumerate) ibg_enumerate:] + 95
15 | Instabug | __63-[IBGSwizzler newImpelementationViewArg:selector:swizzlerInfo:]_block_invoke + 275
16 | Here | NiblessViewController.viewDidAppear(_:) (NiblessViewController.swift:69)
17 | Here | @objc NiblessViewController.viewDidAppear(_:) (<compiler-generated>:0)
18 | Instabug | INSTABUG_SWIZZLER_EXECUTING_ORIGINAL_IMPLEMENTATION + 15
19 | Instabug | __63-[IBGSwizzler newImpelementationViewArg:selector:swizzlerInfo:]_block_invoke + 219
20 | UIKitCore | -[UIViewController _setViewAppearState:isAnimating:] + 1139
21 | UIKitCore | -[UIViewController __viewDidAppear:] + 163
22 | UIKitCore | __64-[UIViewController viewDidMoveToWindow:shouldAppearOrDisappear:]_block_invoke + 43
23 | UIKitCore | -[UIViewController _executeAfterAppearanceBlock] + 83
24 | UIKitCore | -[_UIAfterCACommitBlock run] + 71
25 | UIKitCore | -[_UIAfterCACommitQueue flush] + 163
26 | libdispatch.dylib | _dispatch_call_block_and_release + 31
27 | libdispatch.dylib | _dispatch_client_callout + 19
28 | libdispatch.dylib | _dispatch_main_queue_drain + 983
29 | libdispatch.dylib | _dispatch_main_queue_callback_4CF + 43
30 | CoreFoundation | __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 15
31 | CoreFoundation | __CFRunLoopRun + 1995
32 | CoreFoundation | CFRunLoopRunSpecific + 607
33 | GraphicsServices | GSEventRunModal + 163
34 | UIKitCore | -[UIApplication _run] + 887
35 | UIKitCore | UIApplicationMain + 339

### SDK Version
12.7.0

### iOS Version
17.0.3 - 17.4

### Device Model
Various models

###
Private

**Comment by AhmedAshraf605** [comment]
Hello @Patczuk 
This crash should be fixed in 13.0.0
