### ISSUE TITLE
[Crash] INSTABUG_SWIZZLER_EXECUTING_ORIGINAL_IMPLEMENTATION

### ISSUE THREAD

**Issue by Patczuk** [Instabug/Instabug-iOS#488]
### Steps to Reproduce the Problem
-
### Expected Behavior
The App doesn't crash
### Actual Behavior
The App is crashing

### Instabug integration code
NSRangeException : NSMutableRLEArray replaceObjectsInRange:withObject:length:: Out of bounds
Queue 1: com.apple.main-thread
Serial
INSTABUG_SWIZZLER_EXECUTING_ORIGINAL_IMPLEMENTATION + 15

0 | CoreFoundation | 0x194e78c44
-- | -- | --
1 | libobjc.A.dylib | 0x18df83e5c
2 | Foundation | 0x18f1bf718
3 | Foundation | 0x18f1c0238
4 | UIFoundation | 0x19f2a46e8
5 | UIFoundation | 0x19f26144c
6 | UIFoundation | 0x19f2814e4
7 | UIFoundation | 0x19f281430
8 | UIKitCore | 0x197e33a98
9 | Foundation | 0x18f6fe9bc
10 | Foundation | 0x18f6fd5b8
11 | UIKitCore | 0x197e33e1c
12 | UIKitCore | 0x197def888
13 | UIKitCore | 0x197127a34
14 | UIKitCore | 0x1974fa0a0
15 | TextInputUI | 0x19e5c3e20
16 | UIKitCore | 0x197127a34
17 | UIKitCore | 0x197127734
18 | UIKitCore | 0x1971270c8
19 | UIKitCore | 0x197126b2c
20 | UIKitCore | 0x196fd71c0
21 | UIKitCore | 0x196fd6614
22 | UIKitCore | 0x196fd58c4
23 | Instabug | INSTABUG_SWIZZLER_EXECUTING_ORIGINAL_IMPLEMENTATION + 15
24 | Instabug | __64-[IBGSwizzler newImplementationSendEvent:selector:swizzlerInfo:]_block_invoke + 251
25 | UIKitCore | 0x196fd3bb0
26 | UIKitCore | 0x19701c888
27 | UIKitCore | 0x197321e88
28 | CoreFoundation | 0x194f420cc
29 | CoreFoundation | 0x194f4e758
30 | CoreFoundation | 0x194ed3578
31 | CoreFoundation | 0x194ee9064
32 | CoreFoundation | 0x194eee37c
33 | GraphicsServices | 0x1cfb0d35c
34 | UIKitCore | 0x19727af58
35 | UIKitCore | 0x19727abbc

### SDK Version
12.7.0
### iOS Version
15.1-17.0.3

### Device Model
-

**Comment by ahmedsalah196** [comment]
Hello @Patczuk,
This is not related to Instabug as `INSTABUG_SWIZZLER_EXECUTING_ORIGINAL_IMPLEMENTATION` means that Instabug has finished logging and resumed the original flow
