### ISSUE TITLE
Bug in IBGFeedbackWindow presentation when displayed a second time 

### ISSUE THREAD

**Issue by lypiut** [Instabug/Instabug-iOS#49]
Hi,
I found an issue with the IBGFeedbackWindow. When I send feedback or bug report and invoke a second time the feedback view, this one is displayed on top of the view and is unusable. See my screenshot

![img_0380](https://cloud.githubusercontent.com/assets/2501138/12756637/e63972a6-c9d4-11e5-9732-ab6d77392d26.PNG)

**Comment by msoliman** [comment]
@lypiut thanks for reporting this.
I'll need your help troubleshooting, is there anyway you can reproduce this in a sample project and send it over to me to debug it?

**Comment by lypiut** [comment]
@msoliman I found the way to reproduce it. I have a custom windows with a windows level set at status bar level, maybe a conflict with your windows. I put a project to reproduce the bug in the following zip.
[Instabug Bug.zip](https://github.com/Instabug/Instabug-iOS/files/114388/Instabug.Bug.zip)

**Comment by m619** [comment]
Hi @lypiut. Would you please try this build and see if it fixes your issue? I tested it with the sample app you sent. 
[InstabugW:WindowSizeFix.zip](https://github.com/Instabug/Instabug-iOS/files/114680/InstabugW.WindowSizeFix.zip)

**Comment by lypiut** [comment]
@m619 The windows display is fixed, but the screenshot taken is the status bar window and not the main window.

![img_0006](https://cloud.githubusercontent.com/assets/2501138/12777211/a2744adc-ca5b-11e5-972d-dea71c32ef9e.PNG)

**Comment by m619** [comment]
Thanks for reporting this too. Would you please try the attached build and see if it fixes both issues for you. Thank you for being so patient. =]

[InstabugWindowSizeAndScreenshotFix.zip](https://github.com/Instabug/Instabug-iOS/files/115994/InstabugWindowSizeAndScreenshotFix.zip)

**Comment by lypiut** [comment]
@m619 It's working! Thank for your reactivity!

**Comment by m619** [comment]
Great! It will be integerated in our next release. Thank you for reporting those, you have an interesting setup. :D

**Comment by msoliman** [comment]
Fixed in https://github.com/Instabug/Instabug-iOS/releases/tag/5.0.2
