### ISSUE TITLE
[Crash] IBGSwizzlerManager crashes on launch

### ISSUE THREAD

**Issue by vytautas1991** [Instabug/Instabug-iOS#490]
### Expected Behavior

Application launch

### Actual Behavior

Application crash

### Instabug integration code

Fatal Exception: NSInvalidArgumentException
*** -[__NSPlaceholderArray initWithObjects:count:]: attempt to insert nil object from objects[0]

<img width="918" alt="Screenshot 2024-03-20 at 15 39 27" src="https://github.com/Instabug/Instabug-iOS/assets/84388176/5e95e85e-5aba-4110-b11a-90f5edcfe92d">

### SDK Version

12.9.0

### iOS Version

16.6-17.4

### Device Model

Any

**Comment by ahmedsalah196** [comment]
Hello @vytautas1991,
We're currently working on a fix for this and will update you ASAP. Meanwhile, to avoid this crash you can disable `APM.webViewTrackingEnabled`

**Comment by vytautas1991** [comment]
Thanks for feedback

**Comment by vytautas1991** [comment]
Unfortunately, since the crash happens right after app launch, your suggested fix doesn't help.

**Comment by ahmedsalah196** [comment]
@vytautas1991 Can you please use this build until a fix is officially released?
`pod 'Instabug', :podspec => 'https://ios-releases.instabug.com/custom/fix-nil-navigation-delegate/12.9.2/Instabug.podspec'`

**Comment by vytautas1991** [comment]
How long could it take for official release? We are using SPM :/

**Comment by ahmedsalah196** [comment]
@vytautas1991 Do you initialize a WebView on launch? If yes, can you confirm not setting the `navigationDelegate` as `nil` for this `WebView` or any other. This is just a workaround until we release the fix from our side

**Comment by vytautas1991** [comment]
It's fine now, we are using Your custom build and crash seems to be gone. Thanks.

**Comment by ahmedsalah196** [comment]
A fix has been released in `12.9.2`
