### ISSUE TITLE
Unable to install 12.9.2 SDK via SPM 

### ISSUE THREAD

**Issue by argyrogounari** [Instabug/Instabug-iOS#492]
### Steps to Reproduce the Problem
I tried integrating 12.9.2 SDK to my Xcode project using SPM. 

I've used https://github.com/Instabug/Instabug-SP

I have tried clearing my DerivedData and the issue persists.

### Expected Behavior
The SDK is integrated with no issues.

### Actual Behavior
The SDK is not successfully integrated with error  downloaded archive of binary target 'Instabug' does not contain expected binary artifact named 'Instabug'

### Instabug integration code
*Make sure to remove your app token.*

### SDK Version
12.9.2

**Comment by AhmedAshraf605** [comment]
@argyrogounari we don't have 19.9.2 Do you mean 12.9.2

**Comment by argyrogounari** [comment]
> @argyrogounari we don't have 19.9.2 Do you mean 12.9.2

That's correct, apologies for the typo, I've corrected it now to 12.9.2

**Comment by AhmedAshraf605** [comment]
@argyrogounari, I integrated version 12.9.2, and it's working as expected. Can you please try again and let me know if you're still having issues?
