### ISSUE TITLE
Include privacy info manifest to comply with Apple privacy policy

### ISSUE THREAD

**Issue by LouisKraemer** [Instabug/Instabug-iOS#494]
### Steps to Reproduce the Problem
While submitting an app with Instabug included, this app will get warnings because of 

### Why

After running [this script](https://github.com/omarzl/ios_17_required_reason_api_scanner) on my binary, I got the following result that indicates Instabug is using the [following private API](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api#4278397)

```
Used symbols in binary ./XCFrameworkIntermediates/Instabug/Instabug.framework/Instabug: NSFileSystemFreeSize, NSFileSystemSize, NSURLCreationDateKey, NSUserDefaults, stat
```

Does this mean this package should include a privacy manifest to explain the use of those private APIs?

**Comment by AhmedAshraf605** [comment]
Hello @LouisKraemer 
This should be fixed in 13.0.0
