### ISSUE TITLE
[Crash] NSPersistentStoreCoordinator has no persistent stores (unknown).

### ISSUE THREAD

**Issue by timothy-barnard** [Instabug/Instabug-iOS#498]
Fatal Exception: NSInternalInconsistencyException
This NSPersistentStoreCoordinator has no persistent stores (unknown). It cannot perform a save operation.

### Steps to Reproduce the Problem
This happens on initialise. 

### Expected Behavior
No crash.

### Actual Behavior
Crash happens, not 100% of the time and unreproducible locally. 

### Instabug integration code

Instabug.start(withToken: token, invocationEvents: [])
BugReporting.bugReportingOptions = [.emailFieldOptional]
BugReporting.enabledAttachmentTypes = [.screenShot, .extraScreenShot, .galleryImage, .screenRecording]
BugReporting.promptOptionsEnabledReportTypes = [.bug]
CrashReporting.enabled = false
APM.enabled = false
Replies.enabled = false
Surveys.enabled = false
FeatureRequests.enabled = false
Instabug.welcomeMessageMode = .disabled
BugReporting.invocationEvents = [.shake]
BugReporting.promptOptionsEnabledReportTypes = [.bug]
Instabug.setReproStepsFor(.bug, with: .enable)

Instabug.enabled = true
BugReporting.enabled =  true

### SDK Version
13.1.1

### iOS Version
All Versions

### Device Model
All Versions

**Comment by AhmedAshraf605** [comment]
@timothy-barnard Could you share the stack trace

**Comment by timothy-barnard** [comment]
@AhmedAshraf605 Sorry the stacktrace is hidden, and we can't get it to crash in debug.

**Comment by timothy-barnard** [comment]
HI Any update?

**Comment by asamir0** [comment]
Hello @timothy-barnard  
we are looking into it

**Comment by timothy-barnard** [comment]
Hey team, any luck in finding the bug. This is one of our biggest crashes right now effecting our CFR.

**Comment by timothy-barnard** [comment]
We are also seeing a lot of logs from debug console: 
`[Instabug] - IBGCore: Coultn't find network log with task Id <TASK_ID> in CoreData`

**Comment by asamir0** [comment]
Hello @timothy-barnard 
We apologize for the delayed response.
We're currently working on a fix. We have a quick question regarding the crash you reported. It seems that NSManagedObjectContext is throwing an exception while executing a request. Have you recently changed the protection level related to CoreData to Complete?

**Comment by timothy-barnard** [comment]
Hi, no we do not have data protection enabled.

**Comment by timothy-barnard** [comment]
Hi, another crash is now happening. 
`Crashed: NSManagedObjectContext SIGABRT ABORT`
