### ISSUE TITLE
Instabug 5.0 SDK is not compiled with Bitcode support

### ISSUE THREAD

**Issue by smyrgl** [Instabug/Instabug-iOS#50]
I assume this was an oversight?  I tried to do an archive with the new SDK and got an error that the Instabug framework was not compiled with Bitcode support.

**Comment by msoliman** [comment]
@smyrgl I'm pushing a fix as we speak. Will let you know

**Comment by msoliman** [comment]
@smyrgl Should be fixed in v5.0.1

**Comment by smyrgl** [comment]
Much appreciated!  I'm turning my Bitcode support back on.

**Comment by smyrgl** [comment]
Ok I've confirmed that 5.0.1 fixes this issue.  Thanks for the quick action!
