### ISSUE TITLE
Question: Customise message in dialog prompt displayed in bug reporting section.

### ISSUE THREAD

**Issue by parvez-keeptruckin** [Instabug/Instabug-iOS#501]
Is it possible to customise the dialog box text that shows up when one tries to submit a bug report without entering anything in the textbox provided? 
Include `commentFieldRequired` as one of the `IBGBugReportingOption` option and also call method `setCommentMinimumCharacterCountForReportTypes` to set the minimum characters that must be entered in the report by the user. 
Can we update the text of the message displayed as visible in below screenshot.

<img width="109" alt="Screenshot 2024-08-10 at 2 17 58 AM" src="https://github.com/user-attachments/assets/779b2dff-17dd-4b55-a5a7-b2871ace9290">

### SDK Version
`13.1.1`

**Comment by IslamElgaafary** [comment]
Yes, but you will need to handle the localization part on your end and pass the strings for other languages explicitly to the method.

**Comment by parvez-keeptruckin** [comment]
Also @IslamElgaafary is it possible to enable the submit button only when user enters at least required number of characters in the textbox while trying to send a bug report / suggesting an improvement / asking a question?
