### ISSUE TITLE
Bug in IBGPushNotificationsManager

### ISSUE THREAD

**Issue by mpsnp** [Instabug/Instabug-iOS#51]
Unfortunately after update to 5.0.x appeared crash on receiving push notification:

```
-[AppDelegate application:didReceiveRemoteNotification:]
-[IBGPushNotificationsManager handleSwizzledRemoteNotificationReceived:notification:completionHandler:originalMethodImplementaion:selector:]
-[IBGPushNotificationsManager didReceiveNotificationSwizzler]_block_invoke
-[IBGMethodSwizzler application:didReceiveRemoteNotification:]
```

Whats strange, in app delegate `self` is `IBGPushNotificationsManager`.

**Comment by msoliman** [comment]
@mpsnp thanks for reporting this. I need more info to troubleshoot this though.
Was this notification related to your app or Instabug? Also would you mind sharing your AppDelegate structure? do you implement `application: didReceiveRemoteNotification`?

Can you try disabling Instabug's push notifications and let me know how it goes?
`[Instabug setPushNotificationsEnabled: NO]`

**Comment by mpsnp** [comment]
@msoliman, I think bug is related to Instabug, because with v4.x everything works as expected.

**Our** service sending push notifications which i'm handling in `application: didReceiveRemoteNotification:`. 

Bug is that `IBGPushNotificationsManager` performs selector `application: didReceiveRemoteNotification:` (of **my** AppDelegate) on itself. 
_In other words_, stopping debugger inside of my implementation of `application: didReceiveRemoteNotification:` shows that `self` is instance of class `IBGPushNotificationsManager `

**Comment by m619** [comment]
Hi @mpsnp! Would you please try the attached build and let us know if you're still experiencing this? Thank you!
[InstabugAPNSFix.zip](https://github.com/Instabug/Instabug-iOS/files/116056/InstabugAPNSFix.zip)

**Comment by ljkyser** [comment]
We are experiencing the same issue after the update, no problems before.

**Comment by m619** [comment]
@ljkyser Did you try version 5.0.2? You can run `pod outdated` to make sure, if you're using CocoaPods.

**Comment by ljkyser** [comment]
@m619 don't believe so, I will look in to that now.

**Comment by ljkyser** [comment]
@m619 We were using 5.0.0, we're updating to 5.0.2. Will let you know if that solves it from our end. Thanks!

**Comment by msoliman** [comment]
@ljkyser are you still getting this bug?

**Comment by ljkyser** [comment]
@msoliman hey, sorry for not responding sooner. No, we are not getting that bug anymore once we updated to 5.0.2. Thank you!
