### ISSUE TITLE
Crash when Invoking (5.0.2)

### ISSUE THREAD

**Issue by Rich86man** [Instabug/Instabug-iOS#53]
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Could not load NIB in bundle: 'NSBundle </var/mobile/Containers/Bundle/Application/B405647F-25AF-4CA8-A430-A2FF2EB6448A/Orchestra.app> (loaded)' with name 'IBGActionSheetVC-iPhone''

Installed through cocoapods

**Comment by msoliman** [comment]
@Rich86man looks like the Instabug.bundle isn't being picked up.
Can you make sure that the Instabug.bundle is included in the "Copy Bundle Resources". If it's already there, can you try manually integrating the SDK to double check.

Please let me know how it goes

**Comment by Rich86man** [comment]
If I manually add the Instabug.bundle to my project it works. But now I can't rely on cocoapods updating instabug. Is this due to 
`	[NSBundle mainBundle];`
vs
`[NSBundle bundleForClass:[self class]];`

**Comment by msoliman** [comment]
@Rich86man nope, we already handle that. We've been seeing this happening intermittently. Usually Xcode build doesn't act as expected

**Comment by nirajignited** [comment]
@msoliman  I am experiencing this crash on version 5.1.0.

**Comment by msoliman** [comment]
@nirajignited a workaround for this is to manually add the Instabug.bundle file into your app assets. Can you try this?

**Comment by nirajignited** [comment]
@msoliman that worked. thanks
