### ISSUE TITLE
Latest Version pod install error

### ISSUE THREAD

**Issue by wilferrel** [Instabug/Instabug-iOS#55]
Receiving the following afte your last merge: 

`Specs satisfying the `Instabug (from `https://github.com/Instabug/Instabug-iOS`, branch `no_build_script`)` dependency were found, but they required a higher minimum deployment target.`

Podfile has this for platform:  `platform :ios, '8.0'`

**Comment by msoliman** [comment]
@wilferrel Can you please send me the line that you use to include Instabug into your podfile?
You don't really need to use the branch `no_build_script` anymore. We've removed it from `master` already.

Let me know how it goes.

**Comment by wilferrel** [comment]
I was using  `pod 'Instabug', :git => 'https://github.com/Instabug/Instabug-iOS', :branch => 'no_build_script'`

but regular pod install works just fine I guess I will use that from now on thanks.
