### ISSUE TITLE
Enums are not Swift-friendly

### ISSUE THREAD

**Issue by vocaro** [Instabug/Instabug-iOS#56]
The enums in IBGEnums.h are not Swift-friendly. They force you to type out the entire enum, like this:

    Instabug.invokeWithInvocationMode(IBGInvocationModeFeedbackSender)

while in Swift this is normally reduced to:

    Instabug.invokeWithInvocationMode(.FeedbackSender)

You can enable this syntax sugar by adopting the NS_ENUM macro. For example:

    typedef NS_ENUM(NSInteger, IBGInvocationMode) {
        IBGInvocationModeNA,
        IBGInvocationModeBugReporter,
        IBGInvocationModeFeedbackSender
    };

I'd submit a pull request, but there is no source code to modify. Could you please apply this change to all enums in your upstream code? Thanks!

**Comment by msoliman** [comment]
@vocaro Thanks for sending this over. I'll make sure to add this in our next release.

**Comment by msoliman** [comment]
@vocaro can you check in v5.1.2

**Comment by vocaro** [comment]
Looks good, thanks!
