### ISSUE TITLE
Screenshot cannot be disabled

### ISSUE THREAD

**Issue by vocaro** [Instabug/Instabug-iOS#57]
I recently upgraded from Instabug 4.1 to 5.1 and there is now a screenshot embedded in the feedback message. The screenshot is pointless for our use case because, in our app, Instabug's "Suggest an Improvement" dialog is always triggered by an explicit tap of a "Send Feedback" button in our settings screen -- so the screenshot is always the same: our settings screen. I looked in the API for some way to disable the screenshot functionality, but I can't find one.

**Comment by msoliman** [comment]
@vocaro we're adding this in our next version of the SDK, together with the ability to attach another screenshot from the app

**Comment by brandonminch** [comment]
For anyone else facing this issue, for now you can call `Instabug.setWillTakeScreenshot(false)` to at least disable an automatic screenshot from being embedded.

**Comment by alliamin** [comment]
@vocaro @brandonminch Now you can use `setWillTakeScreenshot:`

**Comment by GocePetrovski** [comment]
This issue is back in 7.13. We had to go back 7.12.7
The call to  `[Instabug setEnabledAttachmentTypes:IBGAttachmentTypeExtraScreenShot |  IBGAttachmentTypeGalleryImage | IBGAttachmentTypeScreenRecording];` is totally ignored and the Feedback starts with screenshot.

**Comment by jlichti** [comment]
Having the same issue as @GocePetrovski. Will revert back.

**Comment by Kmohamed** [comment]
We will release fix very soon

**Comment by Kmohamed** [comment]
@GocePetrovski @jlichti this is issue is fixed please update to the latest.
