### ISSUE TITLE
Detect if Instabug's UI is active

### ISSUE THREAD

**Issue by magnett** [Instabug/Instabug-iOS#58]
Hi!
I know that the title is kind of weird but let me explain:

I am using [MZFormSheetController](https://github.com/m1entus/MZFormSheetController) for presenting modal views (mainly notification events) that may be triggered at any time. Some times when a popup is presented over Instabug's UI, weird things happen.
I need some kind of method or delegate or bool to let me know when your UI is on top to avoid presenting anything else on top of it.
I tried the code below but this is not a class i have access to:
`if ([[GlobalVariables sharedInstance].topRootViewController isKindOfClass:[IBGScreenshotVC class]]`
Even if i did,  you are using multiple VCs (instead of UIViews).
Below is a screenshot from a modal view over your UI.
![again same problem when i am about to report a bit in substitution i get the substitution push again png](https://cloud.githubusercontent.com/assets/1730803/13557522/7760d8c0-e3fa-11e5-8d05-8921b8282987.jpeg)

**Comment by msoliman** [comment]
@magnett there's no API currently for that. But there's a workaround that you can use. Can you please email contactus@instabug.com and we'll take it from there. Just mention this GitHub issue.
