### ISSUE TITLE
Enable and disable Instabug tracking and logging at runtime. 

### ISSUE THREAD

**Issue by Aaang** [Instabug/Instabug-iOS#59]
Hi!

This is more like a feature request for the public interface than a bug. We've just started using Instabug in our Apps (it's great!) and came across an API challenge for our simple use case.

_"We want to enable / disable Instabug only for certain users who might change during runtime"_

But you cannot disable the tracking once it was started, so when the users change during runtime they will eventually have the tracking enabled.

The only "workaround" to prevent showing the form for those users then is to call `Instabug.setInvocationEvent(.None)` and not manually show the feedback form, but this won't disable the tracking.

What would make sense here would be a `stop` method to stop the tracking when we know it's no longer needed. So we could start and stop the tracking at any time, like other tracking tools are doing as well. Furthermore, it would also be nice to have some kind of `isTracking` method to indicate whether Instabug tracking was already started or not.

What do you think?

Thanks in advance,
Aaang

**Comment by msoliman** [comment]
@Aaang that's interesting, thanks for sending this over.
So the `stop`/`start` API will be basically a master switch for the methods `setInvocationEvent(.None)`, `setUserStepsEnabled(false)`, `setCrashReportingEnabled(false)`, `setPushNotificationsEnabled(false)` and `setInAppConversationsEnabled(false)`.

Will this fit your use-case?

**Comment by Aaang** [comment]
Yes it would basically be a master switch. We're actually doing the suggested approach above right now in code and I was wondering if this could somehow be provided by the API.

Maybe a `setupWithToken`, `start`/`enable` and `stop`/`disable` additional to the existing simple `startWithToken:invocationEvent`?

**Comment by TaimurAyaz** [comment]
Hi Guys. Any update on this?

**Comment by HeshamMegid** [comment]
@Aaang and @TaimurAyaz, just to make sure we fully understand how you'd be using this API, could you give us an example of when/why you need to stop tracking after it has started?

**Comment by NadineMansour** [comment]
@Aaang @TaimurAyaz I am following up on Hisham’s previous question. Could you please provide us with an example explaining when and why you would need to stop the tracking after it has already started?
Also, I renamed the issue to help other people identify the topic more quickly.

**Comment by ZiadAyman** [comment]
I will close this one for now and please make sure to contact us back here or email our support team on contactus@instabug.com. 

We would love to help, always!

**Comment by somparkash2835** [comment]
Hey guys, can you please help me how to enable/disable instabug at runtime in iOS

**Comment by somparkash2835** [comment]
Thank you so much @Kmohamed
