### ISSUE TITLE
Help in investigating our app crash

### ISSUE THREAD

**Issue by vlrebrov** [Instabug/Instabug-iOS#61]
Hi there!

Sometimes our app crashes and in our logs we see methods with prefix "IBG", so we suppose that there might be an issue in the included Instabug's library. 
If possible, could you please help us to understand why the issue happens and provide us with a solution or any additional info for preventing this crash?

Below is a crash stack trace:

`Fatal Exception: NSInvalidUnarchiveOperationException
*** -[NSKeyedUnarchiver decodeObjectForKey:]: cannot decode object of class (IBGDeviceRequest) for key (NS.objects); the class may be defined in source code or a library that is not linked`

`Thread : Fatal Exception: NSInvalidUnarchiveOperationException`
`0  CoreFoundation                 0x21f8a2eb __exceptionPreprocess`
`1  libobjc.A.dylib                0x21756dff objc_exception_throw`
`2  Foundation                     0x227565db -[NSCoder(Exceptions) __failWithException:]`
`3  Foundation                     0x22756797 -[NSCoder(Exceptions) __failWithExceptionName:errorCode:format:]`
`4  Foundation                     0x22729785 _decodeObjectBinary`
`5  Foundation                     0x22728833 _decodeObject`
`6  FluentU                        0x2fa4c5 __33-[IBGServersQueue initWithCoder:]_block_invoke`
`7  libdispatch.dylib              0x21b27dc3 _dispatch_client_callout`
`8  libdispatch.dylib              0x21b31055 _dispatch_barrier_sync_f_invoke`
`9  FluentU                        0x2f9d57 -[IBGServersQueue initWithCoder:]`
`10 Foundation                     0x22729405 _decodeObjectBinary`
`11 Foundation                     0x22728833 _decodeObject`
`12 FluentU                        0x2fefdb -[IBGServerManager loadServers]`
`13 FluentU                        0x3005a7 __24-[IBGServerManager init]_block_invoke`
`14 libdispatch.dylib              0x21b27dd7 _dispatch_call_block_and_release`
`15 libdispatch.dylib              0x21b27dc3 _dispatch_client_callout`
`16 libdispatch.dylib              0x21b2c671 _dispatch_main_queue_callback_4CF`
`17 CoreFoundation                 0x21f4cfc5 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__`
`18 CoreFoundation                 0x21f4b4bf __CFRunLoopRun`
`19 CoreFoundation                 0x21e9dbb9 CFRunLoopRunSpecific`
`20 CoreFoundation                 0x21e9d9ad CFRunLoopRunInMode`
`21 GraphicsServices               0x23117af9 GSEventRunModal`
`22 UIKit                          0x26189fb5 UIApplicationMain`
`23 FluentU                        0x1b4517 main (main.m:16)`

Thanks,
Vladimir

**Comment by msoliman** [comment]
@vlrebrov this should be fixed already in the latest version of the SDK. Can you verify it on v5.2.2?

**Comment by vlrebrov** [comment]
Hello @msoliman, thanks a lot for the answer. Ok, I'll try to update to the latest version and will check it.

**Comment by Figo0o** [comment]
@vlrebrov Please let us know if you still facing the same issue using Instabug's latest version.

**Comment by vlrebrov** [comment]
Hi @Figo0o 

Sorry for the delayed answer. Yes, looks like everything was fixed. Thanks a lot again!
