### ISSUE TITLE
Crash on device with NSInvalidArgumentException Reason: *** setObjectForKey: object cannot be nil (key: email)

### ISSUE THREAD

**Issue by SerDev** [Instabug/Instabug-iOS#63]
Hi!

Our app became crashes after update with SDK 5.2.2.
Launch on simulator - OK.

Stack trace below:

UIApplication Exception: Objective-C exception thrown.  Name: NSInvalidArgumentException Reason: *** setObjectForKey: object cannot be nil (key: email)
	Native stack trace:
		0   CoreFoundation                      0x00000001842b4248 <redacted> + 160
		1   libobjc.A.dylib                     0x0000000195f300e4 objc_exception_throw + 60
		2   CoreFoundation                      0x000000018419d0c8 <redacted> + 972
		3   STA                                 0x00000001021159b0 -[IBGFeedbackModel submit] + 196
		4   STA                                 0x00000001008c6b78 -[IBGCrashManager sendCrashReportWithData:] + 248
		5   STA                                 0x00000001008c6898 -[IBGCrashManager handlePendingCrashReportIfExists] + 140
		6   STA                                 0x00000001008c8334 __23-[IBGCrashManager init]_block_invoke + 48
		7   libdispatch.dylib                   0x00000001965ad994 <redacted> + 24
		8   libdispatch.dylib                   0x00000001965ad954 <redacted> + 16
		9   libdispatch.dylib                   0x00000001965b220c _dispatch_main_queue_callback_4CF + 1608
		10  CoreFoundation                      0x000000018426b544 <redacted> + 12
		11  CoreFoundation                      0x00000001842695ec <redacted> + 1492
		12  CoreFoundation                      0x0000000184194f74 CFRunLoopRunSpecific + 396
		13  GraphicsServices                    0x000000018dbf76fc GSEventRunModal + 168
		14  UIKit                               0x0000000188d96d94 UIApplicationMain + 1488
...

**Comment by alliamin** [comment]
Hello SerDev,
I've fixed your issue in this [build](https://www.dropbox.com/s/a6eerwtb9v75had/Instabug%20Fix.zip?dl=0). Please try it and let me know if you have any problem.
Thank you

**Comment by alliamin** [comment]
Hello @SerDev 
Well, after further investigation, I could find out what must be causing this issue. And I've put the fix in new release (Instabug 5.2.3). Please update Instabug to the latest version and let me know how it will work.
