### ISSUE TITLE
Provide a changelog

### ISSUE THREAD

**Issue by keith** [Instabug/Instabug-iOS#64]
Since the instabug framework is closed source, it isn't obvious what changed from release to release. It would be extremely useful if you provided a CHANGELOG ([example](https://github.com/Alamofire/Alamofire/blob/master/CHANGELOG.md)) file that contained the details so we would know what should be fixed/changed in each release.

Thanks!

**Comment by msoliman** [comment]
@keith thanks for the suggestion. We currently maintain this in releases: https://github.com/Instabug/Instabug-iOS/releases

Do you still need a CHANGELOG file or do you think this is enough?

**Comment by keith** [comment]
Ah perfect. I overlooked this after not seeing a CHANGELOG or any info in the commit messages. Thanks!
