### ISSUE TITLE
Cannot clone instabug: fatal: unable to access 'https://github.com/Instabug/Instabug-iOS.git/': transfer closed with outstanding read data remaining

### ISSUE THREAD

**Issue by florianschmidt1994** [Instabug/Instabug-iOS#65]
I can't clone this repository "by hand" using git clone (https / git) and therefore pod install also fails

**Comment by alliamin** [comment]
Hello @florianschmidt1994 
I tried cloning the SDK via git and via cocoapods and both seems to work perfectly.
What happens after you clone via "git clone"? any log/error messages?

**Comment by florianschmidt1994** [comment]
This seemd to be a temporary issue, it is now working again. Thanks for your concern!
