### ISSUE TITLE
Decide when `showIntroMessage` is called

### ISSUE THREAD

**Issue by Serchinastico** [Instabug/Instabug-iOS#66]
Hi Instabug team!

Is there any option to avoid the library from calling `showIntroMessage` automatically? In our case, we want to decide when to show the educating message and show it only once. The fact that the library decides when to show you the popup is not documented anywhere and is kind of surprising IMHO.

We are using Instabug 5.2.2

Thanks for your time!

**Comment by alliamin** [comment]
Hello @Serchinastico 
You can prevent automatic intro message via `[Instabug setIntroMessageEnabled:NO]` and then you can invoke it whenever you want manually via `[Instabug showIntroMessage]`

**Comment by Serchinastico** [comment]
It seems to work just as expected. 

Thanks for your time!
