### ISSUE TITLE
Reported UI buttons are too small for the localized text

### ISSUE THREAD

**Issue by zrxq** [Instabug/Instabug-iOS#67]
![simulator screen shot may 10 2016 13 03 23](https://cloud.githubusercontent.com/assets/820120/15144728/f4368812-16b9-11e6-8b02-37cb6c6dc8dc.png)

Note the ellipsis. 

Instabug 5.2.3 (via Cocoapoda), iOS sim 9.3, any device (5, 6, 6+).

**Comment by alliamin** [comment]
Hello @zrxq 
A fix for this issue will be released next version. It handles text well for 6 and 6+. Can you suggest possible shorter words to fit in 320px screens without truncation.
You can use [this build](https://www.dropbox.com/s/jfy9zbivv1s70xg/Instabug%205.2.3%20Localisation%20Fix.zip?dl=0) until next release.

**Comment by zrxq** [comment]
Hello @alliamin 

Much appreciated!

I can't think of a word that's shorter than "Отмена" for "Cancel" ("Назад" is one character shorter but the literal meaning is "Back" and that's not exactly what you have there, I guess). Perhaps you could use an icon, ╳ or something? As for "Send", I think one could get away with "ОК" there, don't you think so?

Anyways, good to know the fix is on it's way, thanks again!

**Comment by alliamin** [comment]
Thank you @zrxq for help.
Actually we are considering something similar to your suggestion in future releases. [This custom build](https://www.dropbox.com/s/5zrfzjkjav5svr0/Russian%20Instabug.zip?dl=0) uses the word "Улучшение" as you suggest.

**Comment by zrxq** [comment]
Thank you very much :-)
