### ISSUE TITLE
Instabug setUserEmail: does not set the email

### ISSUE THREAD

**Issue by ayushgoel** [Instabug/Instabug-iOS#69]
[setUserEmail:](https://instabug.com/public/ios-api-reference/Classes/Instabug.html#//api/name/setUserEmail:) does not set the email Instabug interface.

Using it this way:

    Instabug.setUserEmail(account.email)

![simulator screen shot 13-may-2016 9 55 34 am](https://cloud.githubusercontent.com/assets/893050/15237987/d9e7253c-18f0-11e6-9a6c-bbe3d7739ff6.png)

**Comment by alliamin** [comment]
hay @ayushgoel 
Please make sure `account.email` is set to valid email value. otherwise it is treated as nil value.

**Comment by ayushgoel** [comment]
The value currently is `ayushgoel111@gmail.com`.
I set the email during initialisation of Instabug. The Feedback reporter is presented later in the lifecycle. Can that be an issue?

**Comment by alliamin** [comment]
Please show me your Instabug initialization code. Also how do you invoke Instabug. using `invoke` or `invokeWithInvocationMode`?

**Comment by ayushgoel** [comment]
```swift
    Instabug.startWithToken("token", invocationEvent: .Shake)
    Instabug.setCrashReportingEnabled(true)
    Instabug.setInAppConversationsEnabled(false)
    Instabug.setFileAttachment(logPath?.relativePath)

    Instabug.setIntroMessageEnabled(false)
    Instabug.setColorTheme(.Light)
    Instabug.setUserStepsEnabled(false)
    Instabug.setUserEmail(account.email)
```
Invocation
```swift
Instabug.invokeWithInvocationMode(.FeedbackSender)
```

**Comment by alliamin** [comment]
Hay @ayushgoel 
Still can't reproduce the issue :(
Please send the link of this issue to ***support@instabug.com*** and I'll follow up with you.
Thank you.

**Comment by ayushgoel** [comment]
Sorry, this issue is wrong.
It does set the email (if given). I tested it in my signup flow, where I had coded it wrong, setting it to `nil`.
Closing..
