### ISSUE TITLE
Instabug crashes in Swift throwing an error.

### ISSUE THREAD

**Issue by saurabhshrivastava2111** [Instabug/Instabug-iOS#70]
Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'NSConcreteMutableAttributedString initWithString:: nil value'
*** First throw call stack:
(
	0   CoreFoundation                      0x00000001065d3d85 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x0000000106045deb objc_exception_throw + 48
	2   CoreFoundation                      0x00000001065d3cbd +[NSException raise:format:] + 205
	3   Foundation                          0x0000000105c378a4 -[NSConcreteMutableAttributedString initWithString:] + 129
	4   Give Plus                           0x00000001025f46fe -[IBGBaseHUD show] + 5511
	5   Give Plus                           0x00000001026e08bf __19+[IBGStartHUD show]_block_invoke + 108
	6   libdispatch.dylib                   0x00000001070e8d9d _dispatch_call_block_and_release + 12
	7   libdispatch.dylib                   0x00000001071093eb _dispatch_client_callout + 8
	8   libdispatch.dylib                   0x00000001070ee686 _dispatch_after_timer_callback + 334
	9   libdispatch.dylib                   0x00000001071093eb _dispatch_client_callout + 8
	10  libdispatch.dylib                   0x00000001070fc7e5 _dispatch_source_latch_and_call + 1750
	11  libdispatch.dylib                   0x00000001070f7770 _dispatch_source_invoke + 1057
	12  libdispatch.dylib                   0x00000001070f1051 _dispatch_main_queue_callback_4CF + 1324
	13  CoreFoundation                      0x000000010652d0f9 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	14  CoreFoundation                      0x00000001064eeb99 __CFRunLoopRun + 2073
	15  CoreFoundation                      0x00000001064ee0f8 CFRunLoopRunSpecific + 488
	16  GraphicsServices                    0x0000000107fa0ad2 GSEventRunModal + 161
	17  UIKit                               0x0000000103cfef09 UIApplicationMain + 171
	18  Give Plus                           0x0000000102511e62 main + 114
	19  libdyld.dylib                       0x000000010713e92d start + 1
	20  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by alliamin** [comment]
Hello @saurabhshrivastava2111. Sorry for late reply.
Are you sure Instabug.bundle is included in your project?
