### ISSUE TITLE
preSendingBlock IBGLog() and NSLog() not included in report

### ISSUE THREAD

**Issue by jweihs** [Instabug/Instabug-iOS#71]
In order to get all necessary information, i'm using the `preSendingBlock` to call some IBGLogs and NSLog.
The block get called properly, but the logs are not contained in the relevant report. 
A second report contains the logs from the first report (due to the delay), but not from the second one.

**Comment by alliamin** [comment]
Hello @jweihs 
I've checked this issue and it is fixed now. It will be available in next release.
Thanks for reporting.

**Comment by jweihs** [comment]
Thanks @alliamin for the fast support - makes Instabug really valuable!
