### ISSUE TITLE
Crash method swizzling only first run

### ISSUE THREAD

**Issue by gilserrap** [Instabug/Instabug-iOS#72]
The first time we run our app from a fresh install on iOS 8.4.1 with Instabug 5.2.5 it crashes when tapping on any random tab of the tab of the tabbar... but then when we launch again the app after the crash it works fine...
I saw that a similar bug was reported previously and it was solved by disabling the tracking of the user steps, but this isn't working for us.

This is the bug report from crashlytics:

![screen shot 2016-06-15 at 11 12 55](https://cloud.githubusercontent.com/assets/5508650/16074332/5152e0b2-32ea-11e6-856b-2b2d0bc0391f.png)

**Comment by alliamin** [comment]
Hello @gilserrap please try removing Instabug from you application and check if crash sill happening. I think this crash is not Instabug related.

**Comment by gilserrap** [comment]
You're absolutely right! It's not the Instabug SDK, sorry for the inconvenience. Thanks for the fast answer.
