### ISSUE TITLE
Remove legacy withArguments parameter from Instabug.IBGLog(:withArguments:)

### ISSUE THREAD

**Issue by haaakon** [Instabug/Instabug-iOS#73]
With Swift there is no need for writing the IBGLog method with a parameter that is va_list
`+ (void)IBGLog:(NSString *)format withArguments:(va_list)arguments;`

as you can do the same thing using String interpolation
given
`    let myAge = 28`
this
 `   Instabug.IBGLog("my age: %lu", withArguments: myAge)`

will be the same as

` Instabug.IBGLog("my age: \(myAge)") `

which is much more "Swifty". My suggestion is to remove the withArguments parameter from this method.

**Comment by Figo0o** [comment]
@haaakon Thanks for the suggestion,

We will make sure to bring this new API next Release, but we have to keep both.

If you have any more questions don't hesitate to let us know!

**Comment by haaakon** [comment]
Cool, yeah prob a good idea to have the parameter optional, and keep the old one for those that use it.

I had a hard time actually using Swift to create the va_list argument so ended up doing this to make it compile (i just want to print the string which i make with String interpolation):

```
func debugLog(string: String) {

    let unsafeMutablePointer = UnsafeMutablePointer<Int>(bitPattern: 0)

    let args: CVaListPointer = CVaListPointer(_fromUnsafeMutablePointer: unsafeMutablePointer)

    Instabug.IBGLog("\(string) %I", withArguments: args)

} 
```

**Comment by Figo0o** [comment]
@haaakon, I see now. But there is an easier way to do so.

 Just Put following function inside you class 
```
    func IBGLog(str: String, _ arguments: CVarArgType...) -> Void {
        return withVaList(arguments) { Instabug.IBGLog(str, withArguments :$0) }
    }
```
And then use it like this `IBGLog("%@ - %d - %0.1f", "foo", 3, 3.0)`

**Comment by haaakon** [comment]
Yeah, but i really didn't want to do it that way as it felt wrong in Swift. Just had a hard time getting the method call to acutally compile, since the weird CVAListPointer stuff :)

**Comment by Figo0o** [comment]
hey @haaakon, Please check the new release and tell us your feedback.

if there is anything else please let us know.
