### ISSUE TITLE
Add Danish localization

### ISSUE THREAD

**Issue by Anders123fr** [Instabug/Instabug-iOS#74]
Hi,
I would be very excited if you could add support for Danish localization.
We are going to use Instabug in a large project in Denmark, but the rest of the app is in Danish so it would be really great if Instabug was too.

I am willing to do the translation as I am a native dane, so you can just post the text to translate here, or send me a message :)

Best Regards

**Comment by msoliman** [comment]
@Anders123fr Thanks for offering to help :)
Sure, let's do this. Can you email us to communicate over the translation strings that we need?
Here's our email address: contactus@instabug.com

**Comment by Anders123fr** [comment]
Sure, I just sent you an email

**Comment by alliamin** [comment]
Hello @Anders123fr 
Instabug 5.3 is now available with Danish localization support 👍

**Comment by Anders123fr** [comment]
Yeah i read the release notes, but the locale enum does not contain a value for Danish. Can you find it?

**Comment by Anders123fr** [comment]
https://github.com/Instabug/Instabug-iOS/blob/master/Instabug.framework/Versions/A/Headers/IBGEnums.h

**Comment by Anders123fr** [comment]
Fixed in release 5.3.1
