### ISSUE TITLE
Instabug invoke conversations

### ISSUE THREAD

**Issue by Azeeshan123** [Instabug/Instabug-iOS#75]
Hi,

I am trying to add the InApp Conversations in my iOS app.

I have added the token in the AppDelegate.m file as below:
[Instabug startWithToken:APP_ID invocationEvent:IBGInvocationEventShake];
[Instabug setInAppConversationsEnabled:NO];

Then on a button tap, I called the "[Instabug invokeConversations];" but nothing happened. 

Can you please let me know where I am wrong? Or is this a bug?

Thanks

**Comment by msoliman** [comment]
@Azeeshan123 you need to keep InAppConversations enabled for the invokeConversations API to work.
Also note that if you didn't report any bug or feedback from this device before, invokeConversations will do nothing.
