### ISSUE TITLE
Crash adding image from library in landscape only app, involving [PUUIAlbumListViewController shouldAutorotate]

### ISSUE THREAD

**Issue by samsonjs** [Instabug/Instabug-iOS#77]
I'm working on an app that only supports landscape orientations and when we try to attach images from the photo library Instabug throws an exception, crashing the app with this log:

`Supported orientations has no common orientation with the application, and [PUUIAlbumListViewController shouldAutorotate] is returning YES`

**Comment by samsonjs** [comment]
While trying to use the pre & post invocation blocks to work around this issue I may have found another bug. The pre & post invocation blocks aren't called when I set the default invocation mode to bug reporter: `[Instabug setDefaultInvocationMode:IBGInvocationModeBugReporter];` ... Should I file a separate issue for that?

**Comment by Kmohamed** [comment]
Hay @samsonjs 
Please report your issue to support@instabug.com and I'll follow up with you.
Thank you.

**Comment by samsonjs** [comment]
will do!

**Comment by leahpsnider** [comment]
Any progress on this issue? It still exists on iOS 10.

**Comment by Kmohamed** [comment]
@leahpsnider actually we can no do anything regarding this issue because photos view only support portait 
The only solution is to implement our own view.
Let me forward this to our product team and get back to you

**Comment by leahpsnider** [comment]
hi @Kmohamed  , 
Another option is to use different `modalPresentationStyle` for image picker. It would be good option to pass it to your SDK.

**Comment by Kmohamed** [comment]
@leahpsnider Thanks a lot for the workaround definitely we will make and release it soon.
If you wanna a custom build I can make it for you.

**Comment by Kmohamed** [comment]
btw this crash is fixed on iOS 11 so we will apply this workaround on iOS versions less than iOS11.
