### ISSUE TITLE
Ability to set intro message.

### ISSUE THREAD

**Issue by 8masterofpuppets8** [Instabug/Instabug-iOS#80]
It would be great to have the ability to set the intro message text. I could not find that option in the SDK.

**Comment by alliamin** [comment]
Hello @8masterofpuppets8 this API will be available in next version. stay tuned.

**Comment by Figo0o** [comment]
Hey @8masterofpuppets8, Please checkout our new Version. Now you can customize any string you like. 

Thanks for your feedback.
