### ISSUE TITLE
Stop storing data in Documents directory

### ISSUE THREAD

**Issue by martinc** [Instabug/Instabug-iOS#81]
The Instabug SDK is storing files in the Documents directory, which is against Apple's iOS Data Storage Guidelines. They specify that only user-generated documents should be in the Documents directory. The files are not large, under 1KB, but they should be moved to /Library as other 3rd-party libraries do.

These files include IBGServers.txt and IBGCache/cachedThreads

**Comment by alliamin** [comment]
@martinc you are absolutely right. we'll consider fixing this in next version.

**Comment by Figo0o** [comment]
Hey @martinc, This now should be solved with the new release. Thanks for your feedback.
