### ISSUE TITLE
preferredStatusBarStyle not called after modal view controller presented

### ISSUE THREAD

**Issue by jaredegan** [Instabug/Instabug-iOS#82]
After integrating Instabug, our UIStatusBar style is no longer updating after modally presenting a view controller. The `preferredStatusBarStyle` is not getting called. Interestingly, after about 10 seconds, it does get called with the following stack trace, but does not affect the status bar style.

![image](https://cloud.githubusercontent.com/assets/303795/17540739/c2acd80e-5e86-11e6-8bad-e40af4dbf330.png)

Our project does have some strange custom navigation stack stuff, but this aspect previously works without Instabug.

**Comment by alliamin** [comment]
Hello @jaredegan 
Can you tell me what version of Instabug do you use?

**Comment by jaredegan** [comment]
5.3.2

**Comment by jaredegan** [comment]
Sorry for the lack of info in the original post. This also only happens when using the `IBGInvocationEventFloatingButton` mode.

**Comment by Figo0o** [comment]
Hey @jaredegan, 

This will be fixed next Release, But please let me know if this issue is blocking you.

**Comment by jaredegan** [comment]
No worries, we can survive. Is there a schedule for the next release?

Instabug seems like a great tool from my POV, looking forward to getting
bug reports from users.

**Comment by Figo0o** [comment]
hey @jaredegan,

please report your issue on support@instabug.com and I will follow up with you.

**Comment by Figo0o** [comment]
hello @jaredegan, 

here is a custom build for you, please try it and tell me if you still facing any issues. 

Thank you.
[instabug.zip](https://github.com/Instabug/Instabug-iOS/files/419701/instabug.zip)
