### ISSUE TITLE
Framework does not include build for x86_64

### ISSUE THREAD

**Issue by victorlin** [Instabug/Instabug-iOS#83]
Since upgrading to 5.3, all our builds against simulator failed

```
ld: framework not found Instabug for architecture x86_64
```

Have no time to look into it closely yet, but it seems x86_64 build is missing in your framework. 5.2 works fine for us.

We need to run unit tests on simulator, as Instabug is always there in our app, can you guys please fix x86_64 for us?

Thanks.

**Comment by Figo0o** [comment]
Hey @victorlin, 

Well, I think that you are using swift. If I am right go to your `xxxx-Bridging-Header.h` and remove `#import <Instabug/Instabug.h>`  

Please let me know if you still facing issue. 
Thank you.
