### ISSUE TITLE
Add Slovak localization

### ISSUE THREAD

**Issue by zaitsevyan** [Instabug/Instabug-iOS#84]
I cannot update from 4.* to 5.* beacause you have no way to add custom localization.

Thanks for czech localization.

p.s. android sdk has opportunity to add custom language support

**Comment by alliamin** [comment]
Hey @zaitsevyan 
Custom SDK strings for custom localization support will be available next release. stay tuned.

**Comment by Figo0o** [comment]
Hey @zaitsevyan, Please check out our new Release. We now do support Czech and custom strings. 

Waiting for your feedback. Thanks.
