### ISSUE TITLE
Instabug cannot be included with targets including Bitcode and using -ObjC

### ISSUE THREAD

**Issue by keith** [Instabug/Instabug-iOS#85]
Currently if you try to include Instabug in a project with Bitcode enabled, that also has `-ObjC` as part of the target's `OTHER_LDFLAGS` archiving the app fails with this error:

```
ld: could not open bitcode temp file: /Users/ksmiley/Desktop/InstabugBitcode/build/Intermediates/ArchiveIntermediates/InstabugBitcode/IntermediateBuildFilesPath/InstabugBitcode.build/Release-iphoneos/InstabugBitcode.build/Objects-normal/armv7/InstabugBitcode.lto.opt.bc for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

There isn't much about this online but there is [this post](https://forums.developer.apple.com/thread/11098) which made the issue sound like it was caused by having inline assembly. Of course I didn't expect Instabug to have any, but the I noticed that the SDK includes [PLCrashReporter](https://github.com/plausiblelabs/plcrashreporter) which has a
[few](https://github.com/plausiblelabs/plcrashreporter/search?utf8=%E2%9C%93&q=__asm__&type=Code) [occurances](https://github.com/plausiblelabs/plcrashreporter/search?utf8=%E2%9C%93&q=mov&type=Code) of inline assembly.

You can easily reproduce with these steps:

1. Download this [sample project](https://github.com/Instabug/Instabug-iOS/files/448176/InstabugBitcode.zip)
1. Open the project in Xcode 8 beta 6
1. Change the bundle ID (since my personal account has the current one)
1. Update the code signing info so that Xcode creates a provisioning profile for you
1. Change the device to "Generic iOS Device"
1. Product -> Archive
1. Note the failure

I think the ideal solution (for us) would be to provide a version of the framework that doesn't include PLCrashReporter, of course this is easy for me to say since we're not using Instabug for crash reporting, but inline assembly will always conflict with bitcode, so unless that changes in PLCrashReporter itself I don't see another solution. If this SDK were open source it would be pretty easy to do that with subspecs, but since it isn't I guess you'd have to vendor multiple pre-compiled frameworks.

Let me know if you can think of any other workaround for this!

**Comment by msoliman** [comment]
@keith I'll look into this and I'll keep you updated.

In the meantime, we've stripped out PLCrashReporter and created a separate branch: https://github.com/Instabug/Instabug-iOS/tree/without_crash_reporting

**Comment by keith** [comment]
Thanks for the quick turn around! We'll integrate this one and test it out!

**Comment by keith** [comment]
Looks like this branch has the same problem. If you change this in the sample project I attached you'll see the same error.

**Comment by msoliman** [comment]
This is now fixed on https://github.com/Instabug/Instabug-iOS/tree/dynamic_framework
PS. This support iOS 8+
