### ISSUE TITLE
Intro dialog showing up in corner of the screen

### ISSUE THREAD

**Issue by michaelbina** [Instabug/Instabug-iOS#87]
I'm not entirely sure when this started, but it might have been when I upgraded to swift 3.0.

Is anyone else seeing this issue?  The other dialogs after someone shows a screenshot are showing up fine.

![img_1216](https://cloud.githubusercontent.com/assets/528845/19018445/057f4ec4-8816-11e6-83dc-7ee1f8d7de8c.PNG)

**Comment by Figo0o** [comment]
Hey @michaelbina, 

Can you provide me with Instabug and iOS version used?

Thanks,

**Comment by michaelbina** [comment]
V5.3.2 and v5.3.1 and iOS 10 with Swift 3

**Comment by Figo0o** [comment]
Hey @michaelbina, 

here is a custom build for you, please try it and let me know if you still facing the same issue.

Thanks,
[Instabug.zip](https://github.com/Instabug/Instabug-iOS/files/507340/Instabug.zip)

**Comment by michaelbina** [comment]
I'm using pods.  Any way you can just make that another branch and i can point my podfile to it?

**Comment by michaelbina** [comment]
Or let me know the changes and I can make them in my own form

**Comment by michaelbina** [comment]
@Figo0o - I tried that custom build and it didn't solve the problem.  Any other ideas?

**Comment by Figo0o** [comment]
@michaelbina Sorry for inconvenience.

Please try this custom build, this issue should be solved. 
[Instabug.zip](https://github.com/Instabug/Instabug-iOS/files/507849/Instabug.zip)

**Comment by michaelbina** [comment]
@Figo0o - Yes that fixes it, thanks!  Will the changes be included in the next release?  I'd like to switch back to using it from cocoapods whenever possible.

**Comment by Figo0o** [comment]
Yeah sure, This issue should be solved in the next release.

**Comment by Figo0o** [comment]
Hey @michaelbina, Check out our new released version. This should be solved for now. 

Thanks for your feedback.
