### ISSUE TITLE
Add vendored_frameworks to the podspec

### ISSUE THREAD

**Issue by negativetwelve** [Instabug/Instabug-iOS#91]
Hi there!

Currently, the podspec for Instabug doesn't include `vendored_frameworks` which (from my understanding) makes it difficult for other pods (not projects) to depend on Instabug as a dependency.

Problem I'm facing right now:
Been hacking on a react-native bridge for Instabug (didn't realize you all were making an official one) and couldn't link this library without specifying the need for `Instabug` directly in my podfile. Other libraries, like Intercom, are able to be installed like: https://github.com/tinycreative/react-native-intercom/blob/master/react-native-intercom.podspec#L17 but using this same technique causes `<Instabug/Instabug.h>` to not be found.

From what I could tell, the only missing piece was `vendored_frameworks` that Intercom seems to have enabled here: https://github.com/intercom/intercom-ios/blob/master/Intercom.podspec#L18

If this is the correct fix for this issue, I'm more than happy to submit a PR for this, otherwise, please advise on what the best way to include the iOS sdk in another podspec is! thanks!

**Comment by yousefhamza** [comment]
Hi Mark,

Thank you for helping us improving Instabug!

About `vendored_frameworks`, It is actually not needed since we have `s.xcconfig     =  { 'FRAMEWORK_SEARCH_PATHS' => '"$(PODS_ROOT)/Instabug/"' }` which is basically the same thing.

More about this here: https://github.com/CocoaPods/CocoaPods/issues/1993

> Allow transitive dependencies upon vendored frameworks, by correctly setting `FRAMEWORK_SEARCH_PATH`

**Comment by negativetwelve** [comment]
thanks for the response @yousefhamza!

Makes sense, I haven't had too much time to look into it, but I'll see if there's something else that's off (on my end).

Just curious, how come you aren't bundling a podspec with https://github.com/Instabug/instabug-reactnative ?

**Comment by yousefhamza** [comment]
We are referencing the framework in the host app instead, we will look into the podspec way for doing that in the future and compare.
The documentation of react-native in that area (native module with dependencies) really comes short and left a lot the imagination and experimentation.

**Comment by negativetwelve** [comment]
sure thing, sounds good I'll keep watch on that repo!
