### ISSUE TITLE
"Instabug.setString" crashes app when used with key ".thankYouText"

### ISSUE THREAD

**Issue by deyil** [Instabug/Instabug-iOS#95]
`Instabug.setString(string, toKey:.thankYouText)` crashes my app. This only happens with key ".thankYouText"

**Comment by Kmohamed** [comment]
Hey @deyil 
Sorry for inconvenience, we will fix it in the next release

**Comment by Kmohamed** [comment]
Hey @deyil ,
I would like to inform you that we just release a new version of Instabug contains the Fix [Instabug](https://github.com/Instabug/Instabug-iOS).
