### ISSUE TITLE
UIWindow disappears after Instabug feedback invocation

### ISSUE THREAD

**Issue by fannt** [Instabug/Instabug-iOS#97]
We have floating UIWindow in the app for the audio player. After Instabug feedback widow hides, our window disappears too. It's still in memory, not hidden, alpha == 1...
Could that be directly related to the SDK code? Some method swizzling?

**Comment by fannt** [comment]
switching color to black for the main view on that Window helped bring it back. Any ideas?

**Comment by HeshamMegid** [comment]
@fannt, let me look into that issue and get back to you.

**Comment by HeshamMegid** [comment]
Unfortunately, I haven't been unable to reproduce this issue. Could you please tell me more about your environment? Like which version of iOS you're experiencing this problem on and which version of the Instabug SDK you have installed.

Also, if you're able to reproduce the issue in a sample project, that would help greatly.

**Comment by fannt** [comment]
@HeshamMegid no problem

here is the project https://github.com/fannt/InstabugBug

steps:
- show window
- toggle instabug with shake
- cancel or do smth
- observe blue window vanished

**Comment by HeshamMegid** [comment]
@fannt thanks for the sample project, that was helpful!

Here's a build of the SDK that fixes this issue. Please give it a try and let me know if that issue still happens.

This fix will be available in our next release.

[Instabug.zip](https://github.com/Instabug/Instabug-iOS/files/648857/Instabug.zip)

**Comment by fannt** [comment]
6.1.3 works well for me, cheers

**Comment by fannt** [comment]
oh, sorry, it doesn't work.
 6.2 works on cancelling but doesn't work after submitting the bug

**Comment by HeshamMegid** [comment]
@fannt oh, sorry about that. Let me look into it.

**Comment by HeshamMegid** [comment]
@fannt We've fixed this issue on 6.2.1.
