### ISSUE TITLE
EXC_BAD_ACCESS crash when cancelling

### ISSUE THREAD

**Issue by Drewpom** [Instabug/Instabug-iOS#98]
I recently upgrade my Instabug SDK after having some issues with the old `addTags` func, but we're now seeing crashes if you try to cancel the Instabug feedback screen. While the crash doesn't always happen, it is nearly guaranteed if you quickly try to back out.

I even made a completely new, empty project, and the crashes are still frequent. If there's anything I can try or provide, please let me know.

**Comment by Kmohamed** [comment]
Hello @Drewpom ,
we are very sorry for convenience.
I just trying to reproduce the crash on the current SDK version but unfortunately no luck.
Could you provide me with Instabug code and your iOS version.
Best,

**Comment by Drewpom** [comment]
Here's my test app code, we're currently stuck on Swift 2.2 / Xcode 7.3.2.

[TestApp.zip](https://github.com/Instabug/Instabug-iOS/files/635028/TestApp.zip)

**Comment by Kmohamed** [comment]
Hello @Drewpom ,
We are very sorry for inconvenience.
Here is a custom build that fixes the crash.
[Instabug.zip](https://github.com/Instabug/Instabug-iOS/files/635209/Instabug.zip)
This fix will be in the next release.

**Comment by Drewpom** [comment]
@Kmohamed thank you so much! Works great.
